### ISSUE TITLE
PFN_vkReallocationFunction is nasty to implement

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#103]
Implementing VkAllocationCallbacks as a wrapper around the system allocator is easy on Windows - just use _aligned_malloc, _aligned_realloc, _aligned_free.

(Sufficiently non-easy for https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/sdk-1.0.3/demos/tri.c#L1702 to get it wrong though, since it calls realloc instead of _aligned_realloc, which won't guarantee alignment and will crash when mixed with _aligned_malloc anyway.)

But on Linux, as far as I can tell, it's really awkward. There's alloc_aligned/posix_memalign/etc to allocate, but no aligned realloc function.

I ended up writing a couple of hundred lines of code with some dodgy pointer arithmetic to implement it on top of unaligned malloc/realloc/free with enough padding to guarantee alignment, plus a header stashed just in front of the aligned region so it can remember the original size in order to memcpy the right amount of data across when doing the aligned realloc.

So it's really easy to do it wrong, and (unless I'm missing something obvious) quite tricky to do it right.

I don't suppose you can just forbid drivers from calling pfnReallocation, and tell them to do pfnFree+pfnAllocation+memcpy instead, and tell applications they don't have to implement the reallocation callback? Or at least forbid reallocation for anything with alignment > 8 (given that malloc/realloc will easily provide alignment of 8 on most modern platforms)?

If not, I suppose I can't do much but moan about it :-(

**Comment by NicolBolas** [comment]
As I understand it, `vkReallocationCallback` is allowed to be implemented as an allocate, followed by a memcpy followed by a free of the original allocation.

>  If satisfying these requirements involves creating a new allocation, then the old allocation must be freed.

If the memory system you're using doesn't have a a true "realloc", you should just do that if the new size is bigger than the old.

**Comment by philiptaylor** [comment]
But how do you work out how many bytes to memcpy? That depends on the original size of the allocation, and I don't think there's any standard way to determine the size of an allocation from a pointer when using the C/POSIX heap functions, so you have to invent some new way of tracking the sizes of allocations, which gets messy.

**Comment by philiptaylor** [comment]
My current attempt at a nearly-the-simplest-possible valid VkAllocationCallbacks is at https://github.com/philiptaylor/vulkan-sxs/blob/9cb21b3/common/AllocationCallbacks.cpp#L87

(I would be quite surprised if there weren't any bugs left in it, though.)

**Comment by NicolBolas** [comment]
> But how do you work out how many bytes to memcpy? That depends on the original size of the allocation, and I don't think there's any standard way to determine the size of an allocation from a pointer when using the C/POSIX heap functions, so you have to invent some new way of tracking the sizes of allocations, which gets messy.

Well, I was going to suggest that you do the usual and allocate an extra `alignment`'s worth of memory to store the size in. But then I realized that the freeing function doesn't have to pass the size or alignment of the memory in question.

That's quite surprising. Even C++14 got into the [sized deallocation game](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3536.html) a while back. Perhaps that would be a better request: requiring implementations to provide sizes and alignments for their reallocation/deallocation.

**Comment by TobiasHector** [comment]
The original idea of the allocation callbacks wasn't really so that you can *just* plop malloc/realloc/free in there, it's meant to allow you to put in a faster/better allocator as determined by your own needs.

Internally, malloc/free/realloc have schemes that track the size because they already have to. The idea is that you would either implement your own allocator, or put in some existing external allocator according to your choice, and they too would normally be tracking sizes.

Why do you want to just replace it with such a simple scheme? If there's a use case we've overlooked then it'd be good to know what you're trying to do here.

**Comment by ratchetfreak** [comment]
A straightfoward usecase is to use them for tracking an implementation's allocations. 

If you want to do that now you have to also implement a conforming allocator with the tricky realloc. Just to get information about the allocations.

**Comment by philiptaylor** [comment]
Yes, I think it's (occasionally) helpful to be able to simply count allocations happening inside the driver and associate them with a particular scope in your application and display the numbers in your profiling tool, so you can easily see that e.g. the driver is doing a thousand allocations per frame in your core rendering loop and you ought to fix your code to avoid that. In the past I've used malloc hooks to get those kinds of numbers from application-internal allocations, and it'd be nice to extend that into driver allocations too.

(Mostly my interest is just theoretical though, I don't have any specific real-world use cases now.)

> a faster/better allocator

Hmm, the spec explicitly says "this is not meant as a performance feature", and michaelworcester pointed at that in issue #21, which makes it sound like the allocation callbacks are largely intended for wrapping allocations to add some tracking/etc rather than for replacing the whole heap implementation.

**Comment by TobiasHector** [comment]
We may have flip flopped a few times internally about their usage... different people want them for different things. I think the understanding was that some people initially wanted it for performance tweaking, but eventually we came to the opinion that you're unlikely to do much better than the driver will be able to here; because it's not practical to capture all the information that the driver has about an allocation in a few dwords.

If you're not planning on running this during an actual run-through where you're intending to get bleeding edge performance, then you can track the sizes yourself - just use a map of some sort.

Any additional information that you want for the realloc, like the initial size, is something we'd probably have to add via a new extension or version - feel free to propose something!

**Comment by oddhack** [comment]
@philiptaylor if there isn't going to be a more specific request or feature proposal, could you close this? I don't think we can do much just with the spec to make things easier.

**Comment by philiptaylor** [comment]
Okay, I think I achieved my original goal of moaning about it and it's too late to do much else.
