### ISSUE TITLE
pEnabledFeatures == NULL

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#104]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkDeviceCreateInfo says:

> pEnabledFeatures must be a pointer to a valid VkPhysicalDeviceFeatures structure

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features says:

> To disable all features which are not required, set pEnabledFeatures to NULL.

NULL is not a pointer to a valid VkPhysicalDeviceFeatures, so one of those is wrong.

Some samples like https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/device/device.cpp#L74 and https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/demos/cube.c#L2497 already set it to NULL and expect it to work.

**Comment by ratchetfreak** [comment]
vk.xml also says the member is not optional

https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L502

**Comment by TobiasHector** [comment]
@philiptaylor I'll take this - should be a simple enough fix. Setting it to NULL should be allowed.

@ratchetfreak The lack of "optional" attribute is pretty much the bug here - adding that will change the auto-generated text to "If pEnabledFeatures is not NULL, pEnabledFeatures must be a pointer to a valid VkPhysicalDevices structure". Which makes sense.

**Comment by TobiasHector** [comment]
This was fixed a while back, not sure in which revision - but it was fixed.

**Comment by krOoze** [comment]
In 1.0.6.
