### ISSUE TITLE
vkMapMemory max contiguous virtual address range limit

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#1043]
> vkMapMemory will fail if the implementation is unable to allocate an
appropriately sized contiguous virtual address range, e.g. due to virtual
address space fragmentation **or platform limits**.

can i haz max mapping size limit k thx bye

**Comment by jekstrand** [comment]
Short answer is "no".  If we tried to enumerate something in the spec about a min/max mapping limit, it would be hopelessly out-of-date in no time.  Even if we added a query, the driver may not have enough information to be able to actually provide an accurate limit.  Even if we did provide a limit, address space fragmentation can still cause problems.

**Comment by procedural** [comment]
> Even if we added a query, the driver may not have enough information to be able to actually provide an accurate limit.

But if a driver don't have enough information, it could just not report support for the extension that would add such a query? What is the problem here for platforms that do know about this limit, like Linux? I'm not talking about address space fragmentation here.

**Comment by critsec** [comment]
Because such limits aren't imposed by the GPU hardware or driver software, reporting them is out of scope for Vulkan, in my opinion. That spec fragment is just saying "the Vulkan driver isn't exempt from whatever max-mapping-size constraints the OS imposes on other software." Also note the "e.g." -- these are examples, but it's not really possible in practice to exactly enumerate in the spec (or, likely, in a driver) all the possible reasons the OS might fail to create a mapping, and providing a query that made promises here would just result in bugs being filed against driver authors that they wouldn't be able to fix.

**Comment by procedural** [comment]
> it's not really possible in practice to exactly enumerate in the spec (or, likely, in a driver) all the possible reasons the OS might fail to create a mapping

Did I miss the moment when computers stopped being deterministic? Not really possible? Are you saying all existing operating systems can't pass any information to a driver when memory mapping fails? No information at all, just "I failed and I have no idea why"?

**Comment by jekstrand** [comment]
> Did I miss the moment when computers stopped being deterministic?

Computers haven't been properly deterministic in the sense you're looking for in 50 years or so.  As soon as you call `malloc()` in your program, you are at the mercy of an unknown memory allocation algorithm which may fragment your address space and start failing without you actually being out of memory.

> Are you saying all existing operating systems can't pass any information to a driver when memory mapping fails? No information at all, just "I failed and I have no idea why"?

Take a look at the docs for the [`mmap(2)`](http://man7.org/linux/man-pages/man2/mmap.2.html) system call.  Assuming the driver did due diligence and only used mappable memory and doesn't pass any bogus offset/size/flag parameters to the call, we're left with possible return values of `ENFILE` and `ENOMEM`.  I've never in my life seen `ENFILE` be thrown by Linux and `ENOMEM` can mean virtually anything.  So, yes, memory mappings can theoretically fail for "reasons" and it's pretty opaque to anything other than core MM deep inside the kernel exactly what those reasons are.

That said, what saves us from doom and why computers have continued working in the last 50 since `malloc()` is that these cases aren't common.  98% of cases in which `vkMapMemory` call (or the `mmap()` which backs it) which one is likely to see in the wild are simply that your address space is fragmented and the OS (or the C standard library) can't find enough contiguous address space in your process.  However, there are also various nebulous OS limits which may also cause it to fail and they could be dependent on configuration files, other running processes, and many other things which are outside the control of your process.  There is simply no way that the Vulkan spec can enumerate all of those possibilities nor should it because the moment you bring up Vulkan on a new OS (or install a new version of the same OS), those limits may change and new ones may be added.

**Comment by procedural** [comment]
@jekstrand Thank you, Jason! This answers all of my questions now. :)
