### ISSUE TITLE
Porting ARB_clip_control to Vulkan

### ISSUE THREAD

**Issue by FernandoS27** [KhronosGroup/Vulkan-Docs#1054]
The new coordinate system in Vulkan is great as it offers more precision on the depth buffer and better compatibility with Dx11. Sadly it also makes porting apps from OpenGL and GL ES a nightmare. I've been porting apps for a while and I've come across many issues related to clipping and depth models.

Normally in order to deal with the screen, one just need to go into viewports and use negative height. That easily solves that. The real issue comes with -1,1 depth and all the magic tricks one needs to pull off. For starters you need to go through every single shader and apply this formula `z = (z + w)*0.5`. That's the easy part but then some games use depth ranges of -1,1 and have shaders hardcoded to accept -1,1, normally doing depth*2 - 1 on every sampler solves it but not always works. In those cases you need rewrite parts of the shader. The nightmare starts when some clients want to keep their OpenGL ES backend compatible with Vulkan, in that case you need to write a meta system for the shaders or just rework the OpenGL ES backend to work as the Vulkan (upper left with zero to one depth) and redo the troubling shaders. Not only that but in my hobby, emulation, there are console gasmes that shift from -1,1 to 0,1 and backwards to achieve different effects.

It would really help a lot if glClipControl existed in Vulkan as an optional extension to pipeline states.

**Comment by Degerz** [comment]
This sounds oddly familiar to a [previously](https://github.com/KhronosGroup/Vulkan-Docs/issues/986) filed issue ...

**Comment by FernandoS27** [comment]
Yeah in that one it does not state too many issues. They closed it unless there were more issues. Here I'm posting my whole experience seeing if it would be reconsidered as I believe the extension is vital for bringing a lot of original GL software into Vulkan.

**Comment by Degerz** [comment]
Ah, so you're looking for OpenGL normalized device coordinates ? Am I correct ? 

Usually, Khronos would prefer if you handle this in the emulation/application layer ...

**Comment by FernandoS27** [comment]
as I mentioned it's a lot of work. Just like ARB_clip_control was created to ease the pain of porting directX games into OpenGL. I expect the same philosophy is used for a similar extension in Vulkan. Surprisingly, in emulation it's less painful than actually porting an App.

**Comment by NicolBolas** [comment]
@FernandoS27 

> Just like ARB_clip_control was created to ease the pain of porting directX games into OpenGL.

I don't agree that this was the *primary* impetus for it. Using a [0, 1] depth range is very important for improving precision. Without ARB_clip_control or similar extensions, it would be impossible to gain this benefit, even though the hardware could do it. I look on this feature, from an OpenGL perspective, as the OpenGL NDC space being a mistake, and ARB_clip_control correcting that mistake in a backwards-compatible way. Even if Direct3D had never existed, we'd still need ARB_clip_control.

And that's why I'm not sure I like the idea of having this as part of Vulkan. If it was a mistake, if OpenGL's standard NDC space was the wrong NDC space to begin with, perpetuating that mistake by making it part of Vulkan seems wrong-headed.

**Comment by TomOlson** [comment]
The working group talked about this on 2019-10-28. We're always interested to know what people are doing with Vulkan and what problems they are having, so thanks for raising the issue. Adding functionality has costs (we have to write CTS and validation paths, for starters), so we have to prioritize; we do that partly based on community input, and partly based on impact compared to other things we could do. 

Agreed that plumbing the transformation through an old GL game is a pain, but it is possible, and as @Degerz says, we prefer to let convenience functionality live outside the spec / driver. We also agree with @FernandoS27 that supporting GL-style NDCs does not really add value for new content. So, this has a low priority at present. I'll close the issue here, but it's tracked internally and revisit if new use cases come up.

**Comment by ReinUsesLisp** [comment]
The current NDC doesn't properly interact with [VK_EXT_transform_feedback](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VK_EXT_transform_feedback.html) for the position varying since it can't properly output to [-1, 0) ranges. This forces to use an extra generic varying for the feedback (which may not be possible in all cases).

It's not a critical issue, but I thought it was worth pointing out.

**Comment by ShabbyX** [comment]
For the record, this is a blocking issue for ANGLE's support for geometry shaders for the reason stated in the previous comment (where `maxGeometryTotalOutputComponents` will exceed due to the additional varying output)

**Comment by sfricke-samsung** [comment]
@FernandoS27 - Happy to update [VK_EXT_depth_clip_control](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_control.html) has been added so now you can use `NEGATIVE_ONE_TO_ONE`

**Comment by pdaniell-nv** [comment]
> @FernandoS27 - Happy to update [VK_EXT_depth_clip_control](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_control.html) has been added so now you can use `NEGATIVE_ONE_TO_ONE`

There is an implementation [here](https://developer.nvidia.com/vulkan-driver) if you want to experiment with it.
