### ISSUE TITLE
Why Vulkan is more verbose than D3D12?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#1055]
I saw [this tweet](https://mobile.twitter.com/adamjmiles/status/1183846317694607364) that got me thinking: why core Vulkan 1.0 is more verbose than D3D12? It does more things than D3D12? If you type more code, it performs better than D3D12? It targets more hardware than D3D12? Can it be that Khronos spec designers are less experienced than Microsoft's spec designers, thus the verbosity, or it's the other way around and Khronos spec designers know what makes an API good better than Microsoft's spec designers? Do APIs try to solve different problems? Which problems are so different they require more verbosity?

Thanks!

**Comment by krOoze** [comment]
Well the problem is the fallacy of the Hello World program. LOC count of a tutorial program is not a valid metric of anything.

Vulkan is **not** made to draw a single triangle or something like that. You could think about it the other way around. A code of a complex\real app in Vulkan is not particularly larger than the simple Hello app;
https://youtu.be/0R23npUCCnw?t=629

BTW I think it was one of the lessons-learned from OpenGL. You can always make a middle-ware to make a verbose API less verbose, if that is your wish. But you can never go the other way around and make a terse API explicit when you actually need that control.

**Comment by procedural** [comment]
One thing I see is if D3D12 is less lines of code to type, and is faster for desktop GPUs than Vulkan, and Microsoft employees are explicitly dedicated to beat APIs like Vulkan in verbosity and performance, than Vulkan has no features left for Microsoft's platform. If D3D12 is less verbose and faster than Vulkan, how Khronos will appeal to any developer on Windows? Portability and tools will be the only things left, and I'm not sure both of these are enough to justify the cons.

**Comment by Tobski** [comment]
Hi @procedural, can you highlight any specific examples where you believe Vulkan to be more verbose? Most of the additional verbosity is in areas that increase portability and extensibility, by design. Other areas are places like synchronisation and render passes, where additional performance opportunities are offered.

In most of the cases I’m aware of the verbosity difference is slim enough to not really matter. This is certainly not a _general_ complaint we’ve heard from developers. We do have requests to simplify or change a couple of specific parts of the API though, which we do work on.

**Comment by procedural** [comment]
> Most of the additional verbosity is in areas that increase portability and extensibility, by design. Other areas are places like synchronisation and render passes, where additional performance opportunities are offered.

Thanks, I was waiting for a specific answer like this.

Closing.

**Comment by procedural** [comment]
I would also add to the list promises to a driver which other APIs don't have, like object groups and layouts. [When ISVs complain enough, it is possible to reduce them](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/VK_KHR_imageless_framebuffer.txt), but then I guess we enter driver and hardware-specific territories.

**Comment by krOoze** [comment]
D3D12 does have [layouts](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_resource_states). Not sure what you mean by "object groups"; Pools?

**Comment by procedural** [comment]
Here's another one from an Intel hardware engineer: https://twitter.com/tom_forsyth/status/1191952259967586306

> It's actively user-unfriendly. That's actually its guiding principle. Until you are absolutely furious with the rendering API you're currently using because it doesn't give you enough rope to hang yourself, I would not start to look at Vulkan (or DX12).

**Comment by krOoze** [comment]
Then again if I wanted "user-friendliness" I would not look at DX11 nor OpenGL. I would simply go for Unity or Unreal, or whatever is specific to my domain or interests.

Half of the problem is you are fulltext serching the internet for anyone that vaguely agrees with your preconceived opinion. The other problem is you may be misunderstanding what Vulkan is for. That engineer says it himself: "unless you're a full-time engine dev". What else you would even be if you are messing with a low-level graphics accelleration API? You are either enthusiast, or rendering backend engineer, or you chose the wrong tool for the job.

**Comment by krOoze** [comment]
PS: "user-friendliness" and reduced verbosity are a concern, but they have the lowest priority under the other guiding principles in Vulkan.

If you have an idea how to make the API more friendly, you basically have to demonstrate these:
1) It cannot be done outside Vulkan
2) It must be explicit. (I.e. combined buffer creation with allocation in OpenGL is not "explicit" because it might or might not allocate, and might do so whenever it feels like - e.g. lazily delay it to first use of the buffer, or not.)
3) It must work on all HW and platforms well enough (if it is to be part of core Vulkan).

**Comment by procedural** [comment]
Note I don't link all the negative opinions on Vulkan, only from driver and hardware engineers.

**Comment by procedural** [comment]
> What else you would even be if you are messing with a low-level graphics accelleration API?

Vulkan is not low-level, acceleration is not guaranteed.

**Comment by krOoze** [comment]
C is not low level, it may be executed on intern with a paper and pencil.

**Comment by procedural** [comment]
I think I express the weak points of Vulkan more clearly than those driver and hardware engineers I link, so you could get a clear picture in future of what went wrong when there will be no drivers left that will accept Vulkan API calls.

**Comment by krOoze** [comment]
Okay Nostradamus. :p
Look, unlike DX or Metal, Vulkan is not a Design by Dictator. What about the engineers that contribute to the shape of Vulkan? The same engineers decide the shape of Vulkan. That should probably needed to be addressed first. There are not really any "Khronos spec designers". The member companies decide on the design.

**Comment by procedural** [comment]
> What about the engineers that contribute to the shape of Vulkan?

I don't know their opinions on Vulkan, afaik most of them are opinion-less, just like they were on OpenGL until Apple replaced it with Metal and Microsoft attempted to do the same with UWP (they seem to change their minds, but time will tell, Xbox still won't adopt Vulkan because I expect Xbox driver engineers think it's a worse API than DirectX, but again, they're silent on this, everyone shut their mouths on this except me and few other people).

**Comment by krOoze** [comment]
Xbox won't adopt it, because Xbox is Microsoft.

**Comment by procedural** [comment]
Yea, that's the hint on no-Vulkan-drivers future I expect.

**Comment by krOoze** [comment]
Ok, but that is a political reason, not engineering. Playstation also has its own thing.
At some point it may call for some more sneaky tactics, as was done with MoltenVK.

**Comment by procedural** [comment]
Now Khronos members spreading fake news that Vulkan is faster than D3D12: https://twitter.com/McCloudStrife/status/1192243041228251136
