### ISSUE TITLE
VK_NV_ray_tracing spec references glsl builtins

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1127]
@ewerness 
The `VK_NV_ray_tracing` specification refers to `gl_InstanceCustomIndexNV`, `gl_RayFlagsNoOpaqueNV`, and `gl_RayFlagsOpaqueNV`.

I think technically SPIR-V equivalents should be listed in the spec instead.

**Comment by dgkoch** [comment]
We could (and arguably should) for gl_InstanceCustomIndexNV, but the NV SPV extension has no representation for the RayFlags. I'm inclined not to change anything now, as this will be irrelevant once the KHR version is published (and will just conflict with internal changes, since all those sections have been rewritten).

**Comment by dgkoch** [comment]
I believe this should all be addressed in the 1.2.135 spec update.
