### ISSUE TITLE
Push constants state per stage or not?

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-Docs#1129]
I have a bug in vkQuake where push constants are set for `VK_SHADER_STAGE_COMPUTE_BIT` and then later a graphics pipeline is run with a different layout which also uses push constants, but on the vertex stage https://github.com/Novum/vkQuake/issues/197

My interpretation of the spec was that there are different push constant states for each stage, i.e. modifying the values for compute doesn't affect vertex push constants. It seems like AMD and NVIDIAs Windows drivers are also interpreting it this way.

It might as well not be true, but from what I can tell the spec is too vague on this.

**Comment by polarina** [comment]
The specification for `VkPushConstantRange` says:
> `stageFlags` is a set of stage flags describing the shader stages that will access a range of push
constants. If a particular stage is not included in the range, then accessing members of that
range of push constants from the corresponding shader stage will return undefined values.

Push constant ranges are specified during the creation of a pipeline layout. Valid usage for `VkCmdPushConstant` says:
> For each byte in the range specified by `offset` and `size` and for each shader stage in
`stageFlags`, there must be a push constant range in `layout` that includes that byte and that
stage

On _pipeline layout compatibility_:
> Two pipeline layouts are defined to be “compatible for push constants” if they were created with
identical push constant ranges.

Valid usage for `vkCmdDraw*` and `vkCmdDispatch*` say:
> For each push constant that is statically used by the `VkPipeline` bound to the pipeline bind
point used by this command, a push constant value must have been set for the same
pipeline bind point, with a `VkPipelineLayout` that is compatible for push constants, with
the `VkPipelineLayout` used to create the current `VkPipeline`, as described in _Pipeline Layout
Compatibility_

Switching between pipelines with non-identical push constant ranges will make your reads undefined; thus your compute and graphics pipelines must have identical push constant ranges if your usage is to work. In that's the case, specify both vertex and compute stages in `stageFlags` for the relevant push constant ranges.

If your graphics and compute pipelines are not compatible for push constants, you must call `vkCmdPushConstant` appropriately before draws/dispatches after binding a new pipeline.

**Comment by Novum** [comment]
Okay, so at least this part here is confusing "a push constant value must have been set for the same
pipeline bind point". `vkCmdPushConstants` doesn't take a pipeline bind point.

**Comment by procedural** [comment]
@Novum 
> vkCmdPushConstants doesn't take a pipeline bind point, therefore push constants are always set for all pipeline bind points anyway?

Three possibilities: either spec writers forgot to add a pipeline bind point for vkCmdPushConstants at the time of Vulkan 1.0 release, and no one cared to fix it for 4 years (very likely), or there is some obscure, no-one-cares-about, probably mobile, hardware that can't store overlapping constant ranges for graphics and compute pipelines separately, and that vendor couldn't emulate pipeline bind points for whatever reason (unlikely), or there's something else going on, but yes, we stuck with global constant ranges for both graphics and compute pipelines right now.

We can only hope that driver writers realize this and shadow state constant ranges per command buffer internally, comparing them and actually setting constants only if they are really changed for a pipeline bind point based on what you call next after the redundant vkCmdPushConstants calls, dispatch or draw.

**Comment by NicolBolas** [comment]
@procedural 

>We can only hope that driver writers realize this and shadow state constant ranges per command buffer internally, comparing them and actually setting constants only if they are really changed for a pipeline bind point based on what you call next after the redundant vkCmdPushConstants calls, dispatch or draw.

Would any of that actually be necessary? It's highly unlikely that a graphics shader and a compute shader would be using the same push constant values, so odds are good that you're going to be uploading new data anyway. Furthermore, the largest push constant range supported by any Vulkan implementation appears to be... 256 bytes. So we're not actually talking about any significant performance problem caused by an occasional copy of hypothetically "redundant" data. And since you're not constantly switching between graphics and compute operations (since graphics operations can only happen in a render pass, and compute operations can't happen in a render pass), even in the hypothetical "redundant" case, this circumstance is not happening with any frequency.

Lastly, it seems to me that doing all of that comparison work would be *slower* than just using the push constant storage as-is. I mean, the whole point of push constants is that changing this data is *fast*. A blanket memcpy is going to be faster than a memcmp.

So it's not clear what the problem here is. It seems clear to me that the "for the same pipeline bind point" text is likely erroneous and not meant to be there, that both kinds of pipelines access the same effective push constant memory storage. And that shared access doesn't pose any actual problem for users.

**Comment by procedural** [comment]
> Would any of that actually be necessary?

Depends on hardware. For hardware that does have separate constant ranges for graphics and compute pipelines, the current `vkCmdPushConstants` without a pipeline bind point is either a driver runtime guess point or a hardware memory waster.

**Comment by NicolBolas** [comment]
> For hardware that does have separate constant ranges for graphics and compute pipelines, the current `vkCmdPushConstants` without a pipeline bind point is either a driver runtime guess point or a hardware memory waster.

Remember that rendering commands cannot be issued outside of a render pass, and that compute operations cannot be issued *inside* of a render pass. So it's hardly a "guess" to assume that `vkCmdPushConstants` calls applied during a render pass instance are for the graphics pipeline, and that such calls outside of a render pass instance are for the compute pipeline.

As such, there would only be waste on this hypothetical hardware if a user is trying to share push constant state. That is, some push constant state from inside the render pass instance would leak to the outside world. But is that even possible?

I can't find the place in the specification that explicitly forbids this, but since subpasses execute in an arbitrary order, it seems decidedly unlikely that code outside of a render pass could depend on the state of the world inside of it. That is, if you set some push constant state inside of a subpass, then after the render pass, how could you know what this state is, if the execution order of that subpass is not guaranteed?

And the same goes for a subpass trying to use state set before the render pass began. Or state from one subpass influencing another. So odds are good that there's some statement in the spec that I can't quickly find that basically says that all such state is invalidated between subpasses. And therefore between render passes and the outside world.

So can you determine a scenario where the context of a `vkCmdPushConstants` function call cannot know whether that call should update the graphics or compute pipeline's push constants (if such a thing exists at all)?
