### ISSUE TITLE
Undefined behavior of incorrect use of vkMapMemory

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#1142]
From https://github.com/KhronosGroup/Vulkan-Docs/blob/7e1df7c/chapters/memory.txt

> It is an application error to call vkMapMemory on a memory object that is already host mapped.

Also, I can't find this in the spec, but I assume calling vkMapMemory on a non-mappable memory object is considered an application error too.

What should happen on an application error? Is it undefined? Graphics drivers are free to crash? Graphics drivers are free to return an unrelated error code like `VK_ERROR_MEMORY_MAP_FAILED` which is reserved for implementation errors, not application errors?

> vkMapMemory will fail if the implementation is unable to allocate an appropriately sized contiguous virtual address range, e.g. due to virtual address space fragmentation or platform limits. In such cases, vkMapMemory must return VK_ERROR_MEMORY_MAP_FAILED.

**Comment by krOoze** [comment]
> What should happen on an application error? 

`VUID-vkMapMemory-memory-00678`:

> `memory` **must** not be currently host mapped

ergo undefined behavior.
(Kinda weird though that different range of that memory cannot be mapped. Spec bug or intentional?)

> Also, I can't find this in the spec, but I assume calling `vkMapMemory` on a non-mappable memory object is considered an application error too.

`VUID-vkMapMemory-memory-00682`:

> `memory` **must** have been created with a memory type that reports `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`

**Comment by procedural** [comment]
> > memory must not be currently host mapped
>
> (Kinda weird though that different range of that memory cannot be mapped. Spec bug, or intentional?)

Yeah, interesting, now I'm wondering too.

> PS: possibly would be good to remove that redundant sentence

What sentence?

As for undefined behavior, I will assume a driver is free to crash on any incorrect use of vkMapMemory.

Thanks for pointing out VUIDs, @krOoze!

**Comment by critsec** [comment]
I don't remember the actual reason for not allowing multiple mappings, but I'm guessing it was a combination of a couple things.

First, if you're going to map something ever, it's better to just map it once as soon as create it (or first need the mapping) and then leave it mapped until ready to free it. We want to encourage that, rather than repeatedly mapping and unmapping. So the expected typical usage for host-visible memory is to just map the whole thing up-front, maybe before you've even assigned parts of it to individual buffers or images.

Second, underneath mapping can only happen at page granularity. If we allowed mapping different ranges, we'd have had to expose that through the API so apps could round to the right granularity. That doesn't seem worth it, and probably wouldn't be very easy to use in the cases where you'd typically want range mappings anyway (those would typically correspond to individual resources, which might not be page aligned).

**Comment by procedural** [comment]
@critsec, in other words, currently Vulkan allows only one mapping range?

**Comment by procedural** [comment]
> If we allowed mapping different ranges, we'd have had to expose that through the API so apps could round to the right granularity.

Apparently some devices use minMemoryMapAlignment for that? 4096 looks like a page size to me: https://vulkan.gpuinfo.org/displaydevicelimit.php?name=minMemoryMapAlignment

**Comment by critsec** [comment]
> in other words, currently Vulkan allows only one mapping range per memory object?

Yes. That's what the VU statement krOoze quoted says, and there's this very similar statement in the text: "It is an application error to call vkMapMemory on a memory object that is already host mapped."

> Apparently some devices use minMemoryMapAlignment for that? 4096 looks like a page size to me: https://vulkan.gpuinfo.org/displaydevicelimit.php?name=minMemoryMapAlignment

Right, that will be page alignment on most/all implementations. But the spec would have had to require that `offset` and `size` are rounded down and up to multiples of that value, and that these expanded mapped ranges didn't overlap each other. Which would be awkward for software that wanted to map at the individual resource level (the main reason to want ranges), but had resources that aren't aligned to page boundaries.

Instead of being a requirement that apps have to meet, `minMemoryMapAlignment` is a guarantee from the implementation about how it will behave. It lets applications make assumptions that, for example, if they make sure their `offset` is suitably aligned for SIMD vector instructions, then the mapped address corresponding to `offset` will also be aligned (as long as they don't need an alignment larger than `minMemoryMapAlignment`).

**Comment by krOoze** [comment]
> As for undefined behavior, I will assume a driver is free to crash on any incorrect use of vkMapMemory.

"Undefided behavior" is undefined. It includes crashing, your PC taking over the world, **or** even seemingly working correctly. You simply must not ever enter this state if you want a well-behaved app.

> What sentence?

PR #1143
