### ISSUE TITLE
Clarify that `vkAllocateMemory` doesn't allocate any memory on an import operation and `vkFreeMemory` doesn't free imported memory

### ISSUE THREAD

**Issue by malte-v** [KhronosGroup/Vulkan-Docs#1145]
The `VK_KHR_external_memory*` family of extensions allows Vulkan to import memory from other applications using `vkAllocateMemory`. Imported memory objects must later be destroyed via `vkFreeMemory`. To me, it's not entirely clear from the specification that `vkAllocateMemory`/`vkFreeMemory` don't actually allocate or free any memory regions when used with imported memory, unlike the function names suggest.

**Comment by jeffbolznv** [comment]
I think this was supposed to go to the SI TSG (Jeff Leger), but I can't find his username.

**Comment by cubanismo** [comment]
vkFreeMemory should probably be defined to unreference rather than free memory in general, with non-exported memory always having a refcount of 1.  We were pretty thorough about the whole payload/object separation in the external semaphores/fences language, but I think less attention was paid to the memory import/export language, since the semantics were much less complex (no  "permanence" issues, no post-creation import, etc.).

**Comment by cubanismo** [comment]
Discussed internally and came to some rough agreements:

* Some language updates are warranted.  Free should probably be defined in terms of unreferencing a payload somehow, and import as referencing the same.  However, care must be taken to avoid implying that importing memory consumes no per-import resources.  For example, at the very least, maxMemoryAllocationCount is affected, and perhaps other device limits.

* The term "payload", used in the semaphore and fence import/export language, is defined generally in the glossary, but is not currently referenced in any of the VkDeviceMemory import/export or allocation language.  Less-normative/less-well-defined references to "the same underlying memory" are used in some places instead, and this should probably be refactored to refer to payloads.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.156 spec update.
