### ISSUE TITLE
MultiViewport and Geometry capabilities

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Docs#1146]
The `MultiViewport` SPIR-V capability implicitly declares the `Geometry` capability.

* The `MultiViewport` capability may be enabled if the `multiViewport` feature is enabled.
* The `Geometry` capability may be enabled if the `geometryShader` feature is enabled.

The Vulkan specification does not, to the best of my knowledge, have any Valid Usage statements that answer the following questions:

Is it true that: implementations that support the `multiViewport` feature must also support `geometryShader`?

Is it true that: applications that enable the `multiViewport` feature must also enable `geometryShader`? If not, may SPIR-V modules use functionality implicitly enabled by the `Geometry` capability, and may SPIR-V modules explicitly enable the `Geometry` capability in addition to `MultiViewport`?

**Comment by krOoze** [comment]
> Is it true that: implementations that support the `multiViewport` feature must also support `geometryShader`?

It would improve sanity, but technically I think it does not have to guarantee it.

> Is it true that: applications that enable the multiViewport feature must also enable geometryShader?

I would think so:

> If `pCode` declares any of the capabilities listed as **optional** in the _SPIR-V Environment_ appendix, the corresponding feature(s) **must** be enabled.

**Comment by jekstrand** [comment]
> Is it true that: implementations that support the multiViewport feature must also support geometryShader?

In theory, no, a driver could expose `multiViewport` without `geometryShader`.  Without `geometryShader` or an extension such as VK_EXT_shader_viewport_index_layer, it would be useless but a driver could, in theory, claim support.  In practice, however, I don't think anyone who exposes `multiViewport` doesn't also expose `geometryShader`.

> Is it true that: applications that enable the multiViewport feature must also enable geometryShader? If not, may SPIR-V modules use functionality implicitly enabled by the Geometry capability, and may SPIR-V modules explicitly enable the Geometry capability in addition to MultiViewport?

Your app should check for and enable the things it needs.  If you need multiple viewports, enable `multiViewport`.  In order to use those multiple viewports, you'll need to enable either `geometryShader` or one of the features in the VK_EXT_shader_viewport_index_layer extension.

Writing to a **ViewportIndex** built-in from a geometry shader requires the **MultiViewport** SPIR-V capability which implies the **Geometry** capability.  Writing to a **ViewportIndex** built-in from a vertex or tessellation shader via VK_EXT_shader_viewport_index_layer requires the **ShaderViewportIndexLayerEXT** or **ShaderViewportIndex** capabilities (depending on if you're using SPIR-V 1.5 or not) and those don't require **GeometryShader**.

Yes, I agree that it's all a bit of a mess thanks to the evolution history of the spec.  However, I'm pretty sure after looking through the details that the spec is fine (if a bit confusing) and that the two features are, indeed, decoupled.
