### ISSUE TITLE
Not sure about "VK_ERROR_DEVICE_LOST is equivalent to VK_SUCCESS" sometimes.

### ISSUE THREAD

**Issue by EqualKirby** [KhronosGroup/Vulkan-Docs#118]
In 4.2.4. Lost Device,
it says, " For any command that may return VK_ERROR_DEVICE_LOST, for the purpose of determining whether a command buffer is pending execution, or whether resources are considered in-use by the device, a return value of VK_ERROR_DEVICE_LOST is equivalent to VK_SUCCESS. "

But after I searched all the document to find any commands whose return value contain VK_ERROR_DEVICE_LOST, I cannot find any description about the text above.

Is my understanding wrong or there is indeed no further information about that ?

**Comment by janharaldfredriksen-arm** [comment]
I think that's the only description of that particular behavior.
What additional information were you looking for?

**Comment by EqualKirby** [comment]
I wonder if there are any instance that a function will return VK_ERROR_DEVICE_LOST for the purpose like that.
If I understand correctly, the text means "those command which has VK_ERROR_DEVICE_LOST", not "some command might return VK_ERROR_DEVICE_LOST, but it's not documented here" ?

Thanks for your answering.

**Comment by janharaldfredriksen-arm** [comment]
I think you may be reading the sentence the "wrong" way around.

There are a number of commands that might return VK_ERROR_DEVICE_LOST, as documented in the Return Codes section of the respective commands. This error always means that the device is lost; it is never used for anything else.

When a DEVICE_LOST error is returned, the application is responsible for destroying all objects before attempting to recreate the device (as described earlier in the "Lost Device" section). But you are not allowed to destroy objects while they are in use - so the spec needs to say something about this special-case.

The paragraph you quote attempts to clarify this by saying that, for example, if you get a DEVICE_LOST error from vkWaitForFences then you are allowed to destroy the command buffer objects (and any other objects referenced by these) submitted ahead of the fence - because they are no longer in use. In this respect, DEVICE_LOST is equivalent to VK_SUCCESS - rather than being equivalent to VK_TIMEOUT).

Does that clarify?

**Comment by EqualKirby** [comment]
Surely it does :)
Thank you very much !
