### ISSUE TITLE
Vulkan PDF does not specify the entire version number

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#119]
The HTML Vulkan spec states the exact version of the specification: major, minor, and revision. The PDF repeatedly states the major and minor version numbers, but _never_ does it state the revision number. As such, it's hard to tell if the PDF has been updated when a new Vulkan spec revision takes place.

**Comment by oddhack** [comment]
Yes, known and annoying problem. Fixing it in the current pipeline will probably take some Docbook XSLT customization. We are hoping that moving to asciidoctor will solve this problem and inject the same author/version/commit tag block that exists in the HTML output.

**Comment by oddhack** [comment]
I could just insert a text block in the introduction with the same comments, in the meantime.

**Comment by elfring** [comment]
@NicolBolas: How do you think about to use the wording "… does **not** specify …" in your bug report title?

@oddhack: Which text formatting commands are responsible for the mentioned version data in these documents?

How should the information display be usually kept consistent for the revision identification?

**Comment by oddhack** [comment]
@NicolBolas I'm fixing the PDF title to include the 1.0.patchnumber going forward. That will roll out in a week or two. I don't think I'm going to deal with the entire commit ID/generation date block, which is autogenerated by asciidoc in the HTML output, until we've seen what asciidoctor can do (which will be a while because that's a lower priority).

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
