### ISSUE TITLE
Can VkInstanceCreateInfo pNext chain contain multiple VkDebugUtilsMessengerCreateInfoEXT structs?

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-Docs#1329]
VkDebugUtilsMessengerCreateInfoEXT structures can be added to the VkInstanceCreateInfo pNext chain to aid in debugging events that occur while creating or destroying an instance.

When attempting to use multiple VkDebugUtilsMessengerCreateInfoEXT structures as part of the VkInstanceCreateInfo pNext chain you are greeted with validation error:
"vkCreateInstance: pCreateInfo->pNext chain contains duplicate structure types: VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT appears multiple times. The Vulkan spec states: The sType value of each struct in the pNext chain must be unique
(https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkInstanceCreateInfo-sType-unique)

It appears as if the Vulkan-Loader fully expects this usage to be valid and it fully supports the use of multiple VkDebugUtilsMessengerCreateInfoEXT structures in the pNext chain. See https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/debug_utils.c::util_CopyDebugUtilsMessengerCreateInfos for more info.

I can see this functionality being useful in certain scenarios for instance applications which record/replay Vulkan application calls. At record time these applications may want to *additionally* record events occurring while creating or destroying an instance without modifying the application's existing pNext chain only appending an additional VkDebugUtilsMessengerCreateInfoEXT structure to it.

**Comment by oddhack** [comment]
@lenny-lunarg the WG wanted to check if this is intended usage. If so there was a more recently added XML mechanism (allowduplicates attribute) that should be added and that will suppress the VU.

**Comment by lenny-lunarg** [comment]
This is intended loader behavior. There's an enum inside that struct (defined in `vk_layer.h`) that says what's actually contained in each of those structs. One of those structs is the information that a layer needs in order to initialize it's dispatch table and the other is a function pointer so the layer can create a dispatchable object (device, queue, command buffer).

@oddhack, I'd say we definitely want this allowduplicates option for this struct. This is actually very old behavior which has been illegal for some time. I didn't realize we had allowed specific structures to be included multiple times, but that's definitely something we want to allow in this case.

**Comment by oddhack** [comment]
@lenny-lunarg thanks. I put an internal MR to that effect on the Monday agenda, if you can examine & sign off on it that would be great.

**Comment by oddhack** [comment]
This should be fixed in the 1.2.150 spec update.

**Comment by rumblehhh** [comment]
Great, thanks for clarifying and fixing this!

**Comment by krOoze** [comment]
@lenny-lunarg Is this expected to work far back into old Loaders? Maybe revision number of the extensions should be bumped.
