### ISSUE TITLE
Using a read-only attachment in a shader binding

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Docs#1345]
We are trying to use a depth image for both depth testing (without writes) and sampling from the shader. We are doing that by ensuring the `DEPTH_STENCIL_READ_ONLY_OPTIMAL` layout, and simply by binding a descriptor set with the sampled image binding for the same depth used in this renderpass (with a single sub-pass). This appears to work on desktops just fine, and also a similar workload is permitted on Metal and D3D12 fwiw. No Vulkan validation layer complaints are seen either.

However, it [came to my attention](https://community.khronos.org/t/sampling-depth-stencil-texture/6933/9) that the specification has a VU against that:

> Image subresources used as attachments in the current render pass must not be accessed in any way other than as an attachment by this command

So I'm a bit confused about which side the bug is on: the spec, or our application and LunarG validation layers?

If we are doing it wrong, would there be a *right* way to do this? Maybe the depth binding has to be done via an "input attachment", in which case the depth would be in two different attachments?

**Comment by critsec** [comment]
Incidentally this came up from a different source recently, and there's an internal issue opened and under active discussion about it. The spec does forbid it currently, but we're investigating whether we can state specific conditions under which it can be relaxed.

Doing this as a depth attachment is allowed and expected to work. For some applications that works well, for others (especially API-on-API translation, depending on the source API) it can be pretty cumbersome.

**Comment by NicolBolas** [comment]
@critsec 

Wait: how is this "expected to work"? In a TBR for example, the depth buffer is just tile data, right? The texels outside of a tile may not even exist yet. Subpasses aren't supposed to force a full dump of TBR data to memory; that's what ending render passes is for.

It seems to me that what is "expected to work" is to be able to use the depth attachment as an *input attachment*. I mean, that's why input attachments were invented, right? To allow a fragment shader to read from the texel that was written by a previous subpass without having to break up subpasses.

**Comment by krOoze** [comment]
@NicolBolas Assumably, if both attachment and non-attachment accesses are read-only, then nothing prevents it? The only problem here are Subpass Layout Transitions, which technically are a potential write access. But if the layout stays the same the whole Render Pass, then it should be ok.

**Comment by NicolBolas** [comment]
@krOoze 

> Assumably, if both attachment and non-attachment accesses are read-only, then nothing prevents it?

How can you read data from tiles that haven't executed yet? Remember: the render pass architexture is intended to allow rasterization generated by a later subpass to execute even though rasterization from a previous subpass hasn't finished yet, so long as they're from distinct *tiles*. That is, an implementation of a renderpass ought to be able to do all of the geometry stuff for basically the *entire* render pass, then, for each tile, execute all of the rasterization on that tile. Hypothetically, at least; individual hardware may or may not be able to handle this for every workload.

If you can read from data generated by a different tile, then you can't do this. So if you're going to allow it, you need some kind of hard barrier built into the render pass architecture that says "all tiles must have finished rasterization up to this point, and all rasterization products must be in *actual GPU accessible memory* at this point in time". I don't believe any form of dependency in the current render pass system allows for that.

Well, except for the obvious: ending the render pass. In fact, that's what "ending the render pass" is *for*. That's *why* you can't do everything within a render pass.

**Comment by Kangz** [comment]
> How can you read data from tiles that haven't executed yet?

You can if the depth attachment is readonly (without subpass transitions) for the duration of the render pass: usage as an attachment will load in tile memory, and usage a sampled texture will fetch the same data again from VRAM. I believe that's why @critsec said:

> The spec does forbid it currently, but we're investigating whether we can state specific conditions under which it can be relaxed.

@kvark was asking about this in the context of WebGPU's [`depthReadOnly`](https://gpuweb.github.io/gpuweb/#dom-gpurenderpassdepthstencilattachmentdescriptor-depthreadonly) on the render pass descriptor (note that WebGPU render passes have only a single subpass). `depthReadOnly` is important for many things, for example to do local ray-tracing in the depth buffer for contact shadows (sampling path) while at the same time using the same depth buffer for occluding the light volumes (attachment path).

**Comment by krOoze** [comment]
@NicolBolas Because the original non-tiled `VkImage` still exists (or is the same thing in non-tiled architectures). Problem with render pass attachments is that you have potentially two copies, which need to be kept consistent and which can pollute each other. That's why attachment and non-attachment use at the same time is forbidden. But if both are kept the same (read-only access), then maintaining consistency is not a problem.

**Comment by NicolBolas** [comment]
> You can if the depth attachment is readonly (without subpass transitions) for the duration of the render pass: usage as an attachment will load in tile memory, and usage a sampled texture will fetch the same data again from VRAM.

OK, that's fair. But if you're going to do it, it has to be a property of the render pass attachment *itself*, not a transitory layout property. Otherwise, every transition into this layout will provoke tiles to fully resolve and store their data to the image's memory. And since people are already using this layout (for depth test and input attachment uses), that could be bad for their performance.

Overall, it shouldn't be something *invisible*; it's got to be something that's part of Vulkan itself. You have to ask for it, and VU rules should be able to exist that detect when you don't want it. It could be an attachment description flag: "VK_ATTACHMENT_DESCRIPTION_IS_IMMUTABLE_BIT" or somesuch.

**Comment by krOoze** [comment]
@NicolBolas IDK, `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` and `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL` are already allowed in both attachments and non-attachments. Only thing that remains is to allow it to be used in both at the same time? What is the perceived performance problem here? There would be no transition allowed, as transition is write access.

**Comment by NicolBolas** [comment]
@krOoze 

> IDK, `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` and `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL` are already allowed in both attachments and non-attachments. Only thing that remains is to allow it to be used in both at the same time for the same aspect?

For depth attachments, it is logically possible to read from it as an attachment and as a shader value without writing to it. You can do depth tests without doing depth writes.

But there is no equivalent read-only operation for color attachments. Yes, you can have pipeline mask off writes to the attachment, but if you do that, then you're not doing *anything* with the attachment, reading or writing. Since there's no read-only operation for color attachments, it doesn't make sense for immutable attachments to be able to be used as color attachments.

> That's perhaps a good idea though. Make a flag that prevents you to change layouts, and prevents to specify a clear op?

That's why I suggested making it an attachment description. But layout transitions wouldn't be altogether forbidden; layout transitions other than the first and last would be forbidden.

The main thing the immutability switch does is ensure that the state of the image data when it is loaded into a tile cannot differ from the state of the image data in GPU-accessible memory. So it is conceptually OK to transition into some layout for the duration of the render pass (the first subpass that uses the attachment can have a different layout from `initialLayout`), and you can transition to some layout after the render pass (the last subpass that uses the attachment can have a different layout from `finalLayout`), but every use of the attachment within the render pass must have the same layout.

So if we were to specify a more complete list of VUs, if `VkAttachmentDescription::flags` for an attachment includes `VK_ATTACHMENT_DESCRIPTION_IS_IMMUTABLE_BIT`:

* `VkAttachmentDescription::loadOp` must be `VK_ATTACHMENT_LOAD_OP_LOAD`. (neither clearing nor discarding makes sense if the attachment is immutable).
* All `VkAttachmentReference::layout`s which reference an immutable attachment must use the same layout as all other `VkAttachmentReference`s.
* The only valid `VkAttachmentReference::layout`s are the `READ_ONLY` depth/stencil layouts.

**Comment by krOoze** [comment]
> But there is no equivalent read-only operation for color attachments.

Yes, that is why I avoided talking about that one. The Input Attachment seems more obvious case.

Though to paraphraze B. Stroustrup, you know you have a great language if it is used in ways that surprise you. To play the devil's advocate, there might be sneaky ways the color attachment is read. Extensions might change something, so it matters. `pResolveAttachments` require the color attachment and read it. There might be some conditional rendering going on, that formally requires two color attachments, but writes to only one. And what if you write the R channel, but B channel is read-only? Blending technically reads the color attachment (and could read all channels, but write only some channels). You never know how will it be used...

Also for better or worse, people like null and dummy parameters in the API. It alows them to duct-tape stuff together, even if it does not necessarily make sense from performance perspective.

> layout transitions other than the first and last would be forbidden.

Not sure that would work. I think an obvious optimization is to make the initial layout transition be a fused operation with the load op. That means the original image in the general purpose memory might remain untransitioned, and so you have coherency problem.

Equally, the final layout transition would not work. Keep in mind the tiler streams tile-by-tile when doing store op. This means you could be storing (writing) a transitioned image data, while the same coordinates still may be sampled later (in non-attachment use) in a different tile.

**Comment by Kangz** [comment]
This seems to have been fixed in https://github.com/KhronosGroup/Vulkan-Docs/commit/f90136facacd25f016e523064f03713bdfe1b22d which is Vulkan 1.X.160. Can we close the issue?

**Comment by krOoze** [comment]
The spec does now say:

> For depth/stencil attachments, an aspect can be used separately as attachment and non-attachment if both accesses are read-only.

Although I am curious why the same is not allowed for color aspect.

Also it is bit unclear about some details. E.g. if the attachment gets unpreserved, does it count as write access?

**Comment by NicolBolas** [comment]
@krOoze 

> Although I am curious why the same is not allowed for color aspect.

It's probably what I mentioned before: there's no point to it. With depth/stencil, you can do read-only tests that affect the fragment from outside the FS. Namely, conditionally discarding the fragment.

By contrast, there is no way to conditionally discard a fragment on the basis of the color at the sample being written. All of the non-FS operations that read from the color attachment only have an effect to the extent that you *write* to that attachment too. Blending or bitwise operations don't have an effect if you mask off all color writes to that attachment.

So there's no point in allowing it.

**Comment by krOoze** [comment]
@NicolBolas The question is what's the point in forbidding it though? Conventionally one does not forbid read-read usages and does not enforce synchronizing them.

You could use the same image as input attachment, and also use it in something completely unrelated as say read-only storage image in some compute. And I don't immediatelly see why the two should be synchronized with each other. What's so inconceivable about such usage?

**Comment by NicolBolas** [comment]
> The question is what's the point in forbidding it though? Conventionally one does not forbid read-read usages and does not enforce synchronizing them.

Because that's not how tile-based renderers work. The whole point of the render pass&attachment model is that it forbids usages that would break the way TBRs work. An attachment is supposed to represent tile memory for such renderers. And you can't read from someone else's tiles.

In short: the *entire point* of having attachments is that you can't touch them with non-attachment operations while they're attached. As such, the question in this case is never "why forbid it"; it's "why *allow* it".

Because of the presence of non-shader uses of read-only depth and stencil operations that affect fragments, there is an actual use case for allowing render-pass-read-only attachment and non-attachment uses of them. But since all non-shader uses of color attachments are *write* operations, there is no actual use case to allow a render-pass-read-only attachment to be treated specially.

Given no reason to allow it, it ought to be forbidden.

> You could use the same image as input attachment, and also use it in something completely unrelated as say read-only storage image in some compute.

But you wouldn't *need* to do that. You could just not have it be an attachment and use it that way.

An input attachment isn't just a convenient way to not have to manually compute the right texture coordinate. It's supposed to represent accesses to tile memory, not to image memory. Tile memory is precious, and taking up a bunch of it just to avoid computing a coordinate is not a good way to use a TBR.

So forbidding this helps users avoid doing something sub-optimal.

**Comment by krOoze** [comment]
@NicolBolas Entire point of attachments is keeping coherence between on-chip memory and RAM. If there are no writes, there are no coherence problems.

> So forbidding this helps users avoid doing something sub-optimal.

AFAIK, using read-only attachments is not forbidden.

**Comment by NicolBolas** [comment]
> AFAIK, using read-only attachments is not forbidden, so the usage you consider sub-optimal is allowed.

What do you mean by a "read-only attachment" in this context? There are entire layouts for depth/stencil images to specify that they are both attachments *and* read-only. There is no such layout for color attachments.

So it is "allowed," but only in the sense that you can make an image a color attachment and only render with pipelines that mask off writes to it. At no point does the API define the concept of a read-only color attachment the way it does for read-only depth/stencil attachments.

**Comment by krOoze** [comment]
Reading color aspect as input attachments.

I don't pretend to know (with all the extensions) when it may come up for color attachments. But forbidding things "just because" in a foundational API is a dangerous business. Notably I think resolve is read-only op, and that is just vanilla Vulkan.

**Comment by NicolBolas** [comment]
> Notably I think resolve is read-only op, and that is just vanilla Vulkan.

This is a more interesting usage scenario, so let's unpack it. You have a multisample image whose data was *not* generated within this current render pass. As such, there are two possibilities:

1. The multisample data was generated by attachment means in a prior render pass.
2. The multisample data was generated by non-attachment means (`imageStore` operations or the like).

In case 1, you could have resolved it right after the rendering process which produced its data. In case 2, you could call `vkCmdResolveImage` to resolve it after generating its data. After all, attachment resolve operations exist to take advantage of tile-based multisample resolve processes, allowing MS images to be resolved within a tile efficiently. But if you didn't generate the data with a render process, there's nothing to be gained from doing the resolve in a tile compared to in memory.

But... there is one exception to both of these: transient images.

Obviously the multisample image in our case can't be transient (since it must maintain its data outside of a render pass). But the target of the resolve *may* be. You could resolve the MS image, use that as input to the next subpass, and write to a third image, with the resolved image being discarded when the render pass ends.

Now for case 1, I would still say that most of the time it is a net negative, as multisample images are (much) larger than single-sample ones. So carrying around all of that multisample data outside of the render pass just to resolve it as needed is unnecessary. In most cases, you could make the MS image the transient one, and the resolved image the one you carry between render passes. It is *possible* that you might need to read from the MS image post-resolve (attachment or non-attachment), but this is straining the bounds of genuine utility (ie: what are you doing that needs to do this?).

For case 2, there is a stronger argument to be made, as the source MS image *cannot* be transient. If you're only ever going to use the resolved image as an attachment, there's no need to keep it afterwards. So `vkCmdResolveImage` would be wasteful if transient allocations are available.

> But forbidding things "just because" in a foundational API is a dangerous business (as can be learned by all the structs that did not have pNext and had to be uglily remade).

Having simple, consistent rules makes the API easier to learn and teach; it is an advantage in and of itself. Simple rules (like attachments cannot be used in non-attachment ways during a render pass) should only be broken if there is a need. Not a hypothetical need, but an actual use case that provides real value to the user. The depth/stencil case provides actual value, and I still maintain that the color case does not.

If a feature comes along that makes this capability meaningful, then that feature can add appropriate read-only color attachment layouts and a carve-out for using them in non-attachment ways. But until then, you're talking about what seems to me to be an edge case. And it'd be better to spend precious time on things that give genuine value to users, not carve-outs for things that might hypothetically be useful someday.

**Comment by krOoze** [comment]
The interesting usage was meant to be the input attachments. Anyway, while we are already hopelessly derailed:

---

> Having simple, consistent rules

Having to care about read-only\constant memory is inconsistent specifically in Vulkan, and generally as multithreaded programming goes. So you are arguing exactly my point. It feels deeper justification is needed why it hard-cannot be done; but we are straying from that point.

Part of why I am asking is that it is so inconsistent I cannot even be sure it is intentional restriction in the first place.

>  it'd be better to spend precious time on things that give genuine value to users

Yes, generic excuse for lot of ills. But anyway, that is exactly my point also. Figuring out how something should be forbiden takes time (see your convoluted justification, and we covered only one feature interaction; what about conditional rendering?). Wording it so no one can weasel around and misinterpret the rules takes time. Making validation layers full of exceptions and obscurities takes time. All of it is highly error prone; which takes time from everybody.

Meanwhile the alternative is dead simple: "Read memory accesses never need to be synchronized with each other". Simple understandable no-nonsense common sense sentence. There's nothing there users can weasel around (it is already permissive). Nill extra validation needed...

---

So, only valid answer is to the question if it works on HW. Only problem I see here is `VK_ATTACHMENT_STORE_OP_DONT_CARE`, which might actually write. But validity of that assertion was brought into question by allowing depth or stencil aspect to be read outside render pass anyway. Which again is inconsistent that one memory is suddenly somehow better than another. And I am not sure it is clearly explained if you can read it while store op might be happening (see above about time spent making sufficiently careful spec wording).

**Comment by NicolBolas** [comment]
> Having to care about read-only\constant memory is inconsistent specifically in Vulkan, and generally as multithreaded programming goes. So you are arguing exactly my point. It feels deeper justification is needed why it hard-cannot be done; but we are straying from that point.

Remember, we're not talking about any old accesses here. We're talking about attachments. Vulkan started off with a blanket declaration:

> Image subresources used as attachments must not be used via any non-attachment usage for the duration of a render pass instance.

*That* is the "simple rule". No question of read-only or whatever. Attachments can't be used as non-attachments. The End.

This became complicated because of the complexity of depth/stencil images. These images effectively package two images into one. So it is reasonable to consider wanting to use one aspect of the image as an attachment and the other aspect as not-an-attachment for read-only purposes. So a carve-out of the simple rule was made in KHR_maintenance2.

Note the specifics of the carve-out: the attachment aspect *can be written to*. It's only the non-attachment aspect that can't. The carve-out isn't about "read-only\constant memory". It's about the API doing its best to pretend that one image is really two, thereby allowing you to use one image as if it were two (within restrictions).

The kind of thing you're talking about derives from this:

> For depth/stencil attachments, an aspect can be used separately as attachment and non-
attachment if both accesses are read-only.

*That* is relatively recent, and is a direct result of this bug report. It took a very simple rule (don't use attachments as non-attachments), that had a very specific carve-out (depth/stencil images can sometimes be treated as two images) and complicated it. It *created* the concept of a "read-only" attachment.

So you're basically saying "now that we over-complicated a simple thing, we should keep going and over-complicate it further".

> Meanwhile the alternative is dead simple: "Read memory accesses never need to be synchronized with each other". Simple understandable no-nonsense common sense sentence. There's nothing there users can weasel around (it is already permissive). Nill extra validation needed...

Except now you have to define a bunch of other things. What constitutes a "read memory access"? How do you know when you're doing a "read memory access" (remember: the first depth/stencil carve-out added layouts that guard against non-read accesses to the non-attachment aspect). What is considered "synchronization" with regard to attachment and non-attachment uses? How do you synchronize non-attachment uses with attachment uses (that's not really a thing at present, because you can't do both at the same time)?

I'd much rather have "don't use attachments as non-attachments". It's much simpler and there's nothing to explain beyond this.

> So, only valid answer is to the question if it works on HW.

If there is no productive end to a particular piece of hardware, there is no point in doing that thing. Especially if it causes other problems, as previously discussed.

You effectively want to remove the blanket "don't use attachments as non-attachments" prohibition and replace it with... well, making attachments not be attachments. You're essentially trying to gut render passes, to bypass the abstraction. To make it solely about "synchronization" and expose whatever the hardware can do.

That's bad.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.205 spec update.
