### ISSUE TITLE
Memory alignment requirements for images with same creation parameters

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1369]
If two images are created with identical VkImageCreateInfo, is there any guarantee that the vkGetImageMemoryRequirements will return requirements with the same alignment?

**Comment by sfricke-samsung** [comment]
Under the `VkMemoryRequirements` struct you will see the section with

> The implementation guarantees certain properties about the memory requirements returned by vkGetBufferMemoryRequirements2, vkGetImageMemoryRequirements2, vkGetBufferMemoryRequirements and vkGetImageMemoryRequirements:

Here it describes that

> The alignment member is identical for all VkBuffer objects created with the same combination of values for the usage and flags members in the VkBufferCreateInfo structure passed to vkCreateBuffer.

But doesn't make the guarantee for `VkImages`. As for if that is intended or not, we will bring up in the next internal Working Group meeting

**Comment by sfricke-samsung** [comment]
@konstantinegorov To confirm from the Working Group meeting,

`no` - The alignments are not guaranteed to be the same

We are going to more internal investigations and see if this can be lifted, but until then, you will have to not make any guarantee

**Comment by TomOlson** [comment]
@konstantinegorov thanks for raising this. We've put it on an internal list of minor annoyances to be fixed in a future core spec.  We don't think it can be fixed any earlier, because there are implementations in the wild that don't make the desired guarantee, and it seems too fiddly for an extension. I'll close this, but feel free to reopen or raise a new issue if you have further questions.
