### ISSUE TITLE
vkGetInstanceProcAddr return value for NULL instances

### ISSUE THREAD

**Issue by jpark37** [KhronosGroup/Vulkan-Docs#1373]
I am seeing other layers in the wild expecting function pointers when vkGetInstanceProcAddr is called with parameters such as (NULL, "vkCreateDevice"). This input combination seems to correspond to the last entry of the table in the documentation, which says to return NULL. If I create a layer that returns NULL in the situation, a misbehaving layer may dereference it, which users may blame on me because the problem only occurs when my layer is installed.

There is some discussion in the Khronos Slack about modifying the loader to make this spec violation more obvious, but that may or may not cause more breakages than desired. This issue should probably get addressed one way or another though.

In the meantime, I think the best course of action for my layer is to ignore the spec and return a function pointer rather than NULL.

**Comment by sfricke-samsung** [comment]
So if you look at the [vkGetInstanceProcAddr](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vkGetInstanceProcAddr) in the spec, there is a table describing the behavior and if you look `vkCreateDevice` is not on that list and according to the spec a layer should return `NULL` in that case.

if a layer is not calling
`vkGetInstanceProcAddr(valid_instance, "vkCreateDevice");`
that layer is at fault. While your layer might get blamed, I feel that is a general software problem in general of knowing who to blame.

cc @lenny-lunarg for "modifying the loader" part

**Comment by jpark37** [comment]
It was suggested to update loader_gpa_instance_internal to return NULL for these situations like the trampoline function does, which will help a layer author realize their mistake if they are the last last layer.

Other layers may be at fault, but I don't think users care. They just want everything to work, which is why we will return a function pointer in our layer for the time being.

**Comment by jpark37** [comment]
We actually were doing the wrong thing before, but I did a cleanup pass to conform to the spec, and that backfired on me a bit.

This is the PR to do what we were doing before: https://github.com/obsproject/obs-studio/pull/3549

**Comment by sfricke-samsung** [comment]
Talked today on the working group call, decided that the reality is that the layer is doing invalid and the defined behavior is that you return NULL and there isn't much to fix about that.

With that, @critsec discussed the idea of having the loader in fact adding logic not to correct this mistake, but to log an error in a way to assert blame to help layer authors write valid code. (still cc Lenny on this)

**Comment by lenny-lunarg** [comment]
Making the loader force a null pointer seems reasonable to me. It seems like a low-cost way to make the app-facing behavior correct. We usually just pass along function pointers from layers/ICDs so that we can support extensions that the loader doesn't recognize. But that doesn't matter here, since even for an unrecognized extension we want to get null.

My only concern here is that this seems likely to encourage people in writing misbehaving layers that don't do what they should. As much as I'd like to avoid that, it sounds like that ship has sailed already.

**Comment by jpark37** [comment]
Sorry, what's your concern? I'm not sure what your pronouns are referring to exactly.

We can't realistically ship with a NULL return. Maybe we can unpeel the hack in a few years if layer authors catch on and pass in a valid instance, but as the ecosystem is right now, forcing crashes on our users for legality's sake is an invitation to use a competing product.

**Comment by lenny-lunarg** [comment]
> We can't realistically ship with a NULL return

My concern was that we'd be making it so that people are able to ship with a null return, which is what we're doing unless I'm mistaken. But I think that's a minor concern compared to just trying to make the system work well together. And if more people than you are shipping layers that do this, then it sounds like we have to work around them for better or worse.

**Comment by jpark37** [comment]
Wait, returning NULL is the "right thing" though? The "we" in that quote was as a layer author, not Vulkan open-source participant. Maybe lets start over.

If an application attempts to call vkGetInstanceProcAddr with a NULL instance, the loader intervenes and returns NULL unless the desired function is specified to not need a valid instance. No layer or ICD even gets involved for this case.

There are layers calling vkGetInstanceProcAddr on the next layer with a NULL instance, and expecting a non-null function pointer. This goes against spec. If this layer is the last layer, the loader does not have the same early return, and probably forwards the request to the ICD, which may incorrectly return a valid function pointer, masking the spec violation. (This is my assumption. I have not verified this.) The loader can be modified for the last layer case to return NULL before asking the ICD, but this will generate crashes for end users at driver upgrade time when the stricter loader is deployed, and comes in contact with bad layers.

The layer I'm working on briefly attempted to return NULL, not realizing these other layers with invalid expectations existed. We are now violating spec by returning a valid function pointer where we can to maintain compatibility with these troublesome layers.

**Comment by pdaniell-nv** [comment]
@jpark37, for your layer's vkGetInstanceProcAddr implementation, can't you just pass the parameters to the next pfnNextGetInstanceProcAddr in the chain and not worry about enforcing any kind of Vulkan rules?

**Comment by jpark37** [comment]
I don't think there's a way to get pfnNextGetInstanceProcAddr when instance is NULL. We can pick an instance from our cache at random, but that seems like a bigger hack than what we're doing.

**Comment by pdaniell-nv** [comment]
> I don't think there's a way to get pfnNextGetInstanceProcAddr when instance is NULL. We can pick an instance from our cache at random, but that seems like a bigger hack than what we're doing.

Yes, you're correct. I overlooked that you don't have access to the nextGetInstanceProcAddr when there instance is NULL.

**Comment by lenny-lunarg** [comment]
I've been getting a bit confused with this conversation, especially since I think we basically agreed in the first place. So going back to the initial thought, I'll go ahead and modify `loader_gpa_instance_internal` to make it return NULL in the case that was originally given, which should make any loader that is the last see the error. I do want to do some testing to see what this does to existing layers, so I'll probably just open it as a pull request on the loader repo while I test it against a bunch of layers.

This will mostly just change the behavior when a layer is last in the ordering, but that is the normal case when someone is writing an explicit layer, so I think it should catch the most common trouble point. Once I've tested this change properly, then I can figure out if I think it's a good idea to merge it into master (which I think it probably will be). I should be able to get that change up and start testing it around the middle of next week.

**Comment by jpark37** [comment]
Maybe we were on the same page, and I read something backwards.

The only issue with returning NULL there is that users with previously working games will be greeted with crashes as as soon as they upgrade their loader, presumably when they upgrade their video drivers, if a buggy layer happens to be last in the chain.

**Comment by lenny-lunarg** [comment]
Adding on to this from Monday's working group discussion, I'm going to continue to do what I outlined in my last post. We think that will be useful and I'll post here when I have that implementation. We also discussed the possibility of adding a sort of loader safe mode. I've opened a loader issue [here](https://github.com/KhronosGroup/Vulkan-Loader/issues/513) to discuss that. The safe mode wouldn't directly change any of the behavior here, but it would be an extra mechanism to help isolate and work around misbehaving layers. Any comments on that idea should probably go on the loader issue.

**Comment by pjaholkowski** [comment]
Pardon me because I think that I didn't undertand you all correctly.
Let's summarize

You wrote vkGetInstanceProcAddr in your layer to be compatible with specification
so in case of calling vkGetInstanceProcAddr(VK_NULL_HANDLE,"vkCreateDevice") you return NULL
which causes calling null pointers in vulkan layers before your layer.
Then in that case why in https://github.com/obsproject/obs-studio/blob/master/plugins/win-capture/graphics-hook/vulkan-capture.c OBS_CreateDevice you call:
PFN_vkCreateDevice createFunc = (PFN_vkCreateDevice)gipa(VK_NULL_HANDLE, "vkCreateDevice");

That's my first question

And here's the second. If doing such thing is incompatible with specification why all layer samples
shipped in VulkanSDK have the same mistake https://github.com/LunarG/VulkanSamples/blob/master/Layer-Samples/Overlay/overlay.cpp ?

**Comment by jpark37** [comment]
Well, that's embarrassing. In my weak defense, I didn't write that particular line, but it should have occurred to me to look when I saw other people doing it. We'll get that squared away soon: https://github.com/obsproject/obs-studio/pull/3700

Apparently there was a code example that people were copy/pasting at one point: https://github.com/KhronosGroup/Vulkan-Loader/issues/442

**Comment by pjaholkowski** [comment]
Not only you made that kind of error https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
It is obvious there is a lot more cases like that because sane persion does not read 600 pages of documentation to find
out why code is working. Sane person copies working example changes it to fit his needs and reads 600 pages of documentation
when it does not work 

In my opinion while calling vkGetInstanceProcAddr(VK_NULL_HANDLE,"vkCreateDevice") is wrong, handling that
case and returning NULL pointer in vkGetInstanceProcAddress of vulkan layer is pure evil. There is two main reasons for that

1. It will crash old not updated any more vulkan layers which worked before. 
2. It is not role of every vulkan layer to check if calls are compatible with vulkan specification (you don't do that with every other call). It is role of vulkan validation layer. When you return null pointer in your layer but program runs with validation layer it won't show any sort of error or warning message because of that.

**Comment by KarenGhavam-lunarG** [comment]
> And here's the second. If doing such thing is incompatible with specification why all layer samples
shipped in VulkanSDK have the same mistake https://github.com/LunarG/VulkanSamples/blob/master/Layer-Samples/Overlay/overlay.cpp ?

Acknowledged. Actually the overlay sample no longer builds (hasn't for a long time). But we erronously had not removed the file from the repository or the SDK. This will be fixed.

**Comment by lenny-lunarg** [comment]
I'll mention first that I made a post [this morning](https://github.com/KhronosGroup/Vulkan-Loader/issues/513#issuecomment-800441404) on the loader safe mode issue about ways to improve the behavior of the loader and implicit layer handling. I think that will help the overarching problem of  in that it would make default layer behavior more manageable. I know @jpark37 has already commented on that, but since it's related I wanted to point that out if anyone else didn't see it.

**Comment by lenny-lunarg** [comment]
I think that it's not worth making the change to the null behavior. The loader can only implement a partial fix because the behavior is dependent on layer ordering. The full fix would be to implement a layer test suite.

In addition, this is a subtle change to loader behavior that creates a corner case that we don't have a way to test. As a result, it's exactly the kind of thing I'd be worried about regressing in the future. 

I'm proposing to close this issue.

**Comment by jpark37** [comment]
Well, I don't have any bright ideas either. Closing.
