### ISSUE TITLE
Immutable samplers and descriptor pool

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1395]
Is it necessary to reserve space in the descriptor pool for immutable samplers?

**Comment by jekstrand** [comment]
Yes, you do.  Depending on the implementation, an immutable sampler may be something that's somehow baked into the pipeline and therefore doesn't take space or it may be a regular sampler that the implementation binds for you.  In the later case, it does take room in the descriptor set so, from an application perspective, you have to assume that they take space and reserve descriptors in the pool.  Even though they don't save you any descriptors, still useful because, for implementations which can embed them in shaders, they're a bit faster.

**Comment by oddhack** [comment]
@konstantinegorov if that answered your question, please close the issue.

**Comment by konstantinegorov** [comment]
Thanks for answer.
