### ISSUE TITLE
VK_EXT_image_drm_format_modifier: how to invalidate imported VkImage?

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/Vulkan-Docs#1445]
Some drivers need to know when an imported image has changed, because they may do some copies on import (e.g. etnaviv).

The use-case is:

- Client submits a DMA-BUF to the compositor
- Compositor imports a DMA-BUF as a `VkImage`
- Client updates the underlying buffer, e.g. redraws
- Compositor re-uses the same `VkImage`

With OpenGL, compositors are expected to re-create the GL texture (but can re-use the same `EGLImage`).

What should a Vulkan compositor do to signal to the driver that the image needs to be invalidated?

cc @cubanismo @fooishbar @bnieuwenhuizen @chadversary @jekstrand

**Comment by chadversary** [comment]
If I correctly understand your use case, then this is outside the scope of Vulkan and is instead in the domain of the client-compositor protocol (such as Wayland or X11).

Also, the question here is really about VkImages that are backed by a dma-buf (that is,this is about `VK_EXT_external_memory_dma_buf`); the question is orhtogonal to `VK_EXT_image_drm_format_modifier`. The two extension specifications are orthogonal and do not depend on each other. (Of course, the expected use case today is to use `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT` and `VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT` together; but in theory you could just as easily use modifiers with `VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT`).

Forgetting about dma_bufs for a moment, consider how VkSwapchain and vkQueuePresentKHR work. The client updates the pixels in a VkImage; then the client calls vkQueuePresentKHR, which communicates to the compositor that the image's underlying buffer now has updated contents and is ready for presentation. For example, see the `wl_*` calls in `mesa:src/vulkan/wsi/wsi_common_wayland.c`.

For a VkImage whose VkDeviceMemory is backed by a dma-buf, the situation is similar. The difference is the client must explicitly send the compositor protocol that would have otherwise been sent by vkQueuePresentKHR.

Compared to EGLImage, this sounds like a lot of additional work, with more room for error. But one of the goals when I designed the `VK_EXT_image_drm_format_modifier` specification, a goal shared by others in Khronos too, was to expose enough internals so as to allow clients to effectively re-implement vkQueuePresentKHR.

**Comment by emersion** [comment]
This issue is from the compositor's point of view, not from the client's point of view.

> Also, the question here is really about VkImages that are backed by a dma-buf (that is,this is about VK_EXT_external_memory_dma_buf

Yes, that is correct. I guess it also applies to any imported external memory, not necessarily just DMA-BUFs.

> If I correctly understand your use case, then this is outside the scope of Vulkan and is instead in the domain of the client-compositor protocol (such as Wayland or X11).

Not really. This issue is about Vulkan guarantees wrt. external memory changes. If I import external memory, when can I expect external changes to be visible on my `VkImage`? How can I ensure that I don't sample from an outdated backing storage when I use a `VkImageView`?

The answer on GL is: re-create the texture from the imported `EGLImage`. I'm looking for the Vulkan equivalent of this.

> Forgetting about dma_bufs for a moment, consider how VkSwapchain and vkQueuePresentKHR work. The client updates the pixels in a VkImage; then the client calls vkQueuePresentKHR, which communicates to the compositor that the image's underlying buffer now has updated contents and is ready for presentation.

Yes, but how does a compositor using Vulkan tells the driver that the image's underlying buffer has been updated?

**Comment by BNieuwenhuizen** [comment]
Isn't this what a vkPipelineBarrier with `srcQueueFamilyIndex` of `VK_QUEUE_FAMILY_FOREIGN_EXT` or `VK_QUEUE_FAMILY_FOREIGN_EXT` is for?

**Comment by chadversary** [comment]
> > If I correctly understand your use case, then this is outside the scope of Vulkan and is instead in the domain of the client-compositor protocol (such as Wayland or X11).
> 
> Not really. This issue is about Vulkan guarantees wrt. external memory changes. If I import external memory, when can I expect external changes to be visible on my `VkImage`? How can I ensure that I don't sample from an outdated backing storage when I use a `VkImageView`?
> 
> The answer on GL is: re-create the texture from the imported `EGLImage`. I'm looking for the Vulkan equivalent of this.

Ah, I didn't fully understand your question. Thanks for clarifying.

In Vulkan, system-wide, at any moment, an external image has at most one owner. (I don't recall if the Vk spec documents that. If it does, it's at <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-queue-transfers>). As Bas said, the ownership transfers to/from a `VkDevice` are managed with `VkImageMemoryBarrier::{src,dst}QueueFamilyIndex` with, in general, `VK_QUEUE_FAMILY_EXTERNAL_KHR` and `VK_QUEUE_FAMILY_FOREIGN_EXT`.  Since you're using `VK_EXT_image_drm_format_modifier`, then the correct choice is `VK_QUEUE_FAMILY_FOREIGN_EXT`, not `EXTERNAL`.

Does that answer your question? Did I overlook anything?

**Comment by emersion** [comment]
Indeed, `VK_QUEUE_FAMILY_FOREIGN_EXT` seems like what I'm looking for. Thanks both!

**Comment by cubanismo** [comment]
While I agree with most of the above, I don't follow why QUEUE_FAMILY_FOREIGN is necessarily implied by format modifiers (Vs. QUEUE_FAMILY_EXTERNAL). The NV format modifiers are set up such that a transfer to the external queue will be sufficient providing the compositor is running on the same device as the client. Given the rather dramatic perf implications of foreign Vs. external, I would hope some effort would be made to allow the client to discover such cases.

**Comment by emersion** [comment]
> uses the same driver version

This requirement is enough to rule out EXTERNAL for the use-case of a Wayland compositor. Even if a compositor had a way to check that the DMA-BUF comes from the same underlying physical device (I don't believe there's a way to know this yet), there's no guarantee that the client uses the same driver (e.g. GL vs. Vulkan).

**Comment by emersion** [comment]
I guess there could be a mechanism to pass around the Vulkan device/driver UUIDs. Not sure it's really worth the effort.

**Comment by cubanismo** [comment]
For my XDC talk two years ago I ran some experiments on NV hardware and it was a very large percentage (~50% if I'm remembering right) perf improvement specifically for simple things like UIs. Seems worth the effort to me. EXTERNAL is essentially a no-op on our hardware, FOREIGN is very heavy.

GL Vs Vulkan or any other graphics API is fine, as long as they're advertising the same driver UUID.

**Comment by emersion** [comment]
Ah, is this UUID thing supported by OpenGL as well?

**Comment by emersion** [comment]
Nevermind, it seems like it's defined here for GL: https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_external_objects.txt

**Comment by swick** [comment]
Since clients could lie about the UUID we would need some guarantee that using EXTERNAL when it's actually FOREIGN doesn't result in undefined behavior if we were to use EXTERNAL in compositors.
