### ISSUE TITLE
Typos: Chapters 00-13 of the KHR-only build of specification

### ISSUE THREAD

**Issue by naiveforce** [KhronosGroup/Vulkan-Docs#1482]
[vkspec_00_13.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6211369/vkspec_00_13.pdf)

**Comment by oddhack** [comment]
Thanks! Would you have any easy way to filter out just the PDF pages containing your comments? I don't have access to anything but Linux-based tools and don't see how to use e.g. evince or xpdf to do this.

**Comment by naiveforce** [comment]
Commented pages only against spec version 172.
[vkspec_00_13_comms.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6212054/vkspec_00_13_comms.pdf)

**Comment by oddhack** [comment]
Thanks for doing all this painstaking review! I will fix these up, or ping you if there are concerns about any specific fixes.

**Comment by oddhack** [comment]
For VkWin32KeyedMutexAcquireReleaseInfoKHR, you comment "keyed mutex object" rather than "keyed mutex" in a couple of places. I looked at the DXGI documentation, which is surprisingly sparse, and it also seems to have inconsistent use of ["keyed mutex"](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nn-dxgi-idxgikeyedmutex) vs. ["keyed mutex object"](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgikeyedmutex-acquiresync). Not sure what's right. The underlying objects are only accessible via the key "handle" AFAICT.

**Comment by naiveforce** [comment]
To be honest: If you would have asked me the question 2 months ago, I'd have given a straight answer right of the bat. The only thing that I can come up with now is: simply for consistency and semantic reasons (to clearly differentiate form "mutex key values" which are referred to in the descriptions of parameters in question). Use whatever you like: handle or object (but IMO object is better suited for this particular context), but bare "keyed mutex" sounds to ambiguous.

**Comment by Tobski** [comment]
Hi @naiveforce - thanks for your review! I'm looking at fixing some of the points you've brought up, and came across one I didn't quite understand.

In your comment on the description of VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT_KHR you've suggested that EARLY_FRAGMENT_TESTS shouldn't be included because that stage "should not perform write accesses". However this stage very much can (and does) perform write accesses - is there some text in the spec that has lead you to believe otherwise?

**Comment by naiveforce** [comment]
It might have come from my past experience: I come from an era in which taking advantage of early fragment tests was predicated on making the appropriate bitplanes of a framebuffer read only or otherwise restricted -- sorry.
In either case I will keep that in mind during my next thorough read of the specification and report back, if there really is something that reinforced my belief in that matter.

**Comment by Tobski** [comment]
Ok thanks for the clarification - I'll leave that description alone for now then! But yea absolutely if you see something suggesting otherwise please do point it out.

**Comment by oddhack** [comment]
Closing this - all the low-hanging fruit should be addressed in the 1.2.178 spec update. There are some remaining issues that need a slightly higher level of oversight or work to resolve and will roll out gradually as that happens, and (as mentioned elsewhere) some that we don't think require any action (in particular, occasional references to vendor extensions from the KHR-only spec). Again, thanks very much for doing this very detailed review!
