### ISSUE TITLE
Typos: Chapters 36-AI of the KHR-only build of specification

### ISSUE THREAD

**Issue by naiveforce** [KhronosGroup/Vulkan-Docs#1484]
[vkspec_36_AI.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6211412/vkspec_36_AI.pdf)

**Comment by naiveforce** [comment]
Commented pages only against spec version 171
[vkspec_36_AI_comms.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6212071/vkspec_36_AI_comms.pdf)
.

**Comment by oddhack** [comment]
I'm working my way through this now and it will appear in an update in a couple of weeks. Most of this is well-taken and will be done (also, we did a related restructuring of the limits & features chapters to achieve uniform phrasing throughout, and that bypassed some of the comments). For suggested fixes we end up not doing, a general explanation of why is that trying to write asciidoctor conditional markup that comes out exactly right under every possible combination of core versions and extensions gets incredibly verbose and tedious to write, and sometimes we judged that not worth the trouble. So stuff like space-before-comma, references to extensions not included in the spec build at issue, an apparently extraneous structure name (VkPhysicalDeviceRayTracingPipelinePropertiesKHR::maxRayRecursionDepth, to disambiguate from another extension's limit of the same name) in a limits table are examples of this. Standalone SPIR-V validation we chose not to conditionalize exactly because it's standalone - perhaps the introductory paragraph of the section could speak more clearly to this, though.

**Comment by naiveforce** [comment]
Appreciate every fix that made trough the "due-to-automation" filter. Thank you.

**Comment by oddhack** [comment]
Much of this has been addressed in the 1.2.176 spec update. Some points that were a bit more complicated than I have scope to resolve myself have been raised as separate internal tracker issues. If it's OK with you I'd like to close this now and roll out the point issues as they get resolved.

**Comment by naiveforce** [comment]
Less distractions == easier read. Much appreciated, thank you.
