### ISSUE TITLE
Why does VK_EXT_global_priority not have a properties struct?

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Docs#1488]
Implementations of `VK_EXT_global_priority` may deny requests to acquire a priority above the default priority (`VK_QUEUE_GLOBAL_PRIORITY_MEDIUM_EXT`) if the caller does not have sufficient privileges. Why is there no way to query if `HIGH_EXT`/`REALTIME_EXT` queues can created for a physical device? Having to call `vkCreateDevice` to see if it succeeds is a very unusual way to expose optional features.

**Comment by critsec** [comment]
This is an issue we've been looking at internally in the WG, but haven't been able to solve adequately. Details vary with OS, but there are basically two problems:

1. The privilege check is sometimes enforced by the OS, and the driver doesn't always have a way of checking without just trying to create the queue. We wouldn't want drivers to create and then tear down an OS-level queue to be able to answer this query.

2. More fundamentally, the privilege is often dynamic, so there is a race condition between asking whether you can use a particular priority, and then actually creating the queue. So even if the query says you have permission, the queue creation might still fail because of the permission check. This is likely the same rationale why the OS doesn't offer such a query for drivers to use.

It doesn't solve this specific problem, but we do have an extension in flight that allows querying which priority levels are actually distinct in a particular implementation, per queue family. So for example, an implementation could report that a compute-only queue family only really supports `MEDIUM` priority, while a graphics+compute+transfer queue family handles `LOW`, `MEDIUM`, and `HIGH` (but not `REALTIME`) as distinct priorities.
