### ISSUE TITLE
Can't add labels to issues

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#15]
In the spec, "Filing Bug Reports" says:

> Please tag issues with appropriate labels, such as “Specification”, “Ref Pages” or “Registry”, to help us triage and assign them appropriately.

But unless I'm being really dumb and failing to understand GitHub's UI, there is no way for me to add labels to new or existing issues. Perhaps it's some permissions thing?

**Comment by salamanderrake** [comment]
it the titles you could do [Specification] [Ref Pages] or [Registry] so its like a tag.

**Comment by salamanderrake** [comment]
I take it back, it seems others are able to add tags to there issues.

**Comment by salamanderrake** [comment]
see if you can ad a Labels, its on the right, at this time it says 
Lables
None yet.
try adding a label.

**Comment by mdsitton** [comment]
on my issues @oddhack added the labels... i'm also unable to add them as well.

**Comment by baldurk** [comment]
Github only allows people with write access to the repository to apply labels (see [collaborator access permissions](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) ). I guess it would be too open to abuse otherwise. Unfortunately, the permission is not fine-grained and only Khronos people could be made collaborators.

**Comment by alonorbach** [comment]
Thanks for raising this issue. We need to decide how to cope with GitHub's blunt read vs write permissions. isaacs/github#311 would help make this easier.

For now, it seems we can't grant label-setting permissions without also giving permissions to delete pull requests and close issues - which would not be workable. Recommend we push for a more fine-grained permission system, and meanwhile, use text tags in the title as @salamanderrake suggests.

**Comment by oddhack** [comment]
My error - this worked for our internal git servers, but I didn't realize the problem with public projects. Agreed with @alonorbach as this appears the best that can be done, at the moment (hopefully some github experts will chime in at this point).

**Comment by oddhack** [comment]
@alonorbach I went to the repo as a non-logged-in user and could not even *see* the applicable labels in the selection interface on the right side. So unless we can find a clever way of describing the labels we have, we can't even reasonably ask people to put [labelname] in the headers, because they won't know what they are :-( We could point them to the pulldown "Labels" filter on the issue summary page, I guess. There are some apparently-standard github labels but they're completely unrelated to the labels I put in the internal server that are Vulkan-specific.

**Comment by salamanderrake** [comment]
Two things, first let people create there own [Text Here] lables and go with it, most who know use stuff like [Bug] [BUG] [LINUX] [Linux] and what ever, but also you can in the same place you told us to use labels what labels you want,  like  [Specification] [Ref Pages] or [Registry] .

**Comment by salamanderrake** [comment]
Then you guys can come around and manually attach labels to what ever you think is valid so people can use the label search feature.

**Comment by mdsitton** [comment]
I'd rather not have [LABEL HERE] type labels in titles because its a pain not everyone will follow it, and it doesn't change anything really.

**Comment by oddhack** [comment]
I added a note in section 1.2, which is the best we can do for now. I've asked our admin to take this up with Github but am not aware of any better options at present, so closing this.
