### ISSUE TITLE
Acceleration Structure Capture replay questions

### ISSUE THREAD

**Issue by rumblehhh** [KhronosGroup/Vulkan-Docs#1513]
The following primarily concerns a few aspects of Vulkan's capture/replay features.

A note in the spec given for the usage of VkAccelerationStructureCreateInfoKHR reads as follows:

"
The expected usage for this is that a trace capture/replay tool will add the VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT flag to all buffers that use VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT, and VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT to all buffers used as storage for an acceleration structure where deviceAddress is not zero. During capture the tool will save the queried opaque device addresses in the trace. During replay, the buffers will be created specifying the original address so any address values stored in the trace data will remain valid.

Implementations are expected to separate such buffers in the GPU address space so normal allocations will avoid using these addresses. Apps/tools should avoid mixing app-provided and implementation-provided addresses for buffers created with VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT, to avoid address space allocation conflicts.
"

The section "and VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT to all buffers used as storage for an acceleration structure where deviceAddress is not zero" 

Firstly I find it odd that this note specifies "used as storage for an acceleration structure" rather than VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR. I assume this happened as VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR was only added in the v11 rework and was missed during the update?

Second and more importantly I find this section slightly unclear. Does this refer only to replay time where deviceAddress is not zero i.e. the acceleration structure device address has been captured using vkGetAccelerationStructureDeviceAddressKHR? If so at capture time the buffer (used as storage for an acceleration structure) may potentially not specify VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT as part of its usage flags meaning vkGetBufferOpaqueCaptureAddress* cannot be used to retrieve its device address meaning there is no device address to use for this same buffer at replay time. Its a little odd to require VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT for these buffers only at replay time only for the buffers to not have any captured opaque handle to make use of.

Should this section also refer to capture time? Something like "and VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT to all buffers that specify VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR as part of their usage"?
Although the issue with adding VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT to all buffers specifying VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR is vkBindBufferMemory currently specifies the following:
"
VUID-vkBindBufferMemory-bufferDeviceAddress-03339
If the VkPhysicalDeviceBufferDeviceAddressFeatures::bufferDeviceAddress feature is enabled and buffer was created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT bit set, memory must have been allocated with the VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT bit set
"

Unless I'm missing something this requirement would then imply capture/replay tools would have to add VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT to all memory allocations to ensure future buffers can be created safely and without violating memory requirements for buffers using VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT?

Its also interesting that vkGetDeviceMemoryOpaqueCaptureAddress* doesn't specify that the memory must have been allocated with VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT/VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR.
vkGetBufferOpaqueCaptureAddress also doesn't specify explicitly that buffers must have been allocated with VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT although this behaviour is implied by the Note given in VkBufferOpaqueCaptureAddressCreateInfo.

**Comment by dgkoch** [comment]
See Internal issue 2769 for discussion

**Comment by dgkoch** [comment]
(summarizing from internal discussions)

To do capture/replay on the AS, the tool needs to do capture/replay on the underlying buffer. Doing so requires the tool to get the address of that buffer, so the tool has to add VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT  even if it doesn't otherwise need the address so that it can supply it on replay.

> Does this mean that the address supplied via VkAccelerationStructureCreateInfoKHR::deviceAddress is queried during capture with vkGetBufferOpaqueCaptureAddress, and not with vkGetAccelerationStructureDeviceAddressKHR?

The replay address for the buffer is queried using vkGetBufferOpaqueCaptureAddress and the replay address for the AS is queried using vkGetAccelerationStructureDeviceAddressKHR - each should use its corresponding type of address.

> If so, a side question that I'm having is whether VkAccelerationStructureCreateInfoKHR::deviceAddress is just the base address of the buffer or if it also includes VkAccelerationStructureCreateInfoKHR::offset.

The address of the acceleration structure includes all information required to process that acceleration structure. In a purely flat, address-based implementation, it'd be reasonable for the AS device address to be equal to the buffer device address plus the offset, but the address spaces aren't guaranteed to act that way - each one is its own unique handle.

We are enhancing the above quoted note with the following as the second sentence:

> This also means that the tool will need to add ename:VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT
to memory allocations to allow the flag to be set where the application may
not have otherwise required it.

Closing as this will be in the next spec update. (~1.2.192)
