### ISSUE TITLE
VK_KHR_sampler_ycbcr_conversion: 

### ISSUE THREAD

**Issue by Peace569** [KhronosGroup/Vulkan-Docs#1519]
Hello,@fluppeteer 
How can I compress the buffer using C# and vulkan ?
So I am going to increase the quality of video .
Could you help me ?
Regards.

**Comment by fluppeteer** [comment]
Hi @Peace569.

I suspect I'm not the best person to help, and this repository is really intended to help resolve issues with the official Vulkan documentation rather than providing general guidance - but if I can point you in the right direction, I'm happy to try.

VK_KHR_sampler_ycbcr_conversion just covers a range of standard image formats (either with separate image planes or with downsampled chroma information, or both) and the ability to access those formats in a shader, with optional conversion to a "normal" RGB representation. These formats are typically used for video processing, partly because reducing the resolution of chroma saves bandwidth with little perceptual quality reduction, partly because processing the channels separately tends to be useful.

The actual hardware decoding of video is available separately using a provisional extension (which means it might change, so don't release code using it yet) - see https://www.khronos.org/blog/an-introduction-to-vulkan-video. I hope that might be what you're looking for?

Does your mention of C# mean you're using MoltenVK? I'm not sure how much is exposed in Vulkan portability, and when or if hardware video decode support might be available.

"Increase the quality of video" suggests that you have some quality to improve? What are you trying to achieve? Visually better video processing? Better performance? Better support for different encodings?

I hope that helps; if you are able to share more information, I might be able to give more specific pointers.

**Comment by oddhack** [comment]
@Peace569 could you close the issue if you've been answered, or follow up otherwise? Thanks.

**Comment by fluppeteer** [comment]
It's been a month, so I'm going to assume @Peace569 is okay with other documentation and this can be closed.
