### ISSUE TITLE
VkColorSpaceKHR enum name inconsistency

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#153]
1.0.7 made this change:
```diff
@@ -3149,10 +3179,10 @@ VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSurfaceKHR)

 typedef enum VkColorSpaceKHR {
     VK_COLORSPACE_SRGB_NONLINEAR_KHR = 0,
-    VK_COLORSPACE_BEGIN_RANGE = VK_COLORSPACE_SRGB_NONLINEAR_KHR,
-    VK_COLORSPACE_END_RANGE = VK_COLORSPACE_SRGB_NONLINEAR_KHR,
-    VK_COLORSPACE_RANGE_SIZE = (VK_COLORSPACE_SRGB_NONLINEAR_KHR - VK_COLORSPACE_SRGB_NONLINEAR_KHR + 1),
-    VK_COLORSPACE_MAX_ENUM = 0x7FFFFFFF
+    VK_COLOR_SPACE_BEGIN_RANGE_KHR = VK_COLORSPACE_SRGB_NONLINEAR_KHR,
+    VK_COLOR_SPACE_END_RANGE_KHR = VK_COLORSPACE_SRGB_NONLINEAR_KHR,
+    VK_COLOR_SPACE_RANGE_SIZE_KHR = (VK_COLORSPACE_SRGB_NONLINEAR_KHR - VK_COLORSPACE_SRGB_NONLINEAR_KHR + 1),
+    VK_COLOR_SPACE_MAX_ENUM_KHR = 0x7FFFFFFF
 } VkColorSpaceKHR;
```
The inconsistency between COLORSPACE and COLOR_SPACE seems unfortunate, it would be nice if they could be changed to match. (Maybe it's too late / too awkward to change them, though, in which case I wouldn't be too upset about wontfixing.)

**Comment by oddhack** [comment]
@TobiasHector has requested that as well. The best we could to is introduce aliases in order not to break the existing API.

**Comment by philiptaylor** [comment]
> the BEGIN_RANGE etc. tokens are not part of the API

If it's not the case that everything in vulkan.h is part of the API, then what *is* part of the API?

If the answer is "everything defined in the main specification document", then there are some things from vulkan.h that are widely used in practice but not even mentioned in the document (e.g. VK_MAKE_VERSION, VK_API_VERSION[_1_0]), and other things that are mentioned but never really defined in the document (e.g. VkBool32, VkDeviceSize, VK_WHOLE_SIZE) that make it impossible to implement or use the API without using vulkan.h as a normative reference.

In that case I think it'd be helpful to have a clearer indication of what's officially considered part of the API (especially as it affects the compatibility semi-guarantees made by the versioning scheme).

**Comment by oddhack** [comment]
The types, enums, and functions required by, or referenced indirectly by the VK_VERSION_1_0 feature block in vk.xml are the Vulkan 1.0 API.

There's a pending action to document the other contents of vulkan.h in an appendix. The reason the BEGIN_RANGE stuff exists is because one of the IHVs said "hey, it would be helpful for our driver optimization to have this information in the header" and I said "yeah, but that's a really narrow use case that pretty much nobody except you is going to care about and can be trivially derived from the XML" and then we held a vote and decided to put it in vulkan.h anyway. Similarly the MAX_ENUM tokens exist only to work around a peculiarity of some C/C++ compilers. To me the distinction is that none of this stuff is relevant to someone writing a Vulkan app, and none of it has any meaning at the interface surface between the app and the driver/layer.

But I don't want to get into a big long thread about semantics of "API". That's just my take and reasonable people can differ. The COLORSPACE issue is in flight.

**Comment by TobiasHector** [comment]
This got fixed a couple of revisions ago. I've just noticed there's a couple of outstanding references to COLORSPACE in the issues sections, but I'll fix that separately. I think we can call this closed?
