### ISSUE TITLE
enumerations VkAccessFlagBits2KHR and VkPipelineStageFlagBits2KHR

### ISSUE THREAD

**Issue by ville-h** [KhronosGroup/Vulkan-Docs#1617]
Howdy,

There seems to be some sort of naming inconsistency with `VkAccessFlagBits2KHR` and `VkPipelineStageFlagBits2KHR` and their enumerators. For example: `VK_ACCESS_2_NONE_KHR`. The enumeration names have the version(?) number at an odd location after FlagBits perhaps making parsing more complicated than necessary.

Should the enumerations be called: `VkAccess2FlagBitsKHR` and `VkPipelineStage2FlagBitsKHR instead?

**Comment by oddhack** [comment]
To give a little more clarify, we usually try to treat standalone numbers in an API name as a separate word. When stringing words together in a type name they are CamelCased, but you can't CamelCase a number. When stringing words together in an enum name they are separate by _ since the enums are all upper case. When stringing words together in an extension name we separate by _ with what is at this point just a historical exception that 'versioned' extensions like copy_commands2 are named that way instead of copy_commands_2.
