### ISSUE TITLE
Clarify behavior of vkQueryPool when used with multiple queues

### ISSUE THREAD

**Issue by pythonesque** [KhronosGroup/Vulkan-Docs#1627]
Currently, the spec is quite clear about how to use query pools correctly when they stay on one queue, or synchronize with the CPU.  And it is similarly clear about the fact that a set of queries must be unavailable before it can be safely used for new commands.  However, they are rather evasive about when (if ever) it is legal to use a query set with a different queue (or queue family) after it's already been used once, even if it's been made unavailable (since availability operations don't seem to be explicitly associated with any visibility requirements).  The closest to a confirmation that this is possible at all that I see is:

> Applications can use *fences* or events to ensure that a query has already been reset before checking for its results or availability status. Otherwise, a stale value could be returned from a previous use of the query.

But that's it (and in context it isn't clear whether fences synchronize strongly enough here); there's no explicit explanation of what kind of dependency is needed for queue transfer or anything like that.  So, is queue transfer of used query sets allowed? 
 If so, what are the minimal requirements for them to be usable, and can they be explicitly spelled out like they are for other objects that hold GPU state (like buffers and images)?

**Comment by Tobski** [comment]
Thanks for raising this @pythonesque! It looks like there might well be some thorny issues here. From a pure execution point of view, any barrier/semaphore/fence with ALL_COMMANDS_BIT in the pipeline stages (if specified) is enough to synchronize the operations:

> VK_PIPELINE_STAGE_ALL_COMMANDS_BIT specifies all operations performed by all commands supported on the queue it is used with.

However, there's still data race potential here because it seems there's no mention or discussion of visibility/availability of the pool's backing memory. Right now I think the best advice would be to _not_ use the same query pools on multiple queues.

We'll track this on an internal issue as we will probably need to poll the various implementers, and we'll update this issue when we've got any sort of progress.

**Comment by Tobski** [comment]
Wait no I take it back, I forgot something fairly important - semaphore guarantee all device operations are made available/visible as part of their operation, so that actually should take care of everything 🤦‍♀️

Does that answer your questions?

**Comment by oddhack** [comment]
We believe @tobski addressed this. If you have further questions please reopen.
