### ISSUE TITLE
DescriptorSetLayout compatibility and immutable sampler

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#164]
The specs say:

> Two pipeline layouts are defined to be “compatible for set N” if they were created with matching (the same, or identically defined) descriptor set layouts for sets zero through N, and if they were created with identical push constant ranges.

That part can be ambiguous: `(the same, or identically defined)`

One of the members of a descriptor set layout is:

> const VkSampler\*      pImmutableSamplers;

In order for two descriptor set layouts to be matching, do they have to be created with a pointer to the same sampler, or can they use two different but identically-defined sampler objects?

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.

**Comment by spencer-lunarg** [comment]
@Tobski @gfxstrand   want to clarify what we decided in https://gitlab.khronos.org/vulkan/vulkan/-/issues/263 / https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/1822 (9 years ago) as it came up today in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10098#issuecomment-3190397619

If I understand correctly, it seems in the end we did agree the `pImmutableSamplers` **can** point to different `VkSampler` handles if they have identically-defined `VkSamplerCreateInfo` (at draw time when doing Pipeline Layout Compatibility check)?

**Comment by spencer-lunarg** [comment]
The other "fun" case if you have 2 samplers, one with `VkSamplerReductionModeCreateInfo::reductionMode == VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE` and one where there is no `VkSamplerReductionModeCreateInfo` so the "reductionMode" is the same even though one `VkSamplerCreateInfo` has a pNext and the other doesn't

**Comment by Tobski** [comment]
I'll answer the question here, but while I appreciate that this issue is relevant, please don't reopen issues that have been closed for 8 years... open a new one and link this one instead. Particularly as this is fairly tangential. I'll close this issue again with my response. If you have further questions or comments - please raise a new issue.

> If I understand correctly, it seems in the end we did agree the pImmutableSamplers can point to different VkSampler handles if they have identically-defined VkSamplerCreateInfo (at draw time when doing Pipeline Layout Compatibility check)?

By my read of the spec this is not true, as the definition of "identically defined" does not allow for different identically created object handles currently. Perhaps it should, but that's not what the spec says at the moment.

> The other "fun" case if you have 2 samplers, one with `VkSamplerReductionModeCreateInfo::reductionMode == VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE` and one where there is no `VkSamplerReductionModeCreateInfo` so the "reductionMode" is the same even though one `VkSamplerCreateInfo` has a pNext and the other doesn't

We explicitly spec out the values when you don't include a structure so that this is unambiguous. These are the same.
