### ISSUE TITLE
The role of preserve attachments in render pass compatibility

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#1644]
The [Render Pass Compability (Section 8.2)](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#renderpass-compatibility) in the 1.2.193 specification states the following:

> 
> Two render passes are compatible if their corresponding color, input, resolve, and depth/stencil attachment references are compatible and if they are otherwise identical except for:
> 
> - Initial and final image layout in attachment descriptions
> - Load and store operations in attachment descriptions
> - Image layout in attachment references
> 
> As an additional special case, if two render passes have a single subpass, the resolve attachment reference compatibility requirements are ignored.
>

This doesn't say anything about preserve attachments, which makes me think that they are ignored in the compatibility rules. Is that really the case? It would be more clear if it was explicitly stated.

**Comment by janharaldfredriksen-arm** [comment]
Hi,
This is intended to be covered by the "otherwise identical" language. That is, two render passes are incompatible _unless_ their differences are covered by the exceptions described here.

Conceptually, preserve attachment need to be identical because (tile-based) implementations need to know if the storage for them has to be kept (on-chip) or if it can be reused for another attachment.
