### ISSUE TITLE
VK_KHR_MAINTENANCE_2_EXTENSION_NAME doesn't exist inside the code, only VK_KHR_MAINTENANCE2_EXTENSION_NAME

### ISSUE THREAD

**Issue by meka-lopo** [KhronosGroup/Vulkan-Docs#1674]
Hi! 

Using Vulkan ver1.2.189.0, I just noticed that there's an extension called VK_KHR_MAINTENANCE_2_EXTENSION_NAME inside the specification page(ver1.2.196.0), but there's only a define call for VK_KHR_MAINTENANCE2_EXTENSION_NAME(so without an underscore after the word MAINTENANCE) inside "vulkan_core.h". Is this an issue that was already noticed?

update : this also includes - 
VK_KHR_MAINTENANCE_1_EXTENSION_NAME
VK_KHR_MAINTENANCE_1_SPEC_VERSION
VK_KHR_MAINTENANCE_2_EXTENSION_NAME
VK_KHR_MAINTENANCE_2_SPEC_VERSION
VK_KHR_MAINTENANCE_3_EXTENSION_NAME
VK_KHR_MAINTENANCE_3_SPEC_VERSION

**Comment by oddhack** [comment]
Yes, this is intentional. Unfortunately we have slightly different naming conventions for extension *names* like "VK_KHR_maintenance2" and extension enums like "VK_KHR_MAINTENANCE_2_EXTENSION_NAME". More unfortunately we violated our own naming conventions by initially calling this token "VK_KHR_MAINTENANEC2_EXTENSION_NAME". The only way to comply with the naming rules and not be disruptive was to support the old, incorrectly spelled token as a backwards-compatibility alias, which you can see [here](https://github.com/KhronosGroup/Vulkan-Docs/commit/a09f9efe488cdd97c0362622fc1187f09302689e#diff-ea2b2280eacdf0647fff0571d64126ecfa6ddb10cc488ecf38c98869254658ce)
