### ISSUE TITLE
VkPipelineDepthStencilStateCreateInfo valid usage

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-Docs#169]
Valid usage for this structure is missing information about `minDepthBounds` and `maxDepthBounds`. These values should be in 0.0, 1.0 range, to be consistent with the description of `vkCmdSetDepthBounds`.

If we provide this information in registry XML, validation layers could be improved to do range checking on these fields.

**Comment by drakos-amd** [comment]
The valid usage language exists, but you have to look at the valid usage section of `VkGraphicsPipelineCreateInfo`.

The reason for this is that whether the `minDepthBounds` and `maxDepthBounds` members of `VkPipelineDepthStencilStateCreateInfo` structure are actually used or are ignored depends on whether `VK_DYNAMIC_STATE_DEPTH_BOUNDS` is used by the pipeline.

The validation layer should range check those members but only if `VK_DYNAMIC_STATE_DEPTH_BOUNDS` is not used, otherwise the members are ignored.
