### ISSUE TITLE
`vkGetPhysicalDeviceFormatProperties` with unknown formats

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1730]
The documentation of `vkGetPhysicalDeviceFormatProperties` states in a VUID that the `format` being queried must be a valid `VkFormat` value. The section on valid usage rules for extensions also states:
> Physical-device-level functionality or behavior added by a device extension to the API **must** not be used unless the conditions described in Extending Physical Device Core Functionality are met.

I discussed this with @charles-lunarg in Discord, and these points seem to say that this particular function follows the same rules for physical device-level functions. Therefore, it can't be given a `VkFormat` value that is either from an API version higher than the device, or from a device-level extension that it doesn't support. But since this function's whole purpose is to query the device's support for formats, this may be a case where it's warranted to make an exception.

**Comment by critsec** [comment]
Hi Rua, thanks for pointing this out. The WG discussed it this morning and agrees that defining `vkGetPhysicalDeviceFormatProperties` and related functions so that you could pass formats not known to the implementation would have been more convenient.

We're not able to say with confidence that existing implementations respond to unknown (to the implementation) formats by returning "not supported" properties, though, so we can't retroactively change the spec to say that. We've added this to the list of candidates for a future maintenance extension. However, as an extension it won't reduce the complexity in application code until the extension is pervasive enough that the developer can require it as part of their minimum requirements (which can take a very long time in some markets).

**Comment by stu-s** [comment]
This has been addressed in https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_maintenance5.html.  Please close this issue if it has been resolved.
