### ISSUE TITLE
Should access to the VkDeviceMemory object passed to vkBindBufferMemory() be externally synchronised?

### ISSUE THREAD

**Issue by conor42** [KhronosGroup/Vulkan-Docs#1731]
The spec states only:

> Host access to buffer must be externally synchronized

Nothing is said about the memory object, but the threading validation layer emits an error if concurrent access occurs:

> UNASSIGNED-Threading-MultipleThreads(ERROR / SPEC): msgNum: 337425955 - Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x980b0000000002e, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x141cb623 | THREADING ERROR : vkBindBufferMemory(): object of type VkDeviceMemory is simultaneously used in thread 0x6794f640 and thread 0x6746f640

The same question applies to vkBindImageMemory().

**Comment by Tobski** [comment]
This is really a validation issue rather than a spec issue - I'm guessing your app is calling something else which is externsync at the same time (maybe vkMapMemory)? If the same parameter is used concurrently in two calls where _either one_ of those calls treats it as externally synchronized, then there's an error.

It seems the error message from the validation layers is always just blaming the "second" call, rather than pointing out the call with the external sync requirement (or perhaps listing all affected calls). I've raised a Validation issue here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3698

**Comment by filnet** [comment]
Related: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3615

**Comment by spencer-lunarg** [comment]
Closing this issue as it is being tracked and worked on in the Validation Layer repo
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3698
