### ISSUE TITLE
Spec clarification on use of float16 capability without VK_VERSION_1_2

### ISSUE THREAD

**Issue by kd-11** [KhronosGroup/Vulkan-Docs#1739]
Currently, when using a plain vulkan 1.0 instance with extensions, it is not possible to use the float16 capability exposed via the VK_KHR_shader_float16_int8 without getting validation errors. Looking at the spec documents, this seems to be intended as the requirements in the capabilities table only name 2 requirements:

- VkPhysicalDeviceVulkan12Features::shaderFloat16 (requires 1.2)
- VK_AMD_gpu_shader_half_float

This makes it so that creating a device with pNext=VkPhysicalDeviceShaderFloat16Int8FeaturesKHR structure from the VK_KHR_shader_float16_int8 extension is no longer enough to satisfy the usage requirements. What is odd is that clicking on the requirement link in the vulkan 1.0 version of spec actually takes you to the VK_KHR_shader_float16_int8 extension and not the VkPhysicalDeviceVulkan12Features entry contradicting itself. Something seems to be amiss here, either the requirement for vulkan 1.0 is still to use the extension ( by enabling use via the VkPhysicalDeviceShaderFloat16Int8FeaturesKHR struct ) or you're forced to use vulkan 1.2 structures in 1.0 which is odd.
Link to the document section: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/chap46.html#spirvenv-capabilities

**Comment by krOoze** [comment]
The `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16` is a feature alias to `VkPhysicalDeviceVulkan12Features::shaderFloat16`.

The SPIR-V cap table might be missing aliases in some places. E.g. `VkPhysicalDeviceVulkan12Features::storageBuffer8BitAccess` vs `VkPhysicalDevice8BitStorageFeaturesKHR::storageBuffer8BitAccess`.

IIRC features were listed only once at one point. But apparently they decided to reduplicate features under every feature struct again.

**Comment by kd-11** [comment]
So I should file a bug report with validation layers? Using float16 capability generates errors on vulkan 1.0.

**Comment by krOoze** [comment]
The validation is probably generated from the vk.xml. I would probably keep it here until someone from Khronos decides what form the xml contents should have. Since this extension promotion to core Vulkan version is nontrivial, they will probably opt to add all the aliases into the xml where it will get picked up by the next validation layer versions automagically.

**Comment by sfricke-samsung** [comment]
@kd-11 thanks for raising this

1. The following hyperlink issue is a known spec bug ([internal issue](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2558)) and just waiting on time to fix the spec generation code for it
> What is odd is that clicking on the requirement link in the vulkan 1.0 version of spec actually takes you to the VK_KHR_shader_float16_int8 extension and not the VkPhysicalDeviceVulkan12Features entry contradicting itself. 

2. If you are using a Vulkan 1.0 or 1.1 instance, you must enable `VK_KHR_shader_float16_int8` **and** `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16`

This is because it is valid for a device to support only `shaderInt8` and not `shaderFloat16`

3. Starting in Vulkan 1.2, you can ignore the step of enabling the extension `VK_KHR_shader_float16_int8` and just enabled `shaderFloat16` by itself for the same effect

----

So your issue is really the confusion that `VkPhysicalDeviceVulkan12Features::shaderFloat16` in the 1.0 or 1.1 spec should say `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16`... but the validations layers already correctly alias the 2 sets of features bits so either way works

**Comment by kd-11** [comment]
> @kd-11 thanks for raising this
> 
> 1. The following hyperlink issue is a known spec bug ([internal issue](https://gitlab.khronos.org/vulkan/vulkan/-/issues/2558)) and just waiting on time to fix the spec generation code for it
> 
> > What is odd is that clicking on the requirement link in the vulkan 1.0 version of spec actually takes you to the VK_KHR_shader_float16_int8 extension and not the VkPhysicalDeviceVulkan12Features entry contradicting itself.
> 
> 2. If you are using a Vulkan 1.0 or 1.1 instance, you must enable `VK_KHR_shader_float16_int8` **and** `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16`
> 
> This is because it is valid for a device to support only `shaderInt8` and not `shaderFloat16`
> 
> 3. Starting in Vulkan 1.2, you can ignore the step of enabling the extension `VK_KHR_shader_float16_int8` and just enabled `shaderFloat16` by itself for the same effect
> 
> So your issue is really the confusion that `VkPhysicalDeviceVulkan12Features::shaderFloat16` in the 1.0 or 1.1 spec should say `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16`... but the validations layers already correctly alias the 2 sets of features bits so either way works

I am using and enabling `VkPhysicalDeviceShaderFloat16Int8Features::shaderFloat16` which is why I filed this ticket. The tools still generate an error regarding float16 usage even when the structure is correctly filled and set as pNext for VKDeviceCreateInfo.
This whole problem is technically a regression, when bringing up float16 support, the validation layers did catch the issue correctly and I fixed it (enabled extension and enabled the feature), only for errors to pop up again months later.

**Comment by kd-11** [comment]
Actually nvm, I accidentally removed some stuff incorrectly while testing what's going on with the spec.
This issue can be closed, thanks for clarifying the hyperlink problem, it all makes sense now when taking that into consideration.
