### ISSUE TITLE
About the VK_PRESENT_MODE_FIFO_RELAXED_KHR documentation

### ISSUE THREAD

**Issue by podain** [KhronosGroup/Vulkan-Docs#174]
Typo error in the trailing note section "SwapBuffers with a swap internal of -1"
*interval

And I've never heard about swap interval -1. Is this correct?

I can understand the above 3 presentation modes, but this one is hard to understand especially the statement "if a vertical blanking period has already passed since the last update of the current image".

With DRM/KMS for example, should I dequeue and drmModePageflip() if there was no image update since the last vblank and dequeue and drmModeSetCrtc() if the internal queue is not empty in the vblank handler?

**Comment by ianelliottus** [comment]
Hi @podain .  Thanks for catching the typo.  The interval of -1 comes from two extensions:

- WGL_EXT_swap_control_tear (see: https://www.opengl.org/registry/specs/EXT/wgl_swap_control_tear.txt)
- GLX_EXT_swap_control_tear (see: https://www.opengl.org/registry/specs/EXT/glx_swap_control_tear.txt)

From the overview of the first:

    This extension extends the existing WGL_EXT_swap_control extension
    by allowing a negative <interval> parameter to wglSwapIntervalEXT.
    The negative <interval> allows late swaps to occur without
    synchronization to the video frame. This reduces the visual stutter
    on late frames and reduces the stall on subsequent frames.

The motivation seems to be for applications (e.g. games) that mostly render at a rate that is similar to the vertical refresh rate of the monitor, but occasionally have a late frame.  In this case, the goal is to perform the swap/present immediately, so that the app continues to appear to be working at the refresh rate.  Most of the time the swap/present occurs with the vsync, but occassionally it doesn't.  Does that help?

I am looking at improving the spec language, and am open to your input.  Would it better for you if the spec referenced those extensions, or simply dropped all reference to the "-1" swap interval, and simply tried to improve the explanation?

**Comment by podain** [comment]
@ianelliottus 
Thanks for your reply.
Now I understand the 4 presentation modes correctly thanks to your explanation.
And also the WGL/GLX extensions are clear to me.

I think references to the swap interval of -1 might help help people understand the modes. But it would be better to provide links to the extension pages as there're peoples (including me) who use EGL most of the time.

**Comment by ianelliottus** [comment]
The change is in the May 12 release.  Thanks again for reporting this!
