### ISSUE TITLE
Unclear status of vkGetInstanceProcAddr after latest spec changes.

### ISSUE THREAD

**Issue by zaiste-linganer** [KhronosGroup/Vulkan-Docs#1763]
After last changes in spec (based on https://github.com/KhronosGroup/Vulkan-Docs/issues/1605, implemented with https://github.com/KhronosGroup/Vulkan-Docs/commit/129f6f69dcbc00184d771d2da969b4ed394ac80c#diff-cc7f020d83a81be0f2bbad08adaca7c415c59b8c6ecd4585ccfbcea7b054fa20), and following Loader changes, we observe new crashes in our product. After diving into the spec, it seems that there is an discrepancy there, regarding behavior of vkGetInstanceProcAddr.

Per literal spec reading (especially footnotes below Table 1 in https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap4.html#vkGetInstanceProcAddr), vkGetInstanceProcAddr is not a global function, so it's core dispatchable function. However, Vulkan Loader recently disallowed calling vkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr") with valid instance for contexts created with 1.3. 

From discussion in https://github.com/KhronosGroup/Vulkan-Loader/issues/825, @charles-lunarg states that current language spec regarding vkGetInstanceProcAddr is probably a mistake. On the other hand, I believe there is no reason to make (globally acquired) vkGetInstanceProcAddr impossible to be called with valid non-null instance over vkGetInstanceProcAddr.

So, if the understanding for vkGetInstanceProcAddr is that it is a global function, can we have it added to the list of global function, and if it's dispatchable, can we have this clarified? Also, if this is kind of hybrid-function, that is neither global nor dispatchable, it would be great to have it described, and having added proper explanation for mentioned Table 1. in https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap4.html#vkGetInstanceProcAddr.

Thanks in advance!

**Comment by pdaniell-nv** [comment]
If I read the spec right, I think vkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr") should work fine. I think this falls under the 5th row "core dispatchable command". It's called a "dispatchable command" because its first parameter is a VkInstance.

**Comment by zaiste-linganer** [comment]
This is my reading of the spec as well. But, as in https://github.com/KhronosGroup/Vulkan-Loader/issues/825, we had discussion, and @charles-lunarg statement is that it looks rather like an unintended effect of the language spec changes, so we came here for clarification...

**Comment by charles-lunarg** [comment]
I just found this vulkan-hpp issue which has a similar read to mine. https://github.com/KhronosGroup/Vulkan-Hpp/issues/1108

There are two ways of interpreting `vkGetInstanceProcAddr(instance, 'vkGetInstanceProcAddr')`.
The first is what ziaste-linganer is, where because vkGetInstanceProcAddr isn't listed as a global function, it is thus a core-dispatchable command, so should be interpreted as the 5th row, thus returning a valid function pointer.

But I read that vkGetInstanceProcAddr isn't a 'dispatchable command' because it doesn't require a valid dispatchable function as its first parameter to work, and thus falls into the last row ("all other case, not covered above -> NULL"). 

The fp3 footnote calls out this inconsistency.
> The returned function pointer must only be called with a dispatchable object (the first parameter) that is instance or a child of instance, e.g. VkInstance, VkPhysicalDevice, VkDevice, VkQueue, VkCommandBuffer
That isn't consistent with the behavior of `vkGetInstanceProcAddr`

**Comment by zaiste-linganer** [comment]
Well, I think it just means that you should not do things like pseudocode below:
`
instanceVkGetInstanceProcAddr = globalVkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr"); // valid
whatever = instanceVkGetInstanceProcAddr(nullptr, "vkGetInstanceProcAddr"); // invalid. Pointer obtained from vkGetInstanceProcAddr should not be called with nullptr as first parameter.
`

Specifically, without any internal knowledge, spec reader is entitled to believe that global vkGetInstanceProcAddr will be different than instance vkGetInstanceProcAddr, for specific valid instance.

Please note that what fp3 is really talking about is that vkGetInstanceProcAddr returns pointer that is inevitably connected to the instance it was obtained from, and shouldn't be used on any other instance. Nowhere is stated that this is what defines dispatchable command. Oppositely, the definition of dispatchable function is provided just above, in fp2. 

While I agree that we might change the spec language to make vkGetInstanceProcAddr global, or just to forbid calling vkGetInstanceProcAddr on vkGetInstanceProcAddr, the longer I read this part of the spec, the more I'm convinced that current behavior of loader is just contradicting the spec.

I would love to have this cleared in one way of other, in spec anyway, to acknowledge the special status of vkGetInstanceProcAddr (by, for example, adding a Note clarifying what is allowed and what is not :) ).

**Comment by r-potter** [comment]
This wasn't a 1.3 change. It's a deliberate change to global functions resolve this issue: https://github.com/KhronosGroup/Vulkan-Docs/issues/1605

vkGetInstanceProcAddr maps to a core dispatchable command, but with a special case allowing for a NULL instance. There should be no changes to the behaviour of `vkGetInstanceProcAddr(instance, 'vkGetInstanceProcAddr')`.

What did change was what happens when you call `vkGetInstanceProcAddr(instance, global_function)` with a non-NULL instance handle. We explicitly list the global functions that this impacts (vkEnumerateInstanceVersion, vkEnumerateInstanceExtensionProperties, vkEnumerateInstanceLayerProperties, and vkCreateInstance).

**Comment by charles-lunarg** [comment]
If that is the case, can we amend the description of what a dispatchable function is? It confuses me to see 

> The returned function pointer must only be called with a dispatchable object (the first parameter) that is instance or a child of instance

But then we allow `vkGetInstanceProcAddr` to be called with a NULL instance handle. I think the behavior of `vkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr") returning itself is fine (instead of null like I initially assumed), just would appreciate some clarity for this case.

**Comment by r-potter** [comment]
I'll propose an internal MR with a further note clarifying that vkGetInstanceProcAddr is effectively a core dispatchable command, but with special case behaviour for NULL instance handles. That was definitely the agreed intent.

**Comment by r-potter** [comment]
Internal MR signed off, in line with my comments above. This change will become public with the next specification release. Closing this as resolved, but feel free to reopen if there are further questions.

**Comment by zaiste-linganer** [comment]
Thanks, it seems that this, along with resulting Loader changes, resolved the issue for us!

**Comment by oddhack** [comment]
This should be fixed in the 1.3.206 spec update.
