### ISSUE TITLE
Question: vkGetPhysicalDevicePresentRectanglesKHR always null with vkGetDeviceProcAddr?

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/Vulkan-Docs#1775]
Hello :smile:  

The method ``vkGetPhysicalDevicePresentRectanglesKHR`` is declared below the extension ``VK_KHR_swapchain``(https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_swapchain.html)
and the extension is defined as device extensions.

Now the but:
When I'm trying to load the ``vkGetPhysicalDevicePresentRectanglesKHR``-Proc with ``vkGetDeviceProcAddr`` is the return value always null, that's means to me - function not found.

I played a little bit around and found out: 
When I'm trying to load the ``vkGetPhysicalDevicePresentRectanglesKHR``-Proc with ``vkGetInstanceProcAddr``  is the return value a valid function pointer.

Everything else works below ``VK_KHR_swapchain`` with ``vkGetDeviceProcAddr``.

Question: 
Can I say: ``vkGetInstanceProcAddr`` is a fallback to ``vkGetDeviceProcAddr`` ? (I don't think so) 

Question:
In the documentation is written 'Requires [VK_KHR_surface](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_surface.html)' and the extension ``VK_KHR_surface`` is market as ``instance extension``.
Is that the reason why I always get zero back with ``vkGetDeviceProcAddr``?

Daniel Baumert

ref: https://github.com/KhronosGroup/Vulkan-Headers/issues/263

**Comment by r-potter** [comment]
This is because `vkGetPhysicalDevicePresentRectanglesKHR` is a physical device function, and physical devices are direct children of `VkInstance` objects. It falls into this row of the `vkGetInstanceProcAddr` table:

<html>
<body>


Instance Parameter | pName | Return Value
-- | -- | --
instance | available device extension^4 dispatchable command for instance | fp^3



</body>
</html>

3
The returned function pointer must only be called with a dispatchable object (the first parameter) that is instance or a child of instance, e.g. [VkInstance](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstance.html), [VkPhysicalDevice](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDevice.html), [VkDevice](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDevice.html), [VkQueue](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueue.html), or [VkCommandBuffer](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBuffer.html).

4
An “available device extension” is a device extension supported by any physical device enumerated by instance.

For `vkGetDeviceProcAddr`, physical device-level commands are specifically excluded:

<html>
<body>


Device Parameter | pName | Return Value
-- | -- | --
device | core device-level dispatchable command^2 | fp^3
device | enabled extension device-level dispatchable command^2 | fp^3


</body>
</html>

2
In this function, device-level excludes all physical-device-level commands.

3
The returned function pointer must only be called with a dispatchable object (the first parameter) that is device or a child of device e.g. [VkDevice](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDevice.html), [VkQueue](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueue.html), or [VkCommandBuffer](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBuffer.html).

**Comment by DanielBaumert** [comment]
How can I determine in an easy way of which kind a given function could be loaded by instance or device proc addr?
and is this somehow reflected in the vk.xml?

**Comment by polarina** [comment]
@DanielBaumert look at the type of the function's first parameter. If it is `VkPhysicalDevice` or `VkInstance` you use use `vkGetInstanceProcAddr`, otherwise `vkGetDeviceProcAddr`.

**Comment by krOoze** [comment]
> Question: Can I say: `vkGetInstanceProcAddr` is a fallback to `vkGetDeviceProcAddr` ? (I don't think so)

Yes it is. It can fetch any command, at the cost of redirection overhead.

> How can I determine in an easy way of which kind a given function could be loaded by instance or device proc addr?
and is this somehow reflected in the vk.xml?

Command first parameter is `VkDevice`, `VkQueue`, or `VkCommandBuffer` -> `vkGetDeviceProcAddr`  
Command first parameter is non-dispatchable, `VkInstance`, or `VkPhysicalDevice` -> `vkGetInstanceProcAddr`
