### ISSUE TITLE
Possible wrong structure in VUID-vkGetPhysicalDeviceSurfaceCapabilities2KHR-pNext-02671

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1781]
This VUID states:
> If a [VkSurfaceCapabilitiesFullScreenExclusiveEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesFullScreenExclusiveEXT.html) structure is included in the `pNext` chain of `pSurfaceCapabilities`, a [VkSurfaceFullScreenExclusiveWin32InfoEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceFullScreenExclusiveWin32InfoEXT.html) structure must be included in the `pNext` chain of `pSurfaceInfo`

This seems a bit odd because `VkSurfaceFullScreenExclusiveWin32InfoEXT` is specific to Windows and can't be used anywhere else (no way to get a valid `HMONITOR`). It would mean that `VkSurfaceCapabilitiesFullScreenExclusiveEXT` can't be used on other platforms. I think the required structure in the chain of `pSurfaceInfo` is actually supposed to be `VkSurfaceFullScreenExclusiveInfoEXT` (note the lack of `Win32`)?

**Comment by cubanismo** [comment]
While this may seem odd, it is intentional. The win32-specific data was put in a separate struct to allow for future use of the base information on other platforms if needed, but at present, there is no other platform supporting this mechanism, so the only way to use it is by specifying both structures, as they are both required on the win32 platform. The VUID may be change if a future extension added support for using VkSurfaceCapabilitiesFullScreenExclusiveEXT on other platforms, but at present, no such extension exists.

**Comment by Rua** [comment]
Can you explain then how `VkSurfaceCapabilitiesFullScreenExclusiveEXT` should be used on non-Windows platforms?

**Comment by Rua** [comment]
Is the whole `VK_EXT_full_screen_exclusive` extension for Windows only at the moment? According to the Vulkan Hardware Database, only Windows drivers support it, which I wasn't aware of. I was talking about the possible case of devices on other platforms supporting it, but since those don't exist, I guess the point is moot.
