### ISSUE TITLE
Circular logic in pipeline VUs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1793]
VUID-VkGraphicsPipelineCreateInfo-renderPass-06044:

> If `renderPass` is not `VK_NULL_HANDLE`, the pipeline is being created with **fragment output interface state**, and `subpass` uses color attachments, `pColorBlendState` **must** be a valid pointer to a valid `VkPipelineColorBlendStateCreateInfo` structure

"fragment output interface state" is defined as:

> Fragment output state is defined by:
>
> - `VkPipelineColorBlendStateCreateInfo`
> - The `alphaToCoverageEnable` and `alphaToOneEnable` members of `VkPipelineMultisampleStateCreateInfo`.
> - `VkRenderPass` and `subpass` parameter

So "If `renderPass` is not `VK_NULL_HANDLE`" is redundant to "being created with **fragment output interface state**"

And the VU basically says "If pipeline is being created with `VkPipelineColorBlendStateCreateInfo`, then it **must** be created with `VkPipelineColorBlendStateCreateInfo`. That is tautological.

Additionally in dynamic rendering it is permissible for `VkRenderPass` to be `VK_NULL_HANDLE`, which basically makes its VU that also invokes "fragment output interface state" to be unsatisfiable, since that state includes render pass parameter per the above.

This case makes very unclear when `pColorBlendState` can be ignored. The parameter descriptions seem to suggest the exact condition should probably be `rasterizerDiscardEnable == VK_FALSE && colorAttachmentCount > 0`.

Other VUs using the term "X state" may be similarly defective.

**Comment by Tobski** [comment]
Hi @krOoze - we discussed and we think there is confusion  over "the pipeline is being created with..." language. The intent is that this should be interpreted as "... the pipeline requires fragment output interface state, ..." - each part of the state is independently validated like with this sentence. Read like that, the "circular logic" should disappear.

We'll take an internal action to change the wording on this, but it might take a little while as there's an incoming spec change touching this area which we want to land first.

**Comment by krOoze** [comment]
That still sounds extremely nebulous what that means, but we shall see what wording you come up with...

<hr>

I am kinda tempted to make a metaissue about discipline. Making low-level API requires an inhumane amount of it, but still. I am not entirely clear how someone in review read that VU, and thought to himself "yes, this is perfectly clear and explicit VU sentence". Then whoever wrote the validation for it seemed to have been embarrassed to admit he does not understand the VU and ask here, and instead made stuff up.

The core validation I think predates this VU language, and iterprets this as "rasterizer discard disabled (or dynamic state) and there being at least one color attachment". I don't really see any connection with that VU whatsoever, even with your clarification. I wouldn't know how I would arrive from that VU wording, to implementing the validation check the way it is.

The validation of similar check for dynamic rendering (which I assume came after this new VU language) interpreted the VU as "the pipeline has a fragment shader". Apparently the implementer felt the VU is sane and he perfectly understands it. And it was also fine with whomever made code review on that.

**Comment by Tobski** [comment]
> That still sounds extremely nebulous what that means, but we shall see what wording you come up with...
>
> I am kinda tempted to make a metaissue about discipline. Making low-level API requires an inhumane amount of it, but still. I am not entirely clear how someone in review read that VU, and thought to himself "yes, this is perfectly clear and explicit VU sentence". Then whoever wrote the validation for it seemed to have been embarrassed to admit he does not understand the VU and ask here, and instead made stuff up.
>
> The core validation I think predates this VU language, and iterprets this as "rasterizer discard disabled (or being a dynamic state) and there being at least one color attachment". I don't really see any connection with that VU whatsoever; even with your clarification. I wouldn't know how I would arrive from that VU wording, to implementing the validation check the way it is.
>
> The validation of similar check for dynamic rendering (which I assume came after this new VU language) interpreted the VU as "the pipeline creation has a fragment shader". Apparently the implementer felt the VU is sane and he perfectly understands it. And it was also fine with whomever made code review on that. Unless you have some internal Issue for this, it perhaps indicates some problem with discipline and attitudes that are incompatible with making this kind of API in a sufficiently responsible way.

I would encourage you to continue to point out flaws in our process as while we're definitely on better footing than we were at Vulkan 1.0, there's always room to grow. However, parts of your commentary here are questioning the abilities of people in a critical manner - nobody is perfect, and we all make mistakes. If you want to provide constructive feedback then we're happy to accept it and action it, but ranting about how bad of a job someone did is not that. In addition to that I'd also ask you to please avoid assuming gender (he/himself) or using ableist language (sane).

Picking out the salient parts of your feedback here:

When writing the VU, I (and the reviewers) considered the context spelled out in the pull request that introduced these VUs, but that is lost for an independent reader. I agree we should work to avoid that context dependency. We're working on revamping our internal documentation so that things like this can be spelled out, and working on adding authoring and review guidelines etc. It's going to take a while to get those up and running, but we are doing it. In this particular case, I'll make sure we consider that in the rewrite; it's probably not as straightforward as I suggested yesterday.

As for the validation layer checks, there's a process here where if the text of a VU changes (which is automatically flagged), the SDK team will check if the new text matches the implementation or not, so once we fix the language it should result in changes to the layers without further input. I'm guessing this issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3805) is relevant as well - so getting that fixed should require no further direct input, but I'll mention there's a potential spec clarification needed on that issue.

**Comment by Tobski** [comment]
@krOoze Ok so after staring at this for a while, it's quite hard to find a way to not make this appear circular at least superficially - the best way I can think of to resolve this is to say something like "if the pipeline includes the X subset" and have the whole "includes X subset" part be a link to the subset definition, with details about what "inclusion" means? That at least gives clear delineation breaking the cycle.

So for example, for 06044, we could word it as:

> If renderPass is not VK_NULL_HANDLE, the pipeline **_includes the fragment output interface subset_**, and subpass uses color attachments, pColorBlendState must be a valid pointer to a valid VkPipelineColorBlendStateCreateInfo structure

with "includes the fragment output interface subset" linking to something like this:

> The fragment output interface subset is included in the pipeline if 
> slink:VkGraphicsPipelineLibraryCreateInfoEXT::pname:flags includes 
> ename:VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT
> and pname:rasterizerDiscardEnable is not ename:VK_FALSE.
> The fragment output interface subset is defined by:
> 
>   * slink:VkPipelineColorBlendStateCreateInfo
>   * slink:VkRenderPass and pname:subpass parameter
>   * ...

(the definition will be a bit more complex but more or less that)

Would that make things clearer? Open to other suggestions of course.

**Comment by krOoze** [comment]
@Tobski As long as the application maker is instructed exactly what to do without unnecessary mental gymnastics.

Assume reading stuff is twice so difficult than writing stuff. If writing it while you have it all fresh in mind leave you unsatisfied,  then a passer-by trying to read this will rather give up, skip it, and (as human brain often works) hallucinate something else that makes some vague sense to him. (Which leads to problems this abstraction level cannot bear. Especially, as per the meta, if the devs of the ecosystem themselves are not immune to this, and the review process tends to propagate "mistakes".)

I think the problem here is we are convoluting two things into one. There's the matter of whether it is "supposed to include FOIS", and second thing whether "FOIS is actually included".

So one solution would be to separate those concepts:

> If the pipeline create info declares FOIS will be part of the pipeline[link to explaining how to declare whether that is so], and {additional conditions}, then `pColorBlendState` **must** be a valid pointer to a valid `VkPipelineColorBlendStateCreateInfo` structure

Then again VUIDs are how you communicate with the VVL what changes, so I do not like "amendable" VUs that like to stuff, because it could lead to incomplete layers where the partial subtle incompleteness is hard to track in retrospect.

So I would recommend somewhat different approach. I believe you now support detached\hierarchical VUs. E.g. the SPIR-V VUs seem to be separated from any specific command. I would revert our VU here to a more direct language including all the extension combinations:

> ifndef:some_extension
> -  If `rasterizerDiscardEnable` is not `VK_FALSE`, createinfo **must** conform to fragment output state VUs[link to another block of VUs]
> endif:
> ifdef:some_extension
> -  If either some_extension is disabled or `flags` includes
ename:VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT, and if `rasterizerDiscardEnable` is not `VK_FALSE`, createinfo **must** conform to fragment output state VUs[link to another block of VUs]
> endif:

**Comment by Tobski** [comment]
> So one solution would be to separate those concepts:

Right, that's what I was going for here. I was tempted to swap the order to make the subset first as well, that just unfortunately means more churn, but it does make it easier to navigate.

> I believe you now support detached\hierarchical VUs.

We don't usually have fully detached VUs, the SPIR-V VUs being detached is more out of necessity than anything else, and I don't think we have a fully baked concept here. Part of the drawback of this is that it makes it awkward for the refpages, as you won't have all the VUs in one place and have to jump around to find them. Technically you have to do that for the definitions of the subsets, but they already have a home in the refpage.

I'm happy with the first approach here, I'm dubious about the second because while I'm not against it, I think it needs more thought before committing to it.

Ultimately I think they're achieving the same thing though - separating "supposed to include FOIS" and "FOIS is actually included", as you've put it. I think I'll plan on doing the first option for now, but since it's going to take me a little bit to get to actually doing that, I'm happy to discuss how the second option could work further if you like?

**Comment by krOoze** [comment]
Not much to discuss. Just feels like an inevitable way to solve the problem.

But as I see it the VUs are like

> - If A then **must** R<sub>1</sub>
> - If A then **must** R<sub>2</sub>
> - ...
> - If A then **must** R<sub>N</sub>

The problem is we need to split A into more variations A<sub>1</sub> and A<sub>2</sub>.

The conceptual way is to just double the amount of VUs, which is annoying (to both writer and reader), because we need copies of R<sub>1</sub> through R<sub>N</sub> with slightly different A. That leads to VU spam.

As it is now (appart for being broken, per the Issue), it links to outside to some text that is potentially amendable and editable. That is not conceptual, and the VVL script won't detect spec changes, and so if prevalent paradigm it leads to subtly incomplete and\or divergent VVL implementation, which is not accounted in VVL coverage stats.

Different way would be to have hierarchical VU. One VU would just link the other block (and would largely not be validated):

> - If A<sub>1</sub> then VUs in linked VU block *must** be followed
> - If A<sub>1</sub> then VUs in linked VU block *must** be followed

then a linked VU block:


> - **must** R<sub>1</sub>
> - **must** R<sub>2</sub>
> - ...
> - **must** R<sub>N</sub>

**Comment by Tobski** [comment]
Ok I've got an MR internally for this that I'm working on, and the gist is that I've changed the "created with X subset" language in the VUs to "requires X subset" (where X is a link to the section describing that subset).

Additionally, I've moved the text describing when particular subsets are required to the sections describing each subset, so that the link in the VU tells you what you need to know.
I've added precise separate VUs that describe these requirements as well, since the sections are worded in a more readable manner than the VUs are, which also link back to those sections.
There's a bunch of other minor supporting changes to back all of this up as well.

You suggested having VUs linking to VUs, but with no precedent for doing that and with some potentialy complications for tooling, saying roughly the same thing twice with cross-links seemed to be the best way to go about it for now.

Still has to go through internal review etc., but it should be a decent improvement once complete.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.251 spec update.
