### ISSUE TITLE
Feature Request: Extension for specifying constraints on the destination address of vkMapMemory.

### ISSUE THREAD

**Issue by Guy1524** [KhronosGroup/Vulkan-Docs#1832]
Background: [The Wine project](https://www.winehq.org/about) is currently progressing towards a new method of supporting 32-bit windows applications within processes matching the host's architecture.  In practice, this means supporting 32-bit consumers of the Vulkan (and other) APIs using 64-bit Vulkan drivers.  One complication in this process is relaying the pointer returned from vkMapMemory to the 32-bit API consumer, if the pointer happens to fall out of the 32-bit range.

To help solve this problem, an extension could be introduced allowing applications to either specify where they want a mapping to be placed, or to constrain the possible area where resources can be mapped to.  One possibility would be a adding a flag to VkMemoryMapFlags specifying that the resource should be mapped into the lower 32-bit address space.  An implementation using mmap could then simply pass this through by setting the MAP_32BIT flag.

Does this sound appropriate for a Vulkan extension?  I think it's worth noting that we are discussing other opportunities to solve our problem like remapping the returned pointer to a compatible address, but as this solution wouldn't involve any implicit assumptions on how the driver maps memory, it could be the best long-term solution for us.

More details and discussion of the problem faced on the wine mailing list: https://www.winehq.org/pipermail/wine-devel/2022-April/214733.html

**Comment by jekstrand** [comment]
Assuming `MAP_32BIT` works (which it probably will), this should be a trivial extension to draft and implement.  Do you have any interest in trying your hand at some extension text?  Or are you looking for volunteers?

To help with figuring out if this will work at all, I've thrown together a driver branch for you that should work on Intel, at least in theory: https://gitlab.freedesktop.org/jekstrand/mesa/-/commits/anv/VK_EXT_mmap_32_bit. On modern kernels, the Intel drivers pass everything through the standard `mmap()` ioctl so I think `MAP_32BIT` should work.  I've not written any detection code about exactly when to expose the feature yet but that should be enough that you can play around.

**Comment by zfigura** [comment]
I think it'd be better to be able to specify a fixed address, and not rely (solely) on MAP_32BIT. The latter is not portable, and we'd also like the ability to restrict the address to the first 3 or 4 GiB if the process is compatible.

**Comment by jekstrand** [comment]
That would be easy to write as an extension as well.  Then Wine can do its own `MAP_ANONYMOUS` to reserve VA and pass that to `vkMapMemory()`.  That's certainly more flexible but it does feel a bit more fragile as you may get `VK_ERROR_MEMORY_MAP_FAILED` if we can't place it there.  However, if you've reserved the VA, I think it should usually succeed.  Not much we (the driver) can do if that fails, though.

As far as portability goes, `D3DKMT_LOCK2` on Windows doesn't seem to support any fancy flags here at all so I don't think it's supportable on Windows anyway.  See https://github.com/microsoft/libdxg/blob/main/include/d3dkmthk.h#L4801.

I hacked up a quick attempt at an implementation again if you want to try: https://gitlab.freedesktop.org/jekstrand/mesa/-/commits/anv/VK_EXT_map_memory_placed.  This time, there's a `PLACED` flag which means the `ppData` pointer is a requested address which may or may not be what you get.  I currently don't return `VK_ERROR_MEMORY_MAP_FAILED` if it doesn't match and leave that to the app.  This matches what `mmap()` does today.  The return value behavior can be changed if we want.

I also found a bug in the `VK_EXT_mmap_32bit` branch posted above where the flag enum value was accidentally zero.  I've force-pushed that branch with the fix and rebased on mesa main while I was at it.

**Comment by jekstrand** [comment]
Just so we're all clear, I'm currently waiting on the Wine folks to play around and help figure out what works best there.  If you need a RADV implementation for testing, I can either implement it myself or get help from one of the Valve guys.  Once we're sure we know what we want, I can probably write up extension text.  I doubt this will be implemented by anyone on Windows so we mostly care about ANV, RADV, and NVIDIA.  Really, it should be fine for any DRM driver as long as they use the GEM mmap offset stuff and not a bespoke mmap.  IIRC, i915 is the only kernel driver for modern hardware that still has a bespoke mmap and that's been deprecated for a year or two.

cc @pdaniell-nv and @cubanismo for visibility for NVIDIA.  I have no idea what it would take to implement either of these for the NVIDIA Linux driver as they have their own kernel APIs.

For folks who don't want to look at my hacked up branches, here are the two proposals:

## VK_EXT_mmap_32_bit
```c++
typedef enum VkMemoryMapFlagBits {
    VK_MEMORY_MAP_32_BIT_POINTER_BIT = 0x00000001,
    VK_MEMORY_MAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkMemoryMapFlagBits;
typedef VkFlags VkMemoryMapFlags;
```
If the `VK_MEMORY_MAP_32_BIT_POINTER_BIT` is set in `flags`, the implementation will ensure that the returned map is in the first 32 bits of the process address space.  If this constraint cannot be satisfied, it will return `VK_ERROR_MEMORY_MAP_FAILED`.

## VK_EXT_memory_map_placed
```c++
typedef enum VkMemoryMapFlagBits {
    VK_MEMORY_MAP_PLACED_BIT = 0x00000001,
    VK_MEMORY_MAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkMemoryMapFlagBits;
typedef VkFlags VkMemoryMapFlags;
```
If the `VK_MEMORY_MAP_PLACED` bit is set in `flags`, `ppData` is read and the implementation attempts to place the memory map at that pointer, if aligned, or at the next aligned pointer after it.  If that doesn't work, it places it somewhere.  See also the man page for `mmap()`.  TBD if it should place the map at an arbitrary location or return `VK_ERROR_MEMORY_MAP_FAILED` if the map doesn't match exactly.

Yes, I know that reading `ppData` is a bit dirty since it's an out parameter.  However, if we didn't do that, we'd need `vkMapMemory2()` which we could do but ugh.

**Comment by Guy1524** [comment]
Thanks for these draft extensions jekstrand.  As Zebediah mentioned earlier, I think the wine community would rather the placed variant, as it provides us the flexibility to handle applications with and without the LAA (large address-space aware) flag set, which enables/disables use the 32nd bit.  I'll send a mail to wine-devel linking to this work and seeing if there are other opinions though.

As somebody who's only somewhat familiar with the details of Vulkan extension convention, I do have a question though.  Is it common for new extensions to change the semantics of already existing function parameters (ppData in this case)?  Would it not be more idiomatic to add a pNext structure for our requested mapping address?

**Comment by jekstrand** [comment]
> As somebody who's only somewhat familiar with the details of Vulkan extension convention, I do have a question though. Is it common for new extensions to change the semantics of already existing function parameters (ppData in this case)? Would it not be more idiomatic to add a pNext structure for our requested mapping address?

Yes and no.  Using what used to be an out parameter as an in parameter is a bit unconventional but not unheard of.  All the `pCount` parameters queries that return multiple things are also in/out params.  Yes, we could do a `pNext` but that would require first adding a `vkMapMemory2()` entrypoint which can be extended because the current one has no place to chain such a thing in.  This is minimally invasive and I think good enough for prorotyping.  Once we get things working and I've got something that looks more like a real extension posted, I'll take it inside the working group and I'm sure people will have opinions about what the most vulkanish thing to do would be.

One open item:  I'm currently copying the semantics of `mmap()` where we attempt to map at the requested location and then fall back to mapping somewhere else if we can't.  Is that what we want?  Or would we rather return `VK_ERROR_MEMORY_MAP_FAILED`?  I don't care much either way.  The `mmap()` behavior has the advantage of being flexible if the client gets the alignment a bit off.

**Comment by Guy1524** [comment]
> One open item: I'm currently copying the semantics of `mmap()` where we attempt to map at the requested location and then fall back to mapping somewhere else if we can't. Is that what we want? Or would we rather return `VK_ERROR_MEMORY_MAP_FAILED`? I don't care much either way. The `mmap()` behavior has the advantage of being flexible if the client gets the alignment a bit off.

I don't want to speak for anyone else, but in my opinion failing when the allocation can't be mapped makes more sense.  In wine we'll just be mapping into reserved space, and a different address returned would just be treated as an error anyway.   Doing it the first way also opens the door to subtle bugs in which other applications also have a requirement for a mapping at a given address, but forget to verify that the implementation hasn't adjusted it.

Of course, if we go down this route, I suppose we should add a note to the spec requiring the input address to be page aligned.

**Comment by jekstrand** [comment]
I posted a draft of some actual XML and extension text here: https://github.com/KhronosGroup/Vulkan-Docs/pull/1906  I've also updated the ANV implementation to have the `VK_ERROR_MEMORY_MAP_FAILED` behavior and also expose the features and limits properly.  I'll try and write a quick crucible test tomorrow to make sure it actually works. :joy:

**Comment by DadSchoorse** [comment]
> In wine we'll just be mapping into reserved space, and a different address returned would just be treated as an error anyway.

I agree, vkMapMemory should be able to to map into reserved space, we basically want mmap's `MAP_FIXED`. Additionally, to avoid race conditions on vkUnmapMemory, there needs to be a way to re-reserve the address space. So basically an option that doesn't free the address space immediately and allows wine to just reuse it with `MAP_FIXED`.

**Comment by jekstrand** [comment]
> Additionally, to avoid race conditions on vkUnmapMemory, there needs to be a way to re-reserve the address space. So basically an option that doesn't free the address space immediately and allows wine to just reuse it with MAP_FIXED.

We have exactly what `mmap()` gives you.  If you can tell me how that race is fixed with `munmap()`, I'm happy to do the same thing inside the driver.

**Comment by jekstrand** [comment]
If you're asking to be able to `vkMapMemory()` over top of other previously used ranges, that's gonna be tricky.  Not because the software is hard but because it really doesn't jive with the rest of the Vulkan spec.

**Comment by DadSchoorse** [comment]
> We have exactly what mmap() gives you. If you can tell me how that race is fixed with munmap(), I'm happy to do the same thing inside the driver.

In order to not have a race, winevulkan's `vkUnmapMemory` implementation needs to mmap over the mapped VkDeviceMemory with `MAP_FIXED`. And to make that legal winevulkan needs a way to tell the linux driver that the memory's address space is going to be remapped. So the driver wouldn't actually call munmap anymore, but something is needed to satisfy the "memory must not be currently host mapped" restriction on the next  `vkMapMemory`.

**Comment by jekstrand** [comment]
How do you not already have a race?  You have to select the address and then map.  If winevulkan is racy, something can happen between those two without any race from an unmap.  If you're using `MAP_FIXED`, there's no failure to tell you that you lost the race, it just succeeds in two places with only one of them getting a correct map.

**Comment by DadSchoorse** [comment]
The goal is to have wine reserve the low 4GiB (or 2GiB without LAA) of address space for the 32bit Windows application. So winevulkan is getting a memory range from wine's sub allocator, then we want to vkMapMemory to map over that reserved range. 
On vkUnmapMemory winevulkan somehow needs to return the range to wine's allocator. If the driver uses munmap something else (as in, not wine) could use the address space without `MAP_FIXED` before wine reserves it again. That race doesn't happen if wine could just mmap over the mapped VkDeviceMemory.

**Comment by jekstrand** [comment]
Ah, I think I see.  The objective is to keep the range reserved.  Would it be acceptable if `vkUnmapMemory()` did
```c++
mmap(mem->map, mem->map_size, PROT_NONE,
     MAP_ANONYMOUS | MAP_FIXED, -1, 0);
```
instead of
```c++
munmap(mem->map, mem->map_size);
```
That would still be an unmap from Vulkan's POV but from the OS view, the VA range would still be reserved.

**Comment by Guy1524** [comment]
Yeah, that would be the most ideal behavior for us.  Maybe it would make sense to look at the state of the page before vkMapMemory, save that, and restore them in vkUnmapMemory.  Then there could be spec language specifying that pages specified will be returned to their previous state on vkUmapMemory.

**Comment by jekstrand** [comment]
I think I'd rather it just be a flag to `vkUnmapMemory()` which can potentially be independent of `MEMORY_MAP_PLACED_BIT`.  That means writing VK_EXT_map_memory2 and basing this extension on that but that's not a big deal.  Just more typing for me.

**Comment by jekstrand** [comment]
Quick update:  I did a bit of digging and it looks like this can be implemented on RADV as well without kernel changes.  It'll require a bit of libdrm plumbing because RADV still uses libdrm and the libdrm helpers don't support fixed maps but the kernel interfaces look like they should be fine.

**Comment by jekstrand** [comment]
Could we please move the discussion to the spec PR: https://github.com/KhronosGroup/Vulkan-Docs/pull/1906.  That way people can comment on actual spec text if they want.  I'll be providing my updates there as well.
