### ISSUE TITLE
`VkShaderModuleCreateInfo` missing `pNext` VU

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1883]
`VkShaderModuleCreateInfo` is missing `pNext` VU. I assume the problem is it has some `structextends` despite the fact that it is 1.0 core struct.

**Comment by r-potter** [comment]
@oddhack `VkShaderModuleCreateInfo` used to be a base-only structure, and then `VK_EXT_graphics_pipeline_library` started allowing it to be be chained from `VkPipelineShaderStageCreateInfo`. 

This is the only case of a structure that is both a base structure and valid to chain that immediately comes to mind, so this unanticipated usage may have broken the auto-validity generator.

**Comment by oddhack** [comment]
> This is the only case of a structure that is both a base structure and valid to chain that immediately comes to mind, so this unanticipated usage may have broken the auto-validity generator.

Agreed that looks like what happened.Do you know if VkShaderModuleValidationCacheCreateInfoEXT is suppose to be allowed in both use cases of VkShaderModuleCreateInfo? It doesn't show up as allowed for VkPipelineShaderStageCreateInfo which I'm assuming is because it marks itself as extending VkShaderModuleCreateInfo instead.

If it's really a rare use case it probably makes more sense to set noautovalidity on pNext and put the constraint in by hand, than to do a ton of scripting work to identify the case and support it. Or perhaps we could introduce a noautovalidity="<term tbd>" to force generation of the VU even though it normally would not be.

**Comment by r-potter** [comment]
> Agreed that looks like what happened.Do you know if VkShaderModuleValidationCacheCreateInfoEXT is supposed to be allowed in both use cases of VkShaderModuleCreateInfo? It doesn't show up as allowed for VkPipelineShaderStageCreateInfo because it marks itself as just extending VkShaderModuleCreateInfo instead.

I believe @HansKristian-Work and I discussed this in a recent call (possibly in the context of VK_EXT_shader_module_identifier)? My recollection was that we should ask LunarG what they wanted to do here, but I'm failing at searching the minutes/gitlab history to find that discussion.

**Comment by r-potter** [comment]
This might need a separate issue, but I've just realised that the same issue exists with `VkPhysicalDeviceFeatures2`, which is a base structure for `vkGetPhysicalDeviceFeatures2` but can also be chained into `VkDeviceCreateInfo`, and I can't imagine us wanting to hand code that one as it gains additional extension structs with almost every extension.

**Comment by oddhack** [comment]
> This might need a separate issue, but I've just realised that the same issue exists with `VkPhysicalDeviceFeatures2`, which is a base structure for `vkGetPhysicalDeviceFeatures2` but can also be chained into `VkDeviceCreateInfo`, and I can't imagine us wanting to hand code that one as it gains additional extension structs with almost every extension.

I'll open an internal tracker on that. The point fix for the original issue is straightforward, this is not.
