### ISSUE TITLE
[Extension proposal] VK_KHR_gpu_usage

### ISSUE THREAD

**Issue by sh7dm** [KhronosGroup/Vulkan-Docs#1910]
# Summary
This extension should return the GPU usage percentage. I have came up with this idea when thinking about Gallium HUD for Zink. After discussing this with @zmike (https://gitlab.freedesktop.org/mesa/mesa/-/issues/6715#note_1496609) we decided to propose an extension for that.

## GPU support
Known support in underlying drivers definitely exists for AMD on Linux, Gallium HUD is able to get GPU usage on those.

Other drivers might also have opportunities to implement the query, but I have not explored that.

## Usability
The primary use-case is generic software getting system information.

This extension can also be helpful in case application developer wants to deprioritize rendering. For example, in case system has high GPU usage, the application might lower its graphics settings to leave more performance to the primary application.

## API
It appears to only require a single method taking physical device and returns (or sets via a pointer) a number (32-bit float), representing normalized GPU busy state (0 is not busy, 1 is maximum) for that device.

CC: @zmike

**Comment by polarina** [comment]
It might be worthwhile to expose the utilisation as a normalized floating-point number, for those drivers that can expose their utilization with more granularity than a whole percentage.

I believe it would be more consistent with the rest of the API as well. See e.g. queue priorities.

**Comment by sh7dm** [comment]
Sure, my proposal is just an outline. Thanks for the idea, I'll change the initial issue.

**Comment by r-potter** [comment]
I can see the appeal for HUD displays, but this sort of information requires additional context to understand and I'd caution against trying to use something like this to inform adaptive application performance. It's likely to have some tricky issues around frequency scaling, at least on mobile. 

We may reduce GPU frequency for thermal management reasons (too much work/heat), but we may also reduce it for efficiency reasons (the workload is light, and we can hit 60FPS at lower frequency/power budget).

There are at least two ways to define this metric:

* % GPU utilization at the current frequency
* % GPU utilization of peak frequency

If you define it as per the first bullet, it is possible to get into a situation where system governors downclock an underutilized GPU to save power, which in turn appears to make the GPU usage % rise. Applications reacting to this apparent increase in utilization by reducing workloads will then just make the situation worse.

If you instead define it as per the second bullet, then you get a situation where reported GPU utilization appears low, but in reality that is because the device is overloaded/hot and has been downclocked to dissipate heat. In that case, interpreting low utilization as an opportunity to increase workloads will also lead to negative results.

**Comment by sh7dm** [comment]
Well, I guess my idea was wrong. HUDs and system info apps are the main target, so the reporting should happen the way driver reports it

**Comment by jackohound** [comment]
Is there a reason you cant leverage [VK_KHR_performance_query](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_performance_query) for the HUD?  While that extension doesn't provide pre-defined metrics like "% GPU utilization", I suspect every implementation would include % GPU utilization as one of the available metrics.

**Comment by sh7dm** [comment]
It seems to be for GPU profiling of the application. Should counters be as implementation-defined as needed for this to report GPU%?

**Comment by zmike** [comment]
As per WG discussion, this is not viable: performance queries of any kind are banned on Android, so mobile vendors will not be able to implement.

On desktop, there are already various performance queries, so zink should be able to leverage those to produce query data for the hud.

**Comment by sh7dm** [comment]
Why are performance queries banned on Android? Is there any reference on it?

**Comment by r-potter** [comment]
Because it was impossible to prove that the queries in [VK_KHR_performance_query](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_performance_query) wouldn't allow one application to infer information about the behaviour of other applications (essentially performing a [side-channel](https://en.wikipedia.org/wiki/Side-channel_attack) attack).

**Comment by sh7dm** [comment]
Well, that might be true. Maybe drivers must add some randomness to hinder side-channels on other clients? A little bit should be enough (well, something that might be important lies in <0.01% of modern GPU capabilities, so 1% precision should be fine.

**Comment by zmike** [comment]
The current avenue of discussion regarding side-channel attack mitigation seems like it could be the topic of another issue, but it probably isn't (as) relevant here, where the WG has determined that extensions already exist for this solution space.

If you have issues with Android security policy, you might consider reporting them to Android.

**Comment by TomOlson** [comment]
@sh7dm, the WG discussed this at our last meeting and we don't think we can offer significant value through an extension like this. We get that a truly device- and platform-independent way to get easily interpreted perf numbers would be great to have at development time - that is what led to [VK_KHR_performance_query](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_performance_query). Developing that extension turned out to be incredibly painful because of the huge variability in what numbers different GPUs collect and what they mean. (See @r-potter's comment above). In the end, it didn't provide the portability we were hoping for, and between that and the side-channel problem, it is not supported widely enough to be particularly useful. We think this proposal would run into the same problems and meet the same fate, and we don't want to go there.

That said, thanks for the input - we are always glad to hear what problems people are having using Vulkan, and to consider ideas for solving them.

**Comment by sh7dm** [comment]
Thank you so much for considering this proposal! That's no problem, apparently sideways can be used like querying sysfs directly, so this isn't a blocker for anything. I will close this report now.
