### ISSUE TITLE
Trivial specs change: Infinity should be UINT32_MAX, not 0

### ISSUE THREAD

**Issue by Beyondo** [KhronosGroup/Vulkan-Docs#1915]
Hello, I really like Vulkan but I don't agree with the current specification for infinities. 0 shouldn't mean infinity. 
Example: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html

A value of `0` here should mean the GPU is not capable of presenting images in the first place.
A value of `UINT32_MAX`  or `0xFFFFFFFF` should mean infinity.

Instead of writing
`uint32_t imageCount = std::min(caps.minImageCount + 1, caps.maxImageCount == 0 ? std::numeric_limits<uint32_t>::max() : caps.maxImageCount);`
It'll be just
`uint32_t imageCount = std::min(caps.minImageCount + 1, caps.maxImageCount);`
As it is supposed to be. Maybe also define a macro called `VK_INFINITE_IMAGE_COUNT` or something that's equal to `UINT32_MAX` if someone wants to check for (_or use..?_) infinities.

In all Vulkan tutorials and resources, they all add those pesky _**infinity checks**_ (in many different shapes and forms of ugly if && blocks). _All because infinity in Vulkan is defined as the **opposite** of what it is... `0`._

**Infinity isn't the smallest number. It is the biggest.** Vulkan should be more logical.

I'd like to note that modifying this spec wouldn't affect any old Vulkan projects at all, in fact, **they'll work perfectly fine**. But it'd remove the need for infinity checks in the future. See how redundant they are?

**Comment by krOoze** [comment]
Frankly makes more sense to me the way it is. In C++ `0` typically means the variable does not exist and can be used in `if`s and such.

For example: 

```
if( maxImageCount ) //in english: "driver has max limit"
	doSomething();
else  //in english: "driver does not have max limit"
	doSomething();
```

**Comment by Beyondo** [comment]
> Frankly makes more sense to me the way it is. In C++ `0` typically means the variable does not exist and can be used in `if`s and such.
> 
> For example:
> 
> ```
> if( maxImageCount ) //in english: "driver has max limit"
> 	doSomething();
> else  //in english: "driver does not have max limit"
> 	doSomethingElse();
> ```

That's not true. You mean **pointers** which utilize `nullptr` or `NULL` for non-existence. However, the `maxImageCount` is a perfectly valid normal storage variable, not a pointing variable; and thus should be treated as such.

Your example doesn't even suggest any kind of useful use because you could replicate the same functionality using the same number of lines of code with `UINT32_MAX` being the code for unlimited. Meanwhile, having `UINT32_MAX` being the norm suggests a lot of useful use like lesser code such as no infinity checks in many creation functions.

```
if( maxImageCount != VK_INFINITE) // has a  limit
	doSomething();
else // does not have maximum limit
	doSomethingElse();
```

I understand change must be hard for some people to accept but all of your reasonings are invalid, and illogical; let alone using 0 as infinity. Vulkan is the future of computer graphics, at least in my view, and I just want its API to be more logical.

Imagine simply checking if a GPU supports more than 3 image count, and it does support unlimited amount! **But suddenly your if-statement fails because as it seems.. infinity is defined to be smaller than 3.** Do you think this is logical?

I rest my case.

**Comment by krOoze** [comment]
I don't mean pointers. For example `0` char can signify "no character" and is often used as end of string.

It feels like qualitative difference whether GPU supports 3 images, 1024 images, or it does not have a limit at all (not infinity). 
I think about it from consistency perspective. If I am using raw values, they must all be equal in importance. But infinity is not equal here. Imagine some driver implementation:

```
constexpr int maxImageCount = 8;

Stuff importantImageStuff[maxImageCount];

int vkReturnLimit() { return maxImageCount; }
VkResult vkCreateSwapchain(){
	for( int i = 0; i < maxImageCount; ++i){
		if( i < swapchainImageCount )
			importantImageStuff[i].img = createPixbuf();
		else
			importantImageStuff[i].img = null_handle;
	}
}
```

You wouldn't just change `maxImageCount` to `UINT32_MAX`. For no limits, the implementation has to be qualitatively different. It is not just a change of int value. The `UINT32_MAX` value would have a different meaning and importance than a value 8. It simply means something else. I don't like raw conditionals as much as the next guy

It's a matter of taste. I do use the `if` in my code, because it looks readable and selfobvious and not lake caffeinated singleline math spaghetti. Esthetics is not logic. Anyway, first world problems. I will leave you be...

**Comment by r-potter** [comment]
Apart from truly exceptional cases, we aim to avoid changing the specification in ways that would invalidate existing shipping drivers.

Whilst it's possible to argue the merits of `0` vs. `UINT32_MAX`, changing the value leads to a situation where some (pre-existing) drivers would return 0, whilst newer drivers would return `UINT32_MAX`. Consequently since the older drivers would continue to exist in the wild, applications would be forced to handle both cases. That doesn't seem like an overall improvement for developers.

**Comment by oddhack** [comment]
The working group discussed this and @r-potter is correct. We cannot change an existing specification in this fashion. Closing as there's no action to be taken.
