### ISSUE TITLE
VK_USE_64_BIT_PTR_DEFINES misclassified as being available starting with Vulkan 1.0

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#1917]
This definition is listed in the section for preprocessor symbols introduced with Vulkan 1.0, but this is not the case, as it was introduced in v1.2.174 and therefore any usage of it fails to compile on older versions of the Vulkan headers (such as any Vulkan 1.0 or Vulkan 1.1 system).

I think this is misleading, confusing and [leads to unexpected failures](https://code.videolan.org/videolan/libplacebo/-/jobs/1111479).

**Comment by oddhack** [comment]
I'm unsure if you're referring to the XML or the spec by "section for preprocessor symbols introduced with Vulkan 1.0"?

The only useful action I can think of offhand is to add a Note to the macro's refpage advising people to check VK_HEADER_VERSION >= 174 if they rely on this macro, and recommend bundling current headers into projects if the build environment is too old. The same sort of issue could come up any time someone relies on a preprocessor-level change in the headers, such as the VK_ENABLE_BETA_EXTENSIONS / vulkan_beta.h change introduced in 1.2.171 (though we do have a Note in that section of the spec).

We have to put the macro somewhere in the XML and since it affects the definition of 1.0 stuff such as VK_NULL_HANDLE, that is the logical place to put it.

**Comment by haasn** [comment]
> I'm unsure if you're referring to the XML or the spec by "section for preprocessor symbols introduced with Vulkan 1.0"?

I wasn't sure there's a distinction, but I noticed it in the XML.

> The only useful action I can think of offhand is to add a Note to the macro's refpage advising people to check VK_HEADER_VERSION >= 174 if they rely on this macro

That would solve my problem, yes.

**Comment by oddhack** [comment]
> > The only useful action I can think of offhand is to add a Note to the macro's refpage advising people to check VK_HEADER_VERSION >= 174 if they rely on this macro
> 
> That would solve my problem, yes.

Please see #1918.
