### ISSUE TITLE
What is the intention of `VkPhysicalDeviceLimits::timestampPeriod` on a GPU that varies its clocking speed based on GPU load?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Docs#1940]
What is the intention of `VkPhysicalDeviceLimits::timestampPeriod` on a GPU that varies its clocking speed based on GPU load?

Is `VkPhysicalDeviceLimits::timestampPeriod` intended to be fixed at some nominal system value, and read once during app start-up, or it is intended to be a dynamic value that changes depending on GPU loading and dynamic clock-speed, and is intended to be read on a regular ongoing basis by the app to calibrate GPU timestamp values?

I also note that the `vkGetCalibratedTimestampsEXT()` call from the Vulkan `VK_EXT_calibrated_timestamps` extension seems to be intended to do periodic calibrations between the GPU and CPU timestamps.

Some clarity on the use of `VkPhysicalDeviceLimits::timestampPeriod` vs `vkGetCalibratedTimestampsEXT()` would be helpful here, and in the Vulkan docs.

**Comment by r-potter** [comment]
> Is VkPhysicalDeviceLimits::timestampPeriod intended to be fixed at some nominal system value, and read once during app start-up, or it is intended to be a dynamic value that changes depending on GPU loading and dynamic clock-speed, and is intended to be read on a regular ongoing basis by the app to calibrate GPU timestamp values?

The spec doesn't explicitly say so (and probably should), but my expectation is that all properties returned by `vkGetPhysicalDeviceProperties` are immutable and thus `VkPhysicalDeviceLimits::timestampPeriod` is a constant. We really don't want applications to be forced to regularly poll physical device properties.

> I also note that the vkGetCalibratedTimestampsEXT() call from the Vulkan VK_EXT_calibrated_timestamps extension seems to be intended to do periodic calibrations between the GPU and CPU timestamps.

The primary purpose of this function is to allow applications to calculate what host timestamp value (as returned by `QueryPerformanceCounter`/`CLOCK_MONOTONIC`) relates to what GPU timestamp value and vice versa. My understanding is that the references to re-calibration in the appendices are to address the fact that host timestamps may drift a little due to NTP servers, not to imply that applications should be doing the sort of high-frequency polling that would be implied if DVFS was a factor.

**Comment by oddhack** [comment]
@billhollings if @r-potter's reply answered the question, could you close this? Thanks.

**Comment by billhollings** [comment]
@r-potter Thanks for the background info. 

If anyone else has any commentary to add, I'd appreciate it, but at the request of @oddhack, I'll close this for now.

**Comment by TomOlson** [comment]
@billhollings no new information, except to say that the WG reviewed @r-potter's comment above and agrees with it.
