### ISSUE TITLE
Does index buffer need to be bound if it is not accessed

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1947]
#1945 cont.

`instanceCount` is allowed to be `0`, or `indexCount` can be `0`? Or  `gl_VertexIndex` need not be acessed if there is only one vertex per instance and using instance id, or perhaps if there is no vertex buffer (maybe something with using atomics)? Or maybe conditional rendering.

Does index buffer indeed always need to be bound?

**Comment by Eearslya** [comment]
If `instanceCount` or `indexCount` were 0, there would be nothing there to draw, and the vertex shader would never get called in the first place. If you only have one vertex per instance, then what's wrong with `vkCmdDraw`?

**Comment by krOoze** [comment]
It's not a question of what command is better to use. It is a question of water-tightness of the Vulkan specification.

**Comment by HansKristian-Work** [comment]
There is very little reason to add special cases for statically empty draws. I think the intention is that index buffers must be bound if you call the indexed command. Otherwise, you'd force a driver into checking for 0 and omit accessing the index buffer which might crash.

**Comment by krOoze** [comment]
It's not about adding special cases neither. The corner cases are already allowed as far as I can tell. It is about the consistency, unambiguity, and completeness of the specification.

**Comment by Tobski** [comment]
Along the lines of water-tightness of the spec, we have a general rule in Vulkan when we come across a hole - either we ban something by VU, or we ensure it works and test it. What drives our decision one way or the other is whether anyone's actually going to use it - we make a value judgement.

Banning something is generally much less impactful than allowing it in terms of working group and implementer resources, so if there's no use cases we will tend towards that. If we allow it we need to add CTS tests and then spend cycles debugging those tests. If it turns out we get it wrong, we fix it in a maintenance extension later.

Right now, our assumption that nobody needs this - there are two key cases for 0-sized draws we're considering:

1. Application doesn't know it'll be 0 in advance, only that it _might be_
2. Application knows that it'll be 0

For 1. if the application doesn't know, then they're going to have the information to bind an index buffer. For 2. if the application **does** know then it could trivially skip the draw call, making this moot.

If we were to enable something like indirect binding of index buffers in future it might make sense to make a different judgement on this, as then it might be that whatever produces the 0 would also not want to generate an index buffer; however even then binding a dummy index buffer would work.

So for now, we see no value in adding this functionality, but certainly can't rule out adding it in the future.

**Comment by oddhack** [comment]
Vulkan WG is closing this as explained in previous comment.

**Comment by krOoze** [comment]
@oddhack So you plan to forbid empty indexed draws?

**Comment by Tobski** [comment]
@krOoze We are requiring that an index buffer be bound when you do an indexed draw, whether it has a count of 0 or not, in keeping with #1945.

**Comment by krOoze** [comment]
@Tobski But creating buffer of size 0 is not possible.

**Comment by Tobski** [comment]
What is the use case where that would be an issue and can't be solved another way?

**Comment by Tobski** [comment]
Sure, if we were to design this API from scratch we'd make different design choices - I don't disagree with you in theory, but in practice we have to be pragmatic when choosing where to spend our cycles fixing things. We could put "non-zero buffers" on the "fix in maintenance5" pile (yes we have one of those), and in fact I may do that. That wasn't the original issue stated here though, hence closing this issue.

I would also note that there's some movement to supercede buffer APIs with device address APIs, and assuming we do that for index binding it would absolutely make sense to allow using an invalid address if it's not going to be accessed. So I think this problem can be solved, it's just a case of choosing how and where we solve it.

**Comment by Tobski** [comment]
I've added this item to our maintenance pile and linked here, and I've also separately noted how we could fix this with device addresses.

**Comment by krOoze** [comment]
Ok ok, how do you feel about a spec note noting the potential discrepancies. The thing is I don't like discrepancies, because my mind goes straight to thinking whether they are meaningful, or whether they are some kind of mistake or what. Explicitly noting the sharp corners goes a long way, even if it leads to things never being fixed. The annoying part is this is simple draws (not tricky device generated stuff or something), so any warts are extra visible...

Doing something with device addresses is not exactly a fix. More of a not repeating the same mistake again...
