### ISSUE TITLE
Missing getter for VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/Vulkan-Docs#1968]
It seems like swapchain functions are guaranteed to return `VK_ERROR_DEVICE_LOST` on device loss. However if an application doesn't use swapchains (just allocates and renders its own images, e.g. a Wayland compositor), then there is no reliable way to check for device loss that I found.

OpenGL for instance has `glGetGraphicsResetStatus()`.

**Comment by K0bin** [comment]
A headless application would run into DEVICE_LOST when calling vkQueueSubmit.

**Comment by emersion** [comment]
That is not guaranteed to happen AFAIU:

> If vkQueueSubmit fails, it may return VK_ERROR_OUT_OF_HOST_MEMORY or VK_ERROR_OUT_OF_DEVICE_MEMORY. If it does, the implementation must ensure that the state and contents of any resources or synchronization primitives referenced by the submitted command buffers and any semaphores referenced by pSubmits is unaffected by the call or its failure. If vkQueueSubmit fails in such a way that the implementation is unable to make that guarantee, the implementation must return VK_ERROR_DEVICE_LOST. See [Lost Device](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#devsandqueues-lost-device).

**Comment by emersion** [comment]
Hm, I now realize that I read that as "VK_ERROR_DEVICE_LOST must be returned only in this situation". But one could read it as "VK_ERROR_DEVICE_LOST must be returned in this situation, but may also be returned in other situations".

It would be nice to have some kind of phrasing saying that `vkQueueSubmit` **must** return VK_ERROR_OUT_OF_HOST_MEMORY after device loss happens.

**Comment by r-potter** [comment]
This one is unfortunately a little bit thorny because device loss is untestable (i.e. we have no specification compliant way to trigger device loss in the first place). Typically device loss indicates invalid usage from an application (in which case we are into undefined behaviour), driver bugs (implying the implementation has strayed beyond the specification), or a physical hardware issue.

I'm actually surprised that the WSI phrasing is as strong as it is. We also have this piece of general text on device loss:

> Once a device is lost, command execution may: fail, and commands that return a elink:VkResult may: return ename:VK_ERROR_DEVICE_LOST.

**Comment by emersion** [comment]
Note, here I'm only interested in physical hardware issues (GPU disconnect or GPU reset).

**Comment by r-potter** [comment]
👍 I'll pick this up for internal discussion. If nothing else I think the language could be more consistent. Just cautioning that it may be hard to provide concrete guarantees on this one.

**Comment by oddhack** [comment]
@r-potter I lost track of where we are on this? The internal tracker was closed but the public issue hasn't been. I believe you made an MR back in December, but not sure if that closed this issue.

**Comment by r-potter** [comment]
This was left open because there was an additional part coming in maintenance5: "Adds stronger guarantees for propagation of VK_ERROR_DEVICE_LOST return values". That change enforces that once device lost has occurred, it must propagate to all entrypoints for which device-lost is a valid return value.

Since maintenance5 is published now, I'll close the issue.
