### ISSUE TITLE
What happens when an extension is promoted?

### ISSUE THREAD

**Issue by LouChiSoft** [KhronosGroup/Vulkan-Docs#1989]
Apologies if this is stated somewhere, but I couldn't find it. I would like to use the Int64Atomics type in my application and when reading the spec it states that it was promoted to core with Vulkan 1.2 and that the original types, enums, etc. are aliases for their core versions. But it also mentions that if Vk 1.2 is supported but the extension isn't that `shaderBufferInt64Atomics` is optional. I find this a bit confusing, does this mean that you still need the extension to use the Int64Atomics data type? Do I still need to use `VkPhysicalDeviceShaderAtomicInt64FeaturesKHR` to query for support etc. 

I figure learning this information from the context of any extension that has been promted will help me better in the future than just learning about this 1 extensions specifically

Edit: My app is targeting Vulkan 1.3

**Comment by critsec** [comment]
Being promoted means that the function entry points will exist, feature queries will be available, and so on. In other words, the implementation knows about the promoted extension and provides basic support for it, without needing to check for or enable an extension. But just like some core functionality in Vulkan 1.0 was optional, the functionality of a promoted extension can be optional, in which case you still need to query whether the feature is supported before trying to use it (e.g. by providing a shader that uses the `Int64Atomics` capability).

The original extension required the functionality, since if the implementation wasn't going to support that, it's simpler to just not advertise the extension at all. When the extension gets promoted into core (so the basic API is always available) then the functionality might be optional.

There's a logical consistency to that, but it's subtle and often confuses people. That's one reason Vulkan 1.3 only promoted extensions when at least some of the features could be required on all Vulkan 1.3 implementations -- then not only does having Vulkan 1.3 guarantee that the basic API constructs are available, but that some useful functionality is also available.

**Comment by LouChiSoft** [comment]
Okay, wow. That was not as simple as I was hoping 😄. So if an extension is promoted I need to check what part of it is optional and what part is required, and show anything I want to use be optional use the same functions calls that the extension uses to check? 

So for my example of the shader atomics that means that `VkPhysicalDeviceShaderAtomicInt64FeaturesKHR` is provided by the extension and `VkPhysicalDeviceShaderAtomicInt64Features` was provided once it was promited to a core feature? And you can query that information without the need for `VK_KHR_shader_atomic_int64` as long as I am using version 1.2 or later because `VkPhysicalDeviceShaderAtomicInt64Features` should always be available?

**Comment by LouChiSoft** [comment]
Thanks, I think that has cleared up most of my confusion and for the most part I think I should be okay to choose whether or not to use suffixes.
