### ISSUE TITLE
PVRTC1 textures must have dimensions that are power-of-two

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/Vulkan-Docs#1991]
The Vulkan spec currently allows the use of PVRTC1 textures that do not have power-of-two dimensions. For one, this requirement is in the [OpenGL ES spec](https://registry.khronos.org/OpenGL/extensions/IMG/IMG_texture_compression_pvrtc.txt) and in the [Khronos Data Format Specification](https://registry.khronos.org/DataFormat/specs/1.3/dataformat.1.3.html#_format_pvrtc1_4bpp). Secondly, this seems to be a design requirement of the texture format itself, meaning that images with non-power-of-two dimensions would simply not work. This does not apply to PVRTC2.

However, I could not find a source from imgtec explicitely saying that PVRTC1 textures have this requirement and instead I only found [this PDF about PVRTC2](https://imgtec.eetrend.com/sites/imgtec.eetrend.com/files/download/201712/10872-31543-pvrtc-and-texture-compression-user-guide.pdf) which states:

> - **Non-Power-of-Two (NPOT) dimensions**: PVRTC2 offers the developer the use of arbitrary-sized NPOT textures, which are textures that do not have dimensions that are limited to powers of two.

And a few other sources I found:

> Remember that PVRTC1 requires square power of 2 size textures, [...] ([BasisU](https://github.com/BinomialLLC/basis_universal/wiki/How-to-Deploy-ETC1S-Texture-Content-Using-Basis-Universal))

> Textures compressed with PVRTC1 formats must be square and power-of-two sized. ([Love2d](https://love2d.org/wiki/CompressedImageFormat))

The layout of PVRTC1 does not require the images to be square (only power-of-two), however there's some hardware which restricts itself to square textures such as iOS devices.

This issue stems from KhronosGroup/MoltenVK#1760.

**Comment by Degerz** [comment]
PVRTC has been deprecated.

**Comment by fluppeteer** [comment]
PVRTC *is* deprecated, but PVRTC1 does need to have dimensions that are powers of two (partly because you're expected to upload the texture in Morton order and there's no allowance for padding); PVRTC2 (which is almost completely a superset) does not have this requirement, and the driver would insert padding as necessary (possibly including not backing pages which fall beyond the limits). The official PVRTexTool will only allow PVRTC1 output for textures with power-of-two dimensions, although they don't need to be square. The square requirement is specific to Apple, though.

The PVRTC1 description in the KDFS should be considered to be authoritative (barring any accidental errors). However, it's true that Vulkan doesn't currently contain validation to confirm that a user hasn't attempted to create an image of PVRTC1 format with npot sizes; we're working on adding this, so thank you for the catch.

**Comment by Degerz** [comment]
> Does that disallow any spec changes to happen now? The extension still allows for invalid textures, which imo should still be changed after the fact, regardless of it being deprecated. It's still a flaw in the spec.

Don't know if the Vulkan working group will consider spending time fixing this issue but I don't think they're opposed to letting the community resolving this ?

**Comment by fluppeteer** [comment]
Yes, deprecated or not we should still fix it. The working group is aware, a clarification line has been written, and I'm on the hook to get validation in once it bubbles through the pipeline (sorry, I'm the stumbling block at the moment, but I'm on it).

**Comment by carlosVirella** [comment]
There's a group of people bothering me everyday at my building they enter to my phone they take out transactions and they keep changing them and saying lots of lies. I've been fighting them a lot while I'm a influential person at securities and investments and crypto. There's specific one girl that talks like a little girl that she is the one planning my everyday destruction. I'm creator of VMWare, Snowflake, Broadcom and many other important securities and seem like there's no peace for me not even on the home side since this people is bothering and harassing me to the point that nobody listens to me. Their bullying is real and i need help confirming myself in front of the S.EC. and others. They destroyed a website called sec report. So if you can talk to someone and make this happen here my number 7187900461 or email CarlosAVirella@gmail.com

**Comment by oddhack** [comment]
This should be fixed in the current spec update.
