### ISSUE TITLE
Redefinition of typedef 'PFN_vkGetInstanceProcAddr'

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-Docs#1998]
Following the commit 2826791bed6a793f164bf534cd859968f13df8a9, there are two instances of this line in `vulkan_core.h`:
`typedef PFN_vkVoidFunction (VKAPI_PTR *PFN_vkGetInstanceProcAddr)(VkInstance instance, const char* pName);` (Lines 3915 and 15545)
This can lead to the following: `error: redefinition of typedef 'PFN_vkGetInstanceProcAddr' is a C11 feature [-Werror,-Wtypedef-redefinition]`

**Comment by oddhack** [comment]
Thanks. We are aware of the problem, and it should be fixed in a day or two. Also the trivial compilation tests we run the headers through in CI are being strengthened so they'll actually catch this sort of thing going forward; the flip side is that I just discovered that the C headers cannot be used with a C++ compiler that isn't C++11 compliant, for reasons unrelated to this issue. Since nobody has reported that I'm guessing it doesn't actually affect anyone.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.237 spec update.

**Comment by aabdolrashidi** [comment]
Thank you for the fix!
