### ISSUE TITLE
Vulkan Specification lacks certain niceties in PDF format

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#2]
In the OpenGL specification PDF, you can look at the page header to see exactly what section you are in. The Vulkan PDF seems more like a printout from a web-browser; the header has the name of the document, but not the name of each section on each page. That makes it hard when you link from one area to another to tell exactly where you are.

Also, the bookmarks on the Vulkan PDF lack chapter names. So if you find a section header that says `8.4`, you have to count the items in the bookmarks to find out the name of Chapter 8. The OpenGL PDF puts the chapter numbers before the chapter names in the PDF bookmarks.

**Comment by fluppeteer** [comment]
Believe me, you have no idea how much better the PDF output is than it could have been. We're investigating some tool chain improvements that might help, but in the short term we have much less control than one might hope for since we're trying not to make modifications to open-source tools (and we're trying to allow everyone to build the spec without heavy toolchain demands). Because the same source is used for multiple output formats, we don't have the level of flexibility available to documents like the GL specification, which is basically a single-format document.

That said, you might find different behaviour in a different PDF reader. Evince currently shows me _only_ the section names (and not the numbers) in the side bar, which is inconvenient in a different way. It does tell me which section my current page is in, however. Or there's the HTML version, if that's easier.

Requests for improvements are much appreciated, and we'd certainly want to incorporate as many as we can into making the spec usable for everyone, I'm just giving a warning that issues of this sort might take a while (and substantial changes) to rectify, no matter the level of interest from those of us who are keen to improve things.

**Comment by oddhack** [comment]
Per @fluppeteer - we are also hoping to move over from asciidoc to asciidoctor (which is actively maintained, unlike asciidoc) soon. Unfortunately it's not a drop-in replacement process, and we know that when it happens, we'll be confronting a different set of output generation issues to fix, so that's limited our appetite for tweaking everything to work just right with asciidoc.

**Comment by krOoze** [comment]
Maybe it is time to revisit this. So:

PDF bookmarks work well for me for some time now (in Foxit Reader and in Chrome anyway).

Links are now blue, which is nice(-er). Not sure how I feel about "here" style links - I guess nobody prints the doc anyway nowadays.

Adding chapter names to page header (or footer) seems trivial now in Asciidoctor (PR #458).
