### ISSUE TITLE
VkPhysicalDeviceLimits::framebuffer*SampleCounts and VK_KHR_dynamic_rendering

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#2015]
[VK_KHR_dynamic_rendering] @tobski

Are  `VkPhysicalDeviceLimits::framebuffer*SampleCounts` and `maxFramebufferWidth`, `maxFramebufferHeight`, `maxFramebufferLayers`  limits still apply to VK_KHR_dynamic_rendering?

I can't see any mention at the specification of `vkCmdBeginRendering`, `VkRenderingInfo`, `VkRenderingAttachmentInfo`.
On the other hand there are no alternatives to report the sample counts and dimension limits of attachments.

**Comment by janharaldfredriksen-arm** [comment]
Hi,
They should apply.  It's true that they aren't mentioned at vkCmdBeginRendering etc. - whereas they are mentioned in VkFramebufferCreateInfo.

That said, there are valid usage statements on image creation to do restrict dimensions:

>If usage includes VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT, or VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, extent.width must be less than or equal to VkPhysicalDeviceLimits::maxFramebufferWidth

I think layers and sample counts get similarly covered by the rules in the "Image Creation Limits", though those are admittedly quite obscure.

**Comment by plasmacel** [comment]
Thanks. For clarity, I think it should be also mentioned at the specification of the appropriate `VK_KHR_dynamic_rendering` commands/structures.

**Comment by Tobski** [comment]
Hi @plasmacel - looking at it, I think we do need to add the max framebuffer width/height/layers to VkRenderingInfo at least for rendering with no attachments, because if there are no attachments then the render area/layers cannot be validated against the image sizes (which would otherwise take care of it).

I don't think the sample counts should be mentioned there though, as it would be impossible to get past image or pipeline creation without running into this, and you wouldn't be able to do much about it at rendering time.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.239 spec update.
