### ISSUE TITLE
Vulkan supports converting yuv to rgb, but does not support converting rgb to yuv. I hope to support it

### ISSUE THREAD

**Issue by jincaihong** [KhronosGroup/Vulkan-Docs#2026]

**Comment by spencer-lunarg** [comment]
A common use case of YUV -> RGB is for taking images from camera that are in YUV formats and being able to sample them.

Currently with `VK_EXT_rgba10x6_formats` you are able to render to `VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16` (if the HW supports it) 

I guess what is the use case you hope to use RGB -> YUV for?

**Comment by jincaihong** [comment]
> A common use case of YUV -> RGB is for taking images from camera that are in YUV formats and being able to sample them.
> 
> 
> 
> Currently with `VK_EXT_rgba10x6_formats` you are able to render to `VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16` (if the HW supports it) 
> 
> 
> 
> I guess what is the use case you hope to use RGB -> YUV for?

**Comment by jincaihong** [comment]
> YUV -> RGB 的一个常见用例是从相机获取 YUV 格式的图像并能够对其进行采样。
> 
> 目前`VK_EXT_rgba10x6_formats`你可以渲染到`VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16`（如果硬件支持的话）
> 
> 我想您希望使用 RGB -> YUV 的用例是什么？

We need to obtain yuv data from the camera, then beautify it, and then convert it to yuv output to the subsequent process

**Comment by fluppeteer** [comment]
At the moment, it appears that IHVs are not in a position to expose any accelerated way to write to YUV, incorporating a conversion. That may change in the future, but for now there are too many options in how the filtering/downsampling/conversion should work in order to meet user requirements, so I'm afraid we don't really have a better option than suggesting you write a shader that writes to the channels separately (e.g. with aliased targets for the channels).

**Comment by oddhack** [comment]
@jincaihong can this issue be closed? As @fluppeteer noted, this isn't a hardware capability that would be expressed through Vulkan today.
