### ISSUE TITLE
VkPipelineShaderStageCreateInfo is defined in the Compute Pipeline section

### ISSUE THREAD

**Issue by kainino0x** [KhronosGroup/Vulkan-Docs#2030]
While searching the spec for "FragDepth" I was surprised to find an instance of it in the [Compute Pipeline section](https://registry.khronos.org/vulkan/specs/1.3/html/chap10.html#pipelines-compute). This turned out just to be because that's where the definition is for the struct `VkPipelineShaderStageCreateInfo`, which is used for both compute and render pipelines.

It seems like that definition should be in a "common" section of some kind?

**Comment by oddhack** [comment]
We try to group all the API descriptions at the point of first use, which is what this is. Meanwhile the VUIDs are grouped with the structure they apply to. Perhaps it would help to add a comment at the start of the structure  definition that it's included in both compute and render parent structs?

**Comment by kainino0x** [comment]
I don't have strong opinions, just figured I'd file it in case it wasn't by design, but sounds like it is, so I won't oppose closing "working as intended".
My confusion was because of the search results (on the multipage spec) which isn't a huge deal.

Just spitballing, is it possible for these validation errors to be written somewhere in the render pipeline section instead of attached to `VkPipelineShaderStageCreateInfo`?

**Comment by oddhack** [comment]
The VUs are by design included with the command or structure they apply to. I do get that some of the description is out of place, just don't see great options other than an explanatory comment - there are some other cases like this where a struct or enumeration used in multiple places is described in only one of those places, too.

Eventually I'd like to modify the source markup generator to inject links from the type names to the corresponding parts of the spec, but that hasn't been straightforward - few of the markup generators available for the asciidoctor pipelines are very actively maintained, so it's hard to get questions answered.
