### ISSUE TITLE
VK_EXT_discard_rectangles and VK_NV_scissor_exclusive compatibility

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/Vulkan-Docs#2060]
The spec adds new functions to existing extensions in 241 update:

```
  * Add dynamic state to apiext:VK_EXT_discard_rectangles
    (ename:VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT and
    ename:VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT) and for
    apiext:VK_NV_scissor_exclusive
    (ename:VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV) that was overlooked
    in apiext:VK_EXT_extended_dynamic_state3. While this is adding
    functionality to existing extensions, the implementers of these
    extensions have all signed off on this change (internal merge request
    5671).
```

I don't fully understand what this means. Are these extensions still "experimental" and not supposed to be used - if so, is that information anywhere in the XML schema?
If they are not experimental, does this mean no driver is shipping support for these and will only ship 241-compatible function set?

(aside: Any retroactive change like this creates problems for volk, as the newer library version becomes incompatible with older SDK headers due to absence of new function prototypes and structures/enums/etc. that they reference. This happened before with VK_NVX_image_view_handle and VK_HUAWEI_subpass_shading but it's worrying that this keeps happening without publishing a new extension.)

**Comment by zeux** [comment]
VK_NV_scissor_exclusive is definitely shipping in the wild. I don't understand this - if I write an application that uses newly added vkCmdSetExclusiveScissorEnableNV, this will *not* work on older drivers. Does this mean any user of VK_NV_scissor_exclusive has to be aware of the extension *version* and check it somehow?

**Comment by zeux** [comment]
Additionally, vk.xml doesn't seem to have any information about which specific functions were added in which extension versions. That seems particularly problematic since there's basically no way to know if any use of a version 2 extension is safe on a version 1 implementation...

**Comment by zeux** [comment]
> That seems particularly problematic since there's basically no way to know if any use of a version 2 extension is safe on a version 1 implementation...

Plus since you can *check* the exposed version, but you can't *declare* that you need a specific version when creating a device, this means that validation layers will never be able to check whether the app correctly checks specVersion when newly added entrypoints are used. This goes against some correctness goals as I understand them, in particular the need to specify extensions that you use and features that you use, even for features/extensions that are zero-cost to enable globally, seems to have come from a desire to be able to guarantee that the app doesn't silently use features/extensions that may or may not be available.

I understand the reluctance to specify yet another dynamic state extension but this really feels like what should have been the route taken :( I don't know if it can be reconsidered at this stage.

**Comment by pdaniell-nv** [comment]
Yes, applications that want to use the new functions will need to make sure the implementation advertises version 2 of the extension. There are the following VUs for this:
- https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdSetDiscardRectangleEnableEXT-specVersion-07851
- https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdSetDiscardRectangleModeEXT-specVersion-07852
- https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdSetExclusiveScissorEnableNV-exclusiveScissor-07853

It's not ideal these extensions were updated like this, and this is not normal process for the working group. It was decided we can make an exception for these particular extensions because they are very esoteric and only implemented by one or two vendors, both of whom plan to update their drivers to support the new functions asap.

Sorry for the trouble it has caused you in updating volk.

**Comment by oddhack** [comment]
@zeux your points are well-taken and we'll continue trying to avoid this in the future; but we don't think there's anything actionable here (or rather, we are not prepared to put in the very large amount of work required to actively support extension versioning). If you agree, please close this.
