### ISSUE TITLE
Request for clarification with `optional="false,true"` params

### ISSUE THREAD

**Issue by Lokathor** [KhronosGroup/Vulkan-Docs#2061]
Some params are listed as `optional="false,true"` in their attributes. For example, 

```xml
<command successcodes="VK_SUCCESS,VK_INCOMPLETE" errorcodes="VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY,VK_ERROR_INITIALIZATION_FAILED">
    <proto><type>VkResult</type> <name>vkEnumeratePhysicalDevices</name></proto>
    <param><type>VkInstance</type> <name>instance</name></param>
    <param optional="false,true"><type>uint32_t</type>* <name>pPhysicalDeviceCount</name></param>
    <param optional="true" len="pPhysicalDeviceCount"><type>VkPhysicalDevice</type>* <name>pPhysicalDevices</name></param>
</command>
```

At first I thought that (because the function can be called in two ways), and the argument is optional in one call mode but not optional in the other call mode.
However, in the [full docs](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkEnumeratePhysicalDevices.html) for `vkEnumeratePhysicalDevices` it says:

> VUID-vkEnumeratePhysicalDevices-pPhysicalDeviceCount-parameter
> pPhysicalDeviceCount must be a valid pointer to a uint32_t value

This seems clear that `pPhysicalDeviceCount` can't ever be null, so I'm not sure why it's listed as optional at all, or what "false,true" is supposed to mean.

**Comment by spencer-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/blob/main/registry.adoc#attributes-of-tagmember-tags

in `attr:optional ` section explains this more

`vkEnumeratePhysicalDevices::pPhysicalDeviceCount` is `false,true`

the `false` is because this means that the pointer to `pPhysicalDeviceCount`needs to be a valid array of type `uint32_t` (it is not optional, as ` VUID-vkEnumeratePhysicalDevices-pPhysicalDeviceCount-parameter` states)

the `true` means that the `uint32_t` can be "null" (in this case `0`)

**Comment by Lokathor** [comment]
ah ha, "must be a valid pointer, but it can point at 0". Alright.
