### ISSUE TITLE
[registry] operator precedence in extension dependencies was left undefined

### ISSUE THREAD

**Issue by 1ace** [KhronosGroup/Vulkan-Docs#2062]
The new dependencies syntax is documented here:
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_attributes_of_extension_tags

There are 3 operators: `,` OR, `+` AND, and `()` grouping, however, the precedence of the two AND & OR operators is not defined.

Intuitively, I would expect `ext1+ext2,ext3` to be grouped as `(ext1+ext2),ext3`, but the only example in `vk.xml` that uses both AND & OR right now also uses the grouping parentheses in a way that implies that the *opposite* precedence would apply without them:
```xml
<extension name="VK_KHR_buffer_device_address" depends="(VK_KHR_get_physical_device_properties2+VK_KHR_device_group),VK_VERSION_1_1">
```

That seems counter-intuitive, so I think it's worth being explicit in the spec, whichever way was intended.

/cc @gfxstrand

**Comment by oddhack** [comment]
TBH I don't know how this works out with pyparsing as we use it - hopefully the couple of different ways we parse the expressions all share left-to-right precedence / associativity but it doesn't make any difference in the XML today, and probably won't in the future because the parentheses are also useful human-interpretable markup indicating that the things in the () are an alternative for the other thing(s) that follow. I'll take a closer look and try to sort what the parsers actually do and document that.

**Comment by oddhack** [comment]
@1ace will #2066 address this issue?
