### ISSUE TITLE
vulkan_sci.h is missing from vulkan-headers

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-Docs#2072]
In one of the recent changes, `"vulkan_sci.h"` has been added in `vulkan.h`. However, this file cannot be found in the directory `vulkan-headers/src/include/vulkan/`.

CC: @oddhack

**Comment by oddhack** [comment]
That platform is currently specific to VulkanSC, so vulkan_sci.h is only generated in the 'sc_main' branch. We're merging the Vulkan and Vulkan SC headers as much as possible which is why the ifdef-protected block appears here, but unless the extensions are eventually supported for Vulkan, the platform can't be enabled.

**Comment by oddhack** [comment]
@dgkoch in case you want to add anything since this is an NV platform.

**Comment by dgkoch** [comment]
No plans to enable that platform for Vulkan. That header might show up once we merge in the rest of the Vulkan SC spec, but as @oddhack said - there is no benefit to enabling it for Vulkat.
