### ISSUE TITLE
`VUID-{refpage}-codeSize-08735`

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Docs#2104]
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkShaderModuleCreateInfo.html

Looks the webpage isn't properly displaying VUIDs?

![image](https://user-images.githubusercontent.com/114601453/231885017-1a67889d-c180-4d6b-94e3-a408d939706d.png)

Noticed this during VVL [code review](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5642#discussion_r1165909804).

**Comment by spencer-lunarg** [comment]
Note that the VUID are correct in the new `validusage.json` , so not sure how the json and the spec became different

**Comment by oddhack** [comment]
There are some missing :refpage: attribute definitions on a few API refpage blocks including these - I filed an internal MR to fix. I'll also track a markup diagnostic test as this is easily detectable and fairly common error. It comes out differently in the spec HTML and refpages, because the spec can inherit the :refpage: attribute from a previous block, so some of the current VUIDs will have the API name portion of the ID changed (to be correct).
