### ISSUE TITLE
VK_KHR_dynamic_rendering: missing validation when pipeline writes to attachment with VK_FORMAT_UNDEFINED format

### ISSUE THREAD

**Issue by zakarumych** [KhronosGroup/Vulkan-Docs#2125]
`VkPipelineRenderingCreateInfo` is not included in `VkGraphicsPipelineCreateInfo` that  does not include a `VkRenderPass`.
This causes all attachment formats to be `VK_FORMAT_UNDEFINED`.

> If depthAttachmentFormat, stencilAttachmentFormat, or any element of pColorAttachmentFormats is VK_FORMAT_UNDEFINED, it indicates that the corresponding attachment is unused within the render pass.

Pipeline **uses** the attachment and it almost works.
The missing format info caused blending to not work on my hardware.

I couldn't find VUID. It doesn't look like valid usage though.

**Comment by spencer-lunarg** [comment]
I moved this here if this missing a VUID, one will need to be added to the spec first

**Comment by pdaniell-nv** [comment]
There has been an internal comment about this issue here: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5520#note_412446

I think the solution is to modify the quoted spec above re "it indicates that the corresponding attachment is unused within the render pass" to make it clear that writes from the fragment shader are discarded when the pipeline rendering info for the attachment is VK_FORMAT_UNDEFINED.

**Comment by zakarumych** [comment]
Except that in practice they are not discarded, but produce some unexpected results.

**Comment by pdaniell-nv** [comment]
Clarifications are being developed internally here: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5936

**Comment by oddhack** [comment]
@pdaniell-nv should we close this once !5936 is merged and published? I don't think there's any back-linkage from the internal MR ATM.

**Comment by pdaniell-nv** [comment]
> @pdaniell-nv should we close this once !5936 is merged and published? I don't think there's any back-linkage from the internal MR ATM.

Yes we should. Thanks.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.254 spec update.
