### ISSUE TITLE
Confusing `ppEnabledExtensionNames` Valid Usage

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#214]
This is part of a `VkInstanceCreateInfo` and `VkDeviceCreateInfo` Valid Usage:

> If an extension listed in `ppEnabledExtensionNames` is provided as part of a layer, then both the layer and extension **must** be enabled to enable that extension

It is unclear what requirement the specification raises. It sounds slightly like the extension will be disabled even if it's listed in `ppEnabledExtensionNames`, if the layer is not enabled.

The point is the trailing "to enable that extension" breaks the premise/assumption of the sentence "If an extension listed in `ppEnabledExtensionNames`". (If we assume the useful definiton, that "enabled" is equal to "being listed in `enabledX` array")

Also it does not cover the case, when extension can be otherwisely provided. E.g. the `EXT_debug_report` is provided by both implementation and by layers.

I think the correct(to my understanding) and less convoluted wording would be:

> Each extension in `ppEnabledExtensionNames` array **must** be one of those provided by the implementation or by an enabled layer (as queried using `vkEnumerateXExtensionProperties`).

The `vkEnumerateXExtensions` mention would also nicely supplant the second Valid Usage sentence (which I think is redundant; it only seems to tell us to write the extension name correctly):

> Any given element of ppEnabledExtensionNames must be the name of an extension present on the system, exactly matching a string returned in the VkExtensionProperties structure by vkEnumerateDeviceExtensionProperties

**Thread summary**(it got little hairy):
- PR for this issue is #223 
- just polishing wording and pointing omissions in suggested replacement statements most of the time
- should names even be full Unicode? Resolution: probably not; out of scope of this issue
- should extension-extension dependencies be reflected in Valid Usage section? Resolution: they are at least in the extension spec, and led to:
- should any deterministic things even be in Valid Usage section?

**Comment by courtney-g** [comment]
> It is unclear what requirement the specification raises. It sounds slightly like the extension will be disabled even if it's listed in ppEnabledExtensionNames, if the layer is not enabled.

This is true. If the layer that implements an extension isn't enabled (part of ppEnabledLayerNames) then that extension will not be enabled - actually, you'll get a VK_ERROR_EXTENSION_NOT_PRESENT.

> Each extension in ppEnabledExtensionNames array must be one of those provided by the implementation or by an enabled layer (as queried using vkEnumerateXExtensionProperties).

That is easier to read, though I think I think we still want to spell out the dependency on VkExtensionProperties. What do you think about:

Each extension in ppEnabledExtensionNames array must be one of those provided by the implementation or by an enabled layer and must exactly match a string returned in the VkExtensionProperties structure by vkEnumerateXExtensionProperties.

**Comment by krOoze** [comment]
piggyback issue/question: There also seem to be dependencies between extensions. Is it/should it be valid to not enable an dependency extension?

> What do you think about:

> Each extension in ppEnabledExtensionNames array must be one of those provided by the implementation or by an enabled layer and must exactly match a string returned in the VkExtensionProperties structure by vkEnumerateXExtensionProperties.

Well, it does fix the issue. There should be "the" before the "array" to be grammatically correct, I think.

I am fine with the `vkEnumerateXExtensionProperties` ( I included it myself ) and `VkExtensionProperties`. It's about the "must exactly match a string" I expressed my thoughts earlier.

Still sounds to me like: "oh, by the way, about the globaly unique identifier, don't forget to write it down correctly". I mean, the extension already have an exact given name.

But it's merely a discussion of esthetics now.

Maybe that careful wording is because of it being UTF-8 string? Perhaps it should be demoted to (UTF-8 compatible) 7-bit ASCII alpha-numeric and some punctuation characters only instead. No one wants an extension names in Gothic or Braille characters or something like that, I hope.

**Comment by courtney-g** [comment]
> Still sounds to me like ...
The wording is chosen to match other parts of the spec. In general, the specification is very specific about where things go / come from.

> Maybe that careful wording is because of it being UTF-8 string? 
Mostly the UTF-8 requirement is to make sure people use strings that have 8bit characters vs. 16bit UTF-16. Since it's used elsewhere, I wouldn't change it here, though you are correct, we don't expect folks to use Gothic or Braille. But that does reinforce the "must match exactly" statement as someone using non-ASCII UTF-8 characters could look like ASCII when displayed, but not be the same when compared byte-for-byte.

**Comment by courtney-g** [comment]
I've posted a branch with changes discussed in this issue. Please take a look and let me know if it says what we intended.

https://github.com/KhronosGroup/Vulkan-Docs/compare/1.0-VK_EXT_debug_report...issue-214-debug_report

**Comment by courtney-g** [comment]
> piggyback issue/question: There also seem to be dependencies between extensions. Is it/should it be valid to not enable an dependency extension?

If an extension or layer depends on another extension or layer then it's up to the implementation to check that it's dependencies have been met and respond accordingly.
For example, say there is an extension VK_ME_part1 and VK_ME_part2 and part2 requires that part1 be enabled to work correctly. Where ever VK_ME_part2 is implemented, in the vkCreateInstance or vkCreateDevice functions, the implementation should check that VK_ME_part1 is also enabled and if not return an error. Probably VK_ERROR_EXTENSION_NOT_PRESENT.

**Comment by krOoze** [comment]
Works for me, but:
1. Why do you base it of Debug branch and not 1.0
2. Why did you remove pname: , also VkExtensionProperties and vkEnumerateDeviceExtensionProperties seems to miss Xname: or Xlink:
3. You do not remove one of the two \<usage\>es that seems to be now part of the new usage

**Comment by krOoze** [comment]
ad piggyback question, I will take your word for it, but:
1. Is any of that in the spec though?
2. And if that's Application responsibilty to enable shouldn't it be too in Valid Usage section
3. If the dependency is of some external character(that is anything, that does require more that the user enabling the Layer/Extension on `Create{Instance|Device}()` ), should the dependent extension be even listed in `Vk{Extension|Layer}Properties`
4. Shouldn't the dependency extension be enabled automaticaly (it is basicaly a part of the dependent extension anyway)

**Comment by courtney-g** [comment]
> Why do you base it of Debug branch and not 1.0

Oops. I'm used to doing things on that branch. Easily fixed.

Updated the branch to address your other comments: https://github.com/KhronosGroup/Vulkan-Docs/pull/223

**Comment by courtney-g** [comment]
> and piggyback question, I will take your word for it, but:
> 1. Is any of that in the spec though?

No, I don't think we state that extensions / layers must validate dependencies during CreateInstance/CreateDevice. I do remember discussing that topic during working group meetings. If we documented it, it would probably be as part of the [LoaderAndLayerInterface.md](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md) document. Layers are intended to be quite flexible so we've tried not to over constrain what they can and cannot do. One thing that is clear, there must not be hidden dependencies or consequences to enabling a layer or extension. That breaks the explicit model of Vulkan. If, to operate properly, an extension needs another extension to be enabled, then the app needs to know that and explicitly enable the needed extension.

> 2. And if that's Application responsibilty to enable shouldn't it be too in Valid Usage section

Hmm. I'm beginning to wonder if these statements really belong in the Valid Usage section. An application can put whatever strings it wants in ppEnabled*Names and the behavior is not undefined, it's well defined, if the extension/layer doesn't exist the call will return an error code and the object will not be created. Maybe these belong in the descriptive text rather than the Valid Usage section. I'll discuss with the working group.

> 3. If the dependency is of some external character(that is anything, that does require more that the user enabling the Layer/Extension on Create{Instance|Device}() ), should the dependent extension be even listed by vkEnumerate*()

In Vulkan, I don't think it would be appropriate to hide things. If the Layer/Extension is on the system an application should see it via the appropriate vkEnumerate... It may be that the extension can't be used, in which case the CreateInstance/CreateDevice should return an error and I would want to see that the layer supports VK_EXT_debug_report so that the details can be provided to the application. Another important thing to remember is that on desktop, layers describe themselves via json files. There won't be an opportunity to validate running conditions until the layer is actually loaded and CreateInstance/CreateDevice is called.

> 4. Shouldn't the dependency extension be enabled automaticaly (it is basicaly a part of the dependent extension anyway) Something like the standard_validation meta-layer.

No, this defies the explicit nature of Vulkan. We've talked about such things in the working group in the past and it's clear folks do not want the implementation pulling in other layers and/or enabling extensions the application hasn't specified. The standard_validation meta-layer is a convenience function for desktop. I can't do the same on Android as layers are an app resource, not a system resource and the Android loader has no way of knowing what layers the app has and thus no way to expand "standard_validation".

**Comment by krOoze** [comment]
> If, to operate properly, an extension needs another extension to be enabled, then the app needs to know that and explicitly enable the needed extension.

Well, the app does not know that, the developer, who learns it from the extension description, does.

> An application can put whatever strings it wants in ppEnabled*Names and the behavior is not undefined, it's well defined, if the extension/layer doesn't exist the call will return an error code and the object will not be created.

I noticed a pattern, that when an Error (negative) result code is returned, it may: be due to an inValid Usage. Also applies to a NULL returned from `Get*ProcAddr()`.

>  There won't be an opportunity to validate running conditions until the layer is actually loaded and CreateInstance/CreateDevice is called.

Hmm, that's a good point. But the Enumerate() function could call something in each layer it finds, no? Though, that's replacing one evil with another...

> It may be that the extension can't be used, in which case the CreateInstance/CreateDevice should return an error

I think so far people depended on the extension/layer received through `Enumerate()` to be simply enableable (assuming Valid Usage is observed). Could use a note, those may fail from reasons outside of app/developer influence...

**Comment by courtney-g** [comment]
> Well, the app does not know that, the developer, who learns it from the extension description, does

Still the apps responsibility in the end. :-)

> I noticed a pattern, that when an Error (negative) result code is returned, ...

In many parts of the spec when a result is "undefined" it really means you cannot predict what will happen. It could have no impact, it could cause the driver to segfault, etc. There are some calls like CreateInstance or GetInstanceProcAddr that have well defined error conditions. Does that mean the call was invalid? Not necessarily. Something in the system could have changed from the time the app checked for extensions / layers and the time it makes the Create call. What we know is at the time we were processing the Create, something was amiss and that should be covered by the available error codes.

> Hmm, that's a good point. But the Enumerate() function

The json configuration files were created because there are some platforms that cannot abide loading & unloading layers to query their Enumerate() functions. That was our original plan...
It so happens that we do call the Enumerate functions on Android, but for consistency we only return the same info that the json contains.

> I think so far people depended on the extension/layer received through Enumerate() to be simply enableable

I believe this will be the most common situation. When there is something that isn't that simple, we'll (the Vulkan community) need to make sure the layer can notify the application of what it needs via VK_EXT_debug_report to minimize confusion.

> BTW there is already hidden/implicit behavior called Implicit Layers

Yeah, but they are explicit for the platform :-)
Note, Android does not implement implicit layers. Violates Android's security policy.
Also note, applications still have a way to disable implicit layers if they need to.

**Comment by krOoze** [comment]
> Also note, applications still have a way to disable implicit layers if they need to.

If they know the magic disable/enable keyword. And if they can write env (or registry). And if Implicit Layer doesn't get (maliciously) installed between that point and `createInstance()` call.

**Comment by oddhack** [comment]
@krOoze it is probably reasonable to document any required extension dependencies in the XML, say by \<required\>\<extension name="VK_required_extension"\> tags, and the extension branch spec. That makes the information readily available.

**Comment by courtney-g** [comment]
FYI - wording tweaks suggested during Khronos review:
Each extension name in the pname:ppEnabledExtensionNames array must: be identical to the value of sname:VkExtensionProperties::pname:extensionName for one of the extensions enumerated by flink:vkEnumerateDeviceExtensionProperties. If the extension is provided only by an explicit layer, that layer must have been enabled when the parent instance was created.

Enabling the layer is critical, wanted to make it more obvious by giving that requirement it's own sentence.

**Comment by krOoze** [comment]
I like how it just links to `vkEnumerateDeviceExtensionProperties` and does not try to solve it localy. Though it gets hard because of its `instance` paramater and all the different ways extension may get provided.

1) seems like two \<usage\>es
2) missing the pesky must `:`
3) Should "name" compare to the "value" of a pointer member?
4) (`vkEnumerateDeviceExtensionProperties()` for which device?)
5) `vkEnumerateDeviceExtensionProperties()` with `layer` equal to what?
6) Is it enforcing the app to enable the layer in the past(if I take the sentence literally)?
7) What if it is provided by (only) **two** explicit layers, must they both "have been" enabled?
8) (Whose "parent instance"?)

#### Counter-proposal

Instance:

> Each extension name in the `ppEnabledExtensionNames` array **must** be identical to the name `VkExtensionProperties::extensionName` of an extension enumerated by `vkEnumerateInstanceExtensionProperties` called with `pLayerName` parameter equal to `NULL`, or to a layer name listed in `ppEnabledLayerNames` array

Device:

> Each extension name in the `ppEnabledExtensionNames` array **must** be identical to the name `VkExtensionProperties::extensionName` of an extension enumerated by `vkEnumerateDeviceExtensionProperties` called with `pLayerName` parameter equal to `NULL`, or to a name of a layer enabled for VkInstance parent of `physicalDevice`

#### Counter-proposal 2 I was working on, that uses (hopefully well-defined) terms instead 

**For instance:**
> Each extension name in the `ppEnabledExtensionNames` array **must** be of an instance extension provided by the implementation or by a layer enabled by this command (implicitly, or explicitly by being listed in the `ppEnabledLayerNames` array)

**For device:**

> Each extension name in the `ppEnabledExtensionNames` array **must** be of a device extension provided by the implementation or by a layer enabled (implicitly, or explicitly) for `VkInstance` parent of `physicalDevice`

**Comment by oddhack** [comment]
> BTW any news on what should be in a Valid Usage section and what outside?

It's the set of conditions that can/should be checked for by a validation layer because the command can't work if they are true - comparable to conditions that raise an error in OpenGL. Some of them are automatically generated from semantic tagging in vk.xml, and a lot of them are just handwritten asciidoc that's imbedded with the struct or command definition in the XML. The "Valid Usage" section of the Fundamentals chapter touches on this at the very end.

**Comment by krOoze** [comment]
Was asking for any resolution of internal discussion (as courtney-g mentioned):

> Hmm. I'm beginning to wonder if these statements really belong in the Valid Usage section. An application can put whatever strings it wants in ppEnabled*Names and the behavior is not undefined, it's well defined, if the extension/layer doesn't exist the call will return an error code and the object will not be created. Maybe these belong in the descriptive text rather than the Valid Usage section. I'll discuss with the working group.

@oddhack So should e.g. these be in or out (or both):
- supplying non-enableable extension to `ppEnabledExtensionsNames` (which should deterministically return some `VK_ERROR_*`)
- supplying non-obtainable function to `vkGet*ProcAddr()` (which should deterministically return NULL)
- asking more device memory that is even in the heap (which should deterministically return VK_ERROR_OUT_OF)

**Comment by oddhack** [comment]
I'm unclear on what a developer would do differently depending on what paragraph the three scenarios you describe occur is described on. Personally I think of them as valid but pointless usage.

There isn't any sort of absolute ruling on this from the WG at this time. Courtney will propose some edits coming out of this issue and others, and likely they will be signed off on without much discussion.

**Comment by krOoze** [comment]
I was asking more of as to know what is a spec bug and what shuld be in a PR if it comes to it (as in my #225 ).

The problem is more of a sending a mixed message. The VU saying something like:

> pName **must** be one of *"

But then descriptive text comes and revisits that and says something like:

> Oh, by the way, if pName is not * you get NULL

Same for the ppEnabledExtensionsNames related to this issue.
So as a developer do I really **must** or do I get the NULL otherwise?

To answer your question directly:
It is dangerous to assume what developer would and wouldn't do and the spec should be water-tight.

But if you lack the imagination consider this case: Developer has the extensions to be enabled in some textfile or even supplied by the user. If it is in VU section he would have to check the list against that of `vkEnumerate*ExtensionProperties` as not to disobey the **must** there. Otherwise he would just pass it to createInstance and expect either VK_SUCCESS or VK_ERROR_*.

**Comment by courtney-g** [comment]
We discussed this issue in the working group today. As for validity statement, these indicate the conditions necessary to get a valid result / well defined behavior.

Based on that, we do not need to say that the "extension name must: be a valid extension" as part of the valid usage section. If a specified extension is not available, the application will get the appropriate VK_ERROR_ return code. I'll update the PR.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.17 spec update.
