### ISSUE TITLE
`VkSwapchainPresentModeInfoEXT` does not allow not specifying a present mode

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#2151]
When specifying a new present mode for one or more swapchains using `VkSwapchainPresentModeInfoEXT`, it is not possible to skip an element for which you don't want to change the present mode, nor is it possible to mix swapchains created with or without `VkSwapchainPresentModesCreateInfoEXT`. Either new present modes must be provided for all the elements of `pSwapchains` (and they must all have been created with `VkSwapchainPresentModesCreateInfoEXT`), or for none of them.

Compare this to `VkPresentIdKHR`, which gives the ability to provide a zero value if no present ID is to be used for a particular swapchain.

**Comment by cubanismo** [comment]
I believe this is as-intended. It's possible to achieve a no-op by re-specifying the original present mode the swapchain was created with, and by specifying a VkSwapchainPresentModesCreateInfoEXT that contains only a single mode, whereas simply specifying a present ID may cause alternate behavior in the driver, since it implies some tracking of the presentation request, so an opt-out special value has... value.

**Comment by ShabbyX** [comment]
I see your point, but I don't believe we could add such an option now that the extension has been out. It'd be a backwards incompatible change for existing implementations.

We should probably add a VU that you can't mix swapchains created with and without `VkSwapchainPresentModesCreateInfoEXT`, or perhaps that you must specify the original present mode if the swapchain was not created with `VkSwapchainPresentModesCreateInfoEXT`. We'll have to check to make sure implementations are ok with the latter.

**Comment by versalinyaa** [comment]
Assigning to @ShabbyX to write VU.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.261 spec update.
