### ISSUE TITLE
Can you compare values written with vkCmdWriteTimestamp from multiple different queues?

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#216]
Let's say that I run `vkCmdWriteTimestamp` on a queue of a queue family A, and then `vkCmdWriteTimestamp` on a queue of a queue family B.

Does it make sense to subtract the two values and determine how much time elapsed between the two, or can the EPOCH be different for each queue family?

On one hand the specs vaguely mentions that you can compare values:

> The application can then compute differences between timestamps to determine execution time.

On the other hand the value of `timestampValidBits` is a property of the queue family, which leads me to think that the timestamp could depend on the queue family.

**Comment by krOoze** [comment]
From what I know of electronics and what is in the spec, I am inclined to believe the answer is **yes**.

The timer is shared in PhysicalDevice with precision VkPhysicalDeviceLimits::timestampPeriod. It is exposed to the queue family through register of size VkQueueFamilyProperties::timestampValidBits.

You only have to make sure the differing bits won't case some artifacts for you. Though my guess would be, the bit size would differ between queue families only in very rare circumstances.

Sure the spec could always use some more clear language....

**Comment by oddhack** [comment]
This is probably worth a clarification or Note - we'll take a look at it.

**Comment by oddhack** [comment]
We are exploring this, which turns out to be interestingly subtle across different hardware devices, and will probably end up saying something like: the timestamps are not meaningful across devices, are not meaningful across queue families, and may not be meaningful within a queue family if there's an external event such as the GPU putting itself to sleep and suspending/resetting its timer counter. What may take a while to resolve this is specifying what the timestamps *can* be used for, because it's fairly limited and we need to explore what everyone's hardware can support and make a conservative positive statement based on that.

**Comment by oddhack** [comment]
This should be addressed in the 1.0.60 spec update
