### ISSUE TITLE
How are hung submissions supposed to be detected?

### ISSUE THREAD

**Issue by msharov** [KhronosGroup/Vulkan-Docs#2173]
I am trying to implement automatic semaphore-based dependencies for queue submissions, and am running into frequent hangs that perhaps explain why nobody does this. It works roughly like this: while the command buffer is being written to, each command can specify a dependent resource that is read or written. The device object keeps a list of submitted command buffers. Before a new command buffer is submitted, previously submitted command buffers are checked for resources being used by the new one, and if so, then the previous cmdbuf's semaphore is added to the new one's wait list.

For each frame, I end up with the uniforms buffer update cmdbuf, followed by the draw cmdbuf. Now, if the window resize occurs right after the draw cmdbuf, then the cmdbufs in the queue become fubared somehow. Trying to submit another cmdbuf dependent on either the unforms buffer update (such as the next frame's uniform buffer update), or the draw cmdbuf, results in validation error:

```
validation layer: Validation Error: [ VUID-vkQueueSubmit-pWaitSemaphores-03238 ] 
Object 0: handle = 0xcc0194000000015f, type = VK_OBJECT_TYPE_SEMAPHORE;
Object 1: handle = 0x562e37e3e230, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xb50452b0 |
vkQueueSubmit(): pSubmits[0].pWaitSemaphores[0] Queue VkQueue 0x562e37e3e230[] is 
waiting on semaphore (VkSemaphore 0xcc0194000000015f[]) that has no way to be signaled.
The Vulkan spec states: All elements of the pWaitSemaphores member of all elements 
of pSubmits created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_BINARY must 
reference a semaphore signal operation that has been submitted for execution and any 
semaphore signal operations on which it depends (if any) must have also been 
submitted for execution (https://www.khronos.org/registry/vulkan/specs/1.3-
extensions/html/vkspec.html#VUID-vkQueueSubmit-pWaitSemaphores-03238)
```
Here, for example is the one from the uniform buffer update dependent on the previous draw call, cmdbuf with signal semaphore 0xcc0194000000015f. Both the ub update and the draw call will not complete normally. vkWaitForFences will never return their fences as completed and their semaphores become unsignallable. There are no validation errors before this one. The draw command can be dependent on the vkAcquireNextImage semaphore, or not, the result is the same.

The app window becomes frozen for a few seconds, after which I can switch back to the terminal and kill -9 it. ^C and SIGTERM have no effect. The app is frozen waiting in device wait idle.

vkQueueSubmit does not give me any errors here, and I don't see any way to detect that a hung submission happens. The queue just becomes fubared. I'll emphasize that this is happening *before* I recreate the swapchain, in the device wait idle I call just before doing that - so swapchain resources have not been destroyed yet. The ANI semaphore has not been destroyed yet either. In fact, the window resize even has not yet arrived, only the _NET_WM_STATE property change notification has, because I'm testing it using fullscreen-to-normal window transition.

So, my question is this: where is this situation supposed to be reported as an error? And what, if anything, can I do to recover from it?

In a related question, am I allowed to use semaphores in this manner at all? All the examples I saw only use the ANI semaphore dependency in the frame draw, and use a hard vkWaitForFences to make all other submissions synchronous. Should I just get rid of the semaphores and wait for each submission by fence, manually postponing vkSubmitQueue of each cmdbuf until the dependencies are satisfied?

**Comment by gfxstrand** [comment]
I suspect you have a bug with your window-system code. The validation error there is because Vulkan does not currently allow wait-before-signal behavior with `vkQueuePresent()`. Instead, we require that you have submitted everything which the `vkQueuePresent()` depends on before you call `vkQueuePresent()`. If I had to take a guess, I'd say that your software is throwing away command buffers and not submitting them without removing them from your tracking framework somehow.

If you're going to skip submitting a command buffer, one way to handle this would be to remove them from the tracking framework so nothing depends on it.  Another would be to submit an empty `VkSubmitInfo` with no command buffers but which does wait on and signal the semaphores just like the real one would have.

Again, this is all based on me making guesses about what your software is doing and how it's written. I may be totally wrong. In either case, I don't see anything strictly wrong with the framework you've described. I think you just have a bug where you're waiting on a time point that you never signal. Sadly, this isn't something that the validation layers can catch for you because wait-before-signal is valid in all cases except window systems and binary semaphores.

**Comment by msharov** [comment]
One other thing I forgot to mention I had to do was to eliminate multipath dependencies. When submission B depends on submission A's signal semaphore, and C depends on both B and A, the validation error and the hang occur. C must remove A's semaphore dependency and only use B's. vkQueueSubmit documentation does not mention why this is needed.

Before elimination of semaphores between ANI, render, and present, as outlined above, any dependencies on ANI or render semaphores also had to be removed to prevent the hang. With ANI,render,present decoupled, removing multipath dependencies is sufficient.

**Comment by gfxstrand** [comment]
> Could you please elaborate on what "wait-before-signal" behavior means? Do you mean that the draw cmdbuf must not have finished execution before vkQueuePresent? Or...?

With timeline semaphores, Vulkan allows you to submit waits on a particular timeline value before you submit the work which signals that timeline value, so long as they're on different queues.  It's the client's job to ensure that they don't end up with any circular dependencies.  (This includes both explicit dependencies from semaphores as well as the implicit dependency each submit has on all previous submits to the same queue.)  This was not the case with binary semaphores.  In the Vulkan 1.0 binary semaphore world, you were required to submit the signal operation before you could submit the wait operation.

Because of this added flexibility, the validation layers are likely not being as helpful for you as maybe they would otherwise be.  You are getting a VU message but only very late in the pipeline after you've already submitted a bunch of stuff.

**Comment by msharov** [comment]
I do not use timeline semaphores. All command buffers use a binary semaphore, recreated for each submit, and pWaitSemaphores contains only the semaphores of command buffers submitted previously (and the ANI one, of course, in one case). The list is generated at submit time from the list of existing submissions kept by the device object.

So no, I'm sorry, but this does not seem to be the problem here.

**Comment by charles-lunarg** [comment]
Maybe a dumb question: How are you making sure that there are enough signal semaphores in the previous submission? IIRC each signal semaphore can be waited on *only once*, so if you have 2 submissions that wait for the same signal semaphore, the second submission is invalid.

**Comment by msharov** [comment]
Ok, that's the problem then. I reread the chapter on semaphores and it really does only support one waiter. I was under the mistaken impression that "waited on only once" just meant that it couldn't be reset.

Therefore, semaphores can not be used for submission synchronization in this manner. Looks like I'll have to rewrite the system using fences and CPU-side waits between submissions.

**Comment by charles-lunarg** [comment]
FYI this exact situation is what timeline semaphores solve
