### ISSUE TITLE
Can't access `vkSurfaceKHR_T`

### ISSUE THREAD

**Issue by JRBros2346** [KhronosGroup/Vulkan-Docs#2192]
[VK_KHR_surface] @cubanismo

I'm new to vulkan and I want to create a custom surface. I don't want the prebuilt extensions. But whenever I try to access `vk::SurfaceKHR`, it says it's an incomplete type. On further notice I saw that `vk::SurfaceKHR` has inner type `vkSurfaceKHR` and it has a typedef of `struct vkSurfaceKHR_T*`. But `vkSurfaceKHR_T` is nowhere to be found. I was searching with VS code

**Comment by oddhack** [comment]
Is this something you're seeing with Vulkan-Hpp C++ bindings? If so, I'll move the issue over to that repository. It does not sound like an issue with the C headers.

**Comment by JRBros2346** [comment]
No, I cant find `struct vkSurfaceKHR_T` even in `<vulkan/vulkan.h>`

**Comment by oddhack** [comment]
Can you link/attach a copy of the offending code? I don't know what 'vk::SurfaceKHR' is, but it's not C syntax which leads me to believe you're compiling using C++ bindings, and the bindings are probably where the problem lies, not the C headers.

**Comment by JRBros2346** [comment]
`vkSurfaceKHR` is C binding tho. I tried using it too. `vk::SurfaceKHR` is a class wrapper around it

**Comment by oddhack** [comment]
It is an incomplete type. The definition of VkSurfaceKHR is

> typedef struct VkSurfaceKHR_T *VkSurfaceKHR;

although the typedef is expanded from a macro which is why you can't find it. There's nothing wrong with that because all you can do with these handles is pass them to and from the API. If you try to do something with the contents of the object the VkSurfaceKHR points to, you will get compiler errors.

I'm not sure what you mean by "don't want the prebuilt extensions". The way to get a surface is through an extension which defines a particular type of surface for a particular platform supported in your environment. You cannot just create a surface object from scratch, you need to go through an extension interface like vkCreateXlibSurfaceKHR for X.

You may find that the [Vulkan Discord](https://discord.com/channels/427551838099996672/610191730595069973) is a helpful place to ask general Vulkan programming questions. This project is only for issues or feature requests for the Vulkan Specification itself.

**Comment by JRBros2346** [comment]
Ok, I get it. But my problem here is, how to render to an array . I guess I'll move to discord then. Thank you for guiding me :)

**Comment by JRBros2346** [comment]
Ok, I get it. But my problem here is, how to render to an array . I guess I'll move to discord then. Thank you for guiding me :)
