### ISSUE TITLE
Interpretation of `StdVideoH264LevelIdc`

### ISSUE THREAD

**Issue by spencercw** [KhronosGroup/Vulkan-Docs#2193]
There seems to be some disagreement about how `StdVideoH264LevelIdc` is supposed to be interpreted. The spec refers to section A.3 of the H.264 specification, which in turn defines `level_idc` to be 'equal to a value of ten times the level number' (e.g., `51` means 'level 5.1'). However, the [Vulkan enum](https://github.com/KhronosGroup/Vulkan-Docs/blob/b9aad705f0d9e5e6734ac2ad671d5d1de57b05e0/xml/video.xml#L850) defines it as a list of ordinal numbers.

A small sampling of drivers shows inconsistent choices here. For example, these are the values of `VkVideoDecodeH264CapabilitiesKHR.maxLevelIdc` I observed:

- Intel, Windows: `1` (`STD_VIDEO_H264_LEVEL_IDC_1_1`)
- NVIDIA, Linux: `15` (`STD_VIDEO_H264_LEVEL_IDC_5_2`)
- Mesa (Intel, AMD), Linux: `51`, (`level_idc` 5.1)

What is the expected behaviour here? Same question applies to `StdVideoH265LevelIdc`.

The Mesa merge request that spawned this discussion can be found [here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24649).

**Comment by aqnuep** [comment]
Indeed this is something that's worth calling out explicitly, as, unfortunately, the `StdVideoH264LevelIdc` and `StdVideoH265LevelIdc` enums do not match the binary encoding that is otherwise used in the bitstream per the codec specifications.

FWIW, the expected driver behavior is the one implemented by the NVIDIA Linux driver above. I'm not sure why the Intel Windows driver exposes support only for level 1.1.

**Comment by spencercw** [comment]
Ok thanks for clarifying. I will feed this back to Mesa.

**Comment by oddhack** [comment]
This should be fixed in the 1.3.263 spec update.
