### ISSUE TITLE
Purpose of VK_NV_descriptor_pool_overallocation

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/Vulkan-Docs#2212]
I'm a bit confused about the purpose of this extension? As far as I know the implementation was already allowed to have this behavior:

> If a call to vkAllocateDescriptorSets would cause the total number of descriptor sets allocated from the pool to exceed the value of [VkDescriptorPoolCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkDescriptorPoolCreateInfo)::maxSets used to create pAllocateInfo->descriptorPool, then the allocation **may** fail due to lack of space in the descriptor pool. Similarly, the allocation **may** fail due to lack of space if the call to vkAllocateDescriptorSets would cause the number of any given descriptor type to exceed the sum of all the descriptorCount members of each element of [VkDescriptorPoolCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorPoolCreateInfo.html)::pPoolSizes with a type equal to that type.

In fact, NVIDIA drivers always did this even without enabling it via this extension. Is there any reason why this was added now?

**Comment by pdaniell-nv** [comment]
Our implementation does support overallocation of the requested pPoolSizes, but does not support overallocation of maxSets. If the application attempts to create just one extra descriptor set above maxSets our implementation will return VK_ERROR_OUT_OF_POOL_MEMORY. When adding support for overallocating descriptor sets beyond maxSets it had a negative effect with several applications. It turns out these applications were relying on the implementation returning VK_ERROR_OUT_OF_POOL_MEMORY and not dynamically expanded the pool indefinitely. Expanding the pool indefinitely for these applications caused a measurable performance loss.

So instead of allowing applications to allocate over maxSets by default we had to add this extension to allow apps to opt into this behavior.

**Comment by oddhack** [comment]
@novum if that answers your question, please close the issue. Thanks.

**Comment by Novum** [comment]
It does. Thank you @pdaniell-nv
