### ISSUE TITLE
Clarify Valid Usage for Structure Pointer Chains

### ISSUE THREAD

**Issue by plasmacel** [KhronosGroup/Vulkan-Docs#2239]
Given https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#fundamentals-validusage-sType, the spec states that:

> Each structure included in the pNext chain must be defined at runtime by either:
> - a core version which is supported
> - an extension which is enabled
> - a supported device extension in the case of physical-device-level functionality added by the device extension

then, a few lines below

> Any component of the implementation (the loader, any enabled layers, and drivers) must skip over, without processing (other than reading the sType and pNext members) any extending structures in the chain not defined by core versions or extensions supported by that component.

These statements seem paradoxical. The implications are not clear whether applications can pass extension structures like `VkPhysicalDeviceRayTracingPipelineFeaturesKHR` in the pNext chain without checking the support of the corresponding extension or not, leaving a door for undefined behaviors.

**Comment by krOoze** [comment]
They are not really contrary:

- an Application **must** not pass stuff that is not supported (or some Layer or something could act on this pNext struct despite not being supported, ergo causing defacto undefined behavior)
- an Implementation component **must** not process stuff it does not understand (or obviously it could muck things up, because it does not understands them)

**Comment by oddhack** [comment]
@plasmacel as @krooze says. The intent is to allow layers to pass through structures they themselves don't want or need to deal with. If this is enough of an explanation, please close.
