### ISSUE TITLE
[registry] [vk.xml] VkPhysicalDeviceSchedulingControlsFlagsARM bits type is missing bit_width

### ISSUE THREAD

**Issue by brandonryan** [KhronosGroup/Vulkan-Docs#2277]
I am writing a code generator for a project I'm working on.
Making assertions while parsing, I found this inconsistency.
All other flag definitions match their bit widths except this one.

Flag Definition: 
```xml
<type bitvalues="VkPhysicalDeviceSchedulingControlsFlagBitsARM" category="bitmask">typedef <type>VkFlags64</type> <name>VkPhysicalDeviceSchedulingControlsFlagsARM</name>;</type>
```

Bits Definition:
*notice there is no bit_width attribute*
```xml
    <enums name="VkPhysicalDeviceSchedulingControlsFlagBitsARM" type="bitmask">
        <enum bitpos="0"    name="VK_PHYSICAL_DEVICE_SCHEDULING_CONTROLS_SHADER_CORE_COUNT_ARM"/>
    </enums>
```

**Comment by oddhack** [comment]
@kpet I believe this is your extension? AFAICT the OP is correct, there's a missing 'bitwidth=64' on the enums tag for the FlagBits type, since the Flags type is VkFlags64. This will emit static const uint64 bits, instead of a 32-bit enums.

AFAICT the extension does not use the FlagBits type as a parameter or member, so making this change should not cause ABI breakage, but you'll need to confirm that. Could you propose a PR or internal MR to this effect, once you're satisfied with the impact of the change?

**Comment by kpet** [comment]
@oddhack Yes, I'm the right person. Agree this is missing. Agree this does not change the ABI. I've created #2280 to fix this. 

Maybe we should automatically check the following in spec tooling:

>An enum used in the `bitvalues` attribute of a bitmask type defined as a typedef of `VkFlags64` must have its `bitwidth` attribute set to 64.

**Comment by oddhack** [comment]
> @oddhack Yes, I'm the right person. Agree this is missing. Agree this does not change the ABI. I've created #2280 to fix this.
> 
> Maybe we should automatically check the following in spec tooling:
> 
> > An enum used in the `bitvalues` attribute of a bitmask type defined as a typedef of `VkFlags64` must have its `bitwidth` attribute set to 64.

Yes - filed as internal issue 3716.

**Comment by brandonryan** [comment]
Thanks guys 😄
