### ISSUE TITLE
[vk.xml] `VK_USE_PLATFORM_SCI` Is Missing `NV` Vendor Suffix

### ISSUE THREAD

**Issue by brandonryan** [KhronosGroup/Vulkan-Docs#2297]
The platform protect flag `VK_USE_PLATFORM_SCI` Doesn't have the `_NV` suffix.
```xml
<platform name="sci" protect="VK_USE_PLATFORM_SCI" comment="NVIDIA SCI"/>
```
Without this, its not possible to programmatically determine what vendor is responsible for the extension without special cases.
I need this because my rust binding feature flags are going to be slightly different than those specified in C. Planning for it to be a combination of `vendor` flag + `platform` flag

**Comment by brandonryan** [comment]
It might be more appropriate to add a "author" attribute to the platforms, to provide a more explicit association.
A good example of this being helpful is:
```xml
<platform name="ggp" protect="VK_USE_PLATFORM_GGP" comment="Google Games Platform"/>
```
Technically I think it should be `VK_USE_PLATFORM_GGP_GGP`... I understand this duplication is undesired, now I have to code a special case for vendor and platform being the same. author attribute would clear this up.

**Comment by oddhack** [comment]
Can you go deeper as to what information you're trying to extract here? The extensions should already be tagged with 'platform' attributes if they are tied to a platform. The platform usually is a window system not specific to a single Vulkan implementation vendor, though SCI may be an exception. The purpose of the vendor tags is namespace control in the C API, but platform names are not part of the Vulkan API and we have not done that for them.

**Comment by brandonryan** [comment]
I'm generating bindings for rust. I am using the vendor information to generate namespaces. I'm using the platform information for conditional compilation flags.

When I opened this issue yesterday, I was thinking of using vendor tags as conditional compilation flags, then platform as further flags, but im realizing now that maybe that doesn't make very much sense. This can be closed, but I think its worth exploring for the sake of "metadata completeness"

> The extensions should already be tagged with 'platform' attributes if they are tied to a platform

Sorry, mis-typed. I meant the platforms should be tagged with the vendor

> The platform usually is a window system not specific to a single Vulkan implementation vendor, though SCI may be an exception.

As far as I can tell, they are marked with "KHR" or "EXT" in these situations. Could that not be the vendor tag?
```xml
<platform name="xlib" protect="VK_USE_PLATFORM_XLIB_KHR" comment="X Window System, Xlib client library"/>
<platform name="xlib_xrandr" protect="VK_USE_PLATFORM_XLIB_XRANDR_EXT" comment="X Window System, Xlib client library, XRandR extension"/>
<platform name="xcb" protect="VK_USE_PLATFORM_XCB_KHR" comment="X Window System, Xcb client library"/>
```
I think I'm just hoping for something a bit more strong than naming convention for knowing what author is responsible for a specific platform. Even if that author is KHR.

**Comment by oddhack** [comment]
I don't think it's well defined who is "responsible" for a platform - once it exists, any extension can be associated with it. The "win32" platform has KHR, EXT, and NV extensions associated, and the "provisional" platform can have an ever-changing roster of extensions from any authors. Responsibility lies with the individual extension owners. Functionally, "platform" is a grouping mechanism for putting some extension APIs in distinct, optional header files, either because they require OS/window system-specific external headers or because they are provisional and we want people to have to explicitly opt in to the header as provisional APIs are subject to change.

Also, I'm not certain there's enough information in the XML alone to do the right thing with platforms; there probably is, but the header generation scripts for the C headers currently rely on additional information outside the scope of the XML (see "genvk.py") in order to emit definitions into the right headers. The main problem we had was that C enumerated types cannot be split into multiple pieces, so while it was possible to put the struct and function prototypes for a platform extension into that header file, the enums defined by that extension and which extend existing core enumerated types still have to go in vulkan_platform.h.

Another issue was that because the scripts follow API dependencies, a mechanism had to be introduced to suppress the dependencies so that non-provisional types like 'VkResult' or 'VkDevice' did not end up defined in both vulkan_core.h and each platform header. It is a pretty fragile retrofit as the platform header requirement came along long after the scripts and schema were initially defined.

**Comment by brandonryan** [comment]
Thank you for the detailed explanation.
