### ISSUE TITLE
Chapter 12.6  - "Acceleration structures" should mention KHR functionality before vendor specific variants

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Docs#2385]
The chapter on acceleration structures ([spec with all exts](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#resources-acceleration-structures), [documentation site](https://docs.vulkan.org/spec/latest/chapters/resources.html#resources-acceleration-structures)) mentions the deprecated NV extension first:

https://docs.vulkan.org/spec/latest/chapters/resources.html#resources-acceleration-structures

This can be quite confusing, esp. for people reading this part of the spec first. The KHR related functions are only mentioned after the NV one.

I think it would be beneficial to siwtch this and mention the KHR functions before the NV ones and maybe even add a hint that the NV ones are deprecated and the KHR ones should be used instead.

**Comment by dgkoch** [comment]
Yes, ideally it would mention the KHR functionality first. I've looked at reordering it several times, but so far given up because it's not as easy as it sounds. But I'll keep this on my queue and try to get to it at some point..

It would also be nice if we had a way to hide deprecated/non-preferred functionality in the spec, but we don't have any mechanism for today.  And on that note -- we haven't actually marked the NV extension as deprecated, but we likely should.

**Comment by oddhack** [comment]
It would not be hard to autogenerate comments in the API interface blocks saying that something is deprecated, and if we're willing to infer "API required by a deprecated extension" -> "API is itself deprecated" then there's a way to invoke that path involving only script changes.

Generating a spec without deprecated extensions is also not hard. But then we're back to the issue of maintaining many different builds of the spec for different needs - who decides, and having made the decision, are we stuck with it forever? (my answer: forever is a long time, but *most* of forever).

Trying to make a document which "hides" those interfaces dynamically would be a lot more work and raises lots of UI questions about navigation and searching.

**Comment by dgkoch** [comment]
This has been done as of the 301 spec release.
