### ISSUE TITLE
video.xml struct fields have inconsistent naming convention

### ISSUE THREAD

**Issue by NogginBops** [KhronosGroup/Vulkan-Docs#2393]
Throughout the structs defined in `video.xml` the naming convention for struct members is all over the place.

For example `StdVideoDecodeAV1PictureInfo` has members called `refresh_frame_flags` (snake case), `OrderHint` (pascal case), and `pSegmentation` (type prefix) all in the same struct. 

Why are they named like that?
And would it be possible to fix their naming convention?

**Comment by aqnuep** [comment]
They are named as such because those names match the names used by the corresponding video compression standards (in this case the AV1 spec: https://aomediacodec.github.io/av1-spec/av1-spec.pdf).

This is intentional, and also the reason why the video compression standard related types are defined in a separate `video.xml` and in separate Video Std headers.
