### ISSUE TITLE
Clarify relationship between LAYOUT_GENERAL and feedback loops

### ISSUE THREAD

**Issue by K0bin** [KhronosGroup/Vulkan-Docs#2430]
Concerning VK_EXT_attachment_feedback_loop_layout:

As far as I understand it, the only supported way to have feedback loops is to transition the image to `VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT`.

The spec mentions `VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT` as an exception at various points:

> If the subresource is in the VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT layout, implementations must not access pixels outside of the render area.

https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap8.html#renderpass-store-operations

> When relying on non-overlapping accesses between attachments and other resources, it is important to note that [load](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap8.html#renderpass-load-operations) and [store](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap8.html#renderpass-store-operations) operations have fairly wide alignment requirements - potentially affecting entire subresources and adjacent depth/stencil aspects. This makes it invalid to access a non-attachment subresource that is simultaneously being used as an attachment where either access performs a write operation.

> The only exception to this is if a subresource is in the VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT image layout, in which case the overlap is defined to occur at a per-pixel granularity, and applications can read data from pixels outside the render area without introducing a data race.

https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap8.html#_non_overlapping_access_between_resources

What's interesting is that those quotes do not mention `VK_IMAGE_LAYOUT_GENERAL`.

The documentation for `VK_IMAGE_LAYOUT_GENERAL` however says (emphasis mine):

> VK_IMAGE_LAYOUT_GENERAL supports **all** types of device access.

Is it truly **all** types of device access if it does not support feedback loops?
This should perhaps be clarified to avoid any misunderstanding there.

I'm not filing this as a purely theoretical issue, this misunderstanding has happened:
https://github.com/Ryujinx/Ryujinx/pull/7226#discussion_r1744293147

**Comment by Joshua-Ashton** [comment]
> As far as I understand it, the only supported way to have feedback loops is to transition the image to VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT.

This is my understanding also.

> Is it truly all types of device access if it does not support feedback loops?
> This should perhaps be clarified to avoid any misunderstanding there.

In my opinion, this is just a misunderstanding of the spec. GENERAL does support all types of device access -- but it does not guarantee that said accesses are not hazardous in the same way that ATTACHMENT_FEEDBACK_LOOP_LAYOUT does.

When it says it supports all types of device access, it means, that it supports being a color attachment, storage image, etc. It doesn't say anything about hazards -- notably the device accesses for `VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT` also does not mention anything about hazards/feedback loops either.

**Comment by IsaacMarovitz** [comment]
> In my opinion, this is just a misunderstanding of the spec. GENERAL does support all types of device access -- but it does not guarantee that said accesses are not hazardous in the same way that ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT does.

How would that qualify as support? A feedback useless without that guarantee is completely useless.

**Comment by IsaacMarovitz** [comment]
It's worth noting that the only driver that seems to not respect `LAYOUT_GENERAL` in feedback loops is RADV, every other vendor has seemingly interpreted this usage as valid.

**Comment by Joshua-Ashton** [comment]
> How would that qualify as support? A feedback loop without that guarantee is completely useless.

I have no idea what you are asking.

> It's worth noting that the only driver that seems to not respect LAYOUT_GENERAL in feedback loops is RADV, every other vendor has seemingly interpreted this usage as valid.

On NVIDIA, they don't even use image layouts to my knowledge, and AMDVLK just disables everything for the usage bit. Correlation is not causation, it is imo merely coincidence that it worked out that way.

**Comment by IsaacMarovitz** [comment]
> I have no idea what you are asking.

How can you claim that `LAYOUT_GENERAL` "supports" all types of device accesses, _including feedback loops_ if it offers no guarantee that said feedback loop won't be a garbled mess? Imo that doesn't qualify as support at all.

**Comment by IsaacMarovitz** [comment]
> This is my understanding also. The spec language only calls out ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT, and not GENERAL.

To my knowledge, this clarification was added quite significantly after the extension landed. If the extension is the only valid usage, it's entirely countercultural to the intended use case of `LAYOUT_GENERAL`. It would be a departure from a core part of the Vulkan spec and the only such exception.

**Comment by Joshua-Ashton** [comment]
> How can you claim that LAYOUT_GENERAL "supports" all types of device accesses, including feedback loops if it offers no guarantee that said feedback loop won't be a garbled mess? Imo that doesn't qualify as support at all.

I do not claim that. "Feedback loop" is not a type of device access. Sampling + Color Attachment are examples of that, and certain usages of those can result in a feedback loop.

**Comment by riperiperi** [comment]
I’ll just quickly summarize my position here. It’s more on the side of the line remaining as is, and instead changing the language of the extension.

Discounting the feedback loop extension, the “general” image layout has supported all types of device access, so long as the associated usage flags are enabled on the image. The language describing this is clear and everything else seems to follow it. 

Additional usage flags have been added via extensions, along with “optimal” layouts that _only_ allow that specific usage, potentially allowing it to be in a better layout for the GPU to work with. This isn’t required though, the general layout _also_ allows the usage, so long as it is provided in the flags at creation. Examples include VK_EXT_fragment_density_map, VK_KHR_fragment_shading_rate. 

Generally, the goal seems to have been for the “general” layout to always represent the worst case usage of the image: to disable any optimizations that might prevent a specific type of usage from being possible. In most cases, the main thing causing corruption during feedback loops will be an optimization such as DCC that can easily be disabled on the image. I think this is a worst case that should appear on the general layout if this usage flag is present.

I don’t see this as being any different from any other usage flag that could disable image optimizations. This includes both storage and format-alias usage, which end up disabling a lot of image optimizations on various GPUs (seemingly including DCC on RDNA2!) on the general layout.

Currently in DXVK, the layout is being used as a way to continue applying DCC on an image that has the feedback usage flag set at creation. They’re using general layout as much as possible, but switching to this layout only when the image has a feedback loop. 

This seems to be the opposite of how image transitions usually work, where a transition to a non-general layout such as COLOR_ATTACHMENT_OPTIMAL allows ony one of the _existing_ usage types available with the general layout and could save you from reduced performance with a storage usage flag, the feedback loop layout would actually disable optimizations to _add_ a usage that’s otherwise impossible.

This means that you can’t remain in the general layout all the time, which has big reprecussions on the usage of descriptor sets, caches for render passes, framebuffers and more, _especially_ for emulators and compatibility layers where the default state of play is not knowing what the guest application is going to do next. You need to support being able to change the layout for the feedback usage, sure, but you also have to worry about changing the layout _back_ for any transfer or storage operation, which can happen at unpredictable times (even during descriptor set updates) and very frequently. 

Without a change to the spec in either direction, other developers will write an entire Vulkan backend assuming they can use only the GENERAL image layout, discover a guest application that uses feedback loops, and be forced into refactoring the whole thing to include potentially expensive cascading image layout updates to just end up disabling one optimization flag on a texture. You could argue that enabling this usage flag would then always reduce performance for this backend, but at least it would be consistent with storage and format aliasing in that sense. If they want, they can solve this usage problem _later_ and with one codepath.

**Comment by K0bin** [comment]
Spec 1.3.302 clarifies this.

Shame that Ryujinx was killed in the meantime.
