### ISSUE TITLE
VkSwapchainCreateInfoKHR does not require the oldSwapchain to belong to the given device

### ISSUE THREAD

**Issue by mahkoh** [KhronosGroup/Vulkan-Docs#2454]
[VkSwapchainCreateInfoKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSwapchainCreateInfoKHR.html) requires that

>VUID-VkSwapchainCreateInfoKHR-commonparent
>Both of oldSwapchain, and surface that are valid handles of non-ignored parameters must have been created, allocated, or retrieved from the same [VkInstance](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkInstance.html)

but it does not require that oldSwapchain was created from the device used in vkCreateSwapchainKHR. This seems like an oversight since the given device will, in general, not be able to interact with the oldSwapchain if it did not create it. Mesa assumes that the oldSwapchain has a mesa-internal layout.

**Comment by benjamin-otte** [comment]
Does the spec forbid creating multiple swapchains for the same surface from different devices?

Because that would be enough to make your use case not work. And I'm pretty sure doing that is not gonna work at least on Wayland, because multiple devices will create unique-per-surface protocol objects

**Comment by benjamin-otte** [comment]
I meant that you cannot have an old swapchain from a different device if you are not allowed to create swapchains from different devices at all.

**Comment by mahkoh** [comment]
I'm not aware of any such restriction.

**Comment by cubanismo** [comment]
Vulkan does not allow creating swapchains on multiple devices for the same surface. From section 34.10, WSI Swapchain: "A native window cannot be associated with more than one non-retired swapchain at a time. Further, swapchains cannot be created for native windows that have a non-Vulkan graphics API surface associated with them."

oldSwapchain can't be from a separate device, because swapchains aren't dispatchable handles, and hence their namespace is limited to that of the dispatchable parent object they're created on. Hence, it would never be possible to provide a valid "oldSwapchain" value that was from another device, because that would mean that handle exists in a separate namespace.

**Comment by mahkoh** [comment]
>oldSwapchain can't be from a separate device, because swapchains aren't dispatchable handles, and hence their namespace is limited to that of the dispatchable parent object they're created on

That's what I was missing. Here is the relevant part of the spec:

>All objects created or allocated from a VkDevice (i.e. with a VkDevice as the first parameter) are private to that device, and must not be used on other devices.
