### ISSUE TITLE
XML: Replace `<comment></comment>` and `comment=""` with `<!-- -->`

### ISSUE THREAD

**Issue by kanashimia** [KhronosGroup/Vulkan-Docs#2468]
So basically vk.xml has a lot of ways of doing comments:

```xml
<comment>tag comment</comment>
<anytag comment="attribute comment" />
<!-- actual comment-->
<anytag>// comment that should be visible in the C headers?</anytag>
```

Looking at the first version of vk.xml https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/d204ac2f6991f75fab2ebc22136fd179d692f84f/src/spec/vk.xml it seems it had a lot more of the third kind, and <comment> was reserved just for the preamble, which makes much more sense, although it had second kind comments too.

Those comments require explicit handling in the schema and ignoring in binding generators, which seems unnecessary.
Comments don't have any specific assigned semantic meaning, so they aren't even useful for binding generators, they are only useful for readers of the XML document. 
Some people even wrote this by mistake: `<anytag comment="// this isn't visible in the headers, you made a mistake" />`
What's more, is even though they don't have any semantic meaning users can still rely on them too easily.

So my proposal is to remove first and second kind of comments from the XML document at all, replace them by the second kind, and to remove them from schema. 

You would think that this is harmless, and can't possibly break anything, _but it does_, it breaks at least one vk.xml generator which _parses comments_, and _compares them literally_, this is not a good thing to do.
Here is the code that does that: https://github.com/expipiplus1/vulkan/blob/b59f1b3c1e00e1b49b76c844df5c662b4b8ed2d2/generate-new/khronos-spec/Khronos/AssignModules.hs#L372
They use them to name modules, which you can view here: https://hackage.haskell.org/package/vulkan
That generator is interesting as it is the only parser I know that generates human readable documentation by parsing asciidoc files.

They specifically only parse comments on requires, so it is possible to replace them with dedicated attributes, promoted extensions could have a special tag that describes extension numbers (they already have that on contained enums), and the core API would have a new tag with enum value, described in the schema.
I'm thinking of:
`<require comment="Pass commands">` -> `<require name="pass commands">`
That `name` is similar to the already existing:
`<syncpipeline name="graphics mesh" depends="VK_NV_mesh_shader,VK_EXT_mesh_shader">`
But other possible names for the attribute could be `type` and `usagetype`.
And promoted extensions:
`<require comment="Promoted from VK_KHR_device_group">` -> `<require extnums="61">`
`<require comment="Promoted from VK_KHR_device_group + VK_KHR_bind_memory2">`  -> `<require extnums="61,158">`

I plan to write PR for that `extnums` / `name` idea first, and then for XML comments..
I wrote a regex to fix all comments, but then found that haskell generator breaks.
`sed -E 's|<comment>|<!--|g; s|</comment>|-->|g; s| comment="([^"]*)"(.*>)|\2<!--\1-->|g'`

XML comments cant be nested, so the following:
`<!--enum name="VK_OBJECT_TYPE_SHADER_MODULE" comment="leave this present for compatibility"/-->`
will look like this after replacement
`<!--enum name="VK_OBJECT_TYPE_SHADER_MODULE"/--><!--leave this present for compatibility-->`

Also note that some XML parsers can't actually parse `<!-- -->` comments, like rxml for Rust, but vk.xml already has such comments so it doesn't matter.

This is related to the issue https://github.com/KhronosGroup/Vulkan-Docs/issues/1491, it will address it, partially at least.
As an alternative of course some documentation could be moved from asciidocs into XML, but I'm not sure if that is a good idea.

Opinions?

**Comment by oddhack** [comment]
Unless you wish to maintain your own fork of vk.xml, I advise against putting any effort into doing this. We are very unlikely to accept such a PR.

If an XML processor is looking for a tag or attribute that is specifically defined to be unused and have no semantic meaning, and then assigning semantic meaning to it - that's on whomever made that decision. Mostly the comments are there to help human editors group and find things, or document some historical curiosity about the API. They're in the form of tags or attributes because we wanted to associate those comments with the parent tags or tags they're associated with. E.g. the "Promoted" comments are there only because when editing the XML to actually do the promotions, I found it helpful to remind of which bits came from which extension. 

If someone needs additional metadata for whatever they're doing, we can discuss that separately. We have added many attributes over time to enable various downstream uses of the schema and various generated artifacts for the spec - and most of them are meaningless to any other uses and are ignored by them.

**Comment by oddhack** [comment]
> As an alternative of course some documentation could be moved from asciidocs into XML, but I'm not sure if that is a good idea.

That is very definitely not a good idea. We tried this for valid usage statements early in Vulkan development and it created a lot of pain.

**Comment by oddhack** [comment]
Closing. We will not be doing this as discussed above.
