### ISSUE TITLE
Can the memory layout of an image change when transitionning its layout?

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/Vulkan-Docs#247]
When you creating an image with linear tiling, you can query its memory layout with `vkGetImageSubresourceLayout`. Is the information returned by this function valid for as long as the image exists, or can it change over time (forcing you to call the function at every memory access)?

More specifically, my worry is that the memory layout could change if you transition the image from `VK_IMAGE_LAYOUT_PREINITIALIZED` to `VK_IMAGE_LAYOUT_GENERAL`. The spec doesn't guarantee that it doesn't change.

**Comment by krOoze** [comment]
Personally I work under the assumption any `Get*` command information is not supposed to change during the whole lifetime of an object for which it is called.
E.g. I do not expect function pointers for commands as received from `GetDeviceProcAddr` to change (until the device is destroyed).

Couldn't hurt to have that explicitly in the spec (at least haven't found such requirement yet)

**Comment by TobiasHector** [comment]
It is static. The Vulkan spec should be calling out state that changes in some semi-obvious way. If it doesn't say anything, it's static for the lifetime of the object (assuming valid behavior...).

**Comment by krOoze** [comment]
Well if I think about it, in this case the command name is `vkGet*Layout` and layout is exactly what the user changes, so even our assumptions won't save this.

**Comment by TobiasHector** [comment]
Ok maybe I should've read this more carefully, though should still definitely be static. It's kind of a weird rabbit hole to dive down though...

So firstly, vkGetImageSubresourceLayout is only for LINEAR_TILING images.

The spec only has well defined behavior for accessing images in certain cases:

> Host access to image memory is only well-defined for images created with VK_IMAGE_TILING_LINEAR tiling and for image subresources of those images which are currently in either the VK_IMAGE_LAYOUT_PREINITIALIZED or VK_IMAGE_LAYOUT_GENERAL layout.

Other layouts are just considered opaque by the spec - so an implementation should never reveal any info about them.

A layout isn't actually even a piece of image state - you can always say something is "pre-initialized" at the start of a transition if you don't care about initial contents. The layouts only tell the device how to interpret the data at the point you do a transition, and what caches might be touched. As an app developer it's useful to think about it as a piece of state because it usually needs to remain consistent - but an implementation shouldn't be setting any state (in the traditional sense) for these.

Having re-read the spec here, I do kind of agree it's not the clearest though - IMO mostly since we've chosen a terrible name for the command - but nevermind. Maybe adding a statement like:

"vkGetImageSubresourceLayout returns details of how the texels of an image subresource created with IMAGE_TILING_LINEAR are organized in memory for any host-accessible layout."?

**Comment by krOoze** [comment]
Still could be interpreted as there being more than one set of details. Also could inadvertently imply the image needs to be in the particular layout for the command call.

counter-proposal:

> From **vkGetImageSubresourceLayout** application **can** obtain the memory layout details (of the **pSubresource** subresource of the **image**) with which the application is supposed to address it (when mapped).

That ties it essentialy to the host memory as received by the app. And alows implementers to do whatever they want as long as the app receives what it expects (e.g. could be useful especially for the device-local mappable memory - the device memory layout would still be opaque, only the app access well-defined)

And it would be awesome if the thing you said earlier got specified for all relevant `vkGet*` commands:  :dog:

> If it doesn't say anything, it's static for the lifetime of the object (assuming valid behavior...).

**Comment by TobiasHector** [comment]
There's a change in flight for this inside Khronos which will undoubtedly get argued about - but it should hopefully be clear how this command operates in the next update.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.19 spec update.
