### ISSUE TITLE
Does the VK_PIPELINE_STAGE_HOST_BIT make sense in all uses of srcStageMask?

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#261]
> - VK_PIPELINE_STAGE_HOST_BIT: A pseudo-stage indicating execution on the host of reads/writes of device memory.

However mapped memory already gets an implicit `vkCmdPipelineBarrier` from `Host` to `All_Commands` on `vkSubmit` (without waiting on the semaphores with `waitStageMask` containing `Host`?).

It's primary use is for barriers concerning data that needs to become visible to the host and events signaled by the host.

This means that the Host Stage for `srcStageMask` is only useful for `vkCmdWaitEvents` and as a "dummy" source stage when image transitions needs to happen.  

It also means that Host Stage is not meaningful for `*StageMasks` of the `subpass` dependencies, except for the `dstStageMask` with a `dstSubpass` of `External`.

---

Does it make sense to disallow `VK_PIPELINE_STAGE_HOST_BIT` for `srcStageMask` values everywhere (including `vkCmdSetEvent`) except `vkCmdWaitEvents` and `PipelineBarriers` with image transitions, and disallow it for subpass dependencies entirely except for `dstStageMask` for a dependency to `External`? Or am I missing something?

**Comment by krOoze** [comment]
>  gets an implicit vkCmdPipelineBarrier from Host to All_Commands on vkSubmit

So what about synchronization **when** vkSubmit is already running?

**Comment by ratchetfreak** [comment]
> >    gets an implicit vkCmdPipelineBarrier from Host to All_Commands on vkSubmit

> So what about synchronization when vkSubmit is already running?


That's what `vkCmdWaitEvents` with a srcStageMask of `HOST` is for. 

I'm talking about host->device sync where the host is accessing some memory and then signals to the device it can access the memory. This can either be done through `vkQueueSubmit` which has an implicit barrier or through `vkSetEvent` with an explicit `vkCmdWaitEvents` and a `srcStageMask` with HOST.

**Comment by philiptaylor** [comment]
I can imagine cases where you want to send data from host to device but don't want the device to block, so you don't want to use an event. E.g. in a VR application you could have a thread on the host continually writing the latest headset position into memory, and get the device to render some position-independent parts of the frame (shadow maps etc) then atomically grab the very latest position from memory and use that for rendering the rest of the frame, without ever waiting for the host.

In that case I think you need a vkCmdPipelineBarrier with srcStageMask=HOST, srcAccessMask=HOST_WRITE to make the host writes available before the device reads them, but you shouldn't need any other synchronisation. (You might also need to rely on some reasonable but probably-unspecified atomicity guarantees between host and device, but that should be safe enough.)

In a different case, you might want to coalesce all your memory barriers for performance reasons, and do e.g. vkCmdWaitEvents(srcStageMask=HOST, dstStageMask=TOP, no memory barriers); vkCmdPipelineBarrier(srcStageMask=HOST|VARIOUS_OTHER_STAGES, dstStageMask=TOP, lots of memory barriers including one with srcAccessMask=HOST_WRITE) which should create an execution dependency chain from the event to the HOST_WRITE barrier. That requires HOST in the vkCmdPipelineBarrier.

> Does it make sense to disallow ...

Currently there are loads of nonsensical synchronisation things (e.g. srcAccessMask=FOO_READ) and the spec doesn't try to disallow any of them. I think piecemeal validity requirements would be worse than the current situation, since it would add a lot of complexity to the specification without really solving the validation problem or the nobody-understands-synchronisation problem. The best thing would be comprehensive machine-checkable validity requirements plus working code that actually checks them, but I think the only realistic way to do that is to write the code before writing the validity requirements, else we'll probably end up with more uncheckable requirements.

**Comment by ratchetfreak** [comment]
I disagree with your second paragraph, A barrier with just HOST in src allows the implementation to move it all the way to the front of the command buffer negating any benefit you would have. Not to mention that device coherency of mapped memory is very much undefined.

Your third paragraph assumes that stageMasks and accessMasks are tightly linked which I don't really agree with. TBH it wouldn't make sense for them to be so tightly linked.

I'll wait until the sync spec has been properly rewritten to suggest something more concrete.

**Comment by philiptaylor** [comment]
> A barrier with just HOST in src allows the implementation to move it all the way to the front of the command buffer negating any benefit you would have.

It might or might not move it that far - anything related to performance is inherently implementation-dependent, and Vulkan encourages use of plenty of features that improve performance on some implementations and not on others, so I think this is still a reasonable use case if it works on some.

> Not to mention that device coherency of mapped memory is very much undefined.

I'm hoping it'll be defined in the future - I guess something like OpenCL's SVM should eventually find its way into Vulkan (since it's useful and hardware supports it) and will need the host/device memory model to be specified more precisely.

**Comment by TobiasHector** [comment]
This issue kind of washed by me, but I'll assign myself to look at it with the rest of the rewrite which isn't going as quickly as I'd hoped, but it is progressing.

It doesn't sound like anything here is particularly broken, just that we allow some usage that maybe is completely pointless - similar to allowing read access masks on srcAccessMask. Because of that it's probably not a high priority right now - as it's going to require *very* careful review of the spec to add the suggested validity - to make sure we're not breaking any use cases.

We'll discuss internally whether we even want to do that (I suspect we should at least consider adding warnings to the validation layers?).

**Comment by ratchetfreak** [comment]
The core reason I brought this up is so that when the implementation sees a vkCmdWaitEvents it knows that it will be a host triggered event. (which requires different handling than a queue triggered event).

Disallowing a vkCmdSetEvent with the host bit set will solve that. Because then the only way to have the Host bit in the srcStageMask is when an event is triggered by the host.

**Comment by TobiasHector** [comment]
@ratchetfreak Ah that's actually a good point - hadn't really considered that. That would possibly be a useful implementation hint.

**Comment by TobiasHector** [comment]
So I'm currently thinking that HOST_BIT makes no sense in vkCmdResetEvent or vkCmdSetEvent, in the semaphore wait masks in VkSubmitInfo, or for subpass dependencies internal to the render pass. For vkCmdWaitEvent it definitely *does* make sense to allow HOST_BIT, and is in fact required to synchronize with vkSetEvent calls on the host.

I'm not sure about pipeline barriers and external subpass dependencies. The reason being that HOST_BIT affects memory barriers, not just the execution dependency. So it seems like it should be legitimate to do something like call vkCmdWaitEvents to wait on the host, and then *later* make host writes visible. But you could do that equally well with another vkCmdWaitEvents so... I'm a little torn. I think I'm erring towards making it invalid to avoid some weird and possibly surprising spec language though, but this is going to be thrown on the mercy of the group for discussion.

All of this is TBD, but I'm putting up a proposal for it next week, and something should be in the spec the week after.

**Comment by krOoze** [comment]
Fixed in 1.0.38 update?

**Comment by oddhack** [comment]
Yes.
