### ISSUE TITLE
[Specification] instanceCount in VkCmdDraw* does not specify 0 or 1 as minimum

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/Vulkan-Docs#275]
Some implementations treat 0 and 1 differently, it would be nice if the spec stated what happens and if it's valid when passing 0 as instanceCount (either not valid, treated as 1 or the draw called is ignored).

**Comment by TobiasHector** [comment]
In the absence of a statement saying "it must not be zero" in the validity - the current spec allows it to be 0.

Equally, since the spec says nothing about it being treated specially, 0 should mean 0 - not 1 or anything else.

We could add language to clarify that "it can be one" - which we currently have for drawCount?

**Comment by RCalocaO** [comment]
I guess in general,  what is the expectation ot a call or dispatch with
zero elements? It could be argued that it is valid to call no-op work. I
personally would like validation to warn (consequence of a warning in the
spec I'd suppose)... At minimum,  language should match with drawCount and
spec should mention that on the zero case for both,  it will not render (ie
we've seen implementations render one instance when it is zero).
On Jul 6, 2016 5:07 AM, "TobiasHector" <notifications@github.com> wrote:

In the absence of a statement saying "it must not be zero" in the validity
- the current spec allows it to be 0.

Equally, since the spec says nothing about it being treated specially, 0
should mean 0 - not 1 or anything else.

We could add language to clarify that "it can be one" - which we currently
have for drawCount?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KhronosGroup/Vulkan-Docs/issues/275#issuecomment-230718474>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGj31I6Ck4NMJdT9QUi_6cALcM9CeQ57ks5qS3BagaJpZM4JFhze>
.

**Comment by TobiasHector** [comment]
I think everyone expects an **indirect** draw call with a count of zero to be ok - so that you can effectively turn off a draw call via a buffer write.

In general we expect the direct version to behave in the same way. Some implementations may even use the exact same path for both - perhaps embedding the drawindirect structure directly in the command buffer.

I don't think there should be any change to the behavior of the spec, but clarifying that behavior would be fine.

Something like a warning in the validation layer is probably valuable for this case - maybe raise an issue against the layers (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues)?

**Comment by RCalocaO** [comment]
Sounds good. I'll let LunarG know. Thanks!

**Comment by philiptaylor** [comment]
> we've seen implementations render one instance when it is zero

I was going to suggest raising a CTS issue, but it looks like there's one already: https://github.com/KhronosGroup/Vulkan-CTS/issues/19

**Comment by jeffbolznv** [comment]
What is the point of warning about legal and possibly even useful behavior?

I think the spec is pretty clear about this: "The primitives are drawn pname:instanceCount times", and as Tobias points out there is no validity rule preventing instanceCount == 0.

**Comment by TobiasHector** [comment]
In the direct case I imagine some people might just accidentally put 0 without really thinking about it. This is one of those times where it might be useful, but it also might not. Hence a warning - ideally you'd be able to turn it on or off I suppose?

**Comment by TobiasHector** [comment]
I think we resolved this - so closing. Feel free to reopen or raise a new bug if you've got any other questions.
