### ISSUE TITLE
A wiki, lower entry barrier and API stability

### ISSUE THREAD

**Issue by TheJJ** [KhronosGroup/Vulkan-Docs#28]
Migrated from KhronosGroup/Vulkan-LoaderAndValidationLayers#5:

Vulkan has the potential to become the most popular graphics API, but:

- [x] I hope, in order to minimize the complexity, boilerplate libraries will emerge and provide abstraction layers fitting for different applications. Some of those should probably be officially supported/listed.

  Only then, those small hobby projects will have a chance to use Vulkan and developers get familiar with it. Just targetting AAA engines will lead to having very few developers that use and understand the API which makes it popular.

- [ ] In order to prevent totally outdated guides and scattering the community, a **central wiki** should be in place from the beginning. There, howtos, examples, tutorials and tipps & tricks should be placed and maintained.

- [ ] After programs have been written, they will most likely not be updated for new Vulkan versions. Although that was never the problem with e.g. OpenGL, I can only hope Vulkan won't do things like the Python2->3 breakage, qt3->4->5, gtk2->3, gnome2->3, kde4->5, etc.
Instead, following the Linux kernel way will guarantee ABI stability for a minimalistic interface that provides space for internal improvements and reliably sane behavior.

If the interface remains stable and the community is actively integrated and supported into further evolvement of Vulkan and not only industry giants, the success is probably guaranteed.

Thanks for making all this possible :smile:

(and please, use better/shorter repo names: "Vulkan-LoaderAndValidationLayers" ...)

**Comment by hlandau** [comment]
I certainly think the establishment of a wiki would be desirable. Mediawiki, ideally.

**Comment by NicolBolas** [comment]
> Some of those should probably be officially supported/listed.

The problem with official lists is that they are only useful if they are properly curated. Indeed, such official lists are negaitvely useful when they are _not_ properly curated.

Consider the so-called [OpenGL SDK](https://www.opengl.org/sdk/libs/). It features a number of dead and/or rarely used libraries, while ignoring equivalents that are far more widely usable.

GLee is dead as a doorknob and has been for years; there are a half-dozen better OpenGL Loading Libraries out there. Equalizer [hasn't had a news update in almost 4 years](http://www.equalizergraphics.com/news.html). KTX as a format is rarely used in the desktop world, yet there are no links to image loading libraries that would load formats that people actually use.

And it's not like these deficiencies in the "SDK" [haven't been pointed out](https://www.khronos.org/bugzilla/show_bug.cgi?id=819). Yet nothing is done. As a consequence, nobody uses the "OpenGL SDK". Nobody talks about it; it's just a dead page on OpenGL.org.

A well-curated list can be an asset. But a _poorly_ curated one is a detriment. If the Khronos Group can't take the time to make sure that such a list exists and is genuinely useful, it'd be better for no such "official" list to exist at all.

> Just targetting AAA engines will lead to having very few developers that use and understand the API which makes it popular.

Vulkan is not the kind of API that will succeed or fail based on hobbiest programmers. Vulkan is not an API _for_ hobbiest programmers. That's not to say that they can't use it or benefit from it. But first and foremost, Vulkan is for high-performance graphics professionals. It is they who will decide whether Vulkan succeeds or fails.

That's not to say that you can't provide such resources. But please do not believe that Vulkan would be hamstrung by those resources not existing.

> In order to prevent totally outdated guides and scattering the community, a central wiki should be in place from the beginning. There, howtos, examples, tutorials and tipps & tricks should be placed and maintained.

Again, curation is _vital._ The OpenGL Wiki proves that creating a place where people are able to put content is not by itself sufficient. You need people who _will_ put that content there. In the initial months of the OpenGL Wiki's opening, there were a number of articles, FAQ pages, and tutorials added. Then, enthusiasm dropped off, and so did content. And it was not well organized even when people were actively involved; people just made pages on whatever struck their fancy.

Look at the Wiki before 2009 and after it. Before, it was a bunch of random pages. After, it became a genuine resource. Why? Because I took the time to _make it_ such a resource.

Will I do the same for a Vulkan Wiki? Will someone else take up that charge? Because if nobody is willing to take the time to make sure that it is a genuinely useful resource... it won't be.

The only way for Khronos to make sure that someone takes the time to do so is for them to actually do it themselves. That doesn't mean it stops being a wiki, but the Khronos group would need to be responsible for making sure that content gets there. If they're not willing to do that, then it will just be another disused MediaWiki collecting spam.

> Although that was never the problem with e.g. OpenGL, I can only hope Vulkan won't do things like the Python2->3 breakage, qt3->4->5, gtk2->3, gnome2->3, kde4->5, etc.

You mean, except for the whole deprecating and removal at the 3.0-3.2 era, right?

Also, I rather hope they do have that kind of breakage. Obviously not for no reason. But OpenGL accrued too many ways of doing the same thing, simply because there was no way of getting rid of the old stuff. We took a hit with the core/compatibility profile distinction, but nothing was done after that.

We got the ability to set vertex attribute locations from shaders, but we still had `glBindAttribLocation`. We got a new program introspection API, but the old APIs still existed. We got the ability to create immutable textures and buffers, but the old `glTexImage` APIs are still there. We got direct state access, but bind-to-edit remains. We got separate programs, but we still allowed non-separate programs. And so forth.

And in the end, we have an API that has 5 ways of doing the same thing. To what end? Most professional graphics programmers have proven (thanks to Direct3D) that they will be willing to update to major changes in an API, so API stability means less to them than getting access to the hardware. The primary beneficiaries of API stability are hobbiest programmers and certain professional graphics developers who don't make high-performance applications (ie: CAD).

Also, the Vulkan specification makes it clear that major version changes are going to be allowed to remove and modify APIs as needed. Whether they make use of this or not remains to be seen. But the possibility is definitely there.

**Comment by BillDStrong** [comment]
If all you want is a curated list, github has proven to be a popular model for just such a list. And since it uses the same workflow that devs use, it makes the barrierto entry much lower. 

In this case, create a new markdown document in the main Vulkan directory. Link to it from the Readme file. And tell library devs that they can file an issue with a commit to have it reviexed by the community. Thus the community could review the the tools and weed out the tools before the Khronos recommendation.

This does still require some work for Khronos, but might lead to a more active list. You might make some requirements as well, such as the date added, version of the spec used, and user votes.

**Comment by oddhack** [comment]
I'm going to close this as not actionable for Khronos. We are fully occupied working on fixing Vulkan spec issues and looking at future features. The LunarG folks have a lot going on with their loader project and sample code, and there are a variety of tutorials from them and others, with more coming. If someone wanted to set themselves up to curate a wiki, or GitHub project index, or whatever mechanism that pulls this sort of information together, that would be great, but none of us have the time right now.
