### ISSUE TITLE
Undocumented error code for vkEnumerateInstanceExtensionProperties

### ISSUE THREAD

**Issue by srjek** [KhronosGroup/Vulkan-Docs#285]
(EDIT: So basically all my issues were actually being caused by me doing something stupid and then relying on the stupid to be correct. The error code being undocumented is still probably an issue though, so that part remains despite it's flawed basis. Apologies for any confusion)

`vkEnumerateInstanceExtensionProperties` returns `VK_ERROR_LAYER_NOT_PRESENT` ~~for all installed layers~~ on my system, however this error is not listed under the possible return codes for that function in the specs. A quick glance at `vkEnumerateDeviceExtensionProperties` suggests it may have a similar issue.

~~In addition to not being listed, the situations that would return an error are not documented. From the name of the error, one would expect the layers to not exist, however they do. I suspect that the layers are simply not providing any extensions, but I would've expected `pPropertyCount` to be set to `0` in that case. Maybe it's a loader error trying to access some nonexistent function in the existing layer? At this point I'm just wildly guessing.~~

~~Finally, there is one layer on my system that does set `pPropertyCount` to `0` when `pProperties` is `NULL`, but on a followup call it returns `VK_ERROR_LAYER_NOT_PRESENT`, where I would expect it to be a success to fill an empty array. I'm not sure if it should be valid for a layer to successfully give a count then return a non-present on the followup outside of a poorly timed uninstall?~~

~~At any rate, the current situation is easy to handle with additional checks in code, although it would be nice if it was more defined.~~

**Comment by TobiasHector** [comment]
So I suspect the reason this isn't documented is actually because... well it's actually undefined behaviour. At least mostly deliberately. It just so happens that the loader provides a useful error here - there's no mandate to do so. You're liable to run into this throughout the API whenever you are, as you put it, "doing something stupid and then relying on the stupid to be correct".

It's always possible that sensible errors will be returned by drivers in places that aren't mandated to return an error, if it's practically free to do so for that implementation. You can't rely on this behaviour though. The Vulkan API only guarantees returning errors that can't be detected by code analysis or a layer. In this particular case, a validation layer will  know that you've not enabled the layer you're asking for, so can determine this for you without the burden of asking implementations to provide run-time error checking. This is a general rule throughout the API, and listed in the fundamentals section in section [2.6. Errors](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-errors).

Hope that clears things up???

**Comment by krOoze** [comment]
Seems like a driver bug. For installed layers, you should get success code.

On the other hand those commands probably need VK_ERROR_LAYER_NOT_PRESENT specified, because the App has no way to guarantee the layer still exists.
On the other other hand the VU is it only must be returned from `EnumerateLayers` and so not App's responsibility. But what is the Impl supposed to behave like in the situation the layer is uninstalled in the meantime (none of the existing return codes seem applicable)?

**Comment by TobiasHector** [comment]
> Seems like a driver bug. For installed layers, you should get success code
I took his "doing something stupid" to mean he didn't have the layers installed/enabled?

> On the other hand those commands probably need VK_ERROR_LAYER_NOT_PRESENT specified, because the App has no way to guarantee the layer still exists.
The layer must have been enabled in the instance in order to query an extension with that layer. Only a few core APIs can be queried without a valid instance - none of which are in extensions.

>But what is the Impl supposed to behave like in the situation the layer is uninstalled in the meantime (none of the existing return codes seem applicable)?
Since you have to enable the layer (i.e. actually use it) "what if it's uninstalled in the meantime" is like saying "what if the driver is uninstalled in the meantime" - i.e. not something we worry about.

**Comment by krOoze** [comment]
> I took his "doing something stupid" to mean he didn't have the layers installed/enabled?

Right. I assumed @srjek edits are now correct description of the situation. Clarify please?

> The layer must have been enabled in the instance in order to query an extension with that layer.

Nope. The `vkEnumerateInstanceExtensionProperties` is freestanding. Furthermore, there is no such requirement there, the layer must be enabled.

**Comment by TobiasHector** [comment]
> Nope. The vkEnumerateInstanceExtensionProperties is freestanding. Furthermore, there is no such requirement there, the layer must be enabled.

Ah you're right - I'm getting confused with vkGetInstanceProcAddr - my bad :/

In which case maybe we should have this error - at least vkEnumerateInstanceExtensionProperties should have it. I'm unclear about the device version - might need to check if that was supposed to encompass an enabled instance layer or not... there's been a lot of churn here with the deprecation of device layers.

**Comment by courtney-g** [comment]
I would have sworn that that error was documented for vkEnumerateDeviceExtensionProperties, so just an oversight in the spec.
It is marked as a "must" in the LoaderAndValidationLayers.md.

I'm curious about why the loader can't find the file. What OS are you testing on?
If Windows/Linux, try setting the environment variable VK_LOADER_DEBUG="all"
and see what the loader is telling you about looking for the layers.

**Comment by srjek** [comment]
> > I took his "doing something stupid" to mean he didn't have the layers installed/enabled?

> Right. I assumed @srjek edits are now correct description of the situation. Clarify please?

My stupid thing boiled down to using a free-ed pointer, so the `VK_ERROR_LAYER_NOT_PRESENT` errors were correct as the layerNames were probably garbage. With regards to having a layers enabled and such, I was querying for what was available for me to enable during the createInstance call, so I did not have an instance yet.

I was thinking `VK_ERROR_LAYER_NOT_PRESENT` should be listed under return codes for the `vkEnumerate*ExtensionProperties` calls because both take a pLayerName as an argument and somewhat obviously do a name->layer lookup of some sort.

> I'm unclear about the device version - might need to check if that was supposed to encompass an enabled instance layer or not... there's been a lot of churn here with the deprecation of device layers.

Regardless of any intentions, the loader code for `vkEnumerateDeviceExtensionProperties` does a lookup of pLayerName against the (I assume enabled?) instance layers. I suppose the specs could be more clear on if whether it's pulling from device and/or instance layers, even if device layers are deprecated.

**Comment by srjek** [comment]
@courtney-g The layer name was free-ed, so it was only finding things depending on the odds that the memory got overwritten. (in my case, nearly always)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.

**Comment by krOoze** [comment]
@oddhack There is extraneous space before the `VK_ERROR_LAYER_NOT_PRESENT` causing `ename:` to be printed in the output.

https://github.com/KhronosGroup/Vulkan-Docs/blob/1ca0ea1ef0ed61ee2e2e818f9616a30e9fc70483/src/spec/vk.xml#L3106
