### ISSUE TITLE
Redundant VU statements regarding the child-parent

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#288]
The generated VU statements handling child-parent handle object relations produce redundant statements. E.g.:

> 
- `commandPool` **must** have been created, allocated or retrieved from `device`
- Each of `device` and `commandPool` **must** have been created, allocated or retrieved from the same `VkPhysicalDevice`

If `commandPool` was created from `device`, that already implies it was created from the same `VkPhysicalDevice`.
(And for two elements appropriate word would be "Both")

**Comment by TobiasHector** [comment]
So I wrote the script that generates that stuff and... it's not the most straightforward coding. I considered fixing it before but that script gets quite messy because, well, English is not a programming-friendly language!

I'll take a look and see if I can improve them and get back to you. Possibly it's not as bad as I thought before - when I first wrote them was in the middle of writing all the auto-generated validity, so I may have just gotten sick of it  :)

I probably won't get to this until after SIGGRAPH (next week) now I'm afraid, but I'll get to it after that.

**Comment by krOoze** [comment]
Don't stress too much about it... Unlike other Issues and PRs, this doesn't actually break anything, so this is a good canditate to be Future'd anyway.

**Comment by TobiasHector** [comment]
Wasn't as brutal as I'd thought. I forgot how bad the original scripts were... but rewriting them properly including fixes only took about 45 minutes. I'll try to get it in the next release.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.22 spec update.
