### ISSUE TITLE
Equations in len attribute without latex:

### ISSUE THREAD

**Issue by 3b** [KhronosGroup/Vulkan-Docs#29]
`registry.rnc` says equations in the `len` attribute of `<member>` and `<param>` are prefixed by `latex:`, but of the three equations I saw, two had no prefix (`codeSize/4` in `VkShaderModuleCreateInfo`, `dataSize/4` in `vkCmdUpdateBuffer`) and the other is prefixed with `latexmath:` (in `VkPipelineMultisampleStateCreateInfo`).

It would be nice if they were consistently marked, so code attempting to generate code based on the `len` attribute can more easily tell which need special/manual processing.

From the rest of the XML file, I assume `latexmath:` is the correct prefix.

**Comment by oddhack** [comment]
Good catch, that should be made consistent. I think whomever edited the attribute for the one latexmath: case was templating off the asciidoc macros, but I suspect we don't want or need to have the full syntax flexibility of latex, since you need something at least as smart as MathJax to interpret it.

My inclination is to accept only the notation 'len="math:expression with no markup"' for things more complex than a constant. Would that work for you? I'll ask inside Khronos in the event anyone is already relying on this notation, but I suspect we can change it without affecting anyone, at this point.

**Comment by 3b** [comment]
That works for me, though I probably still won't bother to try to actually interpret the expressions in code until there are a lot more than 3. Main thing I'm looking for at this point is a reliable way to identify them, and `math:` works fine for that.

**Comment by oddhack** [comment]
We talked about this today and have for the time being agreed to use the latexmath:[$latex expression$] markup for now, since the only actual use cases are in generated validity language for the spec. That does pose a greater burden on other uses of the len= field, unfortunately. I hope we can find a better answer downstream but for now this at least makes the various uses consistent.

**Comment by oddhack** [comment]
Fixed in 1.0.4 updates (well, for values of "fixed" - now the asciidoc is happy but the hypothetical wrapper generator has to parse LaTeX markup).
