### ISSUE TITLE
vk_platform.h (unnecessarily?) includes whole windows.h

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#313]
On Windows (and by defining the appropriate macro) the `Windows.h` is included by `vk_platform.h`.

I assume that is only to have the `HINSTANCE` and `HWND` for `VkWin32SurfaceCreateInfoKHR()`.

Would you consider including only `WinDef.h` instead?

That could mean faster compile times, more responsive and less polluted IDE hint system and allow the user to include `Windows.h` on his terms (also allowing him to "configure" the header e.g. by using `WIN32_LEAN_AND_MEAN` macro).

Also:
`vulkan.h` itself too includes `windows.h`. Isn't it redundant to the one included by `vk_platform.h`?

**Comment by MarkY-LunarG** [comment]
I just tried this locally with the LunarG SDK and I encountered a number of issues.  Several of which stem from this error:  (fatal error C1189: #error:  "No Target Architecture")
I'm sure I could figure out what those are, but I don't think developers would be too happy to encounter new errors like that from a header update.

**Comment by krOoze** [comment]
@MarkY-LunarG I derive pleasure from the fact that this would break code of people that do not include necessary headers properly. :trollface:  But of course I won't be the one to handle the political aftermath.

**Comment by krOoze** [comment]
Also:
`vulkan.h` itself includes `windows.h`. Isn't it redundant to the one included by `vk_platform.h`?

**Comment by philiptaylor** [comment]
Sort of relatedly, a while ago I got weird build errors when modifying the loader/layer code since it turned out one of the fields like `VkLayerDispatchTable::CreateSemaphore` was getting renamed to `VkLayerDispatchTable::CreateSemaphoreA` after you included `windows.h` (because of ANSI vs Unicode Win32 APIs), so I had to randomly shuffle headers around until it started working again. Also some files need to `#define NOMINMAX` before including anything that includes `windows.h`, else a subsequent `#include <algorithm>` breaks with weird syntax errors when trying to defined `std::min`.

I'm not sure I have much of an argument here, just a point that the use of `windows.h` already causes unhappiness when writing new code (which has to be balanced against causing unhappiness in code that's already using vulkan.h).

**Comment by MarkY-LunarG** [comment]
OK, thanks for the clarification.  We're starting to discuss possible resolutions for this internally.  I'll update this issue once the group comes to a decision.

**Comment by MarkY-LunarG** [comment]
Would something like the following changes meet your criteria? [split_vulkan_header_experiment.zip](https://github.com/KhronosGroup/Vulkan-Docs/files/655582/split_vulkan_header_experiment.zip)

**Disclaimer:**
> These are *purely* experimental and are not intended for release or distribution.  The intent is just to show what *I and a few others* am thinking of as a possible solution.  The changes  should not be considered in any way, shape, or form, as approved for release or support by Khronos.

We'll consider the final solution internally based on the results of your findings.

**Comment by krOoze** [comment]
@MarkY-LunarG 
So what exactly did you change?
I see each WSI platform dependent extension is in its own header (I am not sure how that addresses this issue specifically).
And I see you have removed `#include<windows.h>` from both `vk_platform.h` and the declarations. So the vukan header would rely on The App to include it. am I right?

**Comment by MarkY-LunarG** [comment]
Correct.  The issue has been that the #includes are causing problems because:
 1. They might not be the optimal includes (like Windows.h instead of the more specific header(s) needed)
 2. They might be included in an order which causes issues (noticeable especially when building a Qt Vulkan app).

We thought it might be best to just have the application include the windowing system headers before in its own order.  For developers who don't care and just want to get started, they can still use the vulkan.h header which does include those headers internally.

**Comment by krOoze** [comment]
Well that approach works for me.

few notes though:

1) This makes the Vulkan guards unnecessary, no? The header could instead detect whether it has all it needs.

2) There are some extensions that need a specific platform and hijack the Vulkan KHR macro guard (e.g. `VK_NV_external_memory_win32` with `VK_USE_PLATFORM_WIN32_KHR`, which I think they shouldn't, because there is no VK_USE_PLATFORM_LINUX_KHR and because they are stealing from the KHR extension). That needs some consistent solution (similar to issue #409)

3) Future Vulkan releases could perhaps go pointers (and just using simple forward declarations) to avoid include hell. (Some of the WSI Surface extensions already seem to have pointers only)

4) `#ifndef VULKAN_CORE_H` is perhaps too paranoid. Why not just include that? Only reason I see is that it too has macro config (`NO_PROTOTYPES`). Maybe it too should be spread in two (e.g. `vulkan_core_structs.h` and `vulkan_core_prototypes.h`)?

**Comment by MarkY-LunarG** [comment]
@krOoze, thanks again for the suggestions.   Regarding them.

 1. Yes, we don't need the guards outside of the new vulkan.h.  We've made that change to our internal version and I'll be trying to share the new version we've created shortly.
 2. I think we will evaluate that separately from this since we are already making pretty big changes to bring the new header format out.  I can see where you're going, though, and I can bring this up as a follow on change.
 3. Are you referring to removing the sections in the "VK_NO_PROTOTYPE" blocks?  I believe many people including vulkan.h use those and I would be against removing those.
 4. Personally, I don't want to add extra headers for core functionality.  I like the concept of keeping the main functionality in one header, and the platform independent parts in others.  As you pointed out, it could cause problems with the prototypes if we did just include the file as well.  Honestly, I'm not sure why you think it's paranoid.  With the way we've defined it, it will throw a clear error during compilation what a user may have forgotten to include.  I know I myself love clear messages like that instead of spending 10 minutes trying to figure out what I've done wrong.

**Comment by krOoze** [comment]
Great!

ad 3.
Not what I meant. I thought reducing the need for including external headers in the first place.

For structs and classes that is done by passing them as pointers and making only a forward declaration of the type they reference. Though most (all?) of the currently used stuff is probably just primitive types, which would require just copy-paste the definition from the original header (with the bonus of being backwards compatible).

ad 4,
Spreading them in two would remove the need for `VK_NO_PROTOTYPES` macro. Being C++ guy, removing evil macros is worthy goal in of itself. It is just troublesome (the macro works only if before first inclusion - same thing we just criticized `Windows.h` for). Also has non-zero compilation time cost.

People wanting just structs would include `vulkan_structs.h` and people wanting the whole thing would include `vulkan.h` (which would in turn also include `vulkan_structs.h`). It would still be keeping it in one header from the POV of the end user.

As for `#ifndef VULKAN_CORE_H`:
if the `vulkan_core.h` header did not have evil side-effects (as caused by the macro above), then it can be just replaced conventionally with `#include "vulkan_core.h" (or even with only `#include "vulkan_core_structs.h"`).

**Comment by MarkY-LunarG** [comment]
Ok.  I'll see what others think on your other issues.  In the meantime, here's the latest draft of the split headers we've been discussing.

**NOTE:** They're a few months out of date with regard to functionality and shouldn't be used in any product, blah, blah, blah (boiler-plating).

[split_headers_2.zip](https://github.com/KhronosGroup/Vulkan-Docs/files/771929/split_headers_2.zip)

Thanks for your patience @krOoze

**Comment by krOoze** [comment]
@MarkY-LunarG Hey, thanks for your work. Also for sharing it.

Some additional notes:

5)
The `vk_platform.h` is included in top-level `vulkan.h` and also in `vulkan_core.h`, but not in  e.g. `vulkan_win32.h` (which depends on `vulkan_core.h`).

It makes the top-level include redundant.

Maybe for esthetics `vulkan_win32.h` should include it too, I dunno. On the other hand it **could** be considered part of "core Vulkan", which `vulkan_win32.h` only extends.

6)
`#ifndef _WIN32` in `vulkan_win32.h` might be tricky. I think Cygwin or MinGW does not declare it (forgot which :blush:), but is still capable of using Windows API.

**Comment by krOoze** [comment]
Something like this seems to have been implemented along 1.1.70.
