### ISSUE TITLE
[Editing] Invalid anchors in the References

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#336]
In ch. 1.4. Normative References the items use invalid names for their anchor (names with spaces), which end up unencoded in the `href` of the XHTML.

https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L1057
links to the external document directly (bypassing the References chapter), which looks weird.

BTW: Is there a reason, why the output file is not a `*.xhtml` (and so served as a XHTML)?

**Comment by oddhack** [comment]
I don't have any problem following the anchor links with spaces in Chromium, Firefox, or Android Chrome. They all land in section 1.4 as intended. Is there a browser where this is actually a problem? Likewise, is there an actual problem related to how the file is served, and if so, what is that problem?

The https link will be corrected soon.

**Comment by philiptaylor** [comment]
It's invalid since [HTML says](https://html.spec.whatwg.org/multipage/dom.html#global-attributes) "the id attribute value [...] must not contain any space characters". Browsers are still required to support it when it contains spaces though, since HTML doesn't believe in undefined behaviour, so it will always work in all of them.

(Since HTML has well-defined behaviour for documents made of any arbitrary sequence of bytes, some people argued that the concept of document validity should be removed entirely from the specification, but I think the consensus was that it's still useful for guiding people away from edge cases in the language that are inconsistent or dangerous or poorly-designed. HTML validity errors are kind of like compiler warnings - usually it's okay to ignore them, and a lot of people do, but very occasionally they tell you something important, and then it's unfortunate if you can't see them because they're swamped by unimportant messages you didn't clean up earlier.)

I think using .xhtml (i.e. Content-Type: application/xhtml+xml) would be bad because it's an intentionally fragile syntax (so trivial errors can make the entire document unreadable), it has some weird DOM API differences (so normal scripts may stop working), it sometimes has worse performance than text/html (nobody uses application/xhtml+xml so browser developers don't care much about optimising it), etc. XHTML is a failed language and has been for over a decade, and nowadays it should be avoided when possible.

**Comment by oddhack** [comment]
@philiptaylor whenever we can manage to transition to asciidoctor we'll start generating HTML5. The XHTML output is basically an artifact of asciidoc being old and unmaintained, and major differences in its XHTML and HTML5 toolchains which we haven't had time to deal with. That's why I'm more interested in whether it's actually causing problems in real browsers than in whether its technically correct; we have many outstanding issues to deal with, they all take precious group time and energy, and we have to prioritize.

**Comment by krOoze** [comment]
@oddhack Sure, the serve method can be ignored in the meantime until transition.
But spaces are not allowed in HTML5 either.

@philiptaylor :
> I think using .xhtml (i.e. Content-Type: application/xhtml+xml) would be bad

BTW this spec does not conform to [W3C Note](https://www.w3.org/TR/xhtml-media-types/#text-html) recommendaton for serving as text/html either.

> so trivial errors can make the entire document unreadable

I consider that a good thing in a programming language.
Allowing "trivial" errors is why we can't have nice things... :smile: 

>  it sometimes has worse performance than text/html

By design should be the opposite (no tag soup parsing; allowed to panic on error). Of course depends on the state of browser support. Next to the MathJax hog, this is nothing.

> it has some weird DOM API differences (so normal scripts may stop working)

That is almost a non-issue because MathJax declares XHTML support. Only other script is the MathJax config. Inline scripts just must be escaped or a raw string to be proper XML.

> XHTML is a failed language

It is just less frequently adopted for historical reasons. Nothing wrong with the language itself. At least not more wrong than HTML.

**Comment by philiptaylor** [comment]
**Warning:** this is all totally off-topic and definitely not a productive use of time, please ignore.

> BTW this spec does not conform to W3C Note recommendaton for serving as text/html either.

Those XHTML compatibility guidelines are mostly nonsense. The [Polyglot Markup](https://www.w3.org/TR/html-polyglot/) document looks a bit better, though really people should just use the HTML syntax and avoid all that complexity. If you want to build documents with an XML toolchain then use proper XML internally (not a weird dialect of XML) and stick an XML-to-HTML serialiser on the end of it.

>> so trivial errors can make the entire document unreadable
>
> I consider that a good thing in a programming language.

(X)HTML isn't a programming language. Syntax errors in a program are detected by the programmer as they write and test it; but nearly all web pages are generated by programs, and no syntax checking happens until it reaches the user, who won't understand the error and can't do anything about it.

If you find a site that uses application/xhtml+xml, try putting a U+000B or U+FFFE into a search box, and the results page will usually echo the search string back and the page will be ill-formed (even if it tried to escape it to `&#xb;`) and the browser will refuse to display the page. Put those characters into a comment form so they're shown to other users, and nobody will be able to read the page. Bonus points if the site owner is unable to delete the offending comment because the admin pages display the comment and become ill-formed too.

(If I remember correctly, when I last checked many years ago, something on the order of 0.01% of sites used application/xhtml+xml, and every single one that I looked at had some form of these Unicode well-formedness bugs.)

> By design should be the opposite (no tag soup parsing; allowed to panic on error).

I think it's not fundamentally slower to parse tag soup - it just needs a [slightly more complicated state machine](https://html.spec.whatwg.org/multipage/syntax.html#tokenization) with extra states to handle error cases non-fatally, which doesn't affect the basic performance of tokenising and constructing the DOM. You do lose the ability to do SAX-like streaming since [things get reordered strangely](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Ctable%3E%3Ctr%3E%3Ctd%3Eone%3C%2Ftd%3Eoops%2C%20this%20text%20ends%20up%20before%20the%20table%3Ctd%3Etwo%3C%2Ftd%3E%3C%2Ftable%3E) but that shouldn't matter for browsers that are building DOMs instead of streaming. The more important factor is the effort spent optimising the implementation, which is more likely to be on the parser used by ~99.99% of web pages.

> Nothing wrong with the language itself.

Apart from those tricky Unicode rules that everyone implements wrong, and weird things like not having to escape `>` unless it's preceded by `]]`, and internal DTD subsets which are crazy, and arguably namespaces, etc.

And apart from XHTML being strategically misguided: It correctly recognised one of the many problems with HTML4 (that HTML syntax as used in reality was a totally-unspecified incompatible mess), but tried to solve it in the wrong way (by defining a new well-specified compatibly-implemented syntax and hoping the entire world would switch over to it), and did nothing about HTML4's other problems (like pretty much all the semantics being unspecified too, and the feature set stagnating for half a decade), and then the W3C went off to do XHTML Modularization and XHTML 2.0 which were wastes of time.

It took a different group of people outside the W3C to fix HTML properly (by defining a well-specified compatibly-implemented mess of a syntax that worked with the existing web, and specifying all the semantics, and adding new features that people wanted), and XHTML just hangs around as yet another awkward legacy part of the platform that we'll be stuck with forever.

(To be clear, I'm not a huge fan of XHTML :smile:)

**Comment by krOoze** [comment]
^ To be clear. me neither. But that doesn't count; I hate most web-like technologies equally :grin:

**Comment by oddhack** [comment]
The link to the SPIR-V spec has been corrected in the 1.0.25 spec update. We're not planning to do anything about the XHTML issues until and unless they are demonstrated to cause actual problems, not theoretical ones.

**Comment by krOoze** [comment]
@oddhack The spaces in `id` attribute are not XHTML-specific problem.

Apart from relying on strictly browser-specific behavior, let's see what happens if I copy the address bar in Chrome:
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#IEEE 754

Maybe the planned Asciidoctor properly replaces it with `%20`...

Still for sections, figures and tables the style seem to be lower-cased with spaces replaced with hyphens. Why should these links be any different.

**Comment by krOoze** [comment]
BTW: there are some "Khronos Data Format Specification" references, that are not links.

**Comment by philiptaylor** [comment]
> it may trigger some quirks mode of the browsers, having unknown consequences

It won't - quirks mode is a well-defined [concept](https://dom.spec.whatwg.org/#concept-document-quirks) that's triggered by [certain doctypes of historical interest](https://html.spec.whatwg.org/multipage/syntax.html#quirks-mode-doctypes) (or certain parse errors before the doctype). And the consequences of quirks mode are known and [specified](https://quirks.spec.whatwg.org/). I think there are no other errors that cause a mode change, they just have localised effects which are also extensively specified.

(As it happens, the Vulkan spec's current XHTML 1.0 Transitional doctype triggers limited-quirks mode, which is like no-quirks mode but with some quirky CSS spacing for compatibility with the 1990s.)

**Comment by krOoze** [comment]
The anchors seems fixed in 1.0.27.

Still two non-link references to "Khronos Data Format Specification" in Compressed Image Formats and in Blend Operations.
