### ISSUE TITLE
Bits/Flags inconsistent

### ISSUE THREAD

**Issue by PtrMan** [KhronosGroup/Vulkan-Docs#338]
See the "correct" Bit for example:

void vkGetPhysicalDeviceSparseImageFormatProperties(
...
VkSampleCountFlagBits samples,
...
)

when you lookup the type in the docs its just an enum which can be Ored together 

typedef enum VkSampleCountFlagBits {
VK_SAMPLE_COUNT_1_BIT = 0x00000001,
VK_SAMPLE_COUNT_2_BIT = 0x00000002,
VK_SAMPLE_COUNT_4_BIT = 0x00000004,
VK_SAMPLE_COUNT_8_BIT = 0x00000008,
VK_SAMPLE_COUNT_16_BIT = 0x00000010,
VK_SAMPLE_COUNT_32_BIT = 0x00000020,
VK_SAMPLE_COUNT_64_BIT = 0x00000040,
} VkSampleCountFlagBits;

while for for example VkAttachmentDescription

typedef struct VkPipelineRasterizationStateCreateInfo {
...
VkCullModeFlags cullMode;
...
}

where VkCullModeFlags is 

typedef VkFlags VkCullModeFlags;

which is just a ooIoo for any (automated) codegen, the right type for this is VkCullModeFlagBits

I haven't scanned the whole spec for these kinds of errors but its extremly annying for what I do.

**Comment by NicolBolas** [comment]
There is a distinction between the enumeration which contains enumerators whose values are bits, and the actual bitmask type that's used in interfaces. Why?

Because conceptually, the point of an enumeration type is that variables of that type are intended to store *one of those values*. If a function takes an enumeration, then the function is saying that you are to pass exactly one of those values.

By contrast, if a function takes a bitmask, it is taking a value which stores *multiple* values in an enumeration.

Thus, we need a distinction between "I'm taking an enumerator" and "I'm taking a bitmask".

Consider `VkImageCreateInfo`. It takes `VkSampleCountFlagBits`. It doesn't take a bitmask of sample counts; it takes a _single bit_, which represents the specific sample count that will be used for that image. By contrast, `VkImageFormatProperties` returns `VkSampleCountFlags`. This is a true bitmask of allowed sample counts; the system says which bits are acceptable sample counts.

Yes, this is an odd thing to see (and I hadn't noticed it myself) at first glance. But it makes a lot of sense if you think about it.

**Comment by oddhack** [comment]
+1 @NicolBolas . This is by design.

**Comment by PtrMan** [comment]
I know this distinction, still read and lookup my points...

***Bits tells me that I can combine it with the or function. Its also possible that the API returns a or'ed result of all possible values see VkSampleCountFlagBits.

Flags can't get or'ed together, because just one value is valid.

This all breaks down with VkPipelineRasterizationStateCreateInfo for the cullMode, where the type VkCullModeFlags indicates that it can't or'ed together, but the enum says it can be orded together...

In other places in the doc this is different, as I already wrote

**Comment by PtrMan** [comment]
a bit of code to illustrate the issue

the correct one:
```D
VkAttachmentDescription convertForAtachmentDescription(JsonValue jsonValue) {
	return jsonReaderForVulkanStructureWithOnlySpecifiedFields!(VkAttachmentDescription, 
		[
			"flags":"VkAttachmentDescriptionFlags",
			"format":"VkFormat",
			"samples":"VkSampleCountFlagBits",
			"loadOp":"VkAttachmentLoadOp",
			"storeOp":"VkAttachmentStoreOp",
			"stencilLoadOp":"VkAttachmentLoadOp",
			"stencilStoreOp":"VkAttachmentStoreOp",
			"initialLayout":"VkImageLayout",
			"finalLayout":"VkImageLayout",
		]
	)(jsonValue);
}
```

the incorrect one
```D
VkPipelineRasterizationStateCreateInfo convertForPipelineRasterizationStateCreateInfo(JsonValue jsonValue) {
	VkPipelineRasterizationStateCreateInfo result = jsonReaderForVulkanStructureWithOnlySpecifiedFields!(VkPipelineRasterizationStateCreateInfo,
		[
		"depthClampEnable":"VkBool32",
		"rasterizerDiscardEnable":"VkBool32",
		"polygonMode":"VkPolygonMode",
		"cullMode":"VkCullModeFlagBits", // not like in the "specification", where its VkCullModeFlags, which is _not_ the type
		"frontFace":"VkFrontFace",
		"depthBiasEnable":"VkBool32",
		"depthBiasConstantFactor":"float",
		"depthBiasClamp":"float",
		"depthBiasSlopeFactor":"float",
		"lineWidth":"float"
		],"flags"
	)(jsonValue);
...
```

I don't see how this is not an issue if the user(of an engine or middleware) wants to pass in these values in a datendriven fashion.

Currently I check if the name ends with Flags (works fine for the flag field), but this breaks with the 2nd function...

**Comment by philiptaylor** [comment]
> ***Bits tells me that I can combine it with the or function. Its also possible that the API returns a or'ed result of all possible values see VkSampleCountFlagBits.
>
> Flags can't get or'ed together, because just one value is valid.

It's the other way round: a value of type VkFooFlagBits must be a single value from the enum, a value of type VkFooFlags can be zero or more bits or'd together.

That's defined in https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-validusage-enums and https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#fundamentals-validusage-flags , and each function says that FlagBits must be an enum value while Flags is a combination of values, e.g.:

> `VkSampleCountFlagBits samples,`
> ...
> samples must be a valid VkSampleCountFlagBits value 
> ...
> `VkCullModeFlags cullMode;`
> ...
> cullMode must be a valid combination of VkCullModeFlagBits values

cullMode is peculiar because its Bits enum has `VK_CULL_MODE_NONE = 0` and `VK_CULL_MODE_FRONT_AND_BACK = VK_CULL_MODE_FRONT_BIT | VK_CULL_MODE_BACK_BIT`. Essentially it's just an enum with the two values `FRONT_BIT` and `BACK_BIT` plus the convenient extra symbols `NONE` and `FRONT_AND_BACK`, which seems like a design mistake to me since Vulkan isn't meant to be convenient. I think it still makes sense for cullMode to be a VkCullModeFlags though, since it can be set to a combination of zero or more bits like all the other VkFooFlags. And removing the other symbols now would break compatibility for no real benefit.

VkStencilFaceFlagBits has a similar design (minus the `NONE` symbol). I'm not sure if there are any others.

**Comment by krOoze** [comment]
On a side-note the types should perhaps have been named CkXyBit (type/class of bit value is a Bit, not Bits, in contrast to Flags, where more flags can be raised in the object of such type).
