### ISSUE TITLE
Ignore .pyc files, not just __pycache__ 

### ISSUE THREAD

**Issue by FirefoxMetzger** [KhronosGroup/Vulkan-Docs#349]
When creating `vulkan.h` using python 2.7.8, python will create the `.pyc` bytecode in the same folder as the `.py` files (as opposed to the  `__pycache__` folder).

Thus I think it makes sense, to add those to the gitignore:

    # Python cache
    __pycache__
    .pyc

**Comment by oddhack** [comment]
This should be fixed in the next public update (hopefully Friday). Closing it now so I don't lose track of it.

When the bytecode files get created in the local directory under various python versions and circumstances is mystifying. I think I only noticed this myself recently when doing some changes to how the generation scripts were invoked.

**Comment by jjulianoatnv** [comment]
This discusses location of .pyc files:
http://stackoverflow.com/questions/5149832/where-are-the-pyc-files

According to the stackoverflow answers, in python < 3.2 the .pyc files are in same directory as .py files, while in later python versions the .pyc files are in a __pycache__ directory.

I did not used to see the .pyc files in "git status", but today I see them in same directory as the .py files. I don't understand what changed to cause this. However, using "python genvk.py vulkan.h" as described in README.adoc results in .pyc files next to the .py files, while "python3 genvk.py vulkan.h" results in .pyc files created in a __pycache__ subfolder. That seems to suggest that the instructions in README.adoc cause the use of python2 instead of python3.

The ".pyc" line that was added to .gitignore seems wrong. I think it should be "*.pyc", and making this change removes the .pyc files from my "git status" output. I submitted a request to adjust .gitignore.

**Comment by ratchetfreak** [comment]
@jjulianoatnv sounds like your PATH env points to your python 2 install before your python 3 install

**Comment by jjulianoatnv** [comment]
@ratchetfreak Thanks for the suggestion. I think this is unrelated to PATH.

I figured out that I had done:
```
./genvk.py vulkan.h
```
instead of
```
python3 genvk.py vulkan.h
```

The file genvk.py is the only .py in the repo that has a shebang line referencing python instead of python3. According to
```
https://www.python.org/dev/peps/pep-0394/
https://www.python.org/dev/peps/pep-0397/
```
that causes the use of python2. Changing the shebang line s/python/python3/ fixes it to use python3. I've submitted another request that adds "3" to the end of the shebang line, as is already the case for all of the other .py files in the repo.

**Comment by oddhack** [comment]
To repeat something I said internally, while the scripts hopefully run with python2, it's not really "supported" - I'll fix problems if they're brought to my attention. AFAIK all the scripts, Makefiles, and READMEs explicitly invoke python3 by default to run scripts, and it's pretty much on your own recognizance to use python2.
