### ISSUE TITLE
How can a left-handed NDC space be supported?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/Vulkan-Docs#357]
This is a transfer of glslang issue 494, as it sounds this is the correct place to address it.

In particular, see these comments:
- https://github.com/KhronosGroup/glslang/issues/494#issuecomment-243993159
- https://github.com/KhronosGroup/glslang/issues/494#issuecomment-244690458

**Comment by NicolBolas** [comment]
If this is going to be a core requirement of a future Vulkan 1.1, then I say that we should also require Vulkan to support OpenGL conventions. It'd be silly for Vulkan to support D3D12 conventions, as well as compilation from GLSL, but without supporting the actual OpenGL conventions for these things.

If it's going to be part of an extension, then D3D12-only seems reasonable.

**Comment by Novum** [comment]
Note: This is a rant

I have said this before, but this is something that should never have happened. To my knowledge all other platforms use a common convention. Therefore I do not believe this was any sort of hardware limitation that forced Vulkan to be different.

Just support the D3D12 convention and be done with it. All the coordinate systems should be industry standards. Nobody has time for shenanigans like this and there are zero benefits to be different.

**Comment by NicolBolas** [comment]
> To my knowledge all other platforms use a common convention.

I just realized that you're absolutely right (thus making my above point superfluous).

NDC conventions actually _are_ OpenGL's conventions ([using the [0, 1] depth range that GL 4.5 allows, of course](https://www.opengl.org/registry/specs/ARB/clip_control.txt)). And I verified that [Metal also uses the same left-handed axis conventions](https://developer.apple.com/library/mac/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Render-Ctx/Render-Ctx.html). So Vulkan really is the odd one out here.

Unfortunately, since Vulkan 1.0 shipped this way, it must be supported until 2.0 ships. Otherwise, it'd be a backwards-incompatible change.

**Comment by DominikWitczakAMD** [comment]
AMD will shortly be releasing a Vulkan extension called VK_AMD_negative_viewport_height which is going to allow applications to flip Y in viewport space.

**Comment by hrydgard** [comment]
Viewport in hardware is really a scale factor + translation, rather than x/y/w/h. If it was specified that way (centerX, centerY, scaleX, scaleY) instead of x,y,w,h, support for flipping the view by both X and Y would sort of fall out neatly automatically. A bit late to change that now though I guess. Of course, changing the backface culling order to match is always an issue...

**Comment by TobiasHector** [comment]
Surprised this hasn't been closed - VK_KHR_maintenance1 added the ability to select a negative viewport. Think this can be considered dealt with? Please re-open if anyone thinks there are still issues to address...
