### ISSUE TITLE
Files removed from Vulkan-Docs/doc/specs/vulkan/man/

### ISSUE THREAD

**Issue by FacticiusVir** [KhronosGroup/Vulkan-Docs#358]
Prior to Patch 26, the man folder contained text files with extracted documentation for each type and command in the core spec - these were hugely useful for generating code documentation for bindings to other languages, and I was using them as part of SharpVk (https://github.com/FacticiusVir/SharpVk). Are these files available elsewhere, or is there a way to generate them?

**Comment by ratchetfreak** [comment]
check the src/spec/vk.xml 

it should contain everything

**Comment by FacticiusVir** [comment]
It would be awesome if that were the case, but sadly not - for example, in the file https://github.com/KhronosGroup/Vulkan-Docs/blob/85184f305afe0f2e9e99cc9525e8ce25c32e74e0/doc/specs/vulkan/man/VkBuffer.txt we have the text

> Buffers represent linear arrays of data which are used for various
> purposes by binding them to a graphics or compute pipeline via descriptor
> sets or via certain commands, or by directly specifying them as parameters
> to certain commands.

Which is a great summary of the VkBuffer type, but appears nowhere in the vk.xml file.

**Comment by courtney-g** [comment]
I believe those files are now generated when building the Vulkan spec.

**Comment by krOoze** [comment]
@FacticiusVir It should get populated if you do e.g. `make manhtml`.

**Comment by FacticiusVir** [comment]
I'm running the generator in a Windows/.NET environment, so requiring make (and, I presume, python et cetera) is more additional set-up than I was planning; looks like it'll be easier to scrape the text out of the chapter files.

**Comment by oddhack** [comment]
They are generated files, and in the single-branch model, generated files turn out to generate far too much git churn to be maintainable inside the repository. The HTML and PDF outputs from the generated asciidoc are in the Vulkan registry. If you require the asciidoc source, it does now require installing the build tools.

It is possible the asciidoc sources could be checked into the registry as well, since that's part of the build process for the releases anyway and it's mostly a matter of where they're generated. But we'd like to see more feedback that would actually be useful, before signing up to do it in the long term. The asciidoc markup isn't actually renderable (cleanly) in an in-browser asciidoc extension (or GitHub's asciidoc renderer either), because it relies on a ton of custom macro definitions that such extensions won't have available. So the use case seems narrow.

**Comment by FacticiusVir** [comment]
That's fair - having files with the type documentation that can be indexed by type name is a big help for generating bindings, but I can't imagine it has much use outside that. It's probably most efficient if I build a separate tool to run a similar extraction from the spec files. Thanks for the help!

**Comment by FacticiusVir** [comment]
If folks are interested, I've started uploading a machine-readable extract of the asciidoc chapter files for this purpose [here](https://github.com/FacticiusVir/SharpVk-Docs/tree/master/Docs)
