### ISSUE TITLE
Fail to build manpages on ArchLinux since v1.0-core-20160906

### ISSUE THREAD

**Issue by lordheavy** [KhronosGroup/Vulkan-Docs#367]
package is built in a chroot with LANG=C:

`Building KHR extensions for targets manpages
python3 ../../../src/spec/genvk.py -extension VK_KHR_android_surface -extension VK_KHR_display -extension VK_KHR_display_swapchain -extension VK_KHR_mir_surface -extension VK_KHR_sampler_mirror_clamp_to_edge -extension VK_KHR_surface -extension VK_KHR_swapchain -extension VK_KHR_wayland_surface -extension VK_KHR_win32_surface -extension VK_KHR_xcb_surface -extension VK_KHR_xlib_surface -registry ../../../src/spec/vk.xml -o . vkapi.py
- Building vkapi.py
- Generated vkapi.py
  python3 genRef.py chapters/devsandqueues.txt chapters/VK_EXT_debug_marker.txt chapters/synchronization.txt chapters/VK_EXT_validation_flags.txt chapters/textures.txt chapters/copies.txt chapters/resources.txt chapters/geometry.txt chapters/renderpass.txt chapters/drawing.txt chapters/extensions.txt chapters/vertexpostproc.txt chapters/shaders.txt chapters/clears.txt chapters/memory.txt chapters/pipelines.txt chapters/samplers.txt chapters/framebuffer.txt chapters/fxvertex.txt chapters/interfaces.txt chapters/queries.txt chapters/tessellation.txt chapters/sparsemem.txt chapters/primsrast.txt chapters/introduction.txt chapters/descriptorsets.txt chapters/fragops.txt chapters/features.txt chapters/initialization.txt chapters/dispatch.txt chapters/cmdbuffers.txt chapters/fundamentals.txt appendices/VK_EXT_validation_flags.txt appendices/spirvenv.txt appendices/credits.txt appendices/VK_AMD_draw_indirect_count.txt appendices/VK_AMD_rasterization_order.txt appendices/VK_NV_external_memory.txt appendices/VK_NV_external_memory_win32.txt appendices/VK_AMD_shader_explicit_vertex_parameter.txt appendices/extensions.txt appendices/VK_IMG_filter_cubic.txt appendices/VK_KHR_sampler_mirror_clamp_to_edge.txt appendices/VK_AMD_gcn_shader.txt appendices/VK_AMD_negative_viewport_height.txt appendices/boilerplate.txt appendices/invariance.txt appendices/VK_NV_win32_keyed_mutex.txt appendices/VK_EXT_debug_marker.txt appendices/VK_AMD_shader_trinary_minmax.txt appendices/VK_NV_dedicated_allocation.txt appendices/VK_EXT_debug_report.txt appendices/compressedtex.txt appendices/VK_NV_external_memory_capabilities.txt appendices/glossary.txt appendices/VK_NV_glsl_shader.txt chapters/VK_IMG_filter_cubic/filter_cubic_sampled_bit_description.txt chapters/VK_IMG_filter_cubic/supported_formats.txt chapters/VK_IMG_filter_cubic/filter_cubic_texel_selection.txt chapters/VK_IMG_filter_cubic/filter_cubic_texel_filtering.txt chapters/VK_KHR_android_surface/platformCreateSurface_android.txt chapters/VK_KHR_android_surface/platformQuerySupport_android.txt chapters/VK_KHR_swapchain/wsi.txt chapters/VK_NV_win32_keyed_mutex/keyed_mutex_submit.txt chapters/VK_KHR_wayland_surface/platformCreateSurface_wayland.txt chapters/VK_KHR_wayland_surface/platformQuerySupport_wayland.txt chapters/VK_KHR_win32_surface/platformCreateSurface_win32.txt chapters/VK_KHR_win32_surface/platformQuerySupport_win32.txt chapters/VK_NV_external_memory_win32/get_handle_win32.txt chapters/VK_NV_external_memory_win32/handle_permissions.txt chapters/VK_NV_external_memory_win32/import_memory_win32.txt chapters/VK_NV_external_memory_capabilities/external_image_format.txt chapters/VK_KHR_display/display.txt chapters/VK_KHR_xlib_surface/platformCreateSurface_xlib.txt chapters/VK_KHR_xlib_surface/platformQuerySupport_xlib.txt chapters/VK_KHR_xcb_surface/platformCreateSurface_xcb.txt chapters/VK_KHR_xcb_surface/platformQuerySupport_xcb.txt chapters/VK_KHR_surface/wsi.txt chapters/VK_KHR_display_swapchain/create_shared_swapchains.txt chapters/VK_KHR_display_swapchain/display_swapchain_present.txt chapters/VK_KHR_display_swapchain/queue_present_interactions.txt chapters/VK_KHR_display_swapchain/destroy_swapchain_interactions.txt chapters/VK_NV_external_memory/allocate_memory.txt chapters/VK_KHR_mir_surface/platformCreateSurface_mir.txt chapters/VK_KHR_mir_surface/platformQuerySupport_mir.txt appendices/VK_KHR_swapchain/vk_khr_swapchain.txt appendices/VK_KHR_wayland_surface/vk_khr_wayland_surface.txt appendices/VK_KHR_display/vk_khr_display.txt appendices/VK_KHR_android_surface/vk_khr_android_surface.txt appendices/VK_KHR_win32_surface/vk_khr_win32_surface.txt appendices/VK_KHR_xcb_surface/vk_khr_xcb_surface.txt appendices/VK_KHR_xlib_surface/vk_khr_xlib_surface.txt appendices/VK_KHR_surface/vk_khr_surface.txt appendices/VK_KHR_surface/wsi.txt appendices/VK_KHR_display_swapchain/vk_khr_display_swapchain.txt appendices/VK_KHR_mir_surface/vk_khr_mir_surface.txt
  Traceback (most recent call last):
  File "genRef.py", line 521, in <module>
    genRef(file, baseDir)
  File "genRef.py", line 393, in genRef
    file = loadFile(specFile)
  File "/build/vulkan-docs/src/Vulkan-Docs-1.0-core-20160916/doc/specs/vulkan/reflib.py", line 197, in loadFile
    file = fp.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6366: ordinal not in range(128)
  make: **\* [Makefile:322: man/apispec.txt] Error 1`

Forcing LANG to en_US.UTF-8, it succeed but there is no manpages produced.

**Comment by oddhack** [comment]
Some of the files do contain the UTF-8 × symbol, although otherwise I think they're pretty much straight ASCII. So LANG=en_US.UTF-8 seems correct.

I suppose we could override the locale in the scripts that read from the spec sources, though I haven't played enough with the Python locale package to really know how to do that, nor am sure it's the "correct" answer for some value of "correct".

**Comment by krOoze** [comment]
@oddhack Did a quick search and × is the only Unicode in the sources. Mostly in features.txt and sparsemem.txt. It is UTF-8 0xC3 0x97, which is consistent with the log. That could be easily converted to \times in latexmath.

**Comment by oddhack** [comment]
@lordheavy the scripts have been changed to use encoding='utf-8' for file I/O, which might fix this. Can you check against the current repository and see if this still occurs?

**Comment by Ryp** [comment]
Any news on this issue?

**Comment by oddhack** [comment]
@Ryp AFAIK, the ref page asciidoc sources are being generated correctly now whether LANG is "C" or "en_US.UTF-8". It has never been a problem on Debian for me though, so I wanted to hear back from @lordheavy as to whether the little Python fix addressed the issue or not.

Separately, I remembered an underlying problem, separate from the Unicode issue, with the manhtmlpages target. I have never figured out how to properly express the chain of dependencies on generated targets whose names are unknown at the time 'make' is invoked, so the target

> manhtmlpages: man/apispec.txt $(MANHTML)

expands MANHTML to nothing when it's invoked before man/apispec.txt has been separately built, which also generates all the man page sources (man/[Vv][Kk]*txt) as a side effect. A workaround is:

> make man/apispec.txt
> make manhtml

If any of you folks have enough insight into gmake to suggest how to express this dynamic dependency, where the dependencies aren't known at make invocation time, that would be great. The only other workaround I can think of inside the Makefile itself is to recursively invoke $(MAKE) inside the manhtml rule to generate the HTML output pages, once the asciidoc sources are generated by the man/apispec.txt rules.

I TBH forgot about this because I almost never invoke the Makefile directly - the frontend genRelease script does all the right stuff to manage the public updates we do, and other than that, all we generate for internal use is the specification outputs.

**Comment by oddhack** [comment]
Closing this - if it's still a problem for the OP, feel free to reopen. I fixed the Makefile dynamic dependency issue I described in the immediate prior comment a while back, via recursively $(MAKE). We are now publishing 1.1 + all extensions refpages in the registry.
