### ISSUE TITLE
Is reading undefined memory an error?

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Docs#378]
I started this discussion in LoaderAndValidationLayers and was advised to link to it here.

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/965

We'd like more opinions on the topic.

**Comment by krOoze** [comment]
Define "undefined memory". If you mean undefined value/contents, that sounds to me traditionally more like a `WARNING`.

Can't find anything that would forbid such reads (unless breaking some other requirement).
There is something about aliased resources having to be transitioned from `LAYOUT_UNDEFINED` after made undefined, though`.

**Comment by NicolBolas** [comment]
Is reading uninitialized memory considered not to be "Valid Usage" by some part of the specification? By my reading of the specification, no.

Now obviously, you will get undefined behavior by doing anything based on the value being read. But the act of reading it alone should not be considered an error.

That is, if you create a texture, then transition it to the GENERAL layout, and don't copy something into it at some point, you can still read from it. But the values you get will be undefined.

Validation layers can warn over this, but they should not _error_ over it. It's always possible that the value being read will be only conditionally used (perhaps the user multiplies it by 0 or 1, based on some uniform/push constant data).

**Comment by critsec** [comment]
We discussed this in the Working Group this morning, and the consensus was agreement with @NicolBolas: reading memory that has undefined contents is not necessarily an error. You get undefined values, but behavior is otherwise well-defined. The example he gave is a good one: a compiler could quite reasonably take a conditional read in the source language, and do it unconditionally, but then only conditionally use the result. This produces well-defined behavior and results, and calling it an error would essentially be calling this a compiler bug, when in fact its perfectly valid.

Of course, if the application does something with these non-deterministic values that has undefined behavior for some inputs, then they risk triggering that undefined behavior -- but only if the value happens to be one of the ones for which behavior is undefined; if the app happened to get a valid value, then behavior will continue to be well-defined for that particular execution of the program.

**Comment by lentinem** [comment]
*sigh*. I'm not sure I buy that argument - the compiler would be changing the code to be functionally different from the source and while I get that it's "well-defined"; the inability to use it seems to make it not very useful. That being said; if that is the decision so be it; we'll change it to a warning.

**Comment by ShabbyX** [comment]
@lentinem _the compiler would be changing the code to be functionally different from the source_

Not exactly. Unless the value to be read is `volatile`, reading the value out of its original place while still respecting the partial order of operations is perfectly valid. As a matter of fact, it's valid because the result *isn't* functionally different from the source. All compiler optimizations do this.

An example that would be relevant is the compiler potentially changing:

```C
if (a == b)
    c = x;
else
    c = y;
```

to:

```C
_temp = -(a == b);
c = (temp & x) | (~temp & y);
```

if for whatever reason it decides that this branch-less code is faster. Functionally, they would behave the same (assuming all the types and sizes make this a valid change), so the compiler is perfectly correct in doing that.

**Comment by lentinem** [comment]
Thanks for the explanation! However, in this case we are calling into a function instead of reading from local memory. I would expect that the compiler should never decide a function call is cheaper than a branch but perhaps there are some cases where it would?

**Comment by karl-lunarg** [comment]
Validation layers changed to issue a warning instead of an error.  Closing.
