### ISSUE TITLE
VK_ERROR_NATIVE_WINDOW_IN_USE_KHR vs validity

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#387]
`vkCreateAndroidSurfaceKHR` and `vkCreateSwapchainKHR` can return `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` which seems to be intended to be returned when Native Window is already used by something.

1) But both `vkCreateAndroidSurfaceKHR` and `vkCreateSwapchainKHR` have in theirs respective Valid Usages that the Native Window must not already be used, making it an absolute requirement.

2) The description:

> `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` The requested window is already connected to a `VkSurfaceKHR`, or to some other non-Vulkan API.

is probably missing the case, when somebody has only one `VkSurfaceKHR`(as said there), but tries to create two swapchains from it.

3) For the Native Window Surface creation commands not capable of returning `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` it should perhaps be said if `vkCreateSwapchainKHR` will return that error if more `VkSurfaceKHR`es of the same Native Window is created (or otherwise if it will be tolerated as long as a swapchain is not created from the duplicates).

**Comment by cubanismo** [comment]
The current description isn't even valid in the general case.  The error is supposed to be for the swapchain case.  It should be fine to create multiple VkSurface objects from the same native window everywhere except on Android, because Android had to be different than the other native interfaces.  I'm not sure what to suggest as a replacement, but it shouldn't specifically imply that vkCreate*SurfaceKHR return this error, because that won't be the case on most window systems.

**Comment by ianelliottus** [comment]
Response to @krOoze's comments:

> 1) But both vkCreateAndroidSurfaceKHR and vkCreateSwapchainKHR have in theirs respective Valid Usages that the Native Window must not already be used, making it an absolute requirement.

I'm sorry, but can you quote the Valid Usage statements that you are referring to?

That said, there are limitations to using Vulkan with an Android ANativeWindow, which is what this error is about.  If the application attempts to create a 2nd VkSurfaceKHR for the same ANativeWindow, it will fail, and this error will be returned (regardless of any validation layer checking that may or may not also be done).

> 2) The description:
> > VK_ERROR_NATIVE_WINDOW_IN_USE_KHR The requested window is already connected to a VkSurfaceKHR, or to some other non-Vulkan API.
> is probably missing the case, when somebody has only one VkSurfaceKHR(as said there), but tries to create two swapchains from it.

That may be true and can explain why that error can be returned by vkCreateSwapchainKHR.   It can be argued that the error description is meant to be generic and not exhaustive.  I'll check on that.

Regarding @cubanismo's comment, I'm wondering if the error description should be strengthened to state that the error is for Android ANativeWindow's.  Perhaps the wording should be:

> The requested ANativeWindow is already connected to a VkSurfaceKHR, or to some other non-Vulkan API.

We should discuss that inside of Khronos though.

Regarding @krOoze's 3rd point, I'm sorry, but I'm not sure that I follow what you wrote.  Since this error is only for an Android ANativeWindow, I don't see why we need to say anything for the other vkCreate*SurfaceKHR commands.  Perhaps we should explain why this error can be returned by vkCreateSwapchainKHR.  Is that what you were suggesting?

**Comment by krOoze** [comment]
ad 1):
> I'm sorry, but can you quote the Valid Usage statements that you are referring to?

Of course.

`VkAndroidSurfaceCreateInfoKHR`:
> `window` **must** not be in a connected state

`VkSwapchainCreateInfoKHR`:
> The native window referred to by surface must not already be associated with a swapchain other than oldSwapchain, or with a non-Vulkan graphics API surface

But both respective `create*` commands also lists `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` return code which seem to cover the same case.

> (regardless of any validation layer checking that may or may not also be done)

I don't think that is how the Vulkan works. Validation statements have higher priority (=undefined behavior) than error return codes (well-behaved recoverable errors). At least that is how it was resolved, when I pointed similar issue for `vkGet*ProcAddr` (was returning NULL for same cases as were in VU).

To have it directly from the spec (2.6.1. Valid Usage):
> Valid usage conditions do not cover conditions where well-defined behavior ([!]including returning an error code[!]) exists.

---------------------------
ad 2):
>  It can be argued that the error description is meant to be generic and not exhaustive.

It depends on the resolution of 1), but I assumed my counter-example of one `VkSurface` and two swap chains (Vulkan or external) is also intended to return `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` (despite the VU).

I don't see how it is a general description of that case too (it covers only two `VkSurface`, or `VkSurface` + external API, and **not** two swap chains).

----------------------------
ad 3):

> Perhaps we should explain why this error can be returned by vkCreateSwapchainKHR. Is that what you were suggesting?

Yes, that's pretty much what I meant. If it's only for `ANativeWindow` as you claim (which is not obvious from the spec BTW), why can `vkCreateSwapchainKHR` also return that error?

**Comment by ianelliottus** [comment]
> ad 1):
> > Valid usage conditions do not cover conditions where well-defined behavior (including returning an error code) exists.

So, I think the action to take is to remove the VU statements that are covering cases where VK_ERROR_NATIVE_WINDOW_IN_USE_KHR will be returned.  Do you agree?

> ad 2):
> I don't see how it is a general description of that case too (it covers only two VkSurface, or VkSurface + external API, and not two swap chains).

Perhaps different wording is needed, but I don't like the idea of exhaustively articulating all of the possible cases for the error.  How about the following wording?:

> The requested window is already in use, and has limitations that prevent it from being used again.

> ad 3):

Okay.  We'll try to address this.

**Comment by critsec** [comment]
VK_ERROR_NATIVE_WINDOW_IN_USE_KHR is not Android-specific. It was originally part of the VK_KHR_android_surface extension, but other platforms discovered they had a need for it as well so we moved it to VK_KHR_surface.

If I remember right, Android is the only platform that will return this error from `vkCreate*SurfaceKHR`, but several others will return it from `vkCreateSwapchainKHR`.

**Comment by ianelliottus** [comment]
> VK_ERROR_NATIVE_WINDOW_IN_USE_KHR is not Android-specific.

Oh.  I stand corrected:-).  How should we deal with the issues @krOoze brings up?  We can discuss that internally if you want.

**Comment by ianelliottus** [comment]
@krOoze, I have prepared the change to the spec.  The two VU statements that you cited are being removed.  The error's definition will become what I proposed.

Regarding "ad 3):", first, I apologize that I forgot that this error is for multiple window systems for vlCreateSwapchainKHR().  Second, we find that the following statements in the spec address this concern:

> A native window cannot be associated with more than one swapchain at a time. Further, swapchains cannot be created for native windows that have a non-Vulkan graphics API surface associated with them.

Therefore, we don't propose making any changes for this point.  Sound good?

**Comment by krOoze** [comment]
@ianelliottus Yes, that shou'd work. I have minor notes to that though:

1)
> [...] that have a non-Vulkan graphics API surface [...]
Why "surface"? Isn't that too specific a term?

2) That is quite important piece of information, Should perhaps be in a separate paragraph.

3) It should explain the `oldSwapchain` exception to that (, now that that will be removed from the VU).

4) To clarify the intended behavior, is the following correct?: 

It will **not** return that error when:
- Two `VkSurface`s are created from the same native window and one of the `VkSurface` is used with `vkCreateSwapchainKHR()`

It will return that error when:
- Same `VkSurface` is used with the `vkCreateSwapchainKHR()` twice
- Two `VkSurface`s are created from the same native window and both `VkSurface`s are used with `vkCreateSwapchainKHR()`

**Comment by ianelliottus** [comment]
@krOoze, I took your 2nd and 3rd minor notes.  I see the issue with your 1st note.

For your 4th minor note, I think your wording gets into trouble because Android only allows one surface per native window.  I'm concerned that trying to be explicit on this point can end up creating a large amount of complex text, that might decrease clarity for some people:-):-).

**Comment by krOoze** [comment]
@ianelliottus Oh, I was not suggesting wording. Just asking, to make sure it is supposed to work that way (for non-android `VkSurface`).

**Comment by ianelliottus** [comment]
> I was not suggesting wording. Just asking, to make sure it is supposed to work that way (for non-android VkSurface).

Okay then.  I believe that you did summarize it accurately for non-Android surfaces.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.31 spec update.

**Comment by krOoze** [comment]
The VU statement for `VkSwapchainCreateInfoKHR` was just copy-pasted elsewhere, which changes nothing.

If the `VK_ERROR_NATIVE_WINDOW_IN_USE_KHR` is returned deterministically for all such conceivable cases, it should say "cannot"(=impossible to achieve by user), not "must not"(=absolute requirement).
