### ISSUE TITLE
Inconsistency in the required support for StorageImageExtendedFormats

### ISSUE THREAD

**Issue by Dolkar** [KhronosGroup/Vulkan-Docs#395]
From reading the SPIR-V spec and the list of physical device features, it's implied that the support for using images with certain formats as storage images is optional. To be able to use them, the _shaderStorageImageExtendedFormats_ feature needs to be enabled:

> _shaderStorageImageExtendedFormats_ indicates whether the extended storage image formats are available in shader code. If this feature is not enabled, the formats requiring the StorageImageExtendedFormats capability are not supported for storage images.

However, in the Required Format Support section of the Vulkan spec, many of the formats that are supposed to only be available if the _shaderStorageImageExtendedFormats_ feature is enabled have the _VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT_ checked, meaning they are required regardless of the presence of the feature.

For example, as per the SPIR-V spec, the **Rg32f** format requires the _StorageImageExtendedFormats_ shader capability, which in turn needs a device with the _shaderStorageImageExtendedFormats_ feature enabled. According to the Vulkan spec, though, the matching **VK_FORMAT_R32G32_SFLOAT** format is always required to be available for use with storage images, with no footnote or reference to the feature in question.

**Comment by oddhack** [comment]
Closing after merging #1098.

**Comment by kvark** [comment]
Just to get some clarification, if I want to use `Rg32f` storage format, I still have to enable this SPIR-V capability, even if my logical device doesn't have `shaderStorageImageExtendedFormats` feature enabled. Is that right?
If that's right, it's unfortunately very confusing, since the features are named similarly, but in this case I'd have to enable one but not the other...
