### ISSUE TITLE
[Improvement] vk.xml improvement proposal

### ISSUE THREAD

**Issue by realitix** [KhronosGroup/Vulkan-Docs#401]
Hello,
I am building a Python binding to Vulkan ([here](https://github.com/realitix/cvulkan)).
To proceed, I import `vk_plateform.h` and` vulkan.h`, then I use` vk.xml` to create the binding.

I do a lot of parsing in the vk.xml file and I have a proposal to improve this spec in order to simplify its analysis.

# Context
In a `struct`, if there is an array of known size, there are two ways to see it.

## 1 - Enum way
```
<type category="struct" name="VkPhysicalDeviceProperties" returnedonly="true">
    ...
    <member><type>char</type> <name>deviceName</name>[<enum>VK_MAX_PHYSICAL_DEVICE_NAME_SIZE</enum>]</member>
    <member><type>uint8_t</type> <name>pipelineCacheUUID</name>[<enum>VK_UUID_SIZE</enum>]</member>
     ...
</type>
```
In this first example, you can see that `deviceName` and `pipelineCacheUUID` are fixed size array of value `VK_MAX_PHYSICAL_DEVICE_NAME_SIZE` and `VK_UUID_SIZE`.

Parsing this `struct` is easy thanks to the `<enum></enum>`.

## 2 - Literal way
```
<type category="struct" name="VkImageBlit">
    ...
    <member><type>VkOffset3D</type> <name>dstOffsets</name>[2]</member>
</type>
```
In this example, you can see that `dstOffsets` is an array of size 2.

# What's the point ?
If you take a closer look, you can see a major difference, **`enum` size is surrounded by `<enum></enum>` and literal size is surrounded by… nothing.**

I can assure you that it's harder to parse the file that way, here my proposal.

# Proposal
Like for enum, we could surround literal value by `<litteral></litteral>`. It would look like that:
```
<type category="struct" name="VkImageBlit">
    ...
    <member><type>VkOffset3D</type> <name>dstOffsets</name>[<litteral>2</litteral>]</member>
</type>
```
If you think this is a good idea, I'm ready for the pull request.

_Thanks,
_Jean-Sébastien B.__

**Comment by krOoze** [comment]
Funny thing is `VK_MAX_PHYSICAL_DEVICE_NAME_SIZE` is also a literal  (it is a C macro). So probably shouldn't use `<enum>`.

**Comment by realitix** [comment]
You are write, it would offer more information on the underlying value. I took this one ramdomly.

**Comment by ratchetfreak** [comment]
There is an argument to be made to change the notation to be less C like in general and instead use the attributes to communicate the specifics instead of the current pseudo-C syntax. 

But that's been shot down a few times already.

**Comment by realitix** [comment]
I don't argue about the naming convention here but about a missing information.

**Comment by FacticiusVir** [comment]
Having worked through this for the C# bindings, this is probably one of the less awkward things you have to parse to read the spec :-D

It makes somewhat more sense if you don't read the declarations as structured XML - they're much more like XHTML, with decorators around enums or types that point you to look-ups in the spec (as in, you can scan for the `<enum>` or `<type>` elements with those names). No such look-up exists for literals, and if you're looking to parse the text it's not complex (depending on your XML reader, I concede) to distinguish a continuous text node "[2]" after the name element, and a pair of text nodes ("[", "]") wrapping an enum element.

If this is causing a real hassle for you, you might want to look at (or potentially contribute to) @NicolBolas [New Vulkan XML Format](https://github.com/NicolBolas/New-Vulkan-XML-Format) project.

**Comment by ratchetfreak** [comment]
it's technically not "missing" information. you could treat the [ and ] as `<staticArraySize>` and `</staticArraySize>`  resp.

which would turn the entire thing into valid and parsable xml:

```XML
    <member><type>char</type> <name>deviceName</name><staticArraySize><enum>VK_MAX_PHYSICAL_DEVICE_NAME_SIZE</enum></staticArraySize></member>
    <member><type>uint8_t</type> <name>pipelineCacheUUID</name><staticArraySize><enum>VK_UUID_SIZE</enum></staticArraySize></member>
```

and 

```XML
    <member><type>VkOffset3D</type> <name>dstOffsets</name><staticArraySize>2</staticArraySize></member>
```

**Comment by krOoze** [comment]
@FacticiusVir ninja'd. Just wanted to note `vk.xml` has permisive licence and it has been forked.

**Comment by realitix** [comment]
Indeed it's not a big hassle, but I think it would be clearer. 
@FacticiusVir What are the awkward things to you ?

**Comment by NicolBolas** [comment]
@realitix I can't say what precisely has been awkward with vk.xml parsing for him, but I do know what was awkward for me [when I built my new version of that file](https://github.com/NicolBolas/New-Vulkan-XML-Format).

The difference between parsing `<type kind="funcpointer">` vs. `<command>` tags is pretty significant. While they both use that annoying inline markup style, `funcpointer` doesn't wrap the parameter names in a `name` tag, which forces you to do more involved string parsing.

Speaking of string parsing, parsing type definitions (whether in function parameters or structs) is difficult thanks to C's rules.

There's also an unfortunate issue with `enum` tags. In most cases, an `enum` represents a genuine collection of values. But in a few cases, they're used to represent constants. And you have to know how to tell which is which. They use the same XML tag because the C-based processor will generate code with them the same way. But even a C++11-aware processor will have to jump through a bunch of hoops to figure out if you meant to have a real enumeration or a #define or `constexpr` variable.

These are hardly insurmountable problems. But they are highly annoying when generating things based on vk.xml.

But in any case, this issue is a duplicate of #210. The powers-that-be have made it abundantly clear that they're not going to be making any significant alterations to the format.

**Comment by FacticiusVir** [comment]
The most notable pain I've had is parsing some len fields; consider:
`<member len="latexmath:[$codeSize \over 4$]">const <type>uint32_t</type>*            <name>pCode</name></member>` ([here](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L782))
or
`<member optional="true" len="latexmath:[$\lceil{\mathit{rasterizationSamples} \over 32}\rceil$]">const <type>VkSampleMask</type>*    <name>pSampleMask</name></member>` ([here](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L910))
where code is represented in LaTeX Math, which I have to parse to manage array-passing.

Also, as @NicolBolas points out, funcpointers are a format unto themselves.

**Comment by realitix** [comment]
Thanks @NicolBolas I didn't see the #210 
@FacticiusVir My eyes are crying!
I close this issue because it's a duplicate.
