### ISSUE TITLE
VK_EXT_debug_marker steals VK_EXT_debug_report's VkDebugReportObjectTypeEXT

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#409]
`VK_EXT_debug_report` extension adds `VkDebugReportObjectTypeEXT` per C.4. VK_EXT_debug_report chaper.

1)
`VK_EXT_debug_marker` extension also uses `VkDebugReportObjectTypeEXT`. But it is not listed in C.3. VK_EXT_debug_marker chapter, nor is there some note or dependency explaining that use.

Is it correct to just implicitly use entities declared by lower numbered extension?

2)
The `VkDebugReportObjectTypeEXT` specification is included to the `VK_EXT_debug_marker.txt` which is gated in the single branch model.

If only `VK_EXT_debug_report` but not `VK_EXT_debug_marker` is specified (e.g. with `makeExt VK_EXT_debug_report`) the `VkDebugReportObjectTypeEXT` might not appear in the spec text as it should (EDIT: tested it; it is indeed missing it).

**Comment by baldurk** [comment]
I think the lack of an enum definition in the `VK_EXT_debug_report` chapter is because `VK_EXT_debug_report.txt` doesn't have `include::../api/enums/VkDebugReportObjectTypeEXT.txt[]` which I put in for `VK_EXT_debug_marker`. I don't think it's because the enum is used in both extensions.

I'm not sure how inter-extension dependencies will work in general, but from a pragmatic point of view solving this particular problem would probably just need an include of the enum in both places and allow the spec text to have a little bit of duplication. You'd also want to move the [meanings of the values I added](https://github.com/KhronosGroup/Vulkan-Docs/blob/6cdc56d0d73ec65f1cd2db2afafe9aad781fc5b7/doc/specs/vulkan/chapters/VK_EXT_debug_marker.txt#L119-L163) to a common include as well.

To be pedantic, maybe a line under the dependencies of `VK_EXT_debug_marker` in C.3 saying the enum is reused from `VK_EXT_debug_report`, but I don't think anyone is confused as to what's going on without that line.

**Comment by krOoze** [comment]
I can understand pragmatic points. But luckily I am not the one that has to fix such things :satisfied:

I think higher number extension has the responsibility not to break previous ones. So quick fix would be to include it in `VK_EXT_debug_report.txt` and also have it in `VK_EXT_debug_marker.txt` but with `ifndef VK_EXT_debug_report` gate.

> I don't think anyone is confused as to what's going on without that line.

People tend **not** to be confused until stuff stops working. It sure is not serious (at least unless there are 10s of extensions doing that) and with using official `vulkan.h`.

Someone autogenerating from `vk.xml` might be surprised that extensions may use each others structures and enums without that being stated anywhere.

Or someone with unofficial `vulkan.h` using `#IFDEF VK_EXT_debug_marker` might be surprised why all structures neede by the extension are not defined.

Those are rare corner cases. Still should be specified at some point to have full coverage.

**Comment by oddhack** [comment]
@baldurk please propose an internal MR when you've sorted out a path forward in this particular case. If the extension is unusable without an interface defined by another extension, there should be an explicit dependency on the other.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.40 spec update.
