### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#41]
I suggest to reuse a higher level build system than [your current make file](https://github.com/KhronosGroup/Vulkan-Docs/blob/7e195e846e9b3d7b91c2fe57406a97288261fc5e/doc/specs/vulkan/Makefile#L1 "Update candidate") so that powerful checks for [software features](https://github.com/KhronosGroup/Vulkan-Docs/issues/22 "Various software dependencies") will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by oddhack** [comment]
Please feel free to propose one in a PR so people can evaluate it. The current makefile does what it needs to do on all the platforms we need to do it on, so we're not feeling any immediate pressure to change it (I won't say it's elegant, because it isn't).

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by oddhack** [comment]
When there's someone trying to build the Vulkan spec in an environment which can't use GNU make, then they'll have an actual problem - and hopefully, will propose an actual solution in a form other people can evaluate. Personally I think cmake / automake / etc. are massive overkill for a "build system" of the very low complexity we have in the Vulkan tree, but if people need those tools, they should tell us about the specifics that lead them to need the tools. Since the repository builds on Linux, Windows, and MacOS X, we think we've covered the vast majority of use cases already. At the point someone has a full LaTeX, dblatex, asciidoc etc. install available on Android or iOS, we might think about supporting those too.
