### ISSUE TITLE
Question: can vkCmdBlitImage support blending too? 

### ISSUE THREAD

**Issue by annehur** [KhronosGroup/Vulkan-Docs#433]
Hi, 
Vulkan is hard, but it is FUN language.  Thank you for your efforts.
 
This is my question and request that you might concern on.
vkCmdBlitImage supports blit and stretchblit (with LINEAR, NEAREST filter). 
Can vkCmdBlitImage support blending too? 

Because, I think that a developer might not make the best performance on blending blit functionality. 
Web community seems like interesting on Vulkan. This function can be helpful.

-------------------------------------------
I ran performance test on blit operation.
If there was no blend, I used vkCmdBlitImage. The performance was okay. 

But if there was blend, I setup pipeline to render it. The performance was much lower than I expected. (about > 2.3x)
I guess that excellent engineer can make it better.
On the other hands,  I also think how much this simple blending can be differently made. 

Since developers can not expect driver MAGIC like openGL, could you consider that this transfer function shows magic? 

-Hyejung Hur

**Comment by NicolBolas** [comment]
> Since developers can not expect driver MAGIC like openGL, could you consider that this transfer function shows magic?

This request seems confused. On the one hand, you recognize that Vulkan is trying to be lower-level than OpenGL. But on the other, you want something higher-level like OpenGL.

Blending and copying are different operations to Vulkan. They are in fact _so different_ that `vkCmdBlitImage` can execute on any kind of queue, while blending is a rendering operation, thus requiring a graphics queue.

The performance for blending is lower than blitting because blending involves more operations than blitting. One is an interpolated copy; the other is a read/modify/write. There is no "MAGIC" that's going to change that fact.

What you're basically wanting is for the driver to do the work for you. And that's just not what Vulkan is all about.

**Comment by annehur** [comment]
> What you're basically wanting is for the driver to do the work for you. And that's just not what Vulkan is all about.
First, I knew what the paradigm of Vulkan is. So I somehow agree with you. 

Actually, I did not expect vkCmdBlitImage function from Vulkan. 
But Vulkan has vkCmdBlitImage, which is a kind of high-level function.
That's why I request. 

> Blending and copying are different operations to Vulkan. They are in fact so different that vkCmdBlitImage can execute on any kind of queue, while blending is a rendering operation, thus requiring a graphics queue.

Yes, they are different operation-which one is on transfer, the other is on graphics as you said. 
However, both involve computation-based.
For example,  stretch blit applies filter(nearest/linear) because of size difference. 
If driver can directly access both pixels from two images, we can add blending math too. 
That is what I think. 
So I thought that supporting blending with vkCmdBlitImage is not big deal. 

Additionally, I expect that GPU Device driver developers can make better performance than me.

**Comment by NicolBolas** [comment]
First, I made a mistake earlier. `vkCmdBlitImage` does require a graphics queue. It has a "pipeline type" of transfer (meaning that it uses the `PIPELINE_STAGE_TRANSFER`), but it only executes on a graphics-capable queue.

> But Vulkan has vkCmdBlitImage, which is a kind of high-level function.

It is not a high-level function. It's not provoking a rendering operation or anything. It's a pixel transfer function, a basic part of lots of hardware.

And yes, stretching during blitting is a basic part of hardware, and it has been since the late VGA days at least. Linear interpolation as part of that stretching may be new, but even DirectDraw had non-linear stretch-blit as a basic operation.

> If driver can directly access both pixels from two images

But it's not reading "from two images"; it's only reading *from the source*. It's *writing* to the destination.

**Comment by annehur** [comment]
Thank you for your comments.
 
Let me ask other way. 
Do you think blending-blit can be different between developers or do you think developer can make optimize differently about  blending-blit? 
If it is almost same, then why do we think about having this as base api function?

**Comment by NicolBolas** [comment]
> Do you think blending-blit can be different between developers or do you think developer can make optimize differently about blending-blit?

I don't think that's the question that matters when it comes to Vulkan. What matters is whether "blending blit" is functionality directly implemented by most hardware. If it is, then we should have such an API. If it is not, then you should build it yourself.

The argument you put forth is one that could be applied to any number of blitting features. You could argue that rotated-blit could be more optimal if the implementers wrote it. Color-key-blits too. And what about tinted-blit; I'm sure implementers could make those go faster than user-provided pipelines and shaders and such.

Vulkan is intended to be low-level. It exposes what common hardware does; that's the cut-off point for features. Stretch-blit is something that common hardware does. Blended-blit is not.

**Comment by annehur** [comment]
Ok. I got it. Thank you.

**Comment by oddhack** [comment]
Closing - we don't plan to support blending as part of blits.
