### ISSUE TITLE
Directory tree is confusing

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#436]
As a newbie to this repo I always had serious dissonance about how the directories are named and always clicked the wrong one.

In `doc` I would expect project documentation, not sources.
In `src` I would expect project sources, not only the registry and not generated outputs/headers and not related consumable utils.
`spec` and `vulkan` (under `src`) always sounded same to me and also not really matching the content.

If there ever is a breaking change (possibly #434 ), would you also consider using that opportunity to refining the directory structure?

Maybe something like:
`doc` - styleguide and conventions and such - should perhaps be prebuilt
`doc/src` - sources for the above
`src/spec` - the asciidoc sources of the specification
`src/registry`, maybe just `registry` - the xml registry
`src/tools`, maybe just `tools` - all the build scripts
`/Makefile`
`out/spec` - the built specification text
`out/bindingspec/shaderlangs/GLSL/GL_KHR_vulkan_glsl.txt` - example how other built specs could be placed
`out/include/vulkan` - the headers
`out/util` - programs for user consumption e.g. the ext loader

**Comment by oddhack** [comment]
It would cause some disruption among current users of the spec. But the tree structure is more complex than need be, and if we do something significantly disruptive in other ways, this is worth looking at.

N.b. we will be migrating to an asciidoctor toolchain in the next public update. That's disruptive in other ways since people have to install a whole bunch of Ruby packages and get used to it, but it doesn't change the tree structure.

**Comment by TobiasHector** [comment]
Yea I had some idea to look at this as well - ideally to something more like what most common Git projects use with most stuff at a top level and other stuff in as flat a structure as possible.

E.g. https://github.com/asciidoctor/asciidoctor

It's going to be a bit weird compared to other things because we're building documentation, and we have multiple "sources" - the asciidoc text and the registry - but I'm sure we can come up with something better.

**Comment by oddhack** [comment]
@tobias I would certainly prefer not to be typing '../../../out/1.0/html/' so much :-)

**Comment by oddhack** [comment]
Re

> out/bindingspec/shaderlangs/GLSL/GL_KHR_vulkan_glsl.txt - example how other built specs could be placed

This file really doesn't exactly *belong* anywhere we can figure - it's not an actual GL extension so shouldn't go in the GL registry, it's not part of the Vulkan API, it's not a SPIR-V extension - best we could figure was just to stick it in some random corner of the tree. For publication it gets copied out to the registry backing repo along with the generated spec documents. The OUTDIR stuff is just a cache for local copies, not where things ever get published or checked in. It could just as well be in /tmp or ./out or anywhere else people want to put tmpfiles.

**Comment by TobiasHector** [comment]
> This file really doesn't exactly belong anywhere we can figure - it's not an actual GL extension so shouldn't go in the GL registry, it's not part of the Vulkan API, it's not a SPIR-V extension - best we could figure was just to stick it in some random corner of the tree. For publication it gets copied out to the registry backing repo along with the generated spec documents. The OUTDIR stuff is just used as a place to put locally generated files that aren't going to be checked in. It could just as well be in /tmp or ./out or anywhere else people want to put tmpfiles.

I'm still kind of in the mindset that this should just go sit with GLSLang - since that is the only thing that actually implements it. It's not like GLSLang is a closed source external thing; it's under the KhronosGroup after all. It's not like people edit SPIR-V and Vulkan in the same repo, so no enormous reason to keep it in the Vulkan-Docs repo IMO. Something we need to discuss internally I suppose though.

**Comment by oddhack** [comment]
@krOoze we're thinking of reorganizing like this:

Files                     | Move To
--------------------------|---------------------
/doc/specs/vulkan/*       |  /...
src/spec/*                |  /xml/...
src/vulkan/*              |  /include/vulkan/...
src/ext_loader/*          |  /src/ext_loader/...
generated specs/ref pages |  /out/...

If that suits we'll move forward on that basis. We have a bunch of internal branches that we'll have to convince ourselves will do the right thing when the branch they're targeting moves everything around under them, but hopefully git is smart enough for that to just work, modulo any new files introduced by the MRs.

**Comment by Tobski** [comment]
> It does make the root directory "busy".

For this in particular, we'd probably want to move most of the scripts out of root and into /scripts, leaving the root relatively uncluttered.

**Comment by oddhack** [comment]
We've done the major reorganization in the 1.1.72 release. In the future we'll probably migrate the scripts in the top-level directory into a subdirectory to make it a bit cleaner, but this was the bulk of the work, and everything seems to build / generate properly now (cross fingers).
