### ISSUE TITLE
Epub document format

### ISSUE THREAD

**Issue by janix** [KhronosGroup/Vulkan-Docs#450]
I'm trying to create specification document in epub format.
I've added some lines of code to Makefile:
https://github.com/janix/Vulkan-Docs/commit/ab1fc4f128f6e24d596e5aa93d3cd38c3a592f54
but it seems to formatting is far from correct (equations/code) and images are missing.

Will be support for epub files in the future?

**Comment by oddhack** [comment]
Math support in the HTML5 target requires KaTeX be available at runtime in the browser. I don't know much about epub. If the epub specification requires that readers of the packaged HTML be able to execute arbitrary JavaScript, maybe you could wire up the KaTeX distribution that is included with Vulkan-Docs to make that happen. Otherwise a more arcane process would be required to generate SVGs at build time and include those in the epub. Either way, this isn't something we have planned - but if you can figure it out and contribute the build changes back, that would be great.

**Comment by oddhack** [comment]
Oh, need to add that we are migrating from asciidoc to asciidoctor toolchain in the spec update coming this week. It's possible that epub support will be better in asciidoctor; at least, it is actively maintained unlike asciidoc.

**Comment by janix** [comment]
Thank you for your response.
