### ISSUE TITLE
rebase extension branches to the main 1.0 branch

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/Vulkan-Docs#46]
This gives them a common history so they can be diffed in github.

It also allows for consistency when the main branch fixed minor issues they can be pushed to the extension branches .

**Comment by oddhack** [comment]
Yes, we should do that. I'm overwhelmed with internal and external post-release matters but hope to get to it soon (since I seem to have ended up as the de-facto git wrangler for the group, at least for the time being).

**Comment by oddhack** [comment]
@ratchetfreak maybe you could advise me on this, as I'm not a git power user yet. When we exported from our  internal git repository, we stripped the pre-release development history from each branch, and in the process ended up with the extension branches on github not actually sharing common history with each other or the 1.0 branch (I'm certain there was a better way to do that, but it was three hours before release and I was more interested in getting it out than getting at perfect).

Of course, at this point when I try rebasing 1.0-extension-name onto 1.0, I just get a conflict-per-file-difference which has to be walked through tediously by hand. Trying to figure how to do this efficiently now. I'm sure there are git recipes to accomplish it that would be better than the manual diff - delete branch - checkout replacement branch based on 1.0 - apply patch that is the fallback option. Any suggestions?

**Comment by philiptaylor** [comment]
I think you want something like:

    git checkout 1.0-VK_EXT_debug_report
    git reset --soft v1.0-core-20160216
    git commit

("git reset --soft" changes your current HEAD to the specified commit, without modifying your working tree / index. The new commit will include all the differences from that specified commit to your index, i.e. you'll end up with the same files as the original extension branch but with the new history.)

Then I guess either

    git rebase 1.0

or

    git merge 1.0

depending on whether you want the extension branch to be exactly the same as the latest 1.0 plus an extra commit, or whether you want a complicated tangled history of merges.

Then force-push like

    git push origin +1.0-VK_EXT_debug_report

**Comment by salamanderrake** [comment]
@oddhack you could try to use git checkout --orphan using the comment versions you wanted to start with, you could also git diff between each branch against the 1.0 branch creating patches for each branch, then delete the other branches and recreate them by branching directly from 1.0 and applying the patches to them, then push them upstream.

`--orphan <new_branch>
Create a new orphan branch, named <new_branch>, started from <start_point> and switch to it. The first commit made on this new branch will have no parents and it will be the root of a new history totally disconnected from all the other branches and commits.

The index and the working tree are adjusted as if you had previously run "git checkout <start_point>". This allows you to start a new history that records a set of paths similar to <start_point> by easily running "git commit -a" to make the root commit.

This can be useful when you want to publish the tree from a commit without exposing its full history. You might want to do this to publish an open source branch of a project whose current tree is "clean", but whose full history contains proprietary or otherwise encumbered bits of code.

If you want to start a disconnected history that records a set of paths that is totally different from the one of <start_point>, then you should clear the index and the working tree right after creating the orphan branch by running "git rm -rf ." from the top level of the working tree. Afterwards you will be ready to prepare your new files, repopulating the working tree, by copying them from elsewhere, extracting a tarball, etc.

`

git diff example: Sorry its really over complicated, but it works if you want to remove the history of a branch.

`
git checkout 1.0-VK_KHR_xcb_surface
git diff 1.0 > ../1.0-VK_KHR_xcb_surface.patch
git checkout 1.0
git branch -D 1.0-VK_KHR_xcb_surface
git push origin :1.0-VK_KHR_xcb_surface
git branch 1.0-VK_KHR_xcb_surface
git checkout 1.0-VK_KHR_xcb_surface
patch -p1 -i ../1.0-VK_KHR_xcb_surface.patch
git add -A
git commit -a -m "some comment code"
git push origin 1.0-VK_KHR_xcb_surface
`

**Comment by salamanderrake** [comment]
Warning, sorry I should have put it in my previous post

git push origin :1.0-VK_KHR_xcb_surface deletes the remote branch, aka off of github
git branch -D 1.0-VK_KHR_xcb_surface deletes the local branch.

**Comment by oddhack** [comment]
@ratchetfreak at this point I believe all the extension branches have been rebased on 1.0. Let me know if you see anything weird.

@philiptaylor @salamanderrake thanks for the tips. I went down the reset --soft path which worked fine (AFAICT).
