### ISSUE TITLE
Command buffer Invalid state definition

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#469]
Currently it says:

> Some operations, such as modifying or deleting a resource that was used in a command recorded to a command buffer, will transition the state of a command buffer into the _invalid state_. This state is largely equivalent to the _initial state_, except that resources are still associated with it. Command buffers in the _invalid state_ **can** only be reset, moved to the recording state, or freed.

1) _initial state_ cmdbuffers might hold onto resources too:

> If `flags` includes `VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT`, then most or all memory resources currently owned by the command buffer **should** be returned to the parent command pool. If this flag is not set, then the command buffer **may** hold onto memory resources and reuse them when recording commands. commandBuffer is moved to the initial state.

2) Does it mean invalidated buffer **must** hold onto its resources?

Would it make sense to allow invalid state to release resources too? If the implementation does not intend to keep the resources on `vkResetCommandBuffer` anyway, wouldn't it make sense to allow it to potentially release them sooner if it can detect a buffer going into invalid state?

**Comment by TobiasHector** [comment]
Yea this is sloppy wording on my part. If you assume that a command buffer is/includes a "stack"-like allocation, and every command offsets into the stack, then moving to invalid will (probably) not reset the offset, whereas a reset always should. That is sort of the "resource release" I was thinking of.

Agree I need to be a little vaguer here, unfortunately :) Changing "are still associated" to "may: still be associated" is probably the minimum change here, roughly as you suggest - though in practice such "detection" feels like it would just add overhead to a driver rather than saving anything.

I kind of feel like I need to just remove the association to initial state though, because really it just feels quite sloppy.

**Comment by TobiasHector** [comment]
Yea in fact I've just deleted the sentence about being like initial. It is just extra words that are non-functional at best.

**Comment by krOoze** [comment]
> though in practice such "detection" feels like it would just add overhead to a driver rather than saving anything.

Well adding "may" only lifts a restriction, so implementation can do whatever it feels is better.

I don't feel qualified to discuss if some driver can exploit that. I just imagined naively it may be possible; i.e. reseting secondary could recycle the invalidated primary in one go. I guess though there should be no advantage if user does it explicitly (which is the way that should be encouraged).

**Comment by TobiasHector** [comment]
> I don't feel qualified to discuss if some driver can exploit that. I just imagined naively it may be possible; i.e. reseting secondary could recycle the invalidated primary in one go. I guess though there should be no advantage if user does it explicitly anyway (which is the way that should be encouraged).

Yea it's pretty irrelevant I suppose. I think just deleting the linking statement and saying *nothing* about it is the best solution anyway :) - there's other language already handling that for the rest of the spec. Invalid basically means "could be in any state internally but it is recoverable" - which may or may not include some resources being freed.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.44 spec update.
