### ISSUE TITLE
Exposing more debugging/profiling functionality in the next version

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/Vulkan-Docs#485]
Is it possible to have more debugging facilities in vulkan in the next update? Not so much like the layers, though they are great. I was hoping functionality like being able to step through shaders and the like would be great. Historically, GL has been dependent on vendors to release some kind of debugging tool. Rather than relying solely on the vendor, exposing debugging functionality would greatly benefit the vulkan tools ecosystem. If possible, I'd like it to be in the main spec. 

On a side note, is VK_NVX_device_generated_commands going to make it in the next version?

**Comment by NicolBolas** [comment]
The specification defines the behavior of the system. Debugging is an issue that happens outside of the Vulkan system's behavior.

The reason debugging is dependent on vendors is because debugging is *dependent on vendors*. They're the ones with the hardware, so those are the ones who can actually expose some kind of debugging functionality. They are the gate keepers of the hardware.

The best that might be able to happen is that LunarG would get with the vendors and come up with some internal API for exposing debugging functionality. But even that would have to be optional to some degree, because not all vendors have the time or inclination to do so. And Vulkan adoption will not be served by making vendors do *more* work rather than less.

**Comment by Novum** [comment]
https://renderdoc.org/ provides some Vulkan debugging, just in case this is not general knowledge.

**Comment by oddhack** [comment]
With occasional exceptions such as planned presentations at major conferences, we will not be discussing features of future Vulkan versions in public until they're actually available. Sorry.

There isn't any plan for a Khronos-defined and supplied interactive debugging tool at present, as far as I know. There are some extensions developed for the loader and validation layers which provide additional information beyond base Vulkan 1.0, but the sort of step-by-step debugger you're asking about is far beyond that scope.

**Comment by edrickhong** [comment]
I understand not having it in the main spec but I do feel better tools will help Vukan adoption by developers greatly. Historically vendors do not have the best track record for supplying gl tools or their tools aren't available on all platforms. I feel that many of the tools for gl are often supplied by 3rd parties like renderdoc. I think it's worth looking into this to enabling vulkan tool developers.
