### ISSUE TITLE
2.1. Execution Model, typo "device local" mentioned twice

### ISSUE THREAD

**Issue by codepilot** [KhronosGroup/Vulkan-Docs#5]
The following paragraph has "device local" mentioned twice, it may need to be stricken or changed.

Examples of memory areas that may be available on an implementation include device local (memory that is physically connected to the device)~~, device local~~, host visible (device local memory that is visible to the host) and host local, host visible (memory that is local to the host and visible to the device and host). On other architectures, there may only be a single heap that can be used for any purpose.

**Comment by philiptaylor** [comment]
I think that's actually a list of 3 items with no duplicates:

* device local
* device local, host visible
* host local, host visible

But it's written as a comma-separated list, and the only difference between the comma separators and the commas inside the terms is that the latter are italic commas.

Perhaps it would be clearer to avoid the commas and write it like "<em>device local and host visible</em>" or "<em>device local host visible</em>".

**Comment by oddhack** [comment]
We just finished deciding to use the Oxford comma, too :-) I'll suggest we put in semicolons between the clauses to make the categories more clear. Thanks!

**Comment by oddhack** [comment]
Accepted inside Khronos - due to our internal publication processes, it will take some time to filter out to the public repo, but the fix is in. The new asciidoc code is:

"... Examples of memory areas that may: be available on
an implementation include:

  * _device local_ is memory that is physically connected to the device.
  * _device local, host visible_ is device local memory that is visible to
    the host.
  * _host local, host visible_ is memory that is local to the host and
    visible to the device and host.

On other architectures, there may: only be a single heap that can: be used
for any purpose."
