### ISSUE TITLE
Querying emulated/native feature support

### ISSUE THREAD

**Issue by hesiod** [KhronosGroup/Vulkan-Docs#519]
As we all know, every GPU has a fixed set of features that it supports natively. While some graphics API features can only be implemented with actual GPU support, a lot of things can be emulated by the driver. Typical examples of this would be compressed texture support (almost all GPUs only support one natively, drivers usually emulate support for the others using manual conversions behind the scenes) and support for certain data types in shaders, e.g. float64 and int64, which can be implemented using software arithmetic in shaders. Usually, these “emulated” features perform significantly worse than their natively support counterparts.

Similarly, there are sometimes situations in which the GPU prefers certain situations. Consider memory heaps: There may be multiple memory heaps marked as device local. In practice, a certain heap might be preferred for various reasons and the application would ideally pick the preferred heap first. Another example might be certain AMD graphics cards which only use a D32_SFLOAT_S8_UINT depth/stencil buffer behind the scenes IIRC. While an application should usually refrain from selecting a depth buffer with unneeded precision, in that specific case it might as well choose the 32-bit depth buffer.

Now, all those problems could be solved by keeping a database for GPU-specific quirks and intricacies, but such an approach would not work well with newly released GPUs or lesser known models. Furthermore, the GPU vendor usually knows what is best for the GPU and could expose those details via a common API.

You can see where I’m going here: Might a Vulkan extension exposing something similar to VkPhysicalDeviceFeatures be a good place for this kind of information? Or perhaps more generally, is this issue significant enough to warrant a common interface (or am I overthinking this a bit)?​

**Comment by krOoze** [comment]
There are probably some grey areas of what would you consider "native". Is decoding compressed format using a compute shader "native", or not?

In some cases the GPU may even have native support in HW, but it may be such bottleneck for your needs that it would be completely useless to you. As such I would consider "nativity" a useless concept.

That being said, IMO vendors should be discouraged to emulate a feature in a way that would be no better that what the App maker can implement (i.e. fully software/on CPU emulation). IMO Vulkan core does not require **that** much to resort to extensive emulation on modern GPUs.

> Another example might be certain AMD graphics cards which only use a D32_SFLOAT_S8_UINT depth/stencil buffer behind the scenes IIRC. While an application should usually refrain from selecting a depth buffer with unneeded precision, in that specific case it might as well choose the 32-bit depth buffer.

In this particular case the Vulkan spec explicitly prohibit such interchangability:

> [...] implementations **must** not substitute a different depth or stencil precision than that described in the format (e.g. D16 **must** not be implemented as D24 or D32).

> You can see where I’m going here: Might a Vulkan extension exposing something similar to VkPhysicalDeviceFeatures be a good place for this kind of information? Or perhaps more generally, is this issue significant enough to warrant a common interface (or am I overthinking this a bit)?​

My imagination fails to see how this would work. The maximum I can imagine is some pair of feature and five star rating; and that is not much useful.

**Comment by NicolBolas** [comment]
Almost everything you have talked about, from compressed texture support to particular depth formats to the ability to use 64-bit integers and floats, are all *queryable* constructs. You can ask implementations what compressed formats they allow, and the Vulkan specification requires only that implementations support one set of them (since all applicable hardware supports at least one set). Implementations are allowed to specify that they cannot support 24-bit fixed point depth buffers (and AMD's hardware does). Vulkan only requires that implementations support 24-bit fixed point *or* 32-bit float, but not necessarily both. And 64-bit shader support is an optional feature; the user has to ask for it, and devices can choose not to support it.

Could Vulkan implementations choose to advertise these features, even if their hardware can't actually do them? Sure. But *why would they*? It would be inviting people to make their hardware look bad by throwing them off the fast path. There's almost no reason why an IHV would want to emulate something that would be slow.

Vulkan is a low-level API. It has numerous APIs for querying exact what an implementation can do. The de-facto contract we have with IHVs is that they do not *lie* to users about these things. If they support something, then that is a first-class feature of their system.

So unless there is evidence of widespread breaking of this contract, this seems to be a solution in search of a problem.

**Comment by timofonic** [comment]
@hesiod @krOoze @NicolBolas Any news?

**Comment by TomOlson** [comment]
Thanks all for this discussion. This general area is something the Vulkan WG thinks about a lot. We don't like putting developers through caps bit hell, so we do try to minimize the amount of functionality that is guarded by features and limits. However, we *really* hate making developers spend time avoiding slow paths, so we try even harder not to give IHVs reasons to claim support for features they don't support *well*.  On very rare occasions we will ask an IHV to support (i.e. emulate) a feature that doesn't provide any benefit on their implementation, but we do this only if most implementations *do* benefit, *and* emulating adds no significant performance penalty or surprising performance cliff, *and* if working around lack of the feature in the app would be horribly complex and painful. I stress that it's *very* rare that we do this. Vulkan is supposed to be a "no driver magic" API and we try hard to keep it that way.

@krOoze and @NicolBolas make good points about why it would be hard to expose these decisions in the API, so I'm going to close this issue for now. If in future you or anyone else see cases of harmful emulations creeping into implementations, please do raise them as issues here or in [Vulkan-Ecosystem](https://github.com/KhronosGroup/Vulkan-Ecosystem). We don't think this problem can ever be definitively solved - it can only be managed. We will keep trying to do that, and we really appreciate your help in identifying problems.
