### ISSUE TITLE
LocalInvocationIndex SPIR-V decoration in Vulkan

### ISSUE THREAD

**Issue by jozefkucia** [KhronosGroup/Vulkan-Docs#532]
Vulkan spec doesn't mention `LocalInvocationIndex` decoration. Does it mean that Vulkan doesn't allow using this decoration, or is it simply an omission?

**Comment by johnkslang** [comment]
At first look, this does appear to be an omission. Looking internally in Khronos at adding.  It should be the linearized form of `LocalInvocationId`.

**Comment by TobiasHector** [comment]
Hum, it doesn't mention LocalInvocationId either? Both of these are *Core* SPIRV 1.0 though - and the Vulkan spec says it supports core SPIRV, with exceptions to that raised in the environment spec. There's plenty of other SPIRV ops that aren't called out in the Vulkan spec as well - none of the math ops for example.

For the most part, Vulkan only calls out individual operands when it needs to link things to API constructs, as examples, or when there are restrictions on those specific operands. Otherwise it's either core (and thus works) or is behind a capability (the Vulkan spec calls out in the environment appendix which are supported).

I don't think there's a bug here?

**Comment by johnkslang** [comment]
There is section 14.6 describing each "Built-In Variable".  It includes this:

> `LocalInvocationId`
>
> Decorating a variable with the `LocalInvocationId` built-in decoration will make that variable contain the location of the current compute shader invocation within the local workgroup. Each component ranges from zero through to the size of the workgroup in that dimension minus one.
>
>The `LocalInvocationId` decoration must be used only within compute shaders.
>
>The variable decorated with `LocalInvocationId` must be declared using the Input storage class.
>
>The variable decorated with `LocalInvocationId` must be declared as a three-component vector of 32-bit integers.
>
> *Note*
>
> If the size of the workgroup in a particular dimension is one, then the `LocalInvocationId` in that dimension will be zero. If the workgroup is effectively two-dimensional, then `LocalInvocationId.z` will be zero. If the workgroup is effectively one-dimensional, then both `LocalInvocationId.y` and `LocalInvocationId.z` will be zero.

**Comment by jozefkucia** [comment]
Built-in variables are described in the Vulkan spec. `LocalInvocationIndex` seems to be the only exception.

Additionally, the SPIR-V spec text for `LocalInvocationIndex` says:

> See Vulkan or OpenGL API specifications for more detail.

**Comment by TobiasHector** [comment]
Ugh I couldn't find that when I grep'd for it before. Well, my bad. Kind of annoying that we have to list *all* the built-ins though, seems like SPIRV could probably have dealt with at least some of these...

**Comment by oddhack** [comment]
This should be fixed in the 1.1.71 spec update.
