### ISSUE TITLE
Some cleanups, clarifications and fixes to Synchronization page

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/Vulkan-Docs#537]
I didn't find a way to make a PR against the Wiki repo, but I made a readily appliable patch, please review and apply as you see fit.
https://gist.github.com/HansKristian-ARM/b36e4568620b97d81612e916065a16d7.

Some extra clarifying comments were added which might be useful.

VK_IMAGE_LAYOUT_PRESENT_SRC_KHR was not used, fixed that ...

I somewhat rewrote the queue ownership transfer example as the spec states that if you do not require content to be valid, no transfer is necessary. The example transitions from UNDEFINED which already means any queue transfer is redundant.

**Comment by TobiasHector** [comment]
Incorporated as of the latest version - thanks! I made a couple of minor tweaks but nothing beyond typos, formatting issues and an extraneous QueueSubmit.

I forgot about the fact you could ignore a queue transfer - doh. And the present layout I thought existed but couldn't find it - must've been looking at the core spec instead of the extension one :/

Thanks for your help!
