### ISSUE TITLE
Fail to build manhtmlpages with makeKHR et al.

### ISSUE THREAD

**Issue by HeroicKatora** [KhronosGroup/Vulkan-Docs#544]
The Makefile does not work correctly in combination with the makeKHR command when trying to build the target `manhtmlpages`

Expected behaviour
----------

After invoking `./makeKHR manhtmlpages` the html man pages are located in `../../../out/1.0/man/html`

Actual behaviour
-------

Only `./man` is rebuilt but there appear no files in the expected output location. This will also happen for the other build scripts and when invoking `make manhtmlpages` on a clean repository.

Failure
--------
When issuing a new build with `makeKHR` and the other extension scripts, `make clean_generated` is called first. This removes all files from `./man` and then invokes make again with the extensions. But on the second invokation the Makefile will not detect any dependencies besides `man/apispec.txt` since they were all removed. After the text man files are rebuilt as dependencies of `man/apispec.txt` make has finished building all of its targets and their dependencies as they are not dynamically updated.

In the case of a simple `make manhtmlpages` the issue can be rectified by simply calling the command twice as all dependencies will exist the second time. But since `clean_generated` is called at the beginning of all the automated extension scripts, this will not work for them.

Possible workarounds and fixes
--------
1. Call the build command twice in automated extension build scripts. This is quick, very dirty but effective.
2. Detect the build of manpages in the automated scripts and pre-build the specification files, invoking `make` three times. This would even work unconditionally but in this case python would be a dependency for all builds through those files.
3. Update the makefile to generate dependencies of `manhtmlpages` in a smarter way which avoids the whole issue. This is probably the most complicated solution but most robust as it could alleviate all issues touching only the Makefile.

**Comment by oddhack** [comment]
Yes, this is a problem. I've perused the GNU make docs and other sources a number of times trying to find the "Update the makefile in a smarter way" answer, and still don't have one. I think the only likely workaround in the near term is to add a note to the README.adoc about what to do if you require the ref pages, since that's the only place these helper scripts are documented. When I have time I'm going to write a Python wrapper script to replace the clutter of shell script helpers, which is sort of your point 2; I don't mind Python being a dependency because it's a defacto dependency already.

N.b. the 'make clean_generated' is there because it's the only way to be sure that the right generated files are present when building the actual spec artifacts, short of some excessively ornate caching system.

**Comment by TobiasHector** [comment]
NB: This overlaps with #394

**Comment by timofonic** [comment]
@HeroicKatora @oddhack @Tobski Any news?

**Comment by oddhack** [comment]
This was fixed at some point (although you're still going to get all extension refpages being built, not just KHR).
