### ISSUE TITLE
Clarify behavior of vkQueuePresentKHR on VK_ERROR_OUT_OF_DATE_KHR

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Docs#572]
If `vkQueuePresentKHR` fails with `VK_ERROR_OUT_OF_DATE_KHR`, does the `VkSemaphore` indicated in the `VkPresentInfoKHR` still get unsignaled? The spec seems to either be ambiguous about this, or perhaps even imply that it is not the case. Despite this, the validation layers' state trackers seems to believe that the semaphore gets unsignaled in this scenario; and indeed, manually re-submitting an explicit unsignal operation on the `VkSemaphore` gets the GPU stuck.

Could you please clarify, perhaps with a paragraph somewhere in `VkPresentInfoKHR`, under which circumstances exactly the semaphores described by `pWaitSemaphores` get unsignaled?

Compare the following paragraph for `vkAcquireNextImageKHR` which describes the opposite scenario:

> A successful call to vkAcquireNextImageKHR counts as a signal operation on semaphore for the purposes of queue forward-progress requirements. The semaphore is guaranteed to signal, so a wait operation can be queued for the semaphore without risk of deadlock.

**Comment by NicolBolas** [comment]
As a point of comparison, `vkQueueSubmit` is allowed to offer up 3 errors: two OOM, or device lost. If it returns OOM of any kind, then it still has to ensure that synchronization primitives in the batch will be signaled. If the implementation cannot guarantee that, then the _only recourse_ in such cases is to lose the entire device.

However, `vkQueueBindSparse` does *not* have similar language. It doesn't say what the state of any semaphores/fence should be in the event of an error.

I would say that there should be a centralized place that says that any queue submission call, if it fails, will behave like `vkQueueSubmit`: either the synchronization primitives will be honored, or the device is lost. Of course, `vkQueuePresentKHR` isn't _technically_ a "queue submission" operation, so that too needs to be fixed. The present part of `vkQueuePresentKHR` should be considered a "queue operation" as well.

**Comment by haasn** [comment]
> I would say that there should be a centralized place that says that any queue submission call, if it fails, will behave like `vkQueueSubmit`

I would also like to point out that a link to this section should be added to the footnotes of each of these “submission calls”. Proper hyperlinking is almost as important as specifying it to begin with.

**Comment by krOoze** [comment]
It is probably missing in the Fundamentals chapter (it only speaks of result pointers), but reasonable assumption would be that unless otherwisely specified error should mean no state was disturbed.

`vkQueuePresentKHR` is a bit tricky, because it allows partial success if more swapchains are being presented to.

**Comment by NicolBolas** [comment]
> I would also like to point out that a link to this section should be added to the footnotes of each of these “submission calls”.

I see no need for that, specifically. The two calls that are currently "queue submission" calls (`vkQueueSubmit` and `vkQueueSparseBind`) both link to the "Queue Submission" section. That link by itself should be adequate, since that's the section that should centralize error behavior.

**Comment by jjulianoatnv** [comment]
@NicolBolas , is your statement that `vkQueuePresentKHR` is not a "queue submission" derived from spec language, and if so from which spec language?

**Comment by NicolBolas** [comment]
> is your statement that vkQueuePresentKHR is not a "queue submission" derived from spec language, and if so from which spec language?

Well, the specification explicitly states that `vkQueueSubmit` and `vkQueueBindSparse` are "queue submission" commands:

> `vkQueueSubmit` is a queue submission command,

> `vkQueueBindSparse` is a queue submission command,

These are explicitly stated in the explanation for the behavior of those functions.

The specification contains no similar statement on `vkQueuePresentKHR`. As such, I conclude that `vkQueuePresentKHR` is not a "queue submission" operation.

**Comment by jjulianoatnv** [comment]
I see, thanks for explaining @NicolBolas .

My personal opinion is that vkQueuePresentKHR is supposed to be a queue operation.
1. The name includes the substring "queue", and it operates on a queue
1. It gets consumed in queue order of the queue on which it operates

I expect one or more spec clarifications to come out of this discussion. Exactly what those clarifications will be is not yet determined.

I like the suggestion of trying to address in the fundamentals chapter what happens to semaphores when a queue operation fails. We're putting this on the agenda for additional discussion within the working group.

**Comment by drakos-amd** [comment]
Considering that VK_ERROR_OUT_OF_DATE_KHR is special from the point of view that the application has a well defined set of steps to get presentation working again, it seems unfavorable having to resort to returning VK_ERROR_DEVICE_LOST due to potentially leaving the waited semaphores in an undefined state. Thus a reasonable solution is to clarify that in case of VK_ERROR_OUT_OF_DATE_KHR (and other swapchain related failures) the semaphore is unsignalled even if the presentation itself failed with that error. In unrecoverable error scenarios though VK_ERROR_DEVICE_LOST should be expected at least because the wait semaphore may not be in a well-defined state anymore.

We will clarify this in a future revision of the spec.
