### ISSUE TITLE
Why VkBufferImageCopy::bufferOffset multiple of 4

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#574]
Why is `VkBufferImageCopy::bufferOffset` forced to be multiple of 4?
It sounds arbitrary considering it is already restricted to transfer granularity, and considering that other similar parameters (`bufferRowLength`, `bufferImageHeight`) do not have such restriction.

If the second buffer row can be started at non-4 boundary, why not allow the same for the first row (marked by `bufferOffset` )? Shouldn't be any harder for the command...

**Comment by oddhack** [comment]
It was done at IHV request early in Vulkan development, probably to accomodate something arcane about their specific GPU. We discussed briefly today and while it's slightly annoying, nobody thought it was a good use of our time to relax the restriction.

**Comment by haasn** [comment]
Just wanted to point out that this is not a theoretical annoyance - it definitely affects real code: In VLC (and most other video players) we crop videos by just modifying the start pointer. Any crop with an x offset that is not a multiple of 4 requires us to perform an extra round trip through a `vkCmdCopyBuffer` due to this restriction.

For a crop of e.g. 4K 60 fps video playback, this means copying around several gigabytes of memory per second - but only 75% of the time (for a random user-selected crop). It's certainly very weird, and especially on weaker iGPU and APU systems the overhead can be significant.

**Comment by krOoze** [comment]
Relaxed for color formats on a `GRAPHICS` or `COMPUTE` queue family.
