### ISSUE TITLE
vkQueueSubmit Fence Clarification

### ISSUE THREAD

**Issue by dudenamedkev** [KhronosGroup/Vulkan-Docs#577]
It is my understanding (through some research online and my own testing) that the fence object passed to the vkQueueSubmit function is only signaled once all command buffers submitted to said function have finished executing. This allows for checking for submission completion using either vkWaitForFences or vkGetFenceStatus. This behavior makes sense, but I am finding it difficult to find it mentioned explicitly in the specification.
Is this indeed the intended behavior? If so, shouldn't it be explicitly mentioned in the specification? I.E. "The fence passed to vkQueueSubmit is only signaled once all command buffers supplied in the VkSubmitInfo structure(s) have completed executing."
If this is not the intended behavior, is there a better way for checking command buffer execution completion?
Thanks!

**Comment by NicolBolas** [comment]
It does exist, but it's in a very weird place. It's in section 6.3, right after the definition of `vkResetFences`:

> When a fence is submitted to a queue as part of a queue submission command, it defines a memory
dependency on the batches that were submitted as part of that command, and defines a fence signal
operation which sets the fence to the signaled state.
>
> The first synchronization scope includes every batch submitted in the same queue submission
command. Fence signal operations that are defined by vkQueueSubmit additionally include in the
first synchronization scope all previous queue submissions to the same queue via vkQueueSubmit.
>
>The second synchronization scope only includes the fence signal operation.
>
> ...

It seems to be centralized (rather than in the section for `vkQueueSubmit`) because it is the same definition for all "queue submission" commands. This includes `vkQueueSubmit`, but also `vkQueueBindSparse`.

**Comment by TobiasHector** [comment]
Hum. Yea that should probably be put in vkQueueSubmit explicitly.

It's also called out in "2.2.1 queue operation":

> Before a fence or semaphore is signaled, it is guaranteed that any previously submitted queue
operations have completed execution, and that memory writes from those queue operations are
available to future queue operations. Waiting on a signaled semaphore or fence guarantees that
previous writes that are available are also visible to subsequent commands.

That section seems like a relatively sane place to put it, but frankly that section has always felt like it was in the wrong place, at least to me.
I think it makes a lot of sense to just change the definition of the fence parameter in vkQueueSubmit to say:

> `fence` is an optional handle to a fence to be signaled **once all command buffers have completed execution**. If `fence` is not VK_NULL_HANDLE, it defines a fence signal operation.

(new bit in bold)

**Comment by dudenamedkev** [comment]
Thanks for the clarification!
I agree @TobiasHector , that simple addition would make the intended behavior perfectly clear. Perhaps also include a link to the other section(s)? That way there will be no question as to what is supposed to happen.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.63 spec update.
