### ISSUE TITLE
General stability of vk.xml, Release cycle

### ISSUE THREAD

**Issue by Sharplifter** [KhronosGroup/Vulkan-Docs#580]
Is there a special stable branch of the registry vk.xml? I thought things would not be released to [https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml) unless stability is basically guaranteed...
I have often experienced strange behaviors with the copies of vk.xml put there.
As an example, take the 1.0.62 upgrade:

>Change log for October 6, 2017 Vulkan 1.0.62 spec update: 
>
>Other Issues:
>
> -  Fixed typo in flink:VkRenderPassSampleLocationsBeginInfoEXT (renamed
>    field pname:pSubpassSampleLocations to
>   pname:pPostSubpassSampleLocations).
>
>New Extensions:
>
> - Add +vk.xml+ entries for pending `VK_ANDROID_native_buffer` extension
>    (note, this extension is not yet enabled).

It introduces breaking changes by renaming a field. Additionally I'm really unsure whether it's a good idea to introduce a structure referencing enum members defined in disabled extensions (meaning the value for `VkNativeBufferANDROID.sType`).
For the latter, I thought it might be possible to filter this out, but the whole concept of `<require...>` is either broken, too, or implicit to a grade that it will bring you to tears if you want to automate finding out which types and commands to actually take over. It's not like every required type and command actually has a `<require...>` reference...
I also experienced experimental stuff getting renamed and thus "moved" to a non-exprimental stage. Which makes previously existing types and commands vanish that may have worked fine in an earlier revision of the spec.
So I'm totally confused about the rules of what can happen with the registry. I often find it is not really usable for code generation this way, even though it is of course helpful. Some revisions actually do work out, and since it is the only source of input for such activities, there's no real alternative.
I think I've read some rants about code generation and vk.xml before, complaining about similar issues and certain other complexities.
Is it possible we can improve things here? Is there a guide on rules?

**Comment by krOoze** [comment]
> Fixed typo in flink:VkRenderPassSampleLocationsBeginInfoEXT (renamed field pname:pSubpassSampleLocations to pname:pPostSubpassSampleLocations).

Pedantically this is breaking compatibility. But bit of a grey zone, because it was referred to as the new name in the rest of spec text, so with one eye closed can be considered as a spec defect fix. They should have probably introduced macro alias for the old name though.

Not sure what the problem with `VK_ANDROID_native_buffer` you see. Except perhaps that you did not expect disabled extensions to have well defined members (which probably did not happen before).

> For the latter, I thought it might be possible to filter this out, but the whole concept of <require...> is either broken, too, or implicit to a grade that it will bring you to tears if you want to automate finding out which types and commands to actually take over. It's not like every required type and command actually has a <require...> reference...

Not sure what you need `require` here for. If you want to filter it out the `<extension>` tag says exactly what things the given extension defines.

> I also experienced experimental stuff getting renamed and thus "moved" to a non-exprimental stage. Which makes previously existing types and commands vanish that may have worked fine in an earlier revision of the spec.

I believe there is an explicit warning in the specification about that.

> So I'm totally confused about the rules of what can happen with the registry.

 https://www.khronos.org/registry/vulkan/specs/1.0/registry.html#general:stability

> Is it possible we can improve things here?

It is. Starting with proposing **specific** improvements.

> Is there a guide on rules?

Aforementioned [schema document](https://www.khronos.org/registry/vulkan/specs/1.0/registry.html), which can change at any moment if it is considered useful improvement.
Associated [registry.rnc](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/registry.rnc).
Authors should also follow the [styleguide](https://www.khronos.org/registry/vulkan/specs/1.0/styleguide.html). There's probably not all that much there that touches `vk.xml` directly. It can also change at any moment if it is considered useful improvement.
And of course the [Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkRenderPassSampleLocationsBeginInfoEXT), where you would find e.g. the warning about Xperimental extensions or definition of compatibility of Vulkan versions.

**Comment by NicolBolas** [comment]
The Vulkan specification actually lays this out quite well:

> A difference in patch version numbers indicates that some usually small part of the specification or
header has been modified, typically to fix a bug, and may have an impact on the behavior of
existing functionality. Differences in this version number should not affect either _full compatibility_
or _backwards compatibility_ between two versions, or add additional interfaces to the API.

With "full compatibility" being defined as:

> A given version of the API is fully compatible with another version if an application, relying only
on valid behavior and functionality defined by either of those specifications, is able to correctly
run against each version without any modification. This assumes no active attempt by that
application to not run when it detects a different version.

Note that it's talking about a _compiled_ application. So if you wrote and compiled code against 1.0.61, your code will function when run on implementations that implement 1.0.62.

That your 1.0.61 source code may not compile without modifications on 1.0.62 is _not_ part of the guarantee. So basically, patch releases preserve A<b><i>B</i></b>I compatibility, not A<b><i>P</i></b>I compatibility.

Granted, the only changes that affect the API without affecting the ABI are renaming things or adding new functions/structs/etc. All of which represent noisy breaks (aka: compile failures) rather than having code change its behavior silently.

**Comment by oddhack** [comment]
Two things are getting conflated here: the API itself, and the schema describing it.

Yes, there was a source-backwards-incompatible API change in a recently published extension. We discussed renaming the member for consistency with our own rules and that change was approved, under the specific circumstances.

You should not be generating anything for disabled extensions, period. They are only placeholders. The vendor wanted to include more API information for their own internal purposes but the extension still is disabled, until they say otherwise.

> It's not like every required type and command actually has a <require...> reference...

Every interface that's required is included implicitly by transitive reference from the \<require> tags. The XML does not list every interface explicitly, which would be very cumbersome and error-prone.

> I also experienced experimental stuff getting renamed and thus "moved" to a non-exprimental stage. Which makes previously existing types and commands vanish that may have worked fine in an earlier revision of the spec.

KHX extensions are, by definition, experimental and subject to change at any time, including disappearing completely or being changed to stable KHR status.

**Comment by Sharplifter** [comment]
Okay, points taken. I assume with correctly parsing the <require...> tree it should be possible to correctly find all the non-disabled stuff that is actually needed, even though it may be cumbersome. Any other ideas I have are also subject to human error and may make things even worse.

>>Is it possible we can improve things here?

>It is. Starting with proposing specific improvements.

The proposal would be to introduce a way to explicitly mark experimental extensions, either by adding `"experimental"` as legal and desired value to the `supported` attribute or introducing a new attribute `experimental="true"` to the `<extension>` element.
Then change the contract to mandatorily require this new marker to be set for any experimental extension.
The proposal is done under the assumption that authors NVX and AMDX introduce the same precautions as KHX, please correct me if I am wrong about this.
Under this assumption I think it would be better to mark explicitly instead of guess-parsing whether the author ends on "X" which will fail when imagined company ZYX enters the scene, marking _their_ experimental stuff with ZYXX etc.

**Comment by oddhack** [comment]
We don't know what vendors will do with their own extensions, and we can't control it. At most we can suggest guidelines. I'd be happy to run the "experimental" suggestion by the Vulkan working group, but even if we agree on adopting it, there's no way to know if vendors will always use it correctly, or if they might choose to make a change even if they didn't use it.

If we do make further changes in published KHR extensions, it will only be done after weighing the costs and agreeing amongst ourselves that it's an appropriate change that won't adversely affect shipping apps, and it won't happen often. There have been a number of internal proposals for API cleanup that were rejected for exactly the reason that people felt the extensions in question had been out too long.  But we're not going to bind ourselves to an absolute statement that it will never happen again.

VkRect3D was not part of the published API, and it was removed from the XML when we noticed that.

**Comment by Sharplifter** [comment]
Meanwhile I patched my algorithms to make it really possible to filter out the disabled things and choose between including experimental or not based on the "author-ends-on-X" heuristic. And look what the cat brought home:

extension `VK_KHR_external_memory_fd`: `author="KHX"` ... now, is it still experimental or not?
extension `VK_KHX_multiview`:  `author="NV"` ... now, is this experimental or not?

So yes, I do think there is a problem for everybody working on those generators trying to bring the API to a language different from C.
Of course, human error in filling the registry can always happen, and if above cases are related to such lapses, it can be fixed easily enough. However, for proper code generation, you need to be able to recognize how to go about such cases in an automated way. And as you pointed out, sometimes you want to keep the initial names for compatibility. So I really hope we can get this properly recognizable "experimental" marker in the registry.

**Comment by krOoze** [comment]
@Sharplifter The `author` tag is informative (and optional). Actually it is supposed to be full company name if it differs from the author ID in the name of the extension...

**Comment by oddhack** [comment]
+1 @krOoze. The author tag shouldn't be used for this purpose. KHX_multiview is experimental, because it's a KHX extension. KHR_external_memory_fd is not experimental, because it's a KHR extension. What exactly the "AMDX" and "NVX" tags mean, and whether those meanings map onto "experimental", is up to the companies who own the tags. The bottom line is that having or not having an "experimental" tagattributeisn't ever going to prevent an extension owner from making changes if in their judgement, that's required; and if they make those changes, they will have to be reflected in  language bindings. But such changes should be very rare for non-"X" extensions. The overriding caveat about KHX is that people should not ship production apps relying on them, because they can and will change, or be removed entirely, in the future - they are primarily a way of trying out functionality without committing to it eternally.

The 'author' attribute on extensions is unused in our own toolchain. It is just metadata of who originally proposed an extension, which may have later been promoted from vendor-experimental to vendor or EXT or Khronos status before reaching the public registry. Mostly the author tag in the extension name is the same as the author attribute in the \<extension> tag, but there are ca. 10 extensions where the author attribute is something else.

**Comment by Sharplifter** [comment]
So are you saying, with the current possibilities of vk.xml, it would be better to try to deduce from the `<extension name="..."` whether an extension is experimental or not? E. g. VK_`KHX`_device_group --> maps to category `KHX` --> it is experimental?

**Comment by oddhack** [comment]
Yes. KHX == experimental.

**Comment by oddhack** [comment]
I'll ask about the "experimental" tag. Otherwise I think things are resolved as far as they're likely to be.

**Comment by FacticiusVir** [comment]
Would it also be possible to have a `deprecated` value for the `supported` attribute - this way there is a persistent record of experimental extensions that have been replaced without adding significant overhead to the spec, and it allows those of us generating bindings to maintain backwards compatibility for consumers of our APIs without walking the repo history.

**Comment by oddhack** [comment]
@FacticiusVir unlikely. Our expectation is that when an extension is promoted from KHX to stable KHR status, the KHX interface will be completely removed from the spec, the XML, and other artifacts, as well as from drivers. They are not *intended* to be backwards compatible or supported in the long term. Nobody should be using a KHX extension without understanding that they are almost certainly transient in nature.

**Comment by oddhack** [comment]
We have discussed this enough to conclude an "experimental" tag in vk.xml won't happen. Going forward, we think that KHX extensions were not a successful experiment, and we won't be creating any more of them; as they are promoted into KHR extensions, the old KHX interfaces will be removed from vk.xml.

Khronos can't control and doesn't have advance knowledge of what vendors do with their own "experimental" tags. OpenGL history suggests that such extensions will either be abandoned or promoted to non-experimental vendor status eventually, and will probably not be supported on every implementation a vendor ships.
