### ISSUE TITLE
Push constant clarifications

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/Vulkan-Docs#609]
Hello!
I would like to discuss a few edge cases for push constants which are not totally clear in the specification imo:

#### Overlapping push constant blocks:
If we define two push constant blocks in the shaders:
e,g vertex shader:
```
layout(push_constant) uniform foo {
    layout(offset=0) vec2 a;
} u_foo;
```
and fragment shader:
```
layout(push_constant) uniform bar {
    layout(offset=4) vec2 b;
} u_bar;
```
with the push constant layouts `[(VERTEX, 0, 8), (FRAGMENT, 4, 8)]` then `a.y` and `b.x` would share the same push constant memory. Is this legal or must fields match for overlapping ranges?

#### Overlapping push constant updates
Considering the case outlined above. How could the push constants be updated via `vkCmdPushConstants`. The specs states that `stageFlags must match exactly the shader stages used in layout for the range specified by offset and size`. Are 3 ranges (i.e `[VERTEX, 0, 4), (VERTEX|FRAGMENT, 4, 8), (FRAGMENT, 8, 4)]`) required to have matching shader stage flags?

**Comment by NicolBolas** [comment]
Your shader is illegal because `vec2` requires 8 byte alignment, yet your offset assigns a variable 4-byte alignment. But let's pretend you had used `float b;` instead of `vec2 b;`.

Other than that issue, there is nothing illegal about overlapping ranges. There are no Valid Usage statements forbidding elements of `pPushConstantRanges` from having overlapping ranges. So there's nothing that needs to be clarified.

As for the question about `vkCmdPushConstants`, that is odd wording. It suggests that the `offset`/`size` range must match one of the ranges in `pPushConstantRanges` in the layout. If that is the intent, then the wording ought to explicitly say that. Something to the effect of:

> * `offset` and `size` **must** exactly match at least one of the ranges from the `layout`'s `pPushConstantRanges`.
> * `stageFlags` **must** include all of the stages for each `pPushConstantRanges` range which exactly matches `offset` and `size`.

Alternatively, the idea could be that you must put the stage flags for any shader stage that reads values from the provided range. That is:

> * If `layout` contains a `pPushConstantRanges` range for a shader stage that overlaps the range specified by `offset` and `size`, then that shader stage **must** appear in `stageFlags`.
> * `stageFlags` **must** not contain a shader stage which does not have a `pPushConstantRanges` range which overlaps the range specified by `offset` and `size`.

**Comment by msiglreith** [comment]
Thanks! Regarding the first question, I agree no further clarification needed from my side.

**Comment by jeffbolznv** [comment]
We've addressed this in the next spec release (should be available in the next few days). It is legal to have the ranges overlap across shader stages, and we've relaxed/rewritten the VU for vkCmdPushConstants to make it valid/possible to update such ranges. Basically, you have to split the updates so that each update has the exact stageFlags reflecting all the stages that use that range.

I'm going to go ahead and close this now, since the fix is in flight.
