### ISSUE TITLE
Missing "valid" on non-const structures

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#653]
As it emerged in #610 some structures that are taken as a non-const structures are missing the "valid" word in VUs of commands. E.g.

> `pProperties` **must** be a valid pointer to a `VkPhysicalDeviceProperties2KHR` structure

But `VkPhysicalDeviceProperties2KHR` has `sType` that should be filled and so above should say "valid `VkPhysicalDeviceProperties2KHR`".

Those structures are to be filled by the implementation, but I am working under the assumption that the `sType` has to be valid going in, as well as the `pNext` structure allocated (and so on recursively in the `pNext` chain).

I have PR in the works, but I can't get myself to finish it...

Now, to analyze the situation:
1) Structure with `sType` and `pNext` and `returnedonly` should say "valid" in command VU. (The structure won't have any other VUs than the `sType` and `pNext`, so it is safe)
2) Similarly non-`returnedonly` structure that has **only** `sType` and `pNext` VUs should say "valid". (Pretty hard to detect; is there even such case in the spec?)
3) Non-`returnedonly` structure with other VUs. Those need `sType` and `pNext` valid but other VUs should be ignored. What should the spec say there??  Is there even such case in the spec?
4) Rest of the cases should lack the word "valid" in VU section.

**Comment by oddhack** [comment]
Assign to @TobiasHector for triage.

**Comment by Tobski** [comment]
This is old enough that I'm fairly sure we've overhauled this logic several times. IIRC the current logic is to just dump valid in there for any structure whether it's always valid or not, except in cases of "returnedonly" structures. I think this is satisfactory?

Due to the unfortunately out of date nature of this bug now, I'm going to close it, please feel free to raise a new issue if issues with the current logic is found.
