### ISSUE TITLE
"API Order" in Glossary, but not in spec

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#657]
There is "API Order" entry in the Glossary, but it is not used in the spec.
Should be "Rasterization Order"?

**Comment by TobiasHector** [comment]
Ahh man. I thought I purged all uses of "API order" when I added the " Implicit Synchronization Guarantees" section of the sync chapter. Apparently I missed the glossary - go figure.

"API order" should definitely be deleted since it's not used anywhere; adding glossary entries for other ordering terms used in the spec is also maybe not the worst idea, but there are other orders (as you can see from that section) - would be weird to add rasterization order and not the others IMO.

**Comment by NicolBolas** [comment]
It should be noted that a number of extensions still use the term "API Order".

**Comment by oddhack** [comment]
@NicolBolas all I see is "strict API order rasterization" in VK_AMD_rasterization_order at this time; are there any other examples?

**Comment by timofonic** [comment]
@krOoze @Tobski @NicolBolas @oddhack Any news?

**Comment by oddhack** [comment]
Done in the 1.1.80 spec update.
