### ISSUE TITLE
VK_LOD_CLAMP_NONE constant undocumented

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#663]
The constant `VK_LOD_CLAMP_NONE` present in `vk.xml` is undocumented in the specification.

**Comment by hrydgard** [comment]
This seems like a trivial one to fix, deserving a single bump. There was just a question about this on KhronosDevs.

**Comment by oddhack** [comment]
We do have someone assigned to deal with it internally but they're very busy. TBH I'm not sure myself, it's probably an upper LOD clamp bound that will never be reached but exactly where it's used is less obvious.

**Comment by hrydgard** [comment]
Yeah it's a strange little constant, it came up in https://community.arm.com/developer/tools-software/graphics/b/blog/posts/mali-bifrost-usage-recommendations-for-texture-and-sampler-descriptors but they have since changed the article to say 1000.0 explicitly. Probably a GL remnant, since it's default MAX_LOD is 1000.0. For all other practical purposes any large number is probably fine...

**Comment by oddhack** [comment]
This should be addressed in the 1.2.166 spec update.
