### ISSUE TITLE
[Specification] VkImageCreateInfo::flags and mandatory support

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#671]
Everything around mandatory format support seem to be well-specified (if scattered around the spec and described in a bit roundabout way) except `VkImageCreateInfo::flags`.

Can it be assumed that any `flags` may be used with mandatory format?

Closest I could find is this quote (32.4.3. Required Format Support):

> For images, these features must be supported for every `VkImageType` (including arrayed and cube variants) unless otherwise noted.

Which tries to say so for `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` and `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR`, but what about the other `flags`? Is it necessary to call `vkGetPhysicalDeviceImageFormatProperties` even for mandatory formats within Physical Device limits, because of the `flags`?

**Comment by drakos-amd** [comment]
The quoted text doesn't refer to `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` or `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR`. The text in parantheses is really unnecessary (and apparently confusing), as all that sentence tries to say is that the minimum required format features are orthogonal to the `VkImageType`.

Support for individual `flags` are similarly orthogonal to both the minimum required format features and the generic format features queriable using `vkGetPhysicalDeviceFormatProperties`.

The `flags` have their own requirements (as described in the corresponding sections of the spec) which may preclude supporting certain flag-format combinations (e.g. `VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT` requires a compressed format, as stated in the corresponding Valid Usage clause), but that's a separate question.

`vkGetPhysicalDeviceImageFormatProperties` may return an extended set of capabilities based on the value of `flags` (beyond the minimum capabilities) and may return `VK_ERROR_FORMAT_NOT_SUPPORTED` for certain combinations of parameters disallowed by image creation related Valid Usage clauses, but the application does not have to call `vkGetPhysicalDeviceImageFormatProperties` to determine the compatibility of a set of `flags` with a particular format, those rules are statically defined as Valid Usage clauses (as the example I noted above) and thus as long as otherwise all Valid Usage clauses are respected the set of format features returned by `vkGetPhysicalDeviceFormatProperties` should work with any combination of `flags`.

**Comment by krOoze** [comment]
Alright, I just don't see that supported by the spec. Not that it is particulary clear overall, but `flags` are the worst.

It is problematic because of:

> The combination of `format`, `imageType`, `tiling`, `usage`, and `flags` **must** be supported, as indicated by a `VK_SUCCESS` return value from `vkGetPhysicalDeviceImageFormatProperties` invoked with the same values passed to the corresponding parameters.

Now, not being too "anal about the spec", I assume calling `vkGetPhysicalDeviceImageFormatProperties` is actually not necessary assuming I am confident it should return `VK_SUCCESS` for given `(format, imageType, tiling, usage, flags)`.

For most of those parameter combinations I can infer they should be supported (based on `FEATURE` support, minimal limits support, and rules in 30.4.N chapters). It is not particulary ideal, clear or unambiguous... but the `flags` are not mentioned anywhere in this context (except the `CUBE` and `ARRAY`), which make them the worst problem.

**Comment by drakos-amd** [comment]
Refering to requiring `VK_SUCCESS` from `vkGetPhysicalDeviceImageFormatProperties` is practically a "catch-all" kind of requirement which includes both the base set of requirements plus any additional support reported by `vkGetPhysicalDeviceImageFormatProperties`.

I'll look into whether we can better clarify that `flags` does not have an effect on the required format support.

**Comment by oddhack** [comment]
This should be fixed in the 1.1.79 spec update - there was a note added by @drakos-amd .
