### ISSUE TITLE
Backwards compatibility of promoted extensions

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#682]
1) I think it should be said below `vkEnumerateXExtensionProperties` that it **must** return all the promoted extensions (on 1.1+ implementation).

2) It should be clarified whether the command aliases require the extension to be enabled or not. I.e. if GIPA and GDPA may return `NULL`.

3) It should be clarified whether the command aliases are loaded by the default loader.

**Comment by polarina** [comment]
> I think it should be said below vkEnumerateXExtensionProperties that it must return all the promoted extensions (on 1.1+ implementation).

I don't think that's appropriate, at least not for all promoted extensions. For example, the `VK_KHR_variable_pointers` extension mandates that the feature bit `variablePointerStorageBuffer` be `VK_TRUE` whereas in Vulkan 1.1 this feature is optional.

**Comment by krOoze** [comment]
@polarina Well, exceptions breed exceptions.
`variablePointerStorageBuffer == VK_TRUE` should imply the extension is supported and `variablePointerStorageBuffer == VK_FALSE` should imply the extension is not supported. Problem solved.

**Comment by critsec** [comment]
The "should" is there because in most typical consumer operating system environments there are indeed ecosystem and app compat reasons why it would be beneficial if these are exposed. But there is no fundamental reason why a Vulkan 1.1 application running on Vulkan 1.1 implementations needs them to be exposed, i.e. everything is well-defined without that. And there may be specialized / embedded environments where there is no ecosystem need for them to be exposed .. or new platforms in the future that adopt Vulkan starting at 1.1.

The aliasing is done for spec writing and XML convenience, i.e. to make it so we don't have to manually duplicate information (which is prone to accidental inconsistencies). The API itself doesn't treat them as formal aliases: they are distinct commands, available under distinct conditions (Vk1.1 supported, vs. extension supported and enabled), and rules for e.g. GIPA support apply accordingly.

**Comment by ianelliottus** [comment]
Can we close this issue now?

**Comment by krOoze** [comment]
@critsec Ad 1:

> But there is no fundamental reason why a Vulkan 1.1 application running on Vulkan 1.1 implementations needs them to be exposed

There is no fundamental reason why they should not be exposed neither -- the promoted extensions are exact duplicate and require very little additional effort for implementors. Supporting 1.1 but not the same functionality as extensions in 1.0 (which they are transitively obligated to support anyway) sounds just lazy, and I think implementers should be actively dissuaded from doing so by the Specification.

ad 2, 3:

> The API itself doesn't treat them as formal aliases: they are distinct commands, available under distinct conditions

Sounds resonable. Needs Spec wording, because just saying they are "alias" is ambiguous without your explanation above.

**Comment by cubanismo** [comment]
Extensions promoted so far may have been exact aliases (with subtle exceptions noted above), but exact aliasing is not required in general.  I think the only reasonably way to handle this would be to add a note in each extension's appendix stating whether it can be assumed included given Vulkan version X.X or something, and that seems pretty clunky.

**Comment by krOoze** [comment]
@cubanismo Way ahead of ya: PR #690. Not particulary clunky, assuming it can be autogenerated from the xml.

**Comment by critsec** [comment]
I tried to review that change, but it seems to mix together a few different (but related) things, and ran out of time trying to understand what the net effect was especially as it relates to this issue. Can I suggest splitting it up and better describing what each change does?

As far as I saw, it doesn't attempt to change anything about whether an implementation that supports Y must also support X, when X precedes Y. In particular it doesn't seem to do what @cubanismo was suggesting: state whether an extension can be assumed included given Vulkan version X.Y. (I don't think this assumption is ever true in general, but will be true in practice in most markets.)

It looks like it creates an informal/subjective "precedes" relationship in the registry and injects that information into the spec? If so, we've already done that manually for extensions promoted to core (including describing any changes that were made in the process (see `VK_KHR_descriptor_update_template` and `VK_KHR_device_group`, among others). Documenting that for extension -> extension would be good and we don't do that currently. Automating what we have would be nice in principle, but I don't see how we could handle the non-trivial cases. And to be honest, adding that bit to the extension appendices was a very small part of the effort of producing Vulkan 1.1.

**Comment by critsec** [comment]
Short version, though: *Not* requiring implementations to support an extension when it has been promoted to core was a deliberate decision of the WG, after debate. I don't think we'll reverse that (and now that 1.1 has been released, it would be very difficult to add such a requirement) without new information about significant negative effects on the ecosystem; we did consider the motivations that have been raised in this issue, so they're not new.

The argument for not requiring it was basically:
* We don't have precedent for a core API spec to require certain extensions.
* Such a requirement isn't important for some markets Vulkan is present in.
* When there *are* changes during the promotion process, such a requirement is a burden to implementations.
* In the markets where it is important, market forces are just as effective as a spec requirement at getting implementations to support extensions in addition to core versions.
* This requirement makes sense during transitions, but in N years when nobody is targeting Vulkan 1.0 implementations, continuing to require Vulkan 1.LATEST implementations to support extensions that were promoted to core in Vulkan 1.1 would be non-useful and burdensome (even just the additional time spent running conformance tests adds up and becomes a problem).

I suggest we close this issue, since I don't think changes to semantics or requirements are still on the table. Continuing to drive the automation in #690, including automating the "Promoted to Vulkan 1.1 Core" statements we already have, can be done independently of this issue.

**Comment by krOoze** [comment]
> As far as I saw, it doesn't attempt to change anything about whether an implementation that supports Y must also support X, when X precedes Y.

Yes, but it also adds more formal "promoted" relationship.
Without the "promoted" keyword, it is just informal\spiritual predecessor (Here I thought organizing the extensions into "relevant" and "legacy\no longer relevant" would help. Especially incomming DX people tend to complain about extensions and it might help to visualy reduce the number of extensions and introduce some hierarchy.).

That "promoted" relationship is all we need here. All that needs to be added after that is language like:

> If an extension E is "promoted" to 1.N, and implementation supports 1.N, implementation must: also support extension E.

<hr/>

> Automating what we have would be nice in principle, but I don't see how we could handle the non-trivial cases.

You are already handling the non-trivial cases. You are even handling the trivial cases as non-trivial.

> And to be honest, adding that bit to the extension appendices was a very small part of the effort of producing Vulkan 1.1.

It's not as much about effort, as about it being error-prone and brittle. Things like #696.1 might happen (which IMO should be automated too, as well as the "added fn\structs\enums" sections...)

<hr/>

> - We don't have precedent for a core API spec to require certain extensions.

Nor can you, since so far there was only one core version.
Also you actually do: `VK_KHR_sampler_mirror_clamp_to_edge` is required to be supported by 1.0

> - Such a requirement isn't important for some markets Vulkan is present in.

which markets?
Seems useful for Vulkan apps. And Vulkan apps are relevant to all Vulkan markets.

> - When there are changes during the promotion process, such a requirement is a burden to implementations.

So let's not call this non-trivial cases "promotion"
The extension that were promoted verbatim is the subject here.
The non-trivial cases are practically non-existent so far, and can be easily handled manually. The one current exception is clearly a case for inclusion in mandatory extension support as it changes nothing except the enabling mechanism.

> - In the markets where it is important, market forces are just as effective as a spec requirement at getting implementations to support extensions in addition to core versions.

Unless there are also other forces at work :p.
And I mean, this is not exactly advertized on the GPU or SW box. Regular buyers would be completely oblivious to this, while it potentially makes it harder for the devs of their favorite SW to provide them with timely and quality updates.

>  - This requirement makes sense during transitions, but in N years when nobody is targeting Vulkan 1.0 implementations

Sounds like a wishful thinking. All those already sold chinAndroids will be 1.0 for the forseeable future (and that shall be true for all 1.N in the future too unless something changes).
If someone wants to target both that and desktop, he is stuck with 1.0 + extensions (or has to make N separate renderers for each in 1.N)

And in the case we did not do enough blood sacrifices at the "market forces" altar, the support for the extensions will be missing making the SW slower or not able to run at all, forcing everyone to the "N renderer" solution.

And it is as much a problem for old SW (if extensions are dropped despite being supported by newer Vulkan version implicitly).

**Comment by Tobski** [comment]
@krOoze Is it fair to say that your main driving motivation here is "making sure old software works on newer implementations"?

**Comment by Tobski** [comment]
(at least for point 1.)

**Comment by krOoze** [comment]
@Tobski "making sure old software works" is perhaps more that I want here.

I just want the obvious low hanging fruit guaranteed. I do not want the extensions to be denied to older software for non-technical reasons.

1.X implementations are required to support 1.0 forever, ever ever er er r.... ehem 😊 
I would like the same principle to apply to extensions. 1.1 Implementation obviously does support all the promoted extensions, and the hard part implementing them has already been done.
It just should also do the easy work of formally exposing them to the 1.0 Apps, by adding them to `vkEnumerateXExtensionProperties` list and exporting the alias command names.

**Comment by ianelliottus** [comment]
I'm acting as a messenger here ... the Vulkan working group inside Khronos discussed back in April, and chose to not do the proposed action.  Therefore, I'm closing this.
