### ISSUE TITLE
Render pass compatibility rules require external dependencies to match?

### ISSUE THREAD

**Issue by aejsmith** [KhronosGroup/Vulkan-Docs#726]
The rules for render pass compatibility currently seem to require all of the subpass dependencies to match for render passes to be compatible (they are not explicitly mentioned anywhere so presumably fall under the "otherwise identical" part).

This is probably reasonable for dependencies between subpasses within the render pass, but for external dependencies this is an odd restriction - it effectively means that you need different pipelines between render passes that are identical aside from external dependencies, for example, whereas this would not be the case if using explicit barriers before/after the pass instead.

I'm currently implementing a frame graph system and was intending to have it build dependencies into the render passes rather than using explicit barriers. This restriction makes doing this problematic, as it means that I'd need to get dependency information at pipeline creation time, but also because the dependencies could vary each frame meaning I'd need different pipelines.

Is there any reason for this restriction to exist or could it potentially be lifted? On a side note, the validation layers currently don't appear to be checking whether dependencies match at all when checking compatibility between render passes.

**Comment by cdwfs** [comment]
Thanks for bringing this issue to our attention, Alex; it's been raised internally and is being discussed within the Working Group.

**Comment by johannesugb** [comment]
Any news on this?

**Comment by johannesugb** [comment]
> This is probably reasonable for dependencies between subpasses within the render pass

Is it really that reasonable? 

Couldn't it maybe make sense to use a render pass _without_ specifying any subpass dependencies for framebuffer creation; and then use a different---but compatible---render pass for draw calls, which has whichever subpass dependencies are appropriate for such a draw call?

If subpass dependencies are taken into account when deciding upon render pass compatibility, then a different framebuffer has to be created for every render pass, even if subpass dependencies are the only difference between two otherwise compatible render passes. <-- Is this how it is intended to be?

**Comment by Tobski** [comment]
Ah ok, so this ended up transforming into VK_KHR_dynamic_rendering, rather than being a distinct change to render pass object compatibility. I think this is actually ready to be closed.

There's a few reasons we didn't just make this change to render pass object compatibility:

1) Dynamic external dependencies can, in effect, be done by simply using pipeline barriers instead of subpass external dependencies, so the functionality is more or less already there. There are few perf considerations with this alternative.
2) Shipping implementations may factor external dependencies into compatibility, so we'd have needed an extension to fix it, and because of 1) it wouldn't add much value.

The advice then is to use pipeline barriers/events to do synchronization if you need the dependencies to be more dynamic than render pass objects allow in subpass dependencies.

> Is it really that reasonable?

To answer this specifically, the non-external subpass dependencies within a render pass can alter how data is packed into tile memory during rendering, so compatibility isn't possible between different render passes with different subpass depencies. Some vendors use this to determine how the framebuffer object is created, so AFAIK this is intended.
