### ISSUE TITLE
VK_NVX_device_generated_commands stage vs graphics pipeline

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#750]
`VK_NVX_device_generated_commands` extension commands are listed as usable only Inside Render Pass. Render Pass seems to largely assume only graphics pipeline, so there seems to be some issues.

1) Should `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT` include `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` ?

2) Should `VkSubpassDependency` accept `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX`?

3) Similarly to nr. 2 `vkCmdPipelineBarrier` seems to be restricted only to graphics pipeline stages:
>Self-dependencies **must** only include pipeline stage bits that are graphics stages

> A `vkCmdPipelineBarrier` command inside a render pass instance **must** be a subset of one of the self-dependencies of the subpass it is used in, meaning that the stage masks and access masks **must** each include only a subset of the bits of the corresponding mask in that self-dependency.

4) There is the logical ordering restriction to resolve. How does it apply to `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX`?

> Self-dependencies **must** not have any earlier pipeline stages depend on any later pipeline stages (according to the order of _graphics pipeline stages_), unless all of the stages are _framebuffer-space stages_.

The stage is not graphics, and the order is uspecified. Typical usage is 
`srcAccessMask = VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX`
`dstStageMask = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT`
But it is not clear that this is valid usage.

5) The commands say that they are usable on Compute pipeline, but has Render Pass: Inside. What does that mean exactly?

**Comment by pboudier** [comment]
I am not sure why we restricted vkCmdProcessCommandsNVX to only be inside a renderpass. it can generated and execute commands immediately, so should be allowed inside a renderpass. But when it only generates commands, it could be allowed outside a renderpass.

1: I don't think that we should include VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX. there are multiple ways this "generation" of commands can be done: using some dedicated hardware in pipe, using compute shaders, ... So it is just a separate "pipeline" in concept.

2: isn't VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX already supported via the srcStageMask and dstStageMask in VkSubpassDependency ? anyway, see 4 below

3: it seems that we need to make VkSubpassDependency not restricted to just graphics stages, but see 4 below.

4: 
When generating commands in the same command buffer, the implementation will do the ordering internally automatically, with the appropriate synchronization, without any control from the application; so this really acts as a mega API to "bind and draw an array of objects"
for commands processing into a target command buffer, the application needs to first issue a vkCmdReserveSpaceForCommandsNVX in a target command buffer, issue a vkCmdProcessCommandsNVX in the generating command buffer, and then submit those so that the commands are generated first, then executed second, with some kind of barrier in between. Can you clarify why the combination is not valid ?
srcAccessMask = VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX
dstStageMask = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT

5: 
the intent was that the "generation of commands" can be done for compute dispatches (not just draw commands). so we need to change the API to allow "both". (supporting compute dispatches has been made optional in the spec, since we did not implement it yet, and we wanted to get feedback from ISVs/IHVs as early as possible)

**Comment by krOoze** [comment]
ad 1. It is bit problematic, AIS the render pass largely only assumes graphics pipeline. With combination with nr.2, `VkSubpassDependency` does not allow `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT`, so one would have to (bit contra-conventionally) use `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT | VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX`

ad 2. No. `VkSubpassDependency` VU:

>If `srcSubpass` is equal to `dstSubpass`, `srcStageMask` and `dstStageMask` **must** not set any bits that are not `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT`, or not one of the _graphics pipeline stages_

Previously, it listed stages explicitly (and `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` was **not** among them either).
But yea, it seems to otherwisely be allowed for dependencies that are not self-dependencies... I think that is indeed allowed and catches all non-attachment resources as a `VkMemoryBarrier`.

ad 3. Yup, as clarified above nr. 2 and 3 are probably the same issue (only affects self-dependencies)

ad 4.
> Can you clarify why the combination is not valid ?

Simply as a consequence of the above spec quote:

> Self-dependencies **must** not have any earlier pipeline stages depend on any later pipeline stages (according to the order of _graphics pipeline stages_) [...]

Strictly speaking I cannot take "**must** not have any earlier pipeline stages depend on any later pipeline stages", and evaluate that predicate to either `True` or `False`. It is, by its definition, unspecified whether `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` is earlier or later than `VK_PIPELINE_STAGE_X`.

**Comment by krOoze** [comment]
PS: ad 2. Correction!
There is a VU in `VkRenderPassCreateInfo` saying:

> - For any element of `pDependencies`, if the `srcSubpass` is not `VK_SUBPASS_EXTERNAL`, all stage flags included in the `srcStageMask` member of that dependency **must** be a pipeline stage supported by the pipeline _identified_ by the `pipelineBindPoint` member of the source subpass.
>
> - For any element of `pDependencies`, if the `dstSubpass` is not `VK_SUBPASS_EXTERNAL`, all stage flags included in the `dstStageMask` member of that dependency **must** be a pipeline stage supported by the pipeline _identified_ by the `pipelineBindPoint` member of the source subpass.

For `pipelineBindPoint` VU says:

> `pipelineBindPoint` **must** be `VK_PIPELINE_BIND_POINT_GRAPHICS`

Therefore it would be invalid to have `VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX` for `srcStageMask` and `dstStageMask` of `VkSubpassDependency` (even for non&ndash;self-dependencies).

**Comment by pdaniell-nv** [comment]
Closing since VK_NVX_device_generated_commands has been deprecated.
