### ISSUE TITLE
Check exception handling strategy

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#76]
[The chapter file "fundamentals.txt"](https://github.com/KhronosGroup/Vulkan-Docs/blob/7e195e846e9b3d7b91c2fe57406a97288261fc5e/doc/specs/vulkan/chapters/fundamentals.txt#L488 "Description for error detection") contains information like the following.

```
…
Applications should be developed with validation layers enabled, to help catch
and eliminate errors. Once validated, released applications should not enable
validation layers by default.
…
```

* Does this wording indicate that released applications should not check the return values from various calls for functions of this programming interface?
* Can the shown specification requirement conflict with any other [guidelines for secure software usage](https://cwe.mitre.org/data/definitions/252.html "Should unchecked return values be avoided?")?

**Comment by oddhack** [comment]
> Does this wording indicate that released applications should not check the return values from various calls for functions of this programming interface?

Yes, it does. Error checking takes up significant driver overhead, and the class of developers Vulkan was created for are willing to risk uncaught errors in return for maximum performance.

> Can the shown specification requirement conflict with any other guidelines for secure software usage?

There are many guidelines for software usage in the world. Vulkan as it exists today is not designed for "secure" or "safety critical" or a variety of other software domains. Perhaps in the future there will be a WebVulkan or Vulkan - Safety Critical, if there's demand for such a thing, and some of your concerns will become relevant then. But no such projects or products exist today.

We are not going to change the Vulkan design as a result of a flood of leading questions and links to other website, and it's not a good use of our time or yours to keep telling you this over and over in different ways. So please, back off and limit yourself to posting here about things that are specifically *incorrect* in the Vulkan spec, rather than things that you don't *like* about it.
