### ISSUE TITLE
SPIR-V Capability GeometryStreams is not defined in Vulkan spec

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/Vulkan-Docs#818]
According to SPIR-V spec, the GeometryStreams capability is supported since the original 1.0 version and remains the case in latest 1.3 version:
https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html
(3.31. Capability no.54)

However GeometryStreams is not listed in "Capabilies" section of "Appendix A: Vulkan Environment for SPIR-V" in Vulkan spec, neither 1.0 nor 1.1.

**Comment by dgkoch** [comment]
No it doesn't and this is intentional, as it's not currently accepted in Vulkan. 
GeometryStreams is only useful if you have transform feedback capability, so it would be enabled by an extension adding support for transform feedback. 
And for that request, I'll refer you to https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/26

**Comment by pdaniell-nv** [comment]
Improved GeometryStream support has been added to the Vulkan API as part of the [VK_EXT_transfrom_feedback](
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_transform_feedback) extension specification published in the Vulkan 1.1.88 releease.
