### ISSUE TITLE
vkGet*Sparse* incomplete return values

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#82]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-format-props says:

>     void vkGetPhysicalDeviceSparseImageFormatProperties(...)
>
> If pPropertyCount is smaller than the number of sparse image properties for the given set of parameters, VK_INCOMPLETE will be returned instead of VK_SUCCESS to indicate that not all the available values were returned.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#sparsememory-memory-requirements says:

>     void vkGetImageSparseMemoryRequirements(...)
>
> If pSparseMemoryRequirementCount is smaller than the number of sparse memory requirements for the given set of parameters, VK_INCOMPLETE will be returned instead of VK_SUCCESS to indicate that not all the available values were returned.

Both of those are void functions, so they can't return VK_INCOMPLETE or VK_SUCCESS.

**Comment by oddhack** [comment]
That's probably my bad. I was cleaning up a bunch of different array query sections to be consistent and was apparently over-zealous about it (the fact that the prototype isn't visible in the asciidoc since it's in a separate include file makes it harder to be contextually aware when doing that sort of stuff). I'll clean it up in a future weekly release. Thanks!

**Comment by oddhack** [comment]
Should be fixed in the 1.0.6 spec update.
