### ISSUE TITLE
Clarification on layout transitions for unused attachments.

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-Docs#821]
From Validation Layers Git Hub Issue 300 --https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/300 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/303

Vulkan spec section 7.1 states:

If an attachment is not used by any subpass, then loadOp, storeOp, stencilStoreOp, and stencilLoadOp are ignored, and the attachment’s memory contents will not be modified by execution of a render pass instance.

Does the statement "memory contents will not be modified" imply also that the final layout of an unreferenced attachment should be ignored too. However validation tracks the new layout even for unused attachments, currently.

The bug is requesting that these layouts be treated as ignored, but it's unclear whether that is the intention of the spec language above

@janharaldfredriksen-arm

**Comment by janharaldfredriksen-arm** [comment]
I don't think the initial & final layout should be ignored, i.e. that the validation layers are doing the right thing here.

--
The motivation for having the language about load and store ops being ignored in this case is that without it, at least tilers would have to insert an implicit subpass just in order to perform that operation. 

The spec uses different wording to describe when load/store ops happen vs the layout transitions.

Load/Store ops for an attachment happen as part of the subpass that references those attachments:

>  loadOp is a VkAttachmentLoadOp value specifying how the contents of color and depth components of the attachment are treated at the beginning of the subpass where it is first used.

(similar language exists for storeOp)

Layout transitions happen at the begin/end of a render pass instance:

> initialLayout is the layout the attachment image subresource will be in when a render pass instance begins.

And:

> finalLayout is the layout the attachment image subresource will be transitioned to when a render pass instance ends. During a render pass instance, an attachment can use a different layout in each subpass, if desired.

This is saying that the layout transitions happen regardless of whether the attachments are used within the render pass instance.

**Comment by jzulauf-lunarg** [comment]
Thanks for the clarification.
