### ISSUE TITLE
Why VkStructureType in vk.xml does not contain all members

### ISSUE THREAD

**Issue by gchihiha** [KhronosGroup/Vulkan-Docs#826]
Why VkStructureType in vk.xml does not contain all members
Is there a document to find all members?

**Comment by oddhack** [comment]
Do you mean "structure types" rather than "members"? Otherwise I'm not sure what you're asking.

VkStructureType does, AFAICT, contain all structure types, with a possible couple of bugs for recent vendor extensions. But it does not list them all in one place. Look for the \<enum extends="VkStructureType" tags.

**Comment by gchihiha** [comment]
members
thx!
