### ISSUE TITLE
VK_EXT_display_surface_counter should use vkGetPhysicalDeviceSurfaceCapabilities2KHR pNext

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#849]
`VK_EXT_display_surface_counter` should use `pNext` of `vkGetPhysicalDeviceSurfaceCapabilities2KHR` instead of defining its own `vkGetPhysicalDeviceSurfaceCapabilities2EXT`.

It should probably be deprecated and replaced.

**Comment by ianelliottus** [comment]
I'll leave it up to @cubanismo as to whether he'd want to do what you suggest.

**Comment by cubanismo** [comment]
VK_EXT_display_surface_counter predates vkGetPhysicalDeviceSurfaceCapabilities2KHR() by a month or so because we didn't have time for the ratification overhead when this shipped.  While the idea of cleaning house is appealing, realistically we can't remove the EXT version, so deprecating and writing a new version on top of the KHR would just create more spec surface in practice.  Hence, I have no plans to deprecate & replace this functionality absent some larger spec overhaul like a WSI version 2.0 effort.  I'm not aware of any plans along those lines, so closing this out.
