### ISSUE TITLE
What "Multiple Queues" means exactly on Synchronization-Examples doc?

### ISSUE THREAD

**Issue by ToyMachineGraphics** [KhronosGroup/Vulkan-Docs#868]
The section "Swapchain Image Acquire and Present" of the [doc](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples) about "Multiple Queues" part I'm not sure what exactly "different queues" means. Does that means different VkQueue handles no matter they come from the same or different queue families? Or that means they are different as long as  they are from different queue families? I read "6.7.4. Queue Family Ownership Transfer" on 1.0 spec it seems we only need ownership transfer if they are in different queue families. But I can't be 100% certain about it. Thanks for reply!

**Comment by krOoze** [comment]
> If the present queue is a different queue from the queue where rendering is done [...]

somewhat implies different queue families. Platform-independent presentation support is per&ndash;queue-family. Further it talks about ownership transfer, so indeed it is about queue families.

Separate present queue from the same family does not make all that much sense (unnecessary + more complex code + relies on limits + probably hurts perf). But it should be almost identical to the single queue situation, because the presentation is typically guarded by Semaphores anyway.

**Comment by ToyMachineGraphics** [comment]
Thanks for your help! I got it.

**Comment by ToyMachineGraphics** [comment]
Thanks for your help! I got it.
