### ISSUE TITLE
Does non-coherent mapped new memory need to be invalidated?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#889]
There's this note:

> Note
>
> Mapping non-coherent memory does not implicitly invalidate the mapped memory, and device writes that have not been invalidated **must** be made visible before the host reads or overwrites them.

It is ambiguous if newly allocated memory need to be invalidated too. Technically no device write happened yet, but still the memory may contain undefined values. And the note does force us to invalidate even before host writes.

Secondly, the quote should not be a note, as it gives new information containing a "must" sentence. Or the "must" was meant as "should"?

**Comment by Tobski** [comment]
So firstly you're quoting a note, so its non-normative - even with the must in there. I'm afraid I'm not sure how you're reading that in any way that implies invalidates need to be performed for newly allocated memory... the note clearly says "**if there are device writes**" - and nowhere in the spec do we talk about newly allocated memory having device writes performed on it? You can do also host writes immediately if you haven't performed any device writes.

So the normative part of the spec (which this could do with being tidied up in reference to, as it's mostly in the sync chapter) talks about `vkInvalidateMappedMemoryRanges` making device writes visible to the host. The sync chapter is clear that you always need to make a device write visible before reading that value - otherwise it's a data race. This is already defined in the spec elsewhere, which is why this is an informal note. So if there's no device write, there's no need to call `vkInvalidateMappedMemoryRanges`

**Comment by krOoze** [comment]
There are Notes in the spec that seem pretty normative by their wording and by giving new information... this being one of them (as I said in the OP).

Allocation can be a write (e.g. OS zeroing memory).
Besides even if the note does not apply to newly allocated memory, I would still not know from the spec if it should be invalidated or not...

> [...] talks about `vkInvalidateMappedMemoryRanges` making device writes visible to the host.
> [...] So if there's no device write, there's no need to call `vkInvalidateMappedMemoryRanges`

Saying "A must be done if X", does not automatically imply "A may be skipped if not X".

It is also not only about "making device writes visible to the host".
The note says (and gives new information) that the memory has to be invalidated **even if** the device writes are never read on the host.

I.e. it make this invalid:
```
vkCmdDeviceWrite(); vkSubmit();
vkDeviceWaitIdle(); //as fence wait, so device writes are visible on device
pMap[x] = 42; // did not invalidate first
vkFlushMappedMemoryRanges(); // should be safe as the previous write are already visible on device
```
I think the normative parts would otherwisely allow me to do this. So the not is either missleading, or it says new normative information (or I missed something).

**Comment by Tobski** [comment]
In my continued effort to clear the backlog of issues I've amassed...

So for this one, I think looking at the note now I see that it's a tad misleading. The wording could definitely be better. Probably something like the following would make more sense:

> Mapping non-coherent memory does not implicitly invalidate that memory. Device writes to non-coherent memory need to be made visible to the host before any further host access to avoid a data race, irrespective of when that memory was mapped to the host.

The note is really just calling out a specific instance of a data race - just badly. It's not new information, but yes, that code snippet is indeed invalid.
