### ISSUE TITLE
Feature restrictions on static vs dynamic pipeline state

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#89]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-features says:

> depthBiasClamp indicates whether depth bias clamping is supported. If this feature is not enabled, the depthBiasClamp member of the VkPipelineRasterizationStateCreateInfo structure must be set to 0.0.

If it's trying to be comprehensive, it should also say the depthBiasClamp parameter to the vkCmdSetDepthBias command must be set to 0.0. (And I do get the impression that this section is trying to be comprehensive about what the feature flags affect.)

Same for a bunch of the other potentially-dynamic state values. multiViewport already mentions the corresponding dynamic command, but that seems to be the only one.

**Comment by oddhack** [comment]
Agreed. Need to make certain all the vkCmdSet* commands also include that constraint in their validity language (maybe they do, haven't checked everywhere). I will bring it up internally.

**Comment by oddhack** [comment]
Should have been fixed in the 1.0.10 spec update. It's possible that some were missed. The person who did the fix commented:

I think fixing DEPTH_BIAS and LINE_WIDTH is sufficient. For the others:
VIEWPORT and SCISSOR were already covered (per the public issue).
BLEND_CONSTANTS, AND STENCIL_* are not optional
DEPTH_BOUNDS is controlled by a static 'enable' so we don't need to describe restrictions on the values.
