### ISSUE TITLE
`VkMemoryHostPointerPropertiesEXT::memoryTypeBits` missing restrictions?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#897]
It feels that `VkMemoryHostPointerPropertiesEXT::memoryTypeBits` is missing some restrictions?

The pointer can still be used, so it should probably never return `VK_MEMORY_PROPERTY_PROTECTED_BIT` type.

Should `memoryTypeBits == 0` be allowed if `VkExternalMemoryProperties` says the host pointers can be imported? It also seems redundant to `VK_ERROR_INVALID_EXTERNAL_HANDLE`.

**Comment by krOoze** [comment]
> HOST_VISIBLE_BIT at least.

Yea, that probably too. While not strictly speaking necessary, implementing `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` is as trivial as returning the original pointer...

**Comment by Tobski** [comment]
Hmm, not quite - these pointers can be mapped pointers from other devices, for instance. Also HOST_COHERENT is a property relative to a given device - so wouldn't necessarily be always true even for host-allocated pointers. I've settled for just giving a blanket statement that the memory type must be host visible, since that precludes setting any of them as PROTECTED anyway (or anything else that might exclude host visibility).

**Comment by oddhack** [comment]
This should be fixed in the 1.1.101 spec update.
