### ISSUE TITLE
maxViewportDimensions/viewportBoundsRange limits

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#92]
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#features-limits-required says:

>  maxViewportDimensions -  (4096,4096) ^3  min
>  viewportBoundsRange - (-8192,8191) ^4  (max,min)
>  ...
>  3: Maximum image attachment size or maximum display size 
>  4: Double the maxViewportDimensions

Firstly: What do those footnotes mean? Is it trying to say maxViewportDimensions must be either the maximum image attachment size or maximum display size, or the maximum of both of those, or at least as large as either/both of those? And viewportBoundsRange must be exactly double maxViewportDimensions, or can be larger?

Secondly: (-8192,8191) is not double (4096,4096) in either component, it's about (-2, 1.9998) times.

**Comment by oddhack** [comment]
> Firstly: What do those footnotes mean? Is it trying to say maxViewportDimensions must be either the maximum image attachment size or maximum display size, or the maximum of both of those, or at least as large as either/both of those?

I think the "maximum display size" shouldn't be there in the core API spec, as the only notion of "display" is an allusion in the introduction. Maybe the WSI extensions would want to touch on this language, though.

But the deeper question is unclear to me as well. There are constraints on framebuffer attachments that use different limits - maxFramebuffer{Width,Height,Layers} - and perhaps there should be a formal relationship between those limits and the maxViewportDimensions.

The "Double the maxViewportDimensions" seems like a useless comment even if it were accurate (or should be moved into a Note and expanded).

**Comment by dgkoch** [comment]
The point of the footnotes was to add more details to the required limits (and in some cases relationship between limits) that could easily be expressed in a single cell in the table. 

The intent is that the values for both of the these limits must be *at least* as large as indicated.

For Note 3 (maxViewportDimensions) the corresponding definition of this member says: "The maximum viewport dimensions must be greater than or equal to the largest image which can be created and used as a framebuffer attachment."  so I'll update that footnote to be more consistent with that. 
The language for this was actually based on the MAX_VIEWPORT_DIMS limit in GL which says "The maximum viewport dimensions must be greater than or equal to the larger of the visible dimensions of the display being rendered to (if a display exists), and the largest renderbuffer image which can be successfully created and attached to a framebuffer object.", so that's how the display aspect got into it. 

For Note 4 (viewportBoundsRange) This is related to the size of the guard band that some implementations use for clipping.  I'll try to formalize the relationship more precisely, but the reason it's not *exactly* [-2*MAX, 2*MAX] is because there might be limited number of bits available.

**Comment by oddhack** [comment]
Should be fixed in the 1.0.7 spec update. Daniel had to do a lot of archaeology to find the reason for the relationship between the limits since none of us remembered :-)
