### ISSUE TITLE
[Q] Why the indirect commands do not support protected now?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#921]
Why the indirect commands do not support protected now? Is this some newfound HW restriction? Feels bit artificial restriction to me...

**Comment by janharaldfredriksen-arm** [comment]
> Is this some newfound HW restriction?

Basically, yes.
Some implementations require internal writes for indirect commands, and during protected operations those writes are, of course, illegal.
This was discovered fairly recently due to increase CTS coverage, i.e. in practice the restriction has been there all along (on at least some implementations).

**Comment by krOoze** [comment]
What writes? They are supposed to read that struct and that's it no?
What about other read buffers, uniforms, textures, or e.g. the conditional rendering buffer. Why are they not a problem?

**Comment by janharaldfredriksen-arm** [comment]
>What writes? They are supposed to read that struct and that's it no?

Some implementations require writes in that process. (I'm not going to go into implementation details, but think of it as some version of patching the command buffer.)

**Comment by krOoze** [comment]
Thats's weirdass restriction, but ok.

**Comment by krOoze** [comment]
Not sure why patching protected buffer from protected queue would be a problem...
