### ISSUE TITLE
What size should VK_EXT_full_screen_exclusive report in surface caps

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#944]
What supported sizes should VK_EXT_full_screen_exclusive report in the surface caps?

It feels it is not clearly specified. E.g. on win32 the spec says the reported sizes always match the current window size.

That does not seem sensible for an exclusive fullscreen. If the window is already the desired size, then I already created exclusive fullscreen through winapi, and the extension is virtually pointless.

It seem more sensible if the caps return supported resolutions of the monitor. And creating the swapchain, presenting first image, or the explicit control should do the mode switch and attain fullscreen. But that also seems nonsensical, as the caps only report min+max, but monitors usually only support some discreet set of resolutions. (Besides it is not clear how the extension should mess with window decorations that belong to the application.).

Third option is that I already have an exclusive fullscreen window. And am only supposed to beg the swapchain creation not to override it. Which is kinda weird, and I hope the unextended swapchain does the right thing anyway...

**Comment by Tobski** [comment]
@krOoze "Full screen exclusive" is a "legacy" mode for full screen windows in Windows, that basically shuts off the compositor for a given display. By default, a created window is not in FSE mode - drivers typically try to acquire FSE for a window if it matches the size of the screen. FSE increases performance because it avoids a blit, but has undesirable alt+tab behaviour (screen is reinitialized).

This is the behaviour which VK_EXT_full_screen_exclusive dictates, by allowing the application to set the driver behaviour policy (default/allow/disallow) or taking control over the mode acquisition itself (acquire/release calls). This behaviour is exposed to allow applications to decide whether they want faster perf (enable the mode), better alt+tab behaviour (disable the mode), or explicit control of mode switches (app controlled).

If you're using modern Win10 APIs to create a "borderless full screen window", none of this applies - the compositor is aware of full screen borderless windows and gets out of the way, so you get fast perf AND good alt+tab behaviour; this extension will have no effect.

I'm not sure if that helps clear up your questions or not...? Hopefully it's useful background...

So that all said, the spec is supposed to continue returning the size of the window as per usual - I can't remember if we expose screen dimensions for Win32 in Vulkan, but they can be queried using Win32 APIs. The window needs to match the screen for FSE to work, so applications should ensure this when creating the window.

**Comment by krOoze** [comment]
What I mean is, what is the difference from traditional `CDS_FULLSCREEN` on winAPI? That is where the mode switch happens and is the biggest problem for alt-tab. And I would hope the drivers automatically go for the unhooking of compositor in this case as soon as they make a pixbuf for that wnd. Not sure why would I even need the extension, as it will get bad alt-tab behavior anyway.

> FSE increases performance because it avoids a blit

Notably, also decreases input lag, as the compositor is typically frame or two behind reality. Of course, blit becomes problem too if everyone wants 16K display...

> explicit control of mode switches (app controlled).

is this driver hint as the other flags, or is this guaranteed to happen?

> If you're using modern Win10 APIs to create a "borderless full screen window", none of this applies - the compositor is aware of full screen borderless windows and gets out of the way, so you get fast perf AND good alt+tab behaviour;

Assuming the driver uses the DXGI and not the legacy GDI path...
Also there is bit of hidden mechanics to this, and the winapi may still refuse to unhook the compositor for obscure reasons, so it would still be nice to have feedback that uncomposed fullscreen was achieved.

**Comment by Tobski** [comment]
I'm not quite sure if you're getting how the extension works... let me try to explain it and see if there's anything that doesn't make sense...

So by default existing drivers will move into FSE. That's fine. I think we agree that point? The "allow" mode explicitly tells the driver "yes this is ok", and "default" is... well do whatever, which ultimately is the same as allow on existing implementations. So these aren't really anything new.

The "Disallow" mode is the first new thing - this explicitly tells the driver it's not ok, and 100% guarantees that it will not move into that mode, instead sticking to the composited blit path and keeping sane alt+tab behaviour. This is desirable for certain applications.

The other new thing is "app controlled". This basically tells the driver to not try to acquire FSE on its own - instead the functions it uses to do so are exposed to the application. There is no guarantee in the API that acquisition will be successful, but there is a guarantee that will know, and if it's lost it at any other point, it'll also be notified of that.

**Comment by krOoze** [comment]
@Tobski No, that's just reiterating exactly the things I know\read from the spec.

But I think I know the disagreement here, and found a somewhat appropriate Note in the spec. The extension probably just and only unhooks the compositor. I never even considered that a problem. The typical "disruptive transition" happens when the resolution\vidmode is changed (and changed back). **If** unhooking the compositor itself even causes noticable "disruptive transition" (even considering swapchain creation itself may cause some delay), it would typically happen at the same time (from POV of the user) as the resolution change (and its big disruptive transition).

So that being said, I guess this Issue is invalid.

I still kinda miss some motivation for using this extension.
We established that sane implementation will default to circumventing compositor (if it can).
There are only few cases that I can see:

1) App is not actually fullscreen, or it has something that needs composition (e.g. decorations). Then the extension is pointless, because I already know it will not get "exclusive".

2) App is fullscreen and sets temporary resolution it needs. Alt-tab or such always causes disruptive transition. I would always want and expect "exclusive fullscreen". No point ever to try disable it.

3) App is fullscreen and has resolution of the desktop. I do want "exclusive fullscreen" and I already expect that there is no "disruptive transition" (or only a trivial one) on a modern OS. Only thing I would want here is query saying the transition won't be disruptive, and feedback that it actually happened (because it is gimmicky to match the criteria for exclusive, and some notification app may break the exclusiveness). The first is not offered, the second I guess is, but requires to subscribe to the explicit control, which does not allow to render if the "exclusiveness" is lost (which, I think, would cause more harm than good). And you describing it as "legacy" feature does not really fill me with confidence the extension is supposed to work with the borderless exclusive fullscreen (aka direct flip).

4) App works in some old OS, such as Windows XP. In which case there are no driver updates, so little chance of ever getting the extension.

**Comment by Tobski** [comment]
@krOoze Ah ok - yep that just about sums things up.

So the motivation for this case, btw, primarily comes from here: http://themaister.net/blog/2018/09/09/the-state-of-window-system-integration-wsi-in-vulkan-for-retro-emulators/ - At least for the disable case. There's a good case there for at least one application where it's far more useful to have sane windowing behaviour than maximum performance.

The "explicit acquire release" path was added so that applications can have a clear and explicit notification about being knocked out of it, which again is useful for certain applications.
