### ISSUE TITLE
No stride parameter for input arrays of Vk*Info structs was an API mistake.

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#950]
All arrays of Vk..Info structs passed to Vulkan procedures assume they are placed linearly in memory, if they are not you have to allocate temp arrays to fill with tightly packed Vk..Info structs just to submit, you can allocate such temp arrays on a stack if you deal with not that many objects and if your stack is big and free enough, but if pushing arrays (sometimes of variable length) to a stack is not an option, it gets nasty in multithreaded heap allocation scenarios, for no particular benefits other than to please Vulkan's structs linearity requirement.

**Comment by procedural** [comment]
Even better than a single stride value would be an array of offsets to memory where each struct is placed.

**Comment by procedural** [comment]
Same can be said for linear arrays of output objects.

**Comment by jeffbolznv** [comment]
Adding a stride parameter would probably be useful, but it's too disruptive to make this change across the whole API. We're adding this to an internal long-term issue tracking list of things we might change if there's a compatibility break, but it wouldn't happen any time soon.

Most of the commands that operate on arbitrary-sized arrays aren't on the critical path, so reformatting the data shouldn't be a big deal. One example of a place that it is on the critical path is for descriptor updates, and that has already been fixed with VK_KHR_descriptor_update_template.

An array of memory offsets or pointers IMO doesn't really help, because you still need to set put that array somewhere. And it seems unnecessarily hard to use.

I'm going to close this since it'll be tracked internally.

**Comment by procedural** [comment]
> Adding a stride parameter would probably be useful, but it's too disruptive to make this change across the whole API. We're adding this to an internal long-term issue tracking list of things we might change if there's a compatibility break, but it wouldn't happen any time soon.

I understand. Thank you for adding it to internal issues.
