### ISSUE TITLE
Specialization constants not working as expected when applying mathematical operations.

### ISSUE THREAD

**Issue by Destranix** [KhronosGroup/Vulkan-Docs#951]
See this link:
https://stackoverflow.com/questions/55380439/why-arnt-my-specialization-constants-working-correctly-when-i-use-them-for-math

I don't know if this is a bug or if this is the right forum to report.

**Comment by jeffbolznv** [comment]
This repo is for spec issues, so this isn't the right place for this bug report.

I can't tell from the stackoverflow description what the actual failure you're reporting is. Best I can guess is you're saying that Renderdoc isn't handling OpSpecConstantOp. If so, maybe @baldurk can suggest something.

**Comment by baldurk** [comment]
As above, if the problem is a RenderDoc bug it should be reported at the [RenderDoc repository](/baldurk/renderdoc) with a clear repro case (the stackoverflow post only contains the shaders, not a complete repro).

I'm also not clear on the issue. One thing that's a known problem is that shader reflection happens on the module before specialisation, so pipeline constants that affect reflection information like array sizes will always have their default value.

**Comment by Destranix** [comment]
So that's the wrong frorum, ok.

Hm, it really seems to be a renderdoc bug, but not only. 

The output I get in my own application is the same as with constantt values, but validationlayer complains, that vertex input is not consumed, even it must be consumed due I get the same results.

Default values should not cause problems. They are set to the same values for debug reason.

**Comment by Destranix** [comment]
@baldurk 

I send an capture using the built-in function in renderdoc.

**Comment by Destranix** [comment]
@baldurk 

Did you receive the capture?

**Comment by baldurk** [comment]
Yes, I'll respond in due time you don't need to bump this issue.

**Comment by Destranix** [comment]
Sorry, I just wanted to be sure you made the connection, cause I forgot to mention this post when I sent the capture.

**Comment by Destranix** [comment]
Sorry, I just wanted to be sure you made the connection, cause I forgot to mention this post when I sent the capture.
