### ISSUE TITLE
[PETITION] Update tutorials

### ISSUE THREAD

**Issue by NervenCid** [KhronosGroup/Vulkan-Docs#958]
Hello to all:

I'm new to trying to start learning Vulkan and i found some material:

https://vulkan-tutorial.com/
https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md

I checked some of the resources, but i believe that are a few outdated and are quite complex for beginners.

I wonder if it is possible, that khronos or someone make tutorials updated? i mean, nothing complex, just the basic installation and render a simple triangle or animation.

It is possible that khronos make a playlist in their youtube channel?

Thank you, and sorry for the english

**Comment by ratchetfreak** [comment]
A lot of the tutorials linked are actually made by people unrelated to Khronos. 

Instead you can appeal to the tutorial author directly to see if it can be updated. Or if the tutorial is severely out of data appeal to have it removed from the listing (and possibly replaced by a more up to date tutorial).

Having said that, getting started with vulkan is a verbose affair because of how little the api assumes about what you want to render.

**Comment by termhn** [comment]
vulkan-tutorial.com should be completely up to date, what issue are you having?

**Comment by KhronosKris** [comment]
Hi @NervenCid, we are actively reviewing all of our learning resources internally and hope to make gradual improvements in the future that will make discovery of learning resources easier.

**Comment by sfricke-samsung** [comment]
Hey @NervenCid, so recently we have added 2 new items to help for newcomers

1. The [Vulkan Samples](https://github.com/KhronosGroup/Vulkan-Samples)
2. The [Vulkan Guide](https://github.com/KhronosGroup/Vulkan-Guide)

Hopefully, this will help with what you were looking for

**Comment by NervenCid** [comment]
Thank you very much
