### ISSUE TITLE
Contradiction on the result of floating-point divide by zero

### ISSUE THREAD

**Issue by Snektron** [KhronosGroup/Vulkan-Docs#961]
Hello,

According to the most recent spec (1.1.107):
> Dividing a non-zero by a zero results in the appropriately signed IEEE 754 infinity.

but

> By default, the implementation may perform optimizations on half, single, or double-precision floating-point instructions respectively that ignore sign of a zero, or assume that arguments and **results** are not 
Nans or ±∞

Does this mean that a divide by zero always generates a properly signed infinity, or does that
only happen when SignedZeroInfNanPreserve execution mode is enabled?

**Comment by polarina** [comment]
The second paragraph is only applicable when the `VK_KHR_shader_float_controls` extension is enabled. The paragraph is not present when the specification is compiled without that extension.

If you do not enable that extension, there should be no ambiguity.

**Comment by krOoze** [comment]
@polarina Both paragraphs seem to be core.

**Comment by nyorain** [comment]
When an optimization can __assume__ that an operation does not return infinity, doesn't that automatically mean that all operations that would in fact evaluate to or operate on infinity at runtime might trigger undefined behavior? Even if you read the clause about division as an exception from that, what about for instance `large_num + large_num` (given that the result can't be represented as float)? Can it evaluate to any value since the implementation can assume that operations never return inf? Or could overflow safely be detected afterwards using `OpIsInf`? The issues section of "VK_KHR_shader_float_controls" says that this instruction must always detect inf correctly but it would be helpful to mention this in the actual vulkan spec now that the extension was promoted I guess. And it still seems like a contradiction to the statement that implementations can assume the __return value__ of an operation is never inf.

I'm mainly interested in the case where SignedZeroInfNanPreserve is not enabled. Some clarification in the spec would be useful.
