### ISSUE TITLE
I think Event API for split barriers is designed incorrectly, here's how to fix it

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#962]
Currently setting and waiting on an event looks like this:

```c
void vkCmdSetEvent(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask);
void vkCmdWaitEvents(VkCommandBuffer commandBuffer, uint32_t eventCount, const VkEvent * pEvents, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, uint32_t memoryBarrierCount, const VkMemoryBarrier * pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier * pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier * pImageMemoryBarriers);
```

This is obviously incorrect to anyone who understands the supposed asynchrony of this operation.

Currently, if you set an event in a command buffer and submit that command buffer without a corresponding wait, it has no information what memory operations and layout transitions it should start, so an implementation would defer these costly operations to a wait call, defeating the purpose of events in the first place.

My proposal how to fix this:
```c

typedef struct VkEventCreateInfoEXT {
  VkStructureType               sType;
  const void *                  pNext;
  VkPipelineStageFlags          srcStageMask;
  VkPipelineStageFlags          dstStageMask;
  uint32_t                      memoryBarrierCount;
  const VkMemoryBarrier *       pMemoryBarriers;
  uint32_t                      bufferMemoryBarrierCount;
  const VkBufferMemoryBarrier * pBufferMemoryBarriers;
  uint32_t                      imageMemoryBarrierCount;
  const VkImageMemoryBarrier *  pImageMemoryBarriers;
} VkEventCreateInfoEXT;

typedef struct VkEventCreateInfo {
  VkStructureType    sType;
  const void *       pNext;
  VkEventCreateFlags flags;
} VkEventCreateInfo;

VkResult vkCreateEvent(VkDevice device, const VkEventCreateInfo * pCreateInfo, const VkAllocationCallbacks * pAllocator, VkEvent * pEvent);
void vkCmdSetEvent(VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask);
void vkCmdWaitEvents(VkCommandBuffer commandBuffer, uint32_t eventCount, const VkEvent * pEvents, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, uint32_t memoryBarrierCount, const VkMemoryBarrier * pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier * pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier * pImageMemoryBarriers);
```

The idea is to move barriers to existing `vkCreateEvent` procedure using `pNext` extension mechanism so that existing `vkCmdSetEvent` and `vkCmdWaitEvents` could be recorded in any order and still have all the information they need to build a command buffer off the clock.

If the extended `VkEventCreateInfoEXT` is passed to `VkEventCreateInfo::pNext`, then `vkCmdSetEvent`'s `stageMask` and `vkCmdWaitEvents`'s `srcStageMask`, `dstStageMask`, `memoryBarrierCount`, `pMemoryBarriers`, `bufferMemoryBarrierCount`, `pBufferMemoryBarriers`, `imageMemoryBarrierCount` and `pImageMemoryBarriers` can be safely ignored.

I'm not aware of a limit on how many VkEvents you can create, but if there is such a limit, an extension can expose it and events can be destroyed when not used and recreated for other purposes by the user.

**Comment by NicolBolas** [comment]
I'm not sure I understand what this is meant to accomplish. You're basically putting the barrier information in the command that signals the event (which presumably signals the completion of the source operation) rather than the command that waits on the event (which preceeds the operation that will read from the destination). But... what does that actually mean for the GPU's actions?

The question (I think?) revolves around exactly when the GPU performs the barrier operations. You could perform them at the point where you're doing `vkCmdSetEvents`. Or you could perform them at the point where you're doing `vkCmdWaitEvents`.

Here's the thing though. If you want to perform them at the set events point, you can do that already. It's called `vkCmdPipelineBarrier`. The *entire point* of using an event rather than a pipeline barrier is to *delay* the actual barrier operation until the point where the data will be consumed, thus potentially allowing more overlapping of execution. You use a pipeline barrier when the data will be consumed immediately; you use an event when there are intervening commands between the two.

It's not clear to me why you need to put the barrier information at the set events point if the actual barrier _operation_ will not take place until the wait events point. So when exactly do you want the barrier operation to happen?

**Comment by krOoze** [comment]
There's also the thing that `vkCmdWaitEvents` take multiple events, but only a single barrier params `srcStageMask` , `dstStageMask`), which supports what @NicolBolas says.

The Events are simply not what you think they are (they are apparently not so flexible as to start layout transition at the point of `vkCmdSetEvent`).
(TBH I wonder if anybody uses Events successfully and if all platforms do anything useful with them. So far I only see the confusion. Maybe it would be wise to deprecate and revive as better designed extension.)

**Comment by NicolBolas** [comment]
@krOoze 

The useful part of an event is that you don't have to delay processing later commands that aren't actually dependent on the prior command.

OK, let's say you have two compute work items, A and B. Operation A writes data which B reads. But you also have a compute work item C which is in no way dependent on A and B. If you want optimal performance, then you want C to be able to overlap with both A and B. But for correctness, A cannot overlap with B. Therefore, the best submission order is A, C, B.

Given that order, where do you put your barrier? If you put a barrier immediately after A, then the GPU cannot execute *any* of C until all of A finishes, even though C has no actual dependency on A. If you put a barrier immediately before B, then none of B can execute alongside any of C.

By putting an event after A and waiting on the event before B, you allow A/C to overlap, and C/B to overlap, but prevent any A/B overlap. Now, it is theoretically possible for a valid implementation of events to make waiting on an event equivalent to a barrier. But that's no different from just issuing a barrier before B, so even on that worst-case implementation, you've lost nothing.

**Comment by krOoze** [comment]
That assumes two things: The implementation won't just use some kind of expensive fence whenever you use an Event. Remember, Events must unlike barriers be visible to host. Secondly that you would not optimize barrier version better if you would not be lured to use Events; you cannot merge barriers with events.

**Comment by jeffbolznv** [comment]
The working group does consider the existing API for events to be lacking, since the driver is missing some information (particularly the srcAccessMask) at vkCmdSetEvent time. I don't think we would want the dependency information to be specified at vkCreateEvent time, but we are aware of the problem and it's on our list.

**Comment by procedural** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/blob/815e07c850d642d996292f5cdec25d41ecdff0d0/appendices/VK_KHR_synchronization2.txt#L46-L52

**Comment by TomOlson** [comment]
@procedural anything more to do here? Can we close it?
