### ISSUE TITLE
Asciidoctor 2 breaks block [eq]

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#968]
asciidoctor (2.0.9)

![eq](https://user-images.githubusercontent.com/3791331/57801834-f998a700-7754-11e9-9996-fcba0a3c3c4d.PNG)

**Comment by oddhack** [comment]
If you're able to diagnose what the issue is that would be great, but this is going to be low on the priority list. The BUILD.adoc gives versions that are known to work, and for asciidoctor, that's 1.5.8. Since 2.0 is documented to represent a compatibility break - although I can't readily track down exactly what's been changed in a quick look - it isn't surprising.

The toolchain as a whole is fragile with multiple alpha/poorly supported components, and I think the practical answer will be to spin up a Docker image for building and CI that's known to work.

**Comment by krOoze** [comment]
Well, I would guess it is treated as a code block (markdown compatibility?). Plus I am pretty sure `::` markup is invalid in the first place.

I was thinking replacing it with some other markup, but not sure which.

Perhaps it would be best to just use the latexmath. There's no reason to have two types of math markup anyway. It does not help performance much; the actual problem with the math script is that its performance scales badly with total size of html than amount of math in it. Plus even that concern can be alleviated by pr #704.

**Comment by oddhack** [comment]
Please don't propose a PR changing the math markup at this time.

**Comment by krOoze** [comment]
I verified the problem is all the way in `2.0.0.rc.1`. That is perhaps noteworthy in the docs.

**Comment by krOoze** [comment]
Space indents mean "literal block": https://asciidoctor.org/docs/user-manual/#literal-text-and-blocks
Seems just the parser was "fixed", so it converts our markup here.

Doing instead  `  {empty}:: [eq]#whatever#` seems to work.

**Comment by oddhack** [comment]
I've update the BUILD.adoc to note that 1.5.8 is required, for now. We will eventually migrate to asciidoctor 2, but probably not in the near future.

**Comment by krOoze** [comment]
@oddhack Would you accept patches with above ugly hack?
Also how would you feel about just replacing it with latexmath?

**Comment by krOoze** [comment]
@oddhack Seems this was done in 1.1.122. Any other known compatibility problems with asciidoctor 2?

**Comment by krOoze** [comment]
I guess none then. Closing.
