### ISSUE TITLE
[Specification] Dynamic Offsets is not of type VkDeviceSize.

### ISSUE THREAD

**Issue by shaoboyan** [KhronosGroup/Vulkan-Docs#971]
In vulkan, dynamic offsets is of type uint32_t([in section 13.2.5](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#resources-buffers)), which is not the same size as the VkDeviceSize used to create buffers([in section 11.1](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#resources-buffers)).

I think spec need to change dynamic offsets to type VkDeviceSize.

**Comment by shaoboyan** [comment]
@kainino0x @Kangz

**Comment by TomOlson** [comment]
Agreed that the type mismatch doesn't make a lot of sense, but it was a deliberate choice - a possibly misguided micro-optimization of the high-frequency descriptor set binding call. We can't change it unless / until we do a compatibility break, but I've added it to our internal list of issues that could be fixed at that time. Since it is tracked there, I will close this for now. 

I should say, we are assuming this isn't a serious limitation in practice - there are major (desktop) implementations shipping that don't support buffers larger than 2GB. If there are important use cases for huge offsets that are blocked because of this, we'd be interested to hear about them.
