### ISSUE TITLE
VK_KHR_imageless_framebuffer spec issues

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#998]
1) The extension changes VUs' semantics, without changing VUIDs. That can be problem for layers.

2) There's missing restrictiom that the Image Views are created from same device

3) The implicit VU `VUID-VkFramebufferCreateInfo-pAttachments-parameter` is contradictory to the intended extension use.

4) VUID-VkFramebufferCreateInfo-pAttachments-00891 does not seem to account for the new flag

5) VUID-VkRenderPassBeginInfo-pNext-03206 seems to be redundant, as without the cap the user is not allowed to specify the imageless flag. And so if he does not specify it the VUID-VkRenderPassBeginInfo-framebuffer-03207 should cover it.

6) ?

**Comment by Tobski** [comment]
For 1. I assume you're referring to the VUs that now get "If the VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT is not set..." prepended? That's considered "fine" and we don't typically worry about that - the validation is roughly identical and we agreed to allow this case.

2. Yea, the implicit VU generation doesn't handle nesting at all - so it needs an explicit VU adding.

3. Ah I must've missed that one, the `pAttachments` parameter needs tagging as "optional" I guess.

4. Missed that too, seems that's not currently being validated otherwise I'd have caught that doing https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1040

5. Yes I noticed this one when I was implementing the validation layer code - there's no way to hit this condition, so it should be removed.

6. Surely there's no more issues and everything else is perfect :P?

Would you be willing to raise a PR to fix these issues? Otherwise I can look at it when I have time.

**Comment by krOoze** [comment]
Sure, when I have time.

ad 1, as long as the validation is implemented immediately, I guess it is not a problem. Otherwise it breaks coverage stats with something being half-way implemented.
Though it also pollutes the compiled spec without extensions with names that do not exist...
But I suppose the specificator did not want to lose mind writing all the necessary ifdefs...

ad 2, maybe the automatically generated stuff could say summarily that all handles must be child of the dispatchable handle. I am sure this is problem elsewhere too, and I would prefer not to spam the explicit VU list with too generic requirements.

ad 3, it is bit annoying. It almost guarantees that all non-optional parameters will sooner or later become optional as extensions are released. Maybe XML could be modified to cover this. Perhaps new attribute (`eoptional`) containing DNF of extensions or VK versions that make a parameter optional?

ad 6, surely not, considering I have seen these issues speedscrolling through the new content 😁

**Comment by Tobski** [comment]
> But I suppose the specificator did not want to lose mind writing all the necessary ifdefs...

Pretty much this yes. Also meant there were two VUs instead of one, so it didn't actually make the validation any less of a minefield to do it this way 😅 

> ad 2, maybe the automatically generated stuff could say summarily that all handles must be child of the dispatchable handle. I am sure this is problem elsewhere too, and I would prefer not to spam the explicit VU list with too generic requirements.

At last count I think there were only about three places where explicit VU would be needed. Changing the implicit VU would also work.

> ad 3, it is bit annoying. It almost guarantees that all non-optional parameters will sooner or later become optional as extensions are released. Maybe XML could be modified to cover this. Perhaps new attribute (eoptional) containing DNF of extensions or VK versions that make a parameter optional?

I usually scroll through these but missed it this time. Longer term I wanted to do something else entirely, the entire system of implicit VUs is extremely fragile.. not sure adding more mechanisms is the right answer here, this seems like we should just do more rigorous review :).

> ad 6, surely not, considering I have seen these issues speedscrolling through the new content 😁

😱

**Comment by Tobski** [comment]
So one of these things (the implicit VU) has caused the validation layers to go awry, so I've just gone ahead and taken care of all of the issues you pointed out in an internal MR which we'll hopefully ship shortly.

**Comment by Tobski** [comment]
(I also spotted that I'd somehow referred to a parameter that doesn't exist "pname:attachments" in the VUs for VkRenderPassBeginInfo, so I fixed that too.

**Comment by oddhack** [comment]
@Tobski's internal MR has been pushed in the 1.1.117 spec update.
